### ISSUE TITLE
Wrong chromedriver version downloaded

### ISSUE THREAD

**Issue by dagansandler** [bonigarcia/webdrivermanager#1]
When using ChromeDriverManager.setup() a wrong version is downloaded.
Current latest version is 2.15, but the manager downloads version 2.9

This seems to be a result of reading the version folders names and grabbing the last folder on the list, which returns 2.9 rather than 2.15

I suggest using this link to get the latest version number:
http://chromedriver.storage.googleapis.com/LATEST_RELEASE

**Comment by ysparrow** [comment]
Hi, 
Thanks for the great tool, it really helps!
But discovered the same issue with wrong Chrome Driver version. Can you please apply fix? 
Thank you so much

**Comment by bonigarcia** [comment]
Yes, I am aware of it. I'll solve it ASAP.

**Comment by bonigarcia** [comment]
Solved. Bug-fix committed and new version released to Maven Central:

    <dependency>
        <groupId>io.github.bonigarcia</groupId>
        <artifactId>webdrivermanager</artifactId>
        <version>1.0.1</version>
    </dependency>
