### ISSUE TITLE
Ability to operate chrome and Firefox installed via flatpak on arch Linux (feature request)

### ISSUE THREAD

**Issue by leder11011** [bonigarcia/webdrivermanager#1000]
Test steps:
- install arch Linux
- install Firefox/chrome flatpak
- write shell script "google-chrome" for:
flatpak run com.google.Chrome
- for the Firefox flatpak exists a ticket on selenium HQ and here:
[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1755140)

Expected result:
Chrome is operated remotely and target page opens

Current result:
Chrome launches with blank page

**Comment by bonigarcia** [comment]
I don't understand how/why this is related to WebDriverManager.

**Comment by leder11011** [comment]
Hello bonigarcia,

thank you for webdrivermanager!

I see the typical finger pointing now:
- SeleniumHQ says its a webdrivermanager issue
- you say it's not related to webdrivermanager

Please verify the issue present with flatpak and snap browser installations!

Please repoen this issue!

Thank you!

Best regards
Gerrit

**Comment by bonigarcia** [comment]
I continue without understanding this issue. If you think it is related to WebDriverManager, please open a new issue, but informing all the required data (WebDriverManager traces, etc.).
