### ISSUE TITLE
Difference between chrome version in webdrivermanager and the latest one

### ISSUE THREAD

**Issue by yanephatalistA** [bonigarcia/webdrivermanager#1004]
Hi, guys

Sorry if I do it in a wrong way, I just want to ask you a question
As I said before I face this problem: chrome app has already released version 111.0.5563.65 and the previous 111.0.5563.41, and you guys have 111.0.5563.19.
Want to know how to handle this difference on a local machine? make browser version downgrade, wait for your upgrade
Or maybe there is a simple solution

Thanks for your attention and reply

**Comment by bonigarcia** [comment]
I don't understand this issue and how it is related to WebDriverManager. In any case, Chrome is an ever-green browser, which means that it upgrades automatically to the next stable version when it is available. In principle, you should not worry about that.
