### ISSUE TITLE
Adding direct link download support

### ISSUE THREAD

**Issue by kornilovk** [bonigarcia/webdrivermanager#103]
For the Edge browser default link is 
https://www.microsoft.com/en-us/download/details.aspx?id=48740
 It's very old version

A new link is
href="https://download.microsoft.com/download/3/2/D/32D3E464-F2EF-490F-841B-05D53C848D15/MicrosoftWebDriver.exe

But i've got an error

java.lang.RuntimeException: org.jsoup.UnsupportedMimeTypeException: Unhandled content type. Must be text/*, application/xml, or application/xhtml+xml. Mimetype=application/octet-stream, URL=https://download.microsoft.com/download/3/2/D/32D3E464-F2EF-490F-841B-05D53C848D15/MicrosoftWebDriver.exe
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:284)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:108)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:87)

**Comment by bonigarcia** [comment]
This has been solved in version 1.5.1, just released today.

**Comment by Dibyashreejyotiprakash** [comment]
Hi,, is there any dll is available for webdriver manager, for c# selenium
