### ISSUE TITLE
there is a problem on download driver_url when use Mac_m1

### ISSUE THREAD

**Issue by shadow0202** [bonigarcia/webdrivermanager#1030]
**Description of the problem**: 
The download path is wrong when I used   mac_m1, The download path it provides not work . I got a error like that
```
There is no such driver by url  https://registry.npmmirror.com/-/binary/chromedriver/112.0.5615.28/chromedriver_mac64_arm64.zip
```

I had to change the `get_url` in `core/driver.py` myself like that 
```    
def get_url(self):
        return f"{self._url}/{self.get_version()}/{self.get_name()}_mac_arm64.zip"
```
 

**Browser and version**:  112.0.5615.137 (正式版本) (arm64)

**Operating system**:   macos 13.2.1 (22D68)

**WebDriverManager version**:  3.8.2

**WebDriverManager call**:  

**WebDriverManager traces**: 

**Error log**:

**Comment by bonigarcia** [comment]
If you are using Python, this is not the manager you are looking for. See instead:

https://pypi.org/project/webdriver-manager/
