### ISSUE TITLE
Issue with launching Edge browser

### ISSUE THREAD

**Issue by ninhktran** [bonigarcia/webdrivermanager#1037]
**Description of the problem**: 

Hi @bonigarcia,

I was not able to not able to launch Edge browser. I'm using the latest webdrivermanager version 5.3.2. This is the java log message: 
"
Starting Microsoft Edge WebDriver 112.0.1722.39 (e40a520f851f31c19c0c93c4278f5b408ec37d7c) on port 65437
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver 
"
Not sure if this is a bug or I have done something wrong on my end.

Thanks

**Browser and version**: Edge 112.0.1722.39

**Operating system**: MacOs Ventura, Windows 10

**WebDriverManager version**: 5.3.2

**WebDriverManager call**: 
"api 'io.github.bonigarcia:webdrivermanager:5.3.2'"
 "case Edge:
	final WebDriverManager edgeManager = WebDriverManager.edgedriver();
	driverVersion.ifPresent(version -> edgeManager.config().setEdgeDriverVersion(version));
	edgeManager.setup();
	return Result.success();"

**WebDriverManager traces**: Starting Microsoft Edge WebDriver 112.0.1722.39 (e40a520f851f31c19c0c93c4278f5b408ec37d7c) on port 65437
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

**Comment by bonigarcia** [comment]
Hello, these traces proves that WebDriverManager is downloading msedgedriver correctly. So your problem is not due to WebDriverManager.
