### ISSUE TITLE
PhantomJs execution

### ISSUE THREAD

**Issue by sauravkumar05** [bonigarcia/webdrivermanager#105]
i noticed that when the phantom js is downloaded to .m2 folder then its present in a particular subfolder inside phantonmjs whereas the path set is different that where its actually downloaded.

Path set after download - 
C:\Users\<username>\.m2\repository\webdriver\phantomjs\beta-windows\2.5.0\phantomjs.exe

Actual Path where phantomjs.exe is present
C:\Users\<username>\.m2\repository\webdriver\phantomjs\beta-windows\2.5.0\phantomjs-2.5.0.beta-windows\bin\phantomjs.exe

Suggestion - you can always have a code to recursively look for .exe file present or not after downloading the required driver to make sure that it is present.

**Comment by bonigarcia** [comment]
Yes, it would be possible. It should be taken into account that the PhantomJS binary for other platforms (Linux, Mac) is named without the `.exe` extension. In any case, so far this is working.
