### ISSUE TITLE
Edge Driver : The program cant start because msldso.dll is missing from your computer

### ISSUE THREAD

**Issue by sauravkumar05** [bonigarcia/webdrivermanager#106]
I noticed that when edge driver is downloaded using webdrivermanager code then the exe file that is download is complaining about the dll missing in the computer whereas if i manually download the webdriver exe from the microsoft site <https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/>  - Version: 3.14393 | Edge version supported: 14.14393 |  and then try to execute the exe and it doesn't have any problem with the execution
![edgedriverissue](https://cloud.githubusercontent.com/assets/11820297/22362099/2b9e4fe6-e42e-11e6-84ae-d279887e9ced.PNG)

**Comment by sauravkumar05** [comment]
Adding more info to the previous issue - I started looking at the code and i noticed that if i run a code as junit for your getDrivers method in EdgeDriverManager then the path created in .m2 is "C:\Users\<username>\.m2\repository\webdriver\MicrosoftWebDriver\3.14393\MicrosoftWebDriver.exe" whereas if i use your latest wdm release through pom and set it up then the path created for edge driver after download is "C:\Users\<username>\.m2\repository\webdriver\MicrosoftWebDriver\Try Microsoft Edge, a fast and secure browser that's designed for Windows 10Get started\MicrosoftWebDriver.exe" and the size of the downloaded file also seems to be different

**Comment by bonigarcia** [comment]
I think this is related to #101 and #103. It should be fixed in the latest stable version (1.5.1 at writing time).

**Comment by kamillol** [comment]
The same error on Version: 4.15063 but in Version: 3.14393 works fine

**Comment by RoakyWood** [comment]
This seems to be a recurring issue whenever there is an  update to the Edge Browser. Right now, I have Edge 20.10240.17146 the most recent MicrosoftWebDriver seems to be 16257. Will the new WebDriver be coming out soon? Is there a way to prevent this every time Edge Updates?

**Comment by soul3510** [comment]
Also having the same issue

![image](https://user-images.githubusercontent.com/4783552/30521554-f9ee7454-9bc9-11e7-877e-b6411c635832.png)

Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

Any one knows how to fix?
Thanks.

**Comment by bonigarcia** [comment]
@soul3510 First, ensure you are using the latest version of WebDriverManager (**1.7.2** at the moment of this writing).

Then, you need to know which version of the Edge binary is required. To do it by checking the [Edge WebDriver page](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/). In your case (Microsoft Edge 38.14393.0.0, Microsoft EdgeHTML 14.14393), the version is **3.14393**. So, you need to specify the version to WebDriverManager as follows:

`EdgeDriverManager.getInstance().version("3.14393").setup();`

[Here](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/EdgeTest.java) you can find a working example.
