### ISSUE TITLE
ARM64 GeckoDriver version mapping revision (Firefox)

### ISSUE THREAD

**Issue by isotheos96** [bonigarcia/webdrivermanager#1063]
Hello, I'm dealing with an issue that is quite annoying and I would be glad to be helpful to someone. I'm using **Mozilla Firefox 102.12.0esr in a Debian GNU/Linux 11 enviroment based on ARM64** (aka AARCH64) architecture **and running a Java Spring Boot application**; the problem is the driver version: in this case, relying to [versions.properties](https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/versions.properties) file, **WebDriverManager 5.3.3** chooses GeckoDriver version [0.31.0](https://github.com/mozilla/geckodriver/releases/tag/v0.31.0) that is the last not available for a Linux OS based on ARM64 architecture. By this circumstances, I suggest to consider a migration to GeckoDriver version [0.32.0](https://github.com/mozilla/geckodriver/releases/tag/v0.32.0) for Mozilla Firefox versions near to the one I'm using (version 0.32.0 of GeckoDriver should be as compatible as 0.31.0 one) and targeting ARM64 architecture.

I'm fetching the driver using the call: **WebDriverManager.firefoxdriver().setup();**

A partial Java error trace follows:

...
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0
	at io.github.bonigarcia.wdm.online.UrlHandler.getCandidateUrl(UrlHandler.java:287)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1280)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1198)
	... 64 common frames omitted

**Comment by bonigarcia** [comment]
You can force the version to be used as follows:

```
WebDriverManager.firefoxdriver().driverVersion("0.32.0").setup();
```
