### ISSUE TITLE
Setting proxy

### ISSUE THREAD

**Issue by h-tomek** [bonigarcia/webdrivermanager#107]
The only way to set the proxy (either HTTP or HTTPS) is by setting an environmental variable. If proxy is not known before running the program and detecting actual proxy (e.g. based on some proxy script), it is not possible to provide proxy information to BrowserManager in an easy fashion since the method `createProxy` within `Downloader` class.

The existing code try to get proxy info using `String proxyString = System.getenv("HTTPS_PROXY");`. It would be much better if this can be passed in during some initialization, or at least if beside environment variables, Java system properties are cheked, i.e. `System.getProperty("HTTPS_PROXY")`.

**Comment by bonigarcia** [comment]
Version 1.6.0 uses the builder pattern to expose the BrowserManager API. I try to implement this new feature for next release.

**Comment by bonigarcia** [comment]
Version 1.6.1 has the method `proxy()` to setup the HTTP proxy.
