### ISSUE TITLE
Unable to fetch browser logs for the script running on docker container

### ISSUE THREAD

**Issue by ngourkar** [bonigarcia/webdrivermanager#1075]
Description - When the script is executed on local system the browser log file gets created and logs gets appended to it, but the same aspect does not work with execution on docker container.

Github link: https://github.com/ngourkar/WDM_BrowserLogs
A sample simplified project with all description and issue mentioned in readme file.

**Comment by bonigarcia** [comment]
Console log gathering can be tricky. For that reason, WebDriverManager provides custom capabilities to make it easier. See [doc](https://bonigarcia.dev/webdrivermanager/#console-log-gathering). This feature also works in Docker:

https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/watcher/DockerGatherLogsChromeTest.java
https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/watcher/DockerGatherLogsFirefoxTest.java
