### ISSUE TITLE
can't find chrome binary on macos locally

### ISSUE THREAD

**Issue by turnitin-rshanker** [bonigarcia/webdrivermanager#1078]
[ERROR] ExecutionException There was an error in the forked process
[ERROR] Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
[ERROR] Host info: host: 'Ravis-Laptop.local', ip: '2601:641:400:4df:c96:f4b2:b4bc:b01a%en0'
[ERROR] Build info: version: '4.10.0', revision: 'c14d967899'
[ERROR] System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '11.0.18'
[ERROR] Driver info: org.openqa.selenium.chrome.ChromeDriver
[ERROR] Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--test-type, --headless, --disable-gpu, --disable-infobars, --disable-dev-shm-usage, --no-sandbox, --disable-extensions, --disable-web-security, --window-size=1920,1200], extensions: [], prefs: {profile.default_content_settings.popups: 0, profile.password_manager_enabled: false}}, pageLoadStrategy: eager}]}]
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked process
[ERROR] Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
[ERROR] Host info: host: 'Ravis-Laptop.local', ip: '2601:641:400:4df:c96:f4b2:b4bc:b01a%en0'
[ERROR] Build info: version: '4.10.0', revision: 'c14d967899'
[ERROR] System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '11.0.18'
[ERROR] Driver info: org.openqa.selenium.chrome.ChromeDriver
[ERROR] Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--test-type, --headless, --disable-gpu, --disable-infobars, --disable-dev-shm-usage, --no-sandbox, --disable-extensions, --disable-web-security, --window-size=1920,1200], extensions: [], prefs: {profile.default_content_settings.popups: 0, profile.password_manager_enabled: false}}, pageLoadStrategy: eager}]}]
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:418)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
[ERROR]         at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:53)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:152)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
[ERROR] Host info: host: 'Ravis-Laptop.local', ip: '2601:641:400:4df:c96:f4b2:b4bc:b01a%en0'
[ERROR] Build info: version: '4.10.0', revision: 'c14d967899'
[ERROR] System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '11.0.18'
[ERROR] Driver info: org.openqa.selenium.chrome.ChromeDriver
[ERROR] Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--test-type, --headless, --disable-gpu, --disable-infobars, --disable-dev-shm-usage, --no-sandbox, --disable-extensions, --disable-web-security, --window-size=1920,1200], extensions: [], prefs: {profile.default_content_settings.popups: 0, profile.password_manager_enabled: false}}, pageLoadStrategy: eager}]}]
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$null$7(ForkStarter.java:401)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]

**Comment by asolntsev** [comment]
@turnitin-rshanker @bonigarcia I experience the same problem after updating Chrome from 114 to 115. 

I guess it's rather a problem with Chromedriver 115, not WebDriverManager.

Code to reproduce:

```java
public class Chrome115Test {
  @Test
  void check() {
    WebDriverManager.chromedriver().setup();

    // This quick fix solves the problem:
    // WebDriverManager.chromedriver().browserVersion("115").driverVersion("114").setup();

    ChromeDriver driver = new ChromeDriver();
    driver.navigate().to("https://duckduckgo.com");
    driver.quit();
  }
}
```

**Comment by turnitin-rshanker** [comment]
sounds good, thanks closing it

**Comment by asolntsev** [comment]
I am not sure we should close the issue. 

Apparently, starting from version 115, Chromedriver needs to use "Chrome for testing" instead of usual Chrome.
@bonigarcia Does it mean that WebDriverManager should download and cache "Chrome for testing" binary too?

**Comment by HarshaAdutla** [comment]
How can we resolve this issue then? @turnitin-rshanker @asolntsev.

**Comment by bonigarcia** [comment]
I confirmed this problem but also that this is not due to WebDriverManager. The latest version of WebDriverManager (5.4.1) allows managing chromedriver 115+ using the Chrome for Testing (CfT) endpoints. But on the other side, chromedriver 115 seems to have some kind of problem in macOS (see [CfT issue](https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30)).

As a workaround in Selenium (and macOS), we need to specify the Chrome binary path as follows:

```
ChromeOptions options = new ChromeOptions();
options.setBinary("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome");
WebDriver driver = new ChromeDriver(options);
```
