### ISSUE TITLE
Explicit Wait is failing because of guava version included as part of webdriver manager

### ISSUE THREAD

**Issue by sauravkumar05** [bonigarcia/webdrivermanager#108]
it should be set to 21 as required by selenium support jar. Workaround for now is to exclude dependency.

<dependency>
<groupId>io.github.bonigarcia</groupId>
<artifactId>webdrivermanager</artifactId>
<version>1.6.0</version>
  <exclusions>
    <exclusion>
       <groupId>com.google.guava</groupId>
       <artifactId>guava</artifactId>
    </exclusion>
  </exclusions>
</dependency>

**Comment by bonigarcia** [comment]
Already in [master branch](https://github.com/bonigarcia/webdrivermanager/blob/master/pom.xml).

**Comment by sauravkumar05** [comment]
when are you planning to release it ?
