### ISSUE TITLE
WEbDriver manager is not working with the latest Chrome version 115

### ISSUE THREAD

**Issue by gaurav160985** [bonigarcia/webdrivermanager#1081]
Since I have upgraded my Chrome browser to 115.0.5790.98, the chrome-driver is unable to identify the Chrome binary. It shows the error org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary, it was working fine till the time I was using Chrome version 114.

**Comment by bonigarcia** [comment]
See #1078.
