### ISSUE TITLE
Still have "Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary"

### ISSUE THREAD

**Issue by wildpioneer** [bonigarcia/webdrivermanager#1084]
I know there was a similar problem in 5.4.0, but it should have been fixed in 5.4.1, but it still reproduces on mac os.

![image](https://github.com/bonigarcia/webdrivermanager/assets/8968693/c11cefe1-c48e-4152-8fea-5d32411077a2)

**Comment by bonigarcia** [comment]
This issue should be fixed with the latest version of chromedriver, recently released.
