### ISSUE TITLE
WDM picks incompatible binary when using locally cached Geckodriver

### ISSUE THREAD

**Issue by majchman** [bonigarcia/webdrivermanager#109]
**Is:**
WDM exports `geckodriver.exe` Windows binary while running on Mac OS or Linux. We also had it the other way around: started on Windows the WDM picked the Mac OS binary (the only one available in the local repo) instead of downloading the Windows one.
**Note:** This appears to be only geckodriver-related. Chromedriver works fine on all 3 OSes: Mac OS, Windows and Linux (Ubuntu). 

**should be:**
The proper binary for the OS is used from the local repo. If not available, the binary is downloaded

WDM Properties set in the project:
> wdm.targetPath = bin/webdriver
>   wdm.geckoDriverVersion = LATEST
>   wdm.chromeDriverVersion = 0.14.0

Version tested:
1.6.1

Logs:
> 2017-03-14 15:56:48,072 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:285 - Checking if wires 0.14.0 (64 bits) exists in cache bin/webdriver
> 2017-03-14 15:56:48,085 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:299 - Checking bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe
> 2017-03-14 15:56:48,085 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:299 - Checking bin/webdriver/geckodriver/macos/0.14.0/geckodriver
> 2017-03-14 15:56:48,085 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:299 - Checking bin/webdriver/chromedriver/win32/2.28/chromedriver.exe
> 2017-03-14 15:56:48,085 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:299 - Checking bin/webdriver/chromedriver/mac64/2.28/chromedriver
> 2017-03-14 15:56:48,086 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:299 - Checking bin/webdriver/.DS_Store
> 2017-03-14 15:56:48,086 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:312 - 0.14.0 wires (64 bits) do not exist in cache bin/webdriver
> 2017-03-14 15:56:48,086 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:285 - Checking if geckodriver 0.14.0 (64 bits) exists in cache bin/webdriver
> 2017-03-14 15:56:48,087 [main] TRACE io.github.bonigarcia.wdm.BrowserManager:299 - Checking bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe
> 2017-03-14 15:56:48,087 [main] DEBUG io.github.bonigarcia.wdm.BrowserManager:303 - Found 0.14.0 geckodriver (64 bits) in cache: bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe
> 2017-03-14 15:56:48,088 [main] DEBUG io.github.bonigarcia.wdm.BrowserManager:169 - Driver for [wires, geckodriver] 0.14.0 found in cache bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe
> 2017-03-14 15:56:48,088 [main] INFO  io.github.bonigarcia.wdm.BrowserManager:632 - Exporting webdriver.gecko.driver as bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe
> /Users/.../bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe: /Users/.../bin/webdriver/geckodriver/win64/0.14.0/geckodriver.exe: cannot execute binary file

**Comment by bonigarcia** [comment]
Thanks for reporting. I'll be checking this issue ASAP.

**Comment by bonigarcia** [comment]
That should be fixed now. It will be available on next release.
