### ISSUE TITLE
Brave and Vivaldi support

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [bonigarcia/webdrivermanager#1096]
It would be really great if there was Brave and Vivaldi support, that way people can use more privacy focused browsers, like how Brave has a built in ad and tracker blocker, plus removes all the google tracking from the browser. I don't know a whole lot about Vivaldi, but I do know it has an ad a tracker blocker.

**Comment by bonigarcia** [comment]
Sorry, I have no plans to support these browsers in WebDriverManager. However, these two browsers are chromium-based, so I suppose you can automatically download chromedriver with WebDriverManager, and start a Selenium session using `ChromeDriver` and options to specify the browser binary path of Brave and Vivaldi.
