### ISSUE TITLE
116

### ISSUE THREAD

**Issue by bj121212** [bonigarcia/webdrivermanager#1097]
It doesn't seem to support version 116
only up to 114

**Comment by natalliaMikulskaya-tr** [comment]
The same issue. :(

**Comment by mbr-sn** [comment]
Seems like the root cause is that the chromedriver team changed the download site, see:
https://stackoverflow.com/questions/76746946/unable-to-download-chrome-driver-for-version-115
The URLs in webdrivermanager.properties config probably have to be adjusted

**Comment by thc202** [comment]
Are you using the latest version of WebDriverManager? It was updated to use CfT since version 5.4.0 (0d4967115ec77f6054fb32b4030dddb1db119974).

**Comment by bj121212** [comment]
> Are you using the latest version of WebDriverManager? It was updated to use CfT since version 5.4.0 ([0d49671](https://github.com/bonigarcia/webdrivermanager/commit/0d4967115ec77f6054fb32b4030dddb1db119974)).

no，Because it does not support Java8

**Comment by bonigarcia** [comment]
This is already supported in WebDriverManager 5.4.1. And yes, it needs Java 11.

**Comment by sirmikolai** [comment]
@bonigarcia There is any possibility to have these fixes for java 8?

**Comment by bj121212** [comment]
now i use selenium-manage is ok，and support java 1.8

**Comment by bonigarcia** [comment]
@sirmikolai No sorry. In any case, you will need to bump to Java 11 to use the latest version of Selenium by next month (see [Selenium announcement](https://www.selenium.dev/blog/2023/java-8-support/)).

**Comment by PerfectVertigo** [comment]
Do I need to use java 11 specifically or java 11 or higher? Cause I'm using java 17 and I still have the issue.

**Comment by sirmikolai** [comment]
@bj121212 Yeah, thanks a lot, it works for java 8 with selenium-manager from version 4.11.0

**Comment by bonigarcia** [comment]
UPDATE: To provide a solution to those that cannot bump to Java 11, I  released WebDriverManager 5.5.0, compiled with Java 8. 

In any case, my personal opinion is that Java 8 is already an ancient version, and I recommend using at least Java 11+ as soon as possible.
