### ISSUE TITLE
Some issues with ChromeTest

### ISSUE THREAD

**Issue by cgrandsjo** [bonigarcia/webdrivermanager#11]
Hi,

First I just want to say that this project is a great initiative!
However, I would like to mention two things.

1)
Currently version 1.3.1 is unavailable at http://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager
So I had to use version 1.3.0 to get things working with maven.

2)
I had to add this into my pom file to prevent an error when using the example ChromeTest.

\<dependency\>
  \<groupId>org.slf4j\</groupId\>
  \<artifactId>slf4j-simple\</artifactId\>
  \<version>1.7.13\</version\>
\</dependency\>

If not added I get this error/warning:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I'm using Eclipse 4.5.1 on Windows 10 64 bit.
I'm new to Java, Maven and Selenium so maybe I made a mistake somewhere.
I just thought that I should report it if this is an actual error.

Keep up the good work!

Cheers,
Christian

**Comment by bonigarcia** [comment]
Hi Christian,

Regarding 1, I have just released a patch version of webdrivermanager (1.3.1). It should be available on Maven Central in a few minutes.

Regarding 2, indeed you have to include an SL4JF implementation in your project. For further information please check out issue #4.

Kind regards,
Boni
