### ISSUE TITLE
Release version 1.6.2 to add support for Selenium 3.3.1

### ISSUE THREAD

**Issue by vmassol** [bonigarcia/webdrivermanager#110]
Hi, thanks for this very nice project. I'm just testing it but realized I need selenium 3.3.1 support. Do you know when you could release version 1.6.2 which seems to add support for it? Thanks!

**Comment by bonigarcia** [comment]
Using WebDriverManager should be independent of the version of Selenium WebDriver. In fact, WebDriverManager uses the dependency selenium-java but just for internal tests (the Maven scope is test).

Nevertheless, the current development version (1.6.2 at the time of this writing) already uses selenium-java 3.3.1. I cannot say when is going to be released, but it will be soon.

**Comment by vmassol** [comment]
ok my bad indeed. I saw a dep on selenium in the pom and thought it had some impact on the version of selenium I was using. If it's not the case then it's great. Thx
