### ISSUE TITLE
Chrome 116 doesn't download with Selenium 4.11.0 and WebDriverManager 5.4.1

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [bonigarcia/webdrivermanager#1100]
After chrome update to 116, we are facing issues with downloading the latest driver. 

I am using Selenium 4.11.0 and WebDriverManager 5.4.1. Logs shows that webdriver manager defaults to chrome 114.

Please assist.

[main] WARN org.apache.hc.client5.http.impl.auth.HttpAuthenticator - ex-0000000002 Negotiate{FAILED } authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 401 executing https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json to get version of chromedriver (Error HTTP 401 executing https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116)
[main] INFO org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec - Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {s}->https://googlechromelabs.github.io:443
[main] WARN org.apache.hc.client5.http.impl.auth.HttpAuthenticator - ex-0000000005 Negotiate{FAILED } authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 401 executing https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json to get version of chromedriver (Error HTTP 401 executing https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver_win32.zip
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Sak\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe

**Comment by SakthiIsaiBharathi** [comment]
@bonigarcia - Please assist

**Comment by thc202** [comment]
`Error HTTP 401 executing…` is the root problem (I just tried to access the endpoint and I'm not getting a 401), review your environment to make sure you can access that URL.

**Comment by bonigarcia** [comment]
This is clearly a connectivity issue at your end:

```
[main] WARN org.apache.hc.client5.http.impl.auth.HttpAuthenticator - ex-0000000002 Negotiate{FAILED } authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 401 executing https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
```

I suppose you have network restrictions (maybe a proxy or firewall) that forbid connecting to that [JSON endpoint](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json).

**Comment by SakthiIsaiBharathi** [comment]
@bonigarcia - I am able to access the end point. Issue is only while executing scripts.
![image](https://github.com/bonigarcia/webdrivermanager/assets/47920071/75de09b4-479e-431c-a1f5-e8a253bfbf3d)

**Comment by desecheo** [comment]
I'm using the same artifact versions for Selenium and WebDriverManager and tests are failing with "SessionNotCreatedException." But when I pass the VM arguments like so `-Dwdm.chromeDriverVersion=116.0.5793.0` the test do run fine.

**Comment by desecheo** [comment]
If you are running from CLI using maven, you add that argument to your mvn command. If using an IDE, add it to the VM arguments of the runner.
