### ISSUE TITLE
WebDriver Manager will not work with Chrome 116

### ISSUE THREAD

**Issue by Yith1** [bonigarcia/webdrivermanager#1103]
**Description of the problem**:  

WebDriver Manager will not work with Chrome 116

**Browser and version**: 

Chrome 116

**Operating system**: 

Linux and Windows

**WebDriverManager version**: 
5.4.1

**WebDriverManager call**: 

WebDriverManager.chromedriver().setup();

**WebDriverManager traces**: 

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Error log**:

**Comment by SakthiIsaiBharathi** [comment]
@Yith1 What is your selenium version ?

**Comment by MonikaMalolepsza** [comment]
same issue here with selenium 4.11

**Comment by bonigarcia** [comment]
WebDriverManager 5.4.1 works for chromedriver 116 both in Windows and Linux (see #1098 and #1099).

Just in case you cached the invalid driver (i.e., 114), you need to delete your driver cache (i.e., delete completely the folder `C:\Users\<your-user>\.cache\selenium`) and run your Selenium script again. If the issue persists, you need to report the WebDriverManager logs (not only the error trace).

**Comment by Yith1** [comment]
Interesting. I thought it might be due to this:
https://stackoverflow.com/questions/76928702/error-io-github-bonigarcia-wdm-online-httpclient-error-http-404-executing-http?newreg=92c57427cca44786a1524cb7dadb291c

Also I note that this page does not have 115 or 116:
https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/versions.properties

Ok, deleting the selenium cache directory fixed it.

**Comment by bonigarcia** [comment]
> Is it correct though that some earlier versions don't work properly with 116?

Yes.

**Comment by Yith1** [comment]
So I need to upgrade to 5.4.1 AND delete the cached files on my build servers?

**Comment by f4bienp** [comment]
I have always this issue with this config : 
Chrome 116.0.5845.111
java version "19.0.2" 2023-01-17
WebDriverManager version: 
5.4.1
WebDriverManager call:
WebDriverManager.chromedriver().clearDriverCache().setup();

Operating system:
Windows Server 2016 Standard

=> It's Chrome driver 114.0.5735.90 is downloaded

It's OK in local for MacOS.

**Comment by 1ROCKSTAR1** [comment]
Hello. How long will this problem be actual ? I have many colleagues who faced the same problem..In my case WDM 5.4.1 and cleaning cache folder didn't help. I guess I should use chromium and delete original chrome from my pc
