### ISSUE TITLE
Chrome Driver 116 unable to download Using Webdriver manger <version>4.2.2</version> 

### ISSUE THREAD

**Issue by koteswaraotekkem** [bonigarcia/webdrivermanager#1104]
**Description of the problem**: 

**Browser and version**: 

**Operating system**: 

**WebDriverManager version**: 

**WebDriverManager call**: 

**WebDriverManager traces**: 

**Error log**:

**Comment by yimam-michael** [comment]
It is trying to get version information from the following endpoint, but it is getting 404.
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116

The same endpoint works fine for older versions. For example
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114

**Comment by decarbonite** [comment]
Facing same issue, tests are failing with the following error:
`com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe `

Selenium Version 4.8.3
WebDriverManager Version 5.3.2

**Comment by bonigarcia** [comment]
Please use the latest version of WebDriverManager (5.4.1). Also, clear the cache (see [doc](https://bonigarcia.dev/webdrivermanager/)) at least once to ensure the incorrect driver version (114) is not cached.

**Comment by koteswaraotekkem** [comment]
> Please use the latest version of WebDriverManager (5.4.1). Also, clear the cache (see [doc](https://bonigarcia.dev/webdrivermanager/)) at least once to ensure the incorrect driver version (114) is not cached.

I am Using WebDriverManager indirecty from Selenide(which uses 4.2.2 version of WDM), So Selenide i cant upgrade now, is their any other alternatives ? Please suggest

**Comment by decarbonite** [comment]
@bonigarcia Would clearDriverCache() be sufficient to always get latest WebDriver, or do I also have to use it along side clearResolutionCache() to make sure it works?
Unfortunately, can't upgrade to Java 11 at the moment.
