### ISSUE TITLE
How can i Enable the detailed logs from WebDriverManager 5.4.1 (Chrome 116 & Selenium 4.11.0 still an issue)

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [bonigarcia/webdrivermanager#1105]
**Description of the problem**: I am using Selenium 4.11.0 and WebDriverManager - 5.4.1. I am still getting issues with WebdriverManager.

I tried to access this URL - https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json from same machine. I am able to access. I suppose some other thing is breaking.

How can i enable the detailed logs to see where the connectivity is breaking? Is this a valid issue with WebDriverManager.

**Browser and version**: Chrome 116.0.5845.97

**Operating system**: Windows 10

**WebDriverManager version**: 5.4.1

**WebDriverManager call**: WebDriverManager.chromedriver().clearDriverCache().setup();

[main] WARN org.apache.hc.client5.http.impl.auth.HttpAuthenticator - ex-0000000002 Negotiate{FAILED } authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json to get version of chromedriver (CONNECT refused by proxy: HTTP/1.1 407 authenticationrequired)
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116)
[main] WARN org.apache.hc.client5.http.impl.auth.HttpAuthenticator - ex-0000000005 Negotiate{FAILED } authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json to get version of chromedriver (CONNECT refused by proxy: HTTP/1.1 407 authenticationrequired)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver_win32.zip
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Data\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe

**Comment by bonigarcia** [comment]
As I already said, this is clearly a connectivity issue at your end. I said the following in #1100: 

_I suppose you have network restrictions (maybe a proxy or firewall) that forbid connecting to that [JSON endpoint](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)._

And your traces seem to confirm it:

_[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json to get version of chromedriver (**CONNECT refused by proxy**: HTTP/1.1 407 authenticationrequired)_

To enable the proxy settings in WebDriverManager, look at the [configuration section in the WebDriverManager doc](https://bonigarcia.dev/webdrivermanager/#advanced-configuration).

To see the finest WebDriverManager traces (log level `TRACE`), look at the [troubleshooting section in the WebDriverManager doc](https://bonigarcia.dev/webdrivermanager/#troubleshooting).
