### ISSUE TITLE
 webdrivermanager-4.2.2 is failing to run Tests on the Chrome 116 and chrome 115 versions 

### ISSUE THREAD

**Issue by sakkukasetty** [bonigarcia/webdrivermanager#1113]
**Description of the problem**:  Test Execution is failing on the chrome browser version 115 and 116 

**Browser and version**:  115 and above

**Operating system**:  Ubuntu and Windows 11

**WebDriverManager version**:  4.2.2 and 5.0.3

**WebDriverManager call**: 

**WebDriverManager traces**: 

**Error log**:

**Comment by dennisduysak** [comment]
Same issue for me. The chrome driver download links changed. See: https://chromedriver.chromium.org/downloads

**Comment by sakkukasetty** [comment]
> Same issue for me. The chrome driver download links changed. See: https://chromedriver.chromium.org/downloads

Ifound this , looks like a known issue trying out the workaround https://bonigarcia.dev/webdrivermanager/#known-issues

**Comment by reniers-tiobe** [comment]
Seems that updating to version 5.5.0 fixed it for me.

**Comment by bonigarcia** [comment]
Yes, this should be fixed with the latest version of WebDriverManager. See the above-mentioned doc page for details.
