### ISSUE TITLE
Wrong arch for Apple M1 and Chromedriver

### ISSUE THREAD

**Issue by clicman** [bonigarcia/webdrivermanager#1118]
**Description of the problem**: WDM doesn't handle proper arch from Apple M1 

On Apple M1 it downloads mac-x64 of Chromedriver but should mac-arm64

**Comment by stuaxo** [comment]
I'm hitting the same issue on the same hardware.
WDM came with selenium (which I use via pytest on python), how can I check which version of WDM is used ?

Chromium was installed via SNAP and already has a matching chromedriver on the system, available at /usr/bin/chromedriver

The version of chromium and the chromedriver installed by snap is 116.0.5845, I'm not sure where it's possible to download this version outside of the snap distribution.

```
$ ❯ /usr/bin/chromedriver --version
ChromeDriver 116.0.5845.110 (5128dafac6222fd3ac218660ab6dbf7ff260d768-refs/branch-heads/5845@{#1518})
```

```
❯ /usr/bin/chromium-browser --version
Chromium 116.0.5845.110 snap
```

```
...
INFO     WDM:logger.py:11 ====== WebDriver manager ======
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
INFO     WDM:logger.py:11 Driver has been saved in cache [/home/stu/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
```

**Comment by stuaxo** [comment]
EDIT:  My workaround is to manually copy the file /usr/bin/chromedriver into the right place in .wdm/drivers and then update drivers.json.   Today I realised I need to also update the date there, otherwise wdm will overwrite everything.
