### ISSUE TITLE
How to use the system chromedriver ?

### ISSUE THREAD

**Issue by stuaxo** [bonigarcia/webdrivermanager#1125]
I'm on arm64 on ubuntu.

The system comes with chromedriver, but when I run my tests that use webdrivermanager it downloads the x64 version.
(more details here:  https://github.com/bonigarcia/webdrivermanager/issues/1118)

As a workaround (hack) I create a new drivers.json to point at the chromedriver on the system, is there a proper way to do this ?

version:  Sorry, I don't know how to check the version of webdrivermanager, this is part of a larger project and webdriver comes with selenium which is called from pytest_bdd.

```sh
#!/bin/bash
# usesystemchromedriver.sh
if [[ $(which chromedriver) == "" ]]; then
  echo "Chromedriver not found on the system." exit 1
fi

mkdir -p ~/.wdm

# Create a minimal drivers.json file with today's date
DATE=$(date +%d/%m/%Y)
JSON="{\
  \"linux64_chromedriver_latest_for_\": {\
    \"timestamp\": \""$DATE"\",\
    \"binary_path\": \"/usr/bin/chromedriver\"\
  }\
}"

echo $JSON > ~/.wdm/drivers.json
```

# oneliner version
```sh
mkdir -p ~/.wdm; printf '{"linux64_chromedriver_latest_for_":{"timestamp":"%s","binary_path":"/usr/bin/chromedriver"}}\n' $(date "+%d/%m/%Y") > ~/.wdm/drivers.json
```

**Comment by bonigarcia** [comment]
This repo is WebDriverManager (Java). If you are using webdriver-manager (Python), see: https://pypi.org/project/webdriver-manager/

**Comment by stuaxo** [comment]
Ah, thanks - apologies, I assumed it was using this as selenium gets called which creates a lot of Java exception traces when things don't work.
