### ISSUE TITLE
Could not start a new session. Response code 500

### ISSUE THREAD

**Issue by decarbonite** [bonigarcia/webdrivermanager#1128]
**Description of the problem**: I have around 1000 Selenium tests I use 5 threads to run. 99% pass except for 1 or 2 random tests that fail with browser and ChromeDriver version mismatch (the rest run fine). This seems to be related to https://bonigarcia.dev/webdrivermanager/#support-for-chromedriver-115 but I'm already running `.clearDriverCache()` before running the tests

**Browser and version**:  Chrome 116.0.5845.188

**Operating system and architecture**: Windows Server 2016, amd64

**Selenium version**: 4.12.1

**WebDriverManager version**: 5.5.3

**WebDriverManager call**: 
```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

**WebDriverManager traces**: 
```
```

**Error log**: 
```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.188 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: 'REDACTED', ip: 'REDACTED'
Build info: version: '4.12.1', revision: 'REDACTED'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_381'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-gpu], extensions: [], prefs: {credentials_enable_service: false, profile.password_manager_enabled: false}}}]}]

```

**Comment by ShridharaMJ** [comment]
@decarbonite 

Do you calling driver set up for every testcase or before testsuite executions? Because once driver downloaded we don't need to download again unless browser updated.

**Comment by klakier387** [comment]
Since couple of days we receive a repsonse 

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114

I'm wondering if this is connected.

**Comment by klakier387** [comment]
Since couple of days we receive a repsonse, for the project that was running correctly

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114

In other test project I set up chrome driver, but now the opera driver opens.
I'm wondering if this is connected.

**Comment by ZathrasOne** [comment]
I am getting the same issue. The WebDriverManager is not downloading the most current driver (Chrome ==117, but WebDriverManager is downloading 114):
09:42:03.945 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Using WebDriverManager 5.5.3
09:42:13.123 [main] DEBUG io.github.bonigarcia.wdm.cache.ResolutionCache - Resolution chrome=117 in cache (valid until 10:18:51 22/09/2023 PDT)
09:42:13.131 [main] DEBUG io.github.bonigarcia.wdm.cache.ResolutionCache - Resolution chrome117=114.0.5735.90 in cache (valid until 18:25:02 22/09/2023 PDT)
09:42:13.137 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 114.0.5735.90 (resolved driver for Chrome 117)
09:42:13.285 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 114.0.5735.90 found in cache
09:42:13.300 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\BruceRitter\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe

**Comment by ZathrasOne** [comment]
I found that the ~user\.cache\selenium\resolution.properties file was corrupt, it said that Chrome117 compatible chromedriver was 114..., so it was stuck. So I deleted .cache\selenium... and it pulled down the correct versions the next time and started working properly again.

**Comment by bonigarcia** [comment]
The `.clearDriverCache()` was recommended due to the transition to CfT (Chrome for Testing). But currently, it would be better not to use it (unless a corrupt file in the cache, like @ZathrasOne said).

@decarbonite Is this issue still happening for you?

**Comment by akampitsch** [comment]
I am experiencing the issue as of right now, but my machine already ended up on 118 being released

`Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 118.0.5993.89 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: 'DESKTOP-B32COTN', ip: '192.168.4.47'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]`

**Comment by akampitsch** [comment]
using
`WebDriverManager.chromedriver ().clearDriverCache ();`
once seems to have alleviated the problem now

**Comment by JVallad18** [comment]
Thank you 
`WebDriverManager.chromedriver().clearDriverCache().setup();`

 worked for me !

**Comment by RicardoCarroza** [comment]
Where i need to use de line 
WebDriverManager.chromedriver().clearDriverCache().setup();
??

**Comment by dandytech** [comment]
> Thank you `WebDriverManager.chromedriver().clearDriverCache().setup();`
> 
> worked for me !

Thanks for this, this solved mine as well.

**Comment by shubahm-kourav** [comment]
guys even after clearing cache it is downloading the 114 version only

**Comment by AishwaryaExcellarate** [comment]
its not working for me still error is session not created

**Comment by kubanaw** [comment]
> Where i need to use de line WebDriverManager.chromedriver().clearDriverCache().setup(); ??

I used it just after setProperty and it finally worked for me:

System.setProperty("webdriver.chrome.driver", projectPath);
WebDriverManager.chromedriver().clearDriverCache().setup();
driver = new ChromeDriver();

**Comment by hemangidk** [comment]
> The `.clearDriverCache()` was recommended due to the transition to CfT (Chrome for Testing). But currently, it would be better not to use it (unless a corrupt file in the cache, like @ZathrasOne said).
> 
> @decarbonite Is this issue still happening for you?

Thank You. This worked for me.

**Comment by SachinTharaka** [comment]
> I found that the ~user.cache\selenium\resolution.properties file was corrupt, it said that Chrome117 compatible chromedriver was 114..., so it was stuck. So I deleted .cache\selenium... and it pulled down the correct versions the next time and started working properly again.

This is working for me. thank you very much
