### ISSUE TITLE
Unable to use chromeDownloadUrlPattern 

### ISSUE THREAD

**Issue by ShridharaMJ** [bonigarcia/webdrivermanager#1129]
**Description of the problem**:  If an company has firewall and if its block all driver downloads by default then there is no other ways to download drivers, Companies may create own artifact to download drivers in this case we don't have options to download drivers because we can't replace base URL in properties of WebDriver Manager, In webdrivermanager.properties we can update chromeDownloadUrlPattern as " https://{company_artifact}/chrome-for-testing/%s/%s/chromedriver-%s.zip" but in source we observed its directly collect URLS from "chromeGoodVersionsUrl" and filter based on requirement then download driver from that. Hence, we don't have option to download drivers with own artifacts.

**Browser and version**:  Version 116.0.5845.188
**Operating system and architecture**:  Window 10 64 bit
**Selenium version**:  4.12.0
**WebDriverManager version**:  5.5.3

![image](https://github.com/bonigarcia/webdrivermanager/assets/29522573/05599529-7708-4659-aeca-8104229d58c5)

![image](https://github.com/bonigarcia/webdrivermanager/assets/29522573/7d942ec8-bfc7-4bc8-8c7a-83f5f9f3ed96)

![image](https://github.com/bonigarcia/webdrivermanager/assets/29522573/a707b37c-392c-484d-8c22-81fc96ad7f74)

![image](https://github.com/bonigarcia/webdrivermanager/assets/29522573/bb508fbe-91d2-4a4a-aea7-15fe08a631c6)

**Comment by abulat** [comment]
Having similar issue. Even if we override wdm.chromeDownloadUrlPattern with our custom pattern pointing to the companies Nexus artifactory:

> wdm.chromeDownloadUrlPattern=https://nexus.icq.com:8443/repository/chrome-for-testing/%s/%s/chromedriver-%s.zip


 webdrivermanager attempts to download from the original location:

> [main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.88/win64/chrom...

Is there any chance to put higher priority to this ticket? We are partially blocked now in running tests on CI, since our tests containers do not have direct connection to internet and we cannot download chromedrivers for testing.

Thanks in advance.

**Comment by giulong** [comment]
@ShridharaMJ I opened [this PR](https://github.com/bonigarcia/webdrivermanager/pull/1141). Basically, via the new key `wdm.avoidExternalConnections=true` you can avoid pinging external urls when downloading webdrivers. Do you think it's ok?

Disclaimer: this is just a proposal, not sure if this is compliant to code/test style, if I'm missing the context around the lines I changed, or anything else 😬 . So I'm waiting @bonigarcia 's feedback as well ofc

**Comment by bonigarcia** [comment]
Thanks a lot for reporting and contributing @giulong. Your PR is merged now. I'm preparing a new release of WebDriverManager with it.

**Comment by DineshTejaj** [comment]
@bonigarcia  When i am trying run the script from bamboo CI CD am getting the below error
error	06-Dec-2023 01:45:23	io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Connection reset
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1432)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1425)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
error	06-Dec-2023 01:45:23		at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)

I am using the latest version of webdrivermanager, My devops team suggested me this issue 1129 and look for any solution
  <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.6.2</version>
        </dependency>

Can you please help me what should i do, am unable to launch browser in ci cd

 WebDriverManager.chromedriver().setup();
            driver = new ChromeDriver();
          driver.get("https://www.google.com");
