### ISSUE TITLE
webdrivermanager 1.6.1 indirectly requires Java 8

### ISSUE THREAD

**Issue by juanpablo-santos** [bonigarcia/webdrivermanager#113]
Latest version of webdrivermanager uses `com.typesafe:config:1.3.1`, which requires [Java 8](https://github.com/typesafehub/config#binary-releases).

Downgrading to `com.typesafe:config:1.2.1` should be enough to fix the issue.

**Comment by bonigarcia** [comment]
Thanks for reporting. I have just downgraded that library in this [patch](https://github.com/bonigarcia/webdrivermanager/commit/5d8615c16bec8cb553589c7cf9b406b857b58701).
