### ISSUE TITLE
Logger methods not working after updating WebDriverManager to 5.5.3  (latest)

### ISSUE THREAD

**Issue by maheshwaranvk** [bonigarcia/webdrivermanager#1132]
**Description of the problem**: Recently due to CFT issues, we tried upgrading our WebDriverManager to latest 5.5.3 which supports CFT with Seleinium 3.141.x. We cannot update Selenium to 4.x and Java to 11 from 8 for some internal reasons.
So currently on Selenium 3.141 with Java 8, I upgraded WebDriverManager 5.5.3. Execution was fine but our Logger methods which we have in every methods to print logger messages in consoles are not getting executed. logger.info("Console messages"); means I am not getting logger messages in console.

When I revert back to my 5.2.3, Logger is working perfectly fine.

**Browser and version**: Tried with Latest Chrome Version. Selenium - 3.141 and Java 8

**Operating system and architecture**: Windows 10 and architecture 64 bits

**Selenium version**: 3.141.59

**WebDriverManager version**: 5.5.3

**WebDriverManager call**: 
private void setDriverLocation() {
    WebDriverManager.chromedriver().setup();
 }

**WebDriverManager traces**: I cannot able to get the traces even after updating logback.xml as mentioned here -> https://bonigarcia.dev/webdrivermanager/#troubleshooting

**Comment by maheshwaranvk** [comment]
@bonigarcia : Please let me know if any more details needed from my side

**Comment by bonigarcia** [comment]
I am not sure, but maybe this is related to the logging dependencies (`slf4j` and `logback`) used by WebDriverManager. Maybe you can try to skip these dependencies, or analyse the dependencies tree to discover the root of the problem.
