### ISSUE TITLE
Could you make it work with the edge browser?

### ISSUE THREAD

**Issue by notSoTechnical** [bonigarcia/webdrivermanager#1142]
After downgrading my chrome to 104 with changing all those settings, I think it needs to have a better way for this.
If anyone needs to downgrade the chrome version, I used (104.0.5112.102) https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by bonigarcia** [comment]
Edge should work with WebDriverManager. If not, please follow the issue template to report the problem.
