### ISSUE TITLE
Different chrome version on my local and server

### ISSUE THREAD

**Issue by junaid-ansari312** [bonigarcia/webdrivermanager#1144]
I have latest chrome version installed on my local but on server we use 113 chrome version and we do not want to upgrade there. I change my code from local and push it to github and it runs on server. Local does not give any error but on server I am getting error for same code Object reference not set to instance of object . I am using webdriver manager dependency. Is there any solution for this.

**Comment by bonigarcia** [comment]
I don't understand your problem. Please follow the issue template to report any issue.
