### ISSUE TITLE
HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 Connection timed out

### ISSUE THREAD

**Issue by jekozo** [bonigarcia/webdrivermanager#1145]
I am using Selenide and not being able to open() the chrome browser. Getting the below error stack:

**Operating system and architecture**: Windows 10 

**Selenide version**: (v. 6.12.2)

**WebDriverManager version**: (v.5.5.3).

**WebDriverManager call**: open("some_url"));
```
```

**WebDriverManager traces**: 
```
```

**Error log**: 
14:41:53.942    [INFO ][WebDriverThreadLocalContainer] -- No webdriver is bound to current thread: 1 - let's create a new webdriver

14:43:18.800    [WARN ][VersionDetector] -- Error reading commands.properties, using local instead

14:44:43.243    [WARN ][VersionDetector] -- Exception reading CfT URL ('https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json') to get version of chromedriver (Connect to https://googlechromelabs.github.io:443 [googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: no further information)

14:46:07.382    [WARN ][VersionDetector] -- Exception reading https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_117 to get latest version of chromedriver (Connect to https://googlechromelabs.github.io:443 [googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: no further information)

14:47:31.520    [WARN ][VersionDetector] -- Error reading versions.properties, using local instead

14:48:55.670    [WARN ][VersionDetector] -- Exception reading CfT URL ('https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json') to get version of chromedriver (Connect to https://googlechromelabs.github.io:443 [googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: no further information)

14:50:19.802    [WARN ][VersionDetector] -- Exception reading https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE to get latest version of chromedriver (Connect to https://googlechromelabs.github.io:443 [googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: no further information)

14:50:19.806    [INFO ][WebDriverManager] -- Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver

14:55:56.425    [INFO ][ResolutionCache] -- Clearing WebDriverManager resolution cache

14:55:56.427    [WARN ][WebDriverManager] -- There was an error managing chromedriver (latest version) (org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/142.250.186.59, chromedriver.storage.googleapis.com/142.250.185.219, chromedriver.storage.googleapis.com/142.250.181.251, chromedriver.storage.googleapis.com/172.217.16.219, chromedriver.storage.googleapis.com/142.250.186.155, chromedriver.storage.googleapis.com/172.217.18.123, chromedriver.storage.googleapis.com/142.250.186.123, chromedriver.storage.googleapis.com/142.250.74.219, chromedriver.storage.googleapis.com/142.250.186.187, chromedriver.storage.googleapis.com/142.250.184.251, chromedriver.storage.googleapis.com/142.250.186.91, chromedriver.storage.googleapis.com/142.250.185.251, chromedriver.storage.googleapis.com/172.217.16.155, chromedriver.storage.googleapis.com/172.217.18.27, chromedriver.storage.googleapis.com/142.250.184.219, chromedriver.storage.googleapis.com/216.58.206.59] failed: Connection timed out: no further information) ... trying again avoiding reading release from repository

14:55:56.733    [INFO ][WebDriverManager] -- Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver

15:01:33.384    [WARN ][WebDriverManager] -- There was an error managing chromedriver (latest version) (org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/142.250.185.91, chromedriver.storage.googleapis.com/142.250.185.123, chromedriver.storage.googleapis.com/142.250.185.251, chromedriver.storage.googleapis.com/142.250.186.123, chromedriver.storage.googleapis.com/172.217.16.155, chromedriver.storage.googleapis.com/216.58.212.155, chromedriver.storage.googleapis.com/142.250.74.219, chromedriver.storage.googleapis.com/172.217.18.27, chromedriver.storage.googleapis.com/142.250.181.251, chromedriver.storage.googleapis.com/142.250.186.155, chromedriver.storage.googleapis.com/142.250.185.219, chromedriver.storage.googleapis.com/142.250.185.155, chromedriver.storage.googleapis.com/142.250.184.251, chromedriver.storage.googleapis.com/142.250.186.59, chromedriver.storage.googleapis.com/142.250.186.91, chromedriver.storage.googleapis.com/142.250.185.187] failed: Connection timed out: no further information) ... trying again using latest driver stored in cache

15:01:33.394    [INFO ][WebDriverManager] -- Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver

15:07:10.015    [ERROR][WebDriverManager] -- There was an error managing chromedriver (latest version) (org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/172.217.18.123, chromedriver.storage.googleapis.com/142.250.185.251, chromedriver.storage.googleapis.com/142.250.74.219, chromedriver.storage.googleapis.com/142.250.185.219, chromedriver.storage.googleapis.com/142.250.181.251, chromedriver.storage.googleapis.com/172.217.18.27, chromedriver.storage.googleapis.com/142.250.186.59, chromedriver.storage.googleapis.com/142.250.186.123, chromedriver.storage.googleapis.com/142.250.186.155, chromedriver.storage.googleapis.com/142.250.186.187, chromedriver.storage.googleapis.com/216.58.206.59, chromedriver.storage.googleapis.com/172.217.16.155, chromedriver.storage.googleapis.com/142.250.184.219, chromedriver.storage.googleapis.com/142.250.184.251, chromedriver.storage.googleapis.com/142.250.186.91, chromedriver.storage.googleapis.com/172.217.16.219] failed: Connection timed out: no further information)

io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/172.217.18.123, chromedriver.storage.googleapis.com/142.250.185.251, chromedriver.storage.googleapis.com/142.250.74.219, chromedriver.storage.googleapis.com/142.250.185.219, chromedriver.storage.googleapis.com/142.250.181.251, chromedriver.storage.googleapis.com/172.217.18.27, chromedriver.storage.googleapis.com/142.250.186.59, chromedriver.storage.googleapis.com/142.250.186.123, chromedriver.storage.googleapis.com/142.250.186.155, chromedriver.storage.googleapis.com/142.250.186.187, chromedriver.storage.googleapis.com/216.58.206.59, chromedriver.storage.googleapis.com/172.217.16.155, chromedriver.storage.googleapis.com/142.250.184.219, chromedriver.storage.googleapis.com/142.250.184.251, chromedriver.storage.googleapis.com/142.250.186.91, chromedriver.storage.googleapis.com/172.217.16.219] failed: Connection timed out: no further information
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1562)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:132)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1430)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1258)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1177)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1425)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1406)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1183)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1399)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1183)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:425)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.setupWebdriverBinary(ChromeDriverFactory.java:32)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:118)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:118)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:180)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:149)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:72)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:105)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
	at com.codeborne.selenide.Selenide.open(Selenide.java:52)
	....
```
```

**Comment by bonigarcia** [comment]
This seems to indicate a connectivity issue at your end:

```
14:46:07.382 [WARN ][VersionDetector] -- Exception reading https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_117 to get latest version of chromedriver (Connect to [https://googlechromelabs.github.io:443](https://googlechromelabs.github.io/) [googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: no further information)
```

Please see known issues in the doc:

https://bonigarcia.dev/webdrivermanager/#connectivity-issues
