### ISSUE TITLE
No mp4 file actually created in Docker running in Alpine Linux container

### ISSUE THREAD

**Issue by Jmeterrecord** [bonigarcia/webdrivermanager#1146]
**Description of the problem**:  Recording mp4 file is not generated when run with Docker in Alpine Linux container, but the recording file mp4 is generated and viewable when the test is run locally on my Window 10.   The Selenium screen capture of still pictures show that app is displaying correctly in the in the container and the test runs 100% pass locally and in the Alpine Linux container.   Provided that I have installed "Xvfb" and set display, like this:  
   - docker exec $CONTAINER_NAME sh -c "Xvfb :99 &"
   - docker exec  $CONTAINER_NAME sh -c "export DISPLAY=:99"

**Browser and version**:  Chrome 114

**Operating system and architecture**:   Alpine Linux  (Linux runner-gpjrqjwy-project-76369-concurrent-0 4.18.0-477.27.1.el8_8.x86_64  x86_64 Linux)

**Selenium version**:  4.5.0

**WebDriverManager version**: 5.5.3

**WebDriverManager call**: 
```
if (enableRecordings && WebDriverManager.isDockerAvailable()) {
			DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
			desiredCapabilities.acceptInsecureCerts();
			desiredCapabilities.setAcceptInsecureCerts(true);
			String recordingFolderPath = System.getProperty("user.dir") + getProperty("RecordingOutputFolder");
			
			wdm = wdm.browserInDocker().enableRecording().dockerRecordingOutput(recordingFolderPath)
					.dockerRecordingPrefix(getClass().getSimpleName())
					.dockerScreenResolution("1920x1080x24").disableCsp().capabilities(desiredCapabilities);
			driver = wdm.create();

            System.out.println("Create recording ...");
            String pwd = System.getProperty("user.dir");
            System.out.println("CURRENT PWD : " + pwd);
            Path recordingPath = wdm.getDockerRecordingPath();
            System.out.println("recordingpath: " + recordingPath);
            System.out.println("Docker Recording path : " + recordingFolderPath);
            wdm.startRecording();
            driver.get("https://johndoewebsite.com/landing-page/");
            wdm.startRecording();
            driver.get("https://johndoewebsite.com/landing-page/");
            wdm.stopDockerRecording();
            wdm.stopRecording();
```

**WebDriverManager traces**: 
```
    Create recording ...
    CURRENT PWD : /seleniumautotest/SeleniumAutoTest
    recordingpath: /seleniumautotest/SeleniumAutoTest/Recording/TestConfigschrome_2023.10.17_16.23.28.737_8e4afdcf5ce87b26d7ee6ffed0752dbd.mp4
    Docker Recording path : /seleniumautotest/SeleniumAutoTest/Recording
```

**Error log**:  No actual mp4 file is created, and no error.   
```
```

**Comment by bonigarcia** [comment]
I don't know the cause of the problem. In any case, you are not reporting the WebDriverManager traces, and without them, it is very difficult to trace the problem. To get these logs, check this page out:

https://bonigarcia.dev/webdrivermanager/#troubleshooting
