### ISSUE TITLE
Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.   (chrome not reachable)   (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 

### ISSUE THREAD

**Issue by saif8983ansari** [bonigarcia/webdrivermanager#1147]
**Description of the problem**: (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Browser and version**: chrome 118

**Operating system and architecture**: 
Operating system: NAME="Amazon Linux" VERSION="2"

**Selenium version**: 4.13

**WebDriverManager version**: 5.5.3

**WebDriverManager call**: 
```
```

**WebDriverManager traces**: 
```
```

**Error log**: 
stack_trace
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: '1511da2b56a5', ip: '172.17.0.5'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.322-246.539.amzn2.x86_64', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=new, --disable-dev-shm-usage, --remote-debugging-port=9222, --user-data-dir=/home/sassr..., --ignore-certificate-errors, --silent, --no-sandbox], binary: /usr/bin/google-chrome-stable, extensions: []}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	... 5 frames truncated
	... 2 common frames omitted
Wrapped by: java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: '1511da2b56a5', ip: '172.17.0.5'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.322-246.539.amzn2.x86_64', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=new, --disable-dev-shm-usage, --remote-debugging-port=9222, --user-data-dir=/home/sassr..., --ignore-certificate-errors, --silent, --no-sandbox], binary: /usr/bin/google-chrome-stable, extensions: []}}]}]
```
```
Adding my code below
  Add              System.setProperty("webdriver.http.factory", "jdk-http-client");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--headless=new","--disable-dev-shm-usage","--remote-debugging-port=9222","--user-data-dir=/home/sassrv/.config/google-chrome/","--ignore-certificate-errors", "--silent","--no-sandbox");
		options.setBinary("/usr/bin/google-chrome-stable");

		WebDriverManager.chromedriver().clearDriverCache().setup();
		WebDriver driver = new ChromeDriver(options);
		String screenshotFilePath;
		Dimension currentDimension = driver.manage().window().getSize();
		int defaultHeight = currentDimension.getHeight();
		int defaultWidth = currentDimension.getWidth();
		
			logger.info("default driver size "+defaultWidth+" * "+defaultHeight);

			driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);
			driver.get("file://"+htmlFilePath+".html");

**Comment by bonigarcia** [comment]
This is not a WebDriverManager issue. Your Chrome is crashing, so you need to find out why. I would try removing the `--headless=new`, just in case. But perhaps the cause is other.
