### ISSUE TITLE
googlechromelabs.github.io:443

### ISSUE THREAD

**Issue by ShilpaRao2023** [bonigarcia/webdrivermanager#1149]
Hi Team,
Can anyone help me with this issue

'One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (googlechromelabs.github.io:443))'
![Chrome 443](https://github.com/bonigarcia/webdrivermanager/assets/148605540/c8e4832f-7de9-4b0a-8d2a-c72ec4bcc933)

**Comment by mauroao** [comment]
I have the same problem.

**Comment by giulong** [comment]
Can you please provide more info? Which version of WDM are you using? Can you also share the [TRACE log](https://bonigarcia.dev/webdrivermanager/#troubleshooting)? Anything to reproduce your issue is welcome

**Comment by bonigarcia** [comment]
Is it that .NET? If so, you are pointing to the wrong repository. Report it here: https://github.com/rosolko/WebDriverManager.Net
