### ISSUE TITLE
Number Format exception is thrown on versionCompare when using getLatest

### ISSUE THREAD

**Issue by rokko72** [bonigarcia/webdrivermanager#115]
On versionCompare method Method threw 'java.lang.NumberFormatException' exception. Since on IE there is a new IE.Driver.Beta as a version. this causes the driver to fail to download although there are other versions. It would have been better to validate the Integer.valueOf before the compare hence removing it from the list and hence making it not part of the compare process. this means that first line would be validating it is a number.

In current process it is as follows:
1. versionCompare(IE.Driver.Beta,IE.Driver.Beta) -> return IE.Driver>Beta
2. versionCompare(3.3,IE.Driver.Beta) -> Exception and url thrown from list meaning always only IE.Driver.Beta remains meaning no other driver and this driver is not valid.

`public Integer versionCompare(String str1, String str2) {
		String[] vals1 = str1.replaceAll("v", "").split("\\.");
		String[] vals2 = str2.replaceAll("v", "").split("\\.");
		int i = 0;
		while (i < vals1.length && i < vals2.length
				&& vals1[i].equals(vals2[i])) {
			i++;
		}
		if (i < vals1.length && i < vals2.length) {
			int diff = Integer.valueOf(vals1[i])
					.compareTo(Integer.valueOf(vals2[i]));
			return Integer.signum(diff);
		} else {
			return Integer.signum(vals1.length - vals2.length);
		}
	}
`

**Comment by bonigarcia** [comment]
It should be fixed now. It will be available for next version (1.6.2).
