### ISSUE TITLE
Chrome 118 x webdrivermanager 5.5.3 needs update

### ISSUE THREAD

**Issue by jovancosta** [bonigarcia/webdrivermanager#1153]
**Description of the problem**: 
1)the headless options is not been recognized on chrome 118 using webdrivermanager 5.5.3 with Selenium 4.12.1 , 
2)there is no compatible chromedriver in webdrivermanager Lib for chrome v118

**Browser and version**:  chrome 118

**Operating system and architecture**:Windows 10

**Selenium version**: 4.14.1

**WebDriverManager version**: 5.5.3

**WebDriverManager call**: WebDriverManager.chromedriver().setup();
WebDriverManager.chromedriver().options();
options.HEADLESS
I also saw an error on the drive.quit, but I don't have the details here

I opened the ticket with my mobile. I can include more details later

**Comment by giulong** [comment]
Answering to your questions/bullets:

1. Please mind that [how-to-set the headless mode is changing](https://www.selenium.dev/blog/2023/headless-is-going-away/). Moreover, if you were setting the the headless mode with something like this:

```
 WebDriverManager
                .chromedriver()
                .capabilities(new ChromeOptions().setHeadless(true))
                .create();
```

The deprecated `setHeadless()` method was [removed in Selenium 4.14.1](https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG#L46). This is the new way:

```
WebDriverManager
                .chromedriver()
                .capabilities(new ChromeOptions().addArguments("--headless=new"))  // <-- here
                .create();
```

2. It's likely you're relying on an old/cached version. Please try by clearing both caches. Full snippet:

```
WebDriverManager
                .chromedriver()
                .capabilities(new ChromeOptions().addArguments("--headless=new"))
                .clearDriverCache()
                .clearResolutionCache()
                .create();
```

If you still have issues, please provide more info, possibly sharing the [TRACE log](https://bonigarcia.dev/webdrivermanager/#troubleshooting)

**Comment by bonigarcia** [comment]
This issue is caused by WebDriverManager. Thanks a lot @giulong for your input.
