### ISSUE TITLE
Setup() configures the wrong driver for Apple M1

### ISSUE THREAD

**Issue by IvanGambo** [bonigarcia/webdrivermanager#1155]
**Description of the problem**: 
When using Edge browser on Apple M1, setup() sets the driver for X64 instead of M1
I debugged the setup and found that after createUrlHandler(String driverVersion), urlHandler.getCandidateUrls() has 2 values:
- https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_mac64.zip
- https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_mac64_m1.zip

That means it's using the mac64 instead of mac64_m1

**Browser and version**: 
Edge Version 118.0.2088.69

**Operating system and architecture**: 
macOS Venture 13.5.1 - Apple M1

**Selenium version**: 
4.13.0

**WebDriverManager version**: 
5.6.0

**WebDriverManager call**: 
```
WebDriverManager.edgedriver().setup();
```

**WebDriverManager traces**: 
```
[WebDriverManager.java:1473] Driver to be downloaded edgedriver 118.0.2088.76
[WebDriverManager.java:1482] Driver URLs after filtering for version: [
https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_arm64.zip, 
https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_linux64.zip, 
https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_mac64.zip, 
https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_mac64_m1.zip, 
https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_win32.zip, 
https://msedgedriver.azureedge.net/118.0.2088.76/edgedriver_win64.zip
]
```

**Error log**: 
```
```

**Comment by bonigarcia** [comment]
Thanks for reporting. I have just committed a patch to solve this issue. It will be available in the next version of WebDriverManager.
