### ISSUE TITLE
Any chance of allowing the domain hard-coded into CFT_URL to be overridden for corporate use? 

### ISSUE THREAD

**Issue by paul-hammant** [bonigarcia/webdrivermanager#1165]
#FeatureRequest 

https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/java/io/github/bonigarcia/wdm/versions/VersionDetector.java#L77 is the domain hard coded.

Some corporate settings don't allow access to the web, but could easily mirror everything in-house?  How about an env var to allow overriding of the domain ?

- Paul

**Comment by bonigarcia** [comment]
That's a good idea. I would be pleased to merge a PR about that.

**Comment by paul-hammant** [comment]
I'll get on it.  Ideally, it would be a Nexus or an Artifactory that'd be the place where binaries are mirrored. And on there virus checked or whatever corporations do!

**Comment by paul-hammant** [comment]
OK having a slightly deeper look in the code, and I can see `src/main/resources/webdrivermanager.properties` lines 26 to 31 mapping various other chrome-for-testing URLs.

I'm aware that Google changes where the store released versions of chromedriver.exe and wonder if that's the old place. Maybe I'm over thinking this and line 77 of `VersionDetector.java` should be moved to be another property in the same set .. and I should not worry too much. With a test, of course :)

**Comment by paul-hammant** [comment]
OK, so the existing properties are likely good enough.

CFT_URL in `VersionDetector.java` could be replaced with cftUrl like so:

```
            } catch (Exception e) {
                log.warn(
                        "Exception reading CfT URL ('{}') to get version of {} ({})",
                        cftUrl, driverName, e.getMessage());
                String baseCftUrl = InternetDomainName.from(cftUrl).parent().toString();
                try {
                    driverUrl = new URL(baseCftUrl);
                } catch (MalformedURLException e1) {
                    log.error("Exception creating CfT URL {}: {}", baseCftUrl,
                            e.getMessage());
                }
                if (!driverVersion.isPresent()) {
                    versionLabel += "_STABLE";
                }
            }
```

Tests don't hit this logic though.  Maybe I'm mistaken and few real-world usages hit the same catch block. I'll do some research and report back.

**Comment by paul-hammant** [comment]
OK, I think WDM **as is** is ready for useing a property to aim at a local mirror of chromedriver bits and pieces :)
