### ISSUE TITLE
Does it support the method of returning the driver download address?

### ISSUE THREAD

**Issue by zzq517** [bonigarcia/webdrivermanager#1166]
For example, I may want to obtain the corresponding driver download address by passing in browser version and other information, rather than directly helping me download it. Because I may deploy this application to the server, the client obtains the download address of the driver by passing in parameters

**Comment by bonigarcia** [comment]
Do you mean the driver download URLs? If so, no, that is not currently supported by WebDriverManager. You can try to contribute to the project with a PR about that.
