### ISSUE TITLE
WebDriverManager is not working

### ISSUE THREAD

**Issue by krisheltropy** [bonigarcia/webdrivermanager#1178]
I was using selenium version 3.141 and webdrivermanager 5.4.1.

Things were working fine when executed the test cases from IDE. When I used gradle commandline to run, the build failed and had to fix the version(55 and 52 issue). But then the session itself is not running. 
Getting this error:
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 119.0.6045.199 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
Host info: host: 'Krishnas-MacBook-Pro.local', ip: '2405:201:5c05:216d:780a:a8ac:6aef:11b8%en0'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1', java.version: '11.0.19'
Driver info: org.openqa.selenium.chrome.ChromeDriver

It seems as if the webdrive is not being picked up from webdrivermanager but from the system.
Tried a lot of version combinations of selenium and webdrivermanager, no good.

**Comment by Eugene753** [comment]
In this doc https://bonigarcia.dev/webdrivermanager/#support-for-chromedriver-115 mentions that for chromedriver versions 115+ now can be programmatically discovered using the 'Chrome for Testing (CfT) JSON endpoint'. It was added to webdrivermanager v5.6.2, if this won't work try to clean cache, running this command once 'WebDriverManager.chromedriver().clearDriverCache().setup();' helped me to fix the issue.

**Comment by bonigarcia** [comment]
Duplicated: https://stackoverflow.com/questions/77573885/getting-a-mismatch-with-the-chrome-version-for-selenium-project

**Comment by mP1** [comment]
Just to help i can confirm the following works today 4 Feb 2024...

- Ive deleted Chrome For Testing.
- Updated my REAL chrome to latest (Version 121.0.6167.139 (Official Build) (x86_64)
- webdrivermanager 5.6.2

**Comment by NidhiGarg15** [comment]
Same issue has started coming again with Chrome version122.0.6261.70.
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 122.0.6261.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by isorbon** [comment]
The same issue I got when I use WebDriverManager with Chrome, relevant version is 122 and with Edge.
With firefox works fine.
