### ISSUE TITLE
1.3.1 missing in central repo

### ISSUE THREAD

**Issue by wilx** [bonigarcia/webdrivermanager#12]
I see you have recently released version 1.3.1 of your webdrivermanager. I am specifically interested in it because of the Edge driver. [I do not see the version 1.3.1 in central repository.](http://search.maven.org/#search|gav|1|g%3A%22io.github.bonigarcia%22%20AND%20a%3A%22webdrivermanager%22) It would be really really awesome if you could upload it very soon. :)

**Comment by bonigarcia** [comment]
It is now [available](http://search.maven.org/#artifactdetails%7Cio.github.bonigarcia%7Cwebdrivermanager%7C1.3.1%7Cjar).
