### ISSUE TITLE
Not downloading previous version of chrome on mobile

### ISSUE THREAD

**Issue by Redinbox** [bonigarcia/webdrivermanager#1202]
We are using webdrivermanger for desktop and mobile browser management. what we have observed in mobile device in case of chrome version 109, 113,..lower version not getting downloaded but if it is 120 then its working fine.
is there any work around or fix for this?

**Comment by bonigarcia** [comment]
I don't understand this issue. Please follow the issue template to report your problem with WebDriverManager.
