### ISSUE TITLE
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 503 executing https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip

### ISSUE THREAD

**Issue by SchwartzGi** [bonigarcia/webdrivermanager#1230]
Getting this error:

io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 503 executing
https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip

**Comment by bonigarcia** [comment]
I suppose this is a connectivity issue at your end. See [doc](https://bonigarcia.dev/webdrivermanager/#connectivity-issues).
