### ISSUE TITLE
WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"

### ISSUE THREAD

**Issue by gowthamrajar** [bonigarcia/webdrivermanager#1234]
> here is the log The webDriverManager version i have is implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.6.3' Even tried 5.6.2 but its still the same
> 
> failing at my code statements below, tried both of them WebDriverManager.chromedriver().setup(); WebDriverManager.chromedriver().clearDriverCache().setup();
> 
> o.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
> 
> ```
> at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
> at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
> at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
> at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1432)
> at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
> at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1425)
> at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
> at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
> at com.pandora.qa.oms.TestBase.beforeSuite(TestBase.java:45)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
> at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
> at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
> at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
> at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
> at org.testng.SuiteRunner.run(SuiteRunner.java:364)
> at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
> at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
> at org.testng.TestNG.runSuites(TestNG.java:1049)
> at org.testng.TestNG.run(TestNG.java:1017)
> at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
> at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
> ```
> 
> Caused by: java.lang.NumberFormatException: For input string: "public" at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.base/java.lang.Integer.parseInt(Integer.java:652) at java.base/java.lang.Integer.parseInt(Integer.java:770) at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:178) at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:155) at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1272) at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189) ... 26 more

**Comment by Elwis28** [comment]
We had the same issue, but upgrading to 5.7.0 solved this.

**Comment by bonigarcia** [comment]
Duplicated of #1226. Update to 5.7.0.
