### ISSUE TITLE
CONNECT refused by proxy; HTTP/1.1 407 Proxy Authentication required with webdrivermanager 5.7.0

### ISSUE THREAD

**Issue by cyndihu** [bonigarcia/webdrivermanager#1241]
when I use webdrivermanager 5.5.0, I can download edge 121 but fail to download chrome 121, then I upgrade webdrivermanager to 5.7.0, I cannot download both edge and chrome with error: CONNECT refused by proxy; HTTP/1.1 407 Proxy Authentication required. can you please help?

selenium version: 4.3.0
webdrivermanager version: 5.7.0

WebDriverManager.edgedriver().proxy("proxy").proxyUser("user").proxyPass("pass").setup();

![image](https://github.com/bonigarcia/webdrivermanager/assets/44665141/ecbb37fb-6d93-48c0-99a3-c05f5f6fc6c0)

**Comment by bonigarcia** [comment]
I don't know the cause of the problem. It seems the proxy setup is not correct.
