### ISSUE TITLE
Seeing Error io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public" 

### ISSUE THREAD

**Issue by vvsbalu** [bonigarcia/webdrivermanager#1245]
Its working fine on local but facing this issue in jenkins pipeline which is hosted on remote window machine.
Versions using in our env
chrome --> Version 122.0.6261.70 (Official Build) (64-bit)
webdrivermanager - 5.7.0
selenium-java -- 3.141.59

**Comment by bonigarcia** [comment]
Using the latest WebDriverManager version (5.7.0 at the time of this writing) and clearing the cache (at least once) should fix this issue:

```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

If not, please report your WebDriverManager traces. See: https://bonigarcia.dev/webdrivermanager/#troubleshooting

Also, please follow the issue template for reporting any issue.
