### ISSUE TITLE
Allow the option to skip BETA drivers

### ISSUE THREAD

**Issue by OndrejSkalicka** [bonigarcia/webdrivermanager#127]
With default configuration of 

`InternetExplorerDriverManager.getInstance().arch32().setup();`

WebDriverManager downloads newest driver, even if that is unstable / beta. Since the newest IE x32 is now beta and does not really work correctly, there is no way to tell WebDriverManager to download "newest stable version". The only option is to use

`InternetExplorerDriverManager.getInstance().version("3.3").arch32().setup();` 

but that requires manual setup to find the newest stable version and has to be managed manually.

I suggest adding a `requireStable()` option to `BrowserManager` API, otherwise selenium tests might be affected even with no changes in codebase.

**Comment by bonigarcia** [comment]
You have a point here. I think I am going to implement something similar. For next version, the default behaviour of wdm will be skipping beta versions. As you said, we cannot rely 100% in these. On the other hand, I can add a new method to the BrowsermManager API to take beta version into account (`fetchBetaVersions()` or something similar).

**Comment by bonigarcia** [comment]
Solved in version 1.7.0.
