### ISSUE TITLE
Issue with changing Edge Driver version

### ISSUE THREAD

**Issue by jedzme** [bonigarcia/webdrivermanager#128]
Hi,

Thanks for this awesome project!

By the way, I tried changing the Edge driver version to Version: 3.14393 via java using either of these:

System.setProperty("wdm.override", "true");
System.setProperty("wdm.edgeVersion", "3.14393");

or

System.setProperty("wdm.override", "true");
System.setProperty("wdm.edgeVersion", "14393");

I also tried commenting out the System.setProperty("wdm.override", "true");
But the driver being downloaded is still the latest version which is 4.15063.

I verified this by looking at the MicrosoftWebdriver in my .m2 folder.
I tried deleting it several times to verify.

Is this an issue?

Regards,
Jedz

**Comment by bonigarcia** [comment]
The Edge driver web does not allow to select one or another version. For that reason, WebDriverManager is not able to select which version to download. Only if the binary was previously downloaded (i.e. exists in the cache), the version selection will work for Edge.
