### ISSUE TITLE
Latest Driver download not downloading proper driver for specific OS

### ISSUE THREAD

**Issue by Kosles27** [bonigarcia/webdrivermanager#1297]
Hello,
While running automated tests on a Kubernetes pipeline I've noticed that the edge driver being downloaded is the Latest Release (in image)
![image](https://github.com/bonigarcia/webdrivermanager/assets/86309302/ed0dd2ad-30cd-41b7-8158-3a7f506c291e)
however this driver version was not available at the time for the linux OS i'm using,
![image](https://github.com/bonigarcia/webdrivermanager/assets/86309302/16820ab5-8681-4966-9f72-42e3c897e3bf)
it was updated for all OS now however I felt as if I should mention this issue here.

driver initiates like this in my code:
WebDriverManager.edgedriver().setup();

**Comment by bonigarcia** [comment]
Please follow the issue template to report any issue. I would need to know the WebDriverManager version and the complete traces in `DEBUG` or `TRACE` level.
