### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure

### ISSUE THREAD

**Issue by batoolawaan** [bonigarcia/webdrivermanager#1307]
I want to upgrade Chrome browser version from v108 to v126.0 in Selenium grid but I am getting SessionNotCreatedException.  I have made following changes:

1. Updated selenium-java version from 4.13.0 to 4.22.0
2. Updated webdrivermanager version from 5.5.3 to 5.9.1
3. Updated selenium-devtools-v108 4.8.1 to selenium-devtools-v126 4.22.0.
4. Updated node-chrome:108.0 to node-chrome:126.0
5. Updated selenium-hub from 4.8.1 to 4.22.0

everything is working fine with older version, chrome session are creating and running properly but when updating the versions I am getting SessionNotCreatedException.
I have also done this:   
**WebDriverManager.chromedriver().clearDriverCache().setup();**

pom.xml

```
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.22.0</version>
    </dependency>

    <dependency>
      <groupId>io.github.bonigarcia</groupId>
      <artifactId>webdrivermanager</artifactId>
      <version>5.9.1</version>
    </dependency>

    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-devtools-v126</artifactId>
      <version>4.22.0</version>
    </dependency>
```

**[Chrome_logs.txt](https://github.com/user-attachments/files/15972066/Chrome_logs.txt)**

**[SeleniumHub_Logs.txt](https://github.com/user-attachments/files/15972069/SeleniumHub_Logs.txt)**

![ErrorLog](https://github.com/bonigarcia/webdrivermanager/assets/69149269/0618a392-e8dc-4f16-b1f0-6fa01211cd23)
![GridOverview](https://github.com/bonigarcia/webdrivermanager/assets/69149269/3a6f0f15-a3e3-4b78-8c41-59bd4400eacb)
![GridSessionCapabilities](https://github.com/bonigarcia/webdrivermanager/assets/69149269/3568e07d-1db8-4dc3-83a1-e11fbda34208)
![SessionInQueue](https://github.com/bonigarcia/webdrivermanager/assets/69149269/846b4d0d-f0d2-40c2-a818-588f19fd041a)

![pomxml](https://github.com/bonigarcia/webdrivermanager/assets/69149269/4aca66d9-a699-4bde-92e7-0b8e7ec362bd)

![webdriverCacheClear](https://github.com/bonigarcia/webdrivermanager/assets/69149269/6e0ecf7f-8a6d-4fa3-8c3c-948b05360d7e)

![env file](https://github.com/bonigarcia/webdrivermanager/assets/69149269/7cc8cf73-1e74-4db5-b6b9-1c1e0e6b4059)

**Comment by bonigarcia** [comment]
This issue is not related with WebDriverManager. In fact, you can delete the calls to WebDriverManager, which are not necessary when using Selenium Grid. You can try to ask for support about Selenium Grid in the Selenium Slack channel:

https://www.selenium.dev/support/
