### ISSUE TITLE
Provide a "fat-jar"

### ISSUE THREAD

**Issue by mseele** [bonigarcia/webdrivermanager#132]
We do not use maven (jars in a library folder) and therefore it's hard to keep up to date with all the dependencies.

Is it possible to provide a "fat-jar" with all the needed libraries as second option (like selenium with "selenium-server-standalone-x.x.x.jar" does)?

That would help us a lot. Thanks.

**Comment by bonigarcia** [comment]
Take a look to [this](http://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven).
