### ISSUE TITLE
phantomjs - issue fetching latest binary

### ISSUE THREAD

**Issue by isgarlo** [bonigarcia/webdrivermanager#136]
Steps to reproduce:
1) Setup and create a PhantomJSDriver pointing to the latest binaries:
PhantomJsDriverManager.getInstance().setup();
new PhantomJSDriver();

Actual result:
An exception is thrown:
Referenced from: /Users/xxx/.m2/repository/webdriver/phantomjs/macos/2.5.0/phantomjs
Reason: image not found

As I can see from https://bitbucket.org/ariya/phantomjs/downloads/ the latest version is **2.5.0-beta**. Maybe that _-beta_ is causing the issue.
Is this one related to issue #127 ?

**Comment by bonigarcia** [comment]
Yes, somehow it is related. I need some time to implement the new behaviour (i.e. avoid beta versions by default).

**Comment by bonigarcia** [comment]
Solved in version 1.7.0.
