### ISSUE TITLE
Add chrome canary option

### ISSUE THREAD

**Issue by FranAguiar** [bonigarcia/webdrivermanager#137]
When request a new chrome instance, default binary path is settled, in some cases would be useful to set a non stable chrome.

BTW. Thanks for this tool.

**Comment by bonigarcia** [comment]
This question has nothing to do with WebDriverManager. To change that, you need to customize the way you create Selenium WebDriver. See for example [this](https://stackoverflow.com/questions/18499367/run-webdriver-with-chrome-canary).
