### ISSUE TITLE
ChromeDriverManager().install() does not return the chromedriver path but instead THIRD_PARTY_NOTICES.chromedriver

### ISSUE THREAD

**Issue by pmouget** [bonigarcia/webdrivermanager#1375]
Did it. My current version is webdriver-manager-4.0.2

**Description of the problem**: 
ChromeDriverManager().install() does not return the chromedriver path but instead THIRD_PARTY_NOTICES.chromedriver

**Browser and version**: 
Chrome: 129.0.6668.101
Chromedriver: 129.0.6668.100

**Operating system and architecture**: 
Windows 11 x64

**Selenium version**: 
selenium == 3.14.1

**WebDriverManager version**: 
webdriver-manager-4.0.2

**WebDriverManager call**: 
ChromeDriverManager().install()
```

**WebDriverManager traces**: <!-- Copy the WebDriverManager traces here. This information is very important to analyze your issue, so please do not skip this part. Find more info about how to get the WebDriverManager traces here: https://bonigarcia.dev/webdrivermanager/#troubleshooting -->
```
```

**Error log**: <!-- Copy the Java error trace (if any) here. -->
```
```

**Comment by bonigarcia** [comment]
Wrong repo. Not sure if that is Python or JavaScript, but definitively not Java.

**Comment by pmouget** [comment]
it's python. Do I need to create a new ticket?
