### ISSUE TITLE
Support for Chrome Headless browser

### ISSUE THREAD

**Issue by RajAsapu** [bonigarcia/webdrivermanager#139]
Please include support for chrome headless browser

Chrome download url : https://www.google.com/chrome/browser/desktop/index.html?extra=devchannel&platform=win64

We have a need to use headless browser in our project and chrome 59+ has the support for it.So please add the dependencies for those.

I would be able to work with below code once i have the support

         ChromeOptions options = new ChromeOptions();
                options.addArguments("--headless");
                options.addArguments("--disable-plugins");
                options.addArguments("--start-maximized");
                options.addArguments("--disable-extensions");

**Comment by bonigarcia** [comment]
WebDriverManager just automated the management (download and export the proper variable) needed to use Selenium WebDriver from Java code. What you are proposing has to do with the way you instantiate ChromeDriver, and so, it is out of the scope of WebDriverManager.

**Comment by RajAsapu** [comment]
@bonigarcia : Does it have support for chromedriver 2.29 ! thats my question
