### ISSUE TITLE
Gecko driver Cannot read the array length because "<local8>" is null

### ISSUE THREAD

**Issue by amir-lili** [bonigarcia/webdrivermanager#1393]
im using the latest version (5.9.2)
at this part of code (setup function) : 
```
WebDriverManager.firefoxdriver().clearDriverCache().setup(); <——
WebDriverManager.firefoxdriver().clearResolutionCache().setup();
WebDriverManager.firefoxdriver().setup();
```

im getting the following exception:

```
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NullPointerException: Cannot read the array length because "<local8>" is null
```

the issue started in the last 2 hours +-, earlier today there was no issue at all.

**Comment by bonigarcia** [comment]
Please try again. There were an [issue](https://github.com/bonigarcia/webdrivermanager/issues/1392) related to the online endpoint, which is solved now.

**Comment by amir-lili** [comment]
now its solved, thanks a lot @bonigarcia 👑
