### ISSUE TITLE
OperaDriver is not getting downloaded

### ISSUE THREAD

**Issue by DmitryRak** [bonigarcia/webdrivermanager#146]
I used WebDriverManager in my project. Tried to run tests in different browsers. Chrome, Firefox, IE11 work fine, but I've got an error for Opera:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting OperaDriver 0.2.0 (ba47709ed9e35ce26dbd960fb5d75be104290d96) on port 41796
Only local connections are allowed.
org.openqa.selenium.WebDriverException: unknown error: cannot find Opera binary
  (Driver info: OperaDriver=0.2.0 (ba47709ed9e35ce26dbd960fb5d75be104290d96),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 71 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'PC', ip: '192.168.0.15', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: OperaDriver`

**Comment by DmitryRak** [comment]
Also please note that version 0.2.0 tried to be used while the latest one is 0.2.27

**Comment by bonigarcia** [comment]
It seems related to #134.

**Comment by bonigarcia** [comment]
Solved in version 1.7.0.
