### ISSUE TITLE
support for --headless in chrome

### ISSUE THREAD

**Issue by hennr** [bonigarcia/webdrivermanager#148]
Hi,

are there any plans to add a method which enables the headless mode that is available in chrome 59+?

**Comment by bonigarcia** [comment]
Headless Chrome can be used simply changing the way it is instantiated the `ChromeDriver` object, totally independent to WebDriverManager. [Here](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ChromeHeadlessTest.java) you can find an example (working with Chrome 59, in Linux).
