### ISSUE TITLE
using with maven-failsafe-plugin

### ISSUE THREAD

**Issue by stepio** [bonigarcia/webdrivermanager#15]
Hi,

First of all, thanks for sharing your library!
Is it possible to use it with maven-failsafe-plugin? Have you tried this already?

**Comment by bonigarcia** [comment]
Hi there,

WebDriverManager works in runtime, so I don't see any potential issue to be used in conjunction with failsafe/surefire Maven plugins.

Kind regards,
Boni

**Comment by stepio** [comment]
Hi again, thanks for the prompt response.

Actually, as I understand, to use your library I need to initialise the appropriate driver.
So I had to include the next code into the tests:
```java
        switch (getBrowser()) {
            case "chrome":
                ChromeDriverManager.getInstance().setup();
                break;
            case "iexplorer":
                InternetExplorerDriverManager.getInstance().setup();
                break;
            case "edge":
                EdgeDriverManager.getInstance().setup();
                break;
            case "opera":
                OperaDriverManager.getInstance().setup();
                break;
        }
```
So I've just wanted to consult if I'm doing this right or wrong. Maybe you already have the solution for this.

**Comment by bonigarcia** [comment]
Hi again,

Yes, that code looks nice.

Alternatively, you can call to the generic manager, i.e. `WebDriverManager`. You can find an example [here](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/WebDriverTest.java).

Kind regards,
Boni

**Comment by stepio** [comment]
Ok, thanks!
