### ISSUE TITLE
Authentication failed on NTLM Proxy

### ISSUE THREAD

**Issue by andrew-sumner** [bonigarcia/webdrivermanager#150]
I've raised a pull request that resolves this issue.  

It adds an NTCredentials to the BasicCredentialsProvider that is scoped to AuthSchemes.NTLM so will not impact any other proxy types.

Assuming you accept this pull request do you have a timeframe for your next release as this is causing some problems on our project.

Regards
  Andrew

**Comment by bonigarcia** [comment]
I have just reviewed your PR, and I have several concerns about it.

What happen if not using NTLM?
Have you tested it properly? (I mean with and without NTLM) To be more confident about that I would need some automated test together with the PR.

Moreover, the `getWorkstation` method seems a bit weird.

What happen when the hard-coded word `Unknown` is returned? If possible, I would avoid doing things like this.

Regarding your question about the timing, I plan to release a new version of wdm quite soon. If you want your PR to be merged I need you to improve it a bit.

**Comment by andrew-sumner** [comment]
My change only affects NTLM proxies:

This authScope setting restricts the NTCredentials to NTLM proxies
_authScope = new AuthScope(proxyHost.getHostName(), proxyHost.getPort(),  AuthScope.ANY_REALM, AuthSchemes.NTLM);_

While this authScope is sets allows the UsernamePasswordCredentials to become the default credentials for all other proxy types.
_authScope = new AuthScope(proxyHost.getHostName(), proxyHost.getPort());_
 
I have thouroughly tested this change and the getWorkstation() method in a windows envrionment behind an NTLM proxy as I have been using this code in a rest library that I built for use at work because I struggled to find anything that would work through an NTLM proxy.  

Regarding getWorkstation(), I've just had a look at the code for NTCredentials and null is a valid value.  I'm updating my pull request so getWorkstation() will return null instead of unknown.  If you still don't like getWorkstation() then I'm happy to remove it and just supply null for that value.

When you say "provide some automated tests for the PR" I don't know how I would do this for a proxy.  I haven't seen any tests in the code base for proxies and don't have access to non NTLM proxy for manual testing.  Any suggestions?

**Comment by bonigarcia** [comment]
Thanks for your comments.

Regarding the test, take a look to [this one](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ProxyTest.java). Maybe something similar can be done to test your code. Please let me know.

**Comment by andrew-sumner** [comment]
I've added testCredentials() to ProxyTest.java to illustrate my changes and prove that only NTLM proxies are affected by my change.

There are some nice proxy tests in there by the way - I might have to "borrow" some for my rest client :-)

**Comment by andrew-sumner** [comment]
Just noticed the merge conflict in ProxyTest.  All sorted now.

**Comment by bonigarcia** [comment]
Thanks for contributing. It has been merged and released to Maven Central in version 1.7.1.
