### ISSUE TITLE
JUNit with @RunWith(Parameterized.class) class?

### ISSUE THREAD

**Issue by kaygee** [bonigarcia/webdrivermanager#153]
Should this project work with https://github.com/junit-team/junit4/wiki/parameterized-tests? I'm having results such as the browsers not starting and/or parameters (@Parameter) not being injected.

**Comment by christian-draeger** [comment]
Should have nothing to do with the webdriver manager. Me using it different kind of parameterized tests (junit parameterized test, Junit theories and Junit params runner, most of them running in parallel with different runners). Never found issues regarding WDM. Can you serve an example test or link to an example project? 

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kaygee** [comment]
Thanks for the response @christian-draeger. The issue was coming from elsewhere in my code. In other words... my bad! :)
