### ISSUE TITLE
[Suggestion] wdm architecture property

### ISSUE THREAD

**Issue by kyleshrader** [bonigarcia/webdrivermanager#154]
Is there a wdm.{drivername}Architecture property available to use in wdm config? It is a common practice to use 32-bit ie on all platforms, so this is important to specify for ie, for the time being.

**Comment by larryricker** [comment]
Use this syntax to get the 32 bit version:
		InternetExplorerDriverManager.getInstance().arch32().setup();
The 64 bit version is terribly slow and after one test it is terribly apparent that the 64 bit version is downloaded by default.

**Comment by kyleshrader** [comment]
Sure. I would like to manage this with configuration, so if we could get that as a wdm properties value that would be preferable. I am currently managing my own configuration file and using architecture(Architecture arch)

**Comment by bonigarcia** [comment]
Implemented in [cc80823](https://github.com/bonigarcia/webdrivermanager/commit/cc808239a52fd6f7c6aadac1934a9cd41499327b). To be available in next version (although there is no date for next release, sorry).
