### ISSUE TITLE
Which selenium-server-standalone is downloaded and where is it stored?

### ISSUE THREAD

**Issue by goatsy** [bonigarcia/webdrivermanager#156]
Hello,
I implemented the webdrivermanager into our selenium framework and it works really good. Thank you for the efforts made.

My question:

As I don't have to manually start the selenium-server-standalone.jar I assume webdrivermanager downloads it automatically. Where is it downloaded? I can find the different drivers for the browsers but not the selenium-server-standalone.jar
Can you please explain where the standalone server is located and if I can determine which version to download.

I would also love to see the output console of the standalone server for debugging reasons, where can I find it?

Thank you.

**Comment by bonigarcia** [comment]
WebDriverManager downloads automatically WebDriver binaries (e.g. *chromedriver* or *geckodriver*), not JAR files. I suppose you are using a build tool (Maven, Gradle), and therefore your *.jar files should be located in your local repository (`~/.m2/repository` or `~/.gradle/caches/modules-2/files-2.1` respectively).

**Comment by goatsy** [comment]
Thanks for your answer. 
Is it possible that the console of the standalone-server is displayed automatically? 
I want to see what steps are currently done.
