### ISSUE TITLE
SAXParseException on local chromedriver storage

### ISSUE THREAD

**Issue by dimkin-eu** [bonigarcia/webdrivermanager#157]
We created local mirror of  `http://chromedriver.storage.googleapis.com/index.html`
Created `webdrivermanager.properties` with record
`wdm.chromeDriverUrl=https://rms.___.com/chromedriver/`
and it fails with
`09:12:33.364 WARN [main] [io.github.bonigarcia.wdm.BrowserManager] [1/3] Exception reading https://rms.___.com/chromedriver/ to seek [chromedriver]: org.xml.sax.SAXParseException White spaces are required between publicId and systemId.`

1. it fails because page sourse has
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">`
not (note extra `""`)
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN" "">`

should we add "" to source or it could be fixed?
2. `http://chromedriver.storage.googleapis.com/` actually points to xml file
do wdm need this file or it takes all drivers from `http://chromedriver.storage.googleapis.com/index.html`?

**Comment by bonigarcia** [comment]
Regarding `chromedriver`, the important thing for WebDriverManager is the information in the XML file, not the HTML. Said that, to mirror the host of `chromedriver` binaries, you need to take care of the XML file in your local repository. The content of that file should be the same as the one contained in [http://chromedriver.storage.googleapis.com/](http://chromedriver.storage.googleapis.com/):

```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
    <Name>chromedriver</Name>
    <Prefix />
    <Marker />
    <IsTruncated>false</IsTruncated>
    <Contents>
        <Key>2.0/chromedriver_linux32.zip</Key>
        <Generation>1380149859530000</Generation>
        <MetaGeneration>2</MetaGeneration>
        <LastModified>2013-09-25T22:57:39.349Z</LastModified>
        <ETag>"c0d96102715c4916b872f91f5bf9b12c"</ETag>
        <Size>7262134</Size>
    </Contents>
    <Contents>
        <Key>2.0/chromedriver_linux64.zip</Key>
        <Generation>1380149860664000</Generation>
        <MetaGeneration>2</MetaGeneration>
        <LastModified>2013-09-25T22:57:40.449Z</LastModified>
        <ETag>"858ebaf47e13dce7600191ed59974c09"</ETag>
        <Size>7433593</Size>
    </Contents>

    ...

</ListBucketResult>
```

**Comment by alatyshev** [comment]
With XML file from http://chromedriver.storage.googleapis.com/ also uploaded to Artifactory, I am getting this error:

[Fatal Error] :1:55: White spaces are required between publicId and systemId.io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 55; White spaces are required between publicId and systemId.

Any suggestion how to fix it?
