### ISSUE TITLE
Is there any plans for Safari browser?

### ISSUE THREAD

**Issue by kermek** [bonigarcia/webdrivermanager#16]

**Comment by bonigarcia** [comment]
In order to use Safari with WebDriver it is required the installation of an [extension](http://www.seleniumhq.org/download/) in the browser.

I don't know how to do it automatically from Java code, I think it is not possible. Do you know any way to do it?

**Comment by rosolko** [comment]
As I know, for now you can't manually add extension to safari from code. 
But you can add it to safari manually and after that use `System.setProperty("webdriver.safari.noinstall", "true");` property to stop uninstall it.

**Comment by bonigarcia** [comment]
Maybe that's an alternative, thanks for the pointer. I'll try to look into it as soon as I have time.

As always, pull requests are welcome.
