### ISSUE TITLE
Exception while initializing Webdriver

### ISSUE THREAD

**Issue by gitissuepost** [bonigarcia/webdrivermanager#160]
@bonigarcia 
Post instance setup, while initializing webdriver, it is throwing timeout exception.
Version Used : 1.7.2

> 1518 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
2273 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Latest version of [chromedriver] is 2.32
2288 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Exporting webdriver.chrome.driver as C:\Users\XXXXXXXX\.m2\repository\webdriver\chromedriver\win32\2.32\chromedriver.exe
Oct 01, 2017 12:27:33 PM org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\XXXXXX\.m2\repository\webdriver\chromedriver\win32\2.32\chromedriver.exe" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)

Code:

```
package dummy;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.ChromeDriverManager;

public class Dummy3 {	
	@BeforeClass
	public static void setupClass() {
		ChromeDriverManager.getInstance().setup();
	}
	@Test
	public void driverManagerTest() {
		WebDriver driver = new ChromeDriver();
		driver.quit();
	}
}
```

pom.xml
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>dummy</groupId>
	<artifactId>dummy</artifactId>
	<version>0.0.1</version>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<!-- <encoding>UTF-8</encoding> -->
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>1.7.2</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.5.1</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.11</version>
		</dependency>
	</dependencies>
</project>
```

**Comment by gitissuepost** [comment]
This is intermittent. But, it will be helpful, if I know, why it was throwing this exception

**Comment by bonigarcia** [comment]
No clue. Is this error still happening to you?
