### ISSUE TITLE
How to add browser extensions using WebDrivermanager

### ISSUE THREAD

**Issue by Samolevar** [bonigarcia/webdrivermanager#162]
Can i somehow add extensions for browsers (chrome or IE) if i am using WebDrivermanager library? And if not how can i connect this functionality with selenium's ChomeOptions?

**Comment by gitissuepost** [comment]
WebDriverManager helps in downloading the latest/expected version of driver executable just before execution instead maintaining these on our own.

Extensions and exceptions are independent of how you are handling driver executable. So, same statements as in the usual approach, can be used here as well.
