### ISSUE TITLE
WebDriverManager tries to use ZIP even if it was partially downloaded because of I/O error

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#163]
Below is a log from my failing build. 
WebDriverManager started downloading `chromedriver_linux64.zip` - and created this file. But some I/O error happened during download. 

To avoid this problem, there is a common practice to download content to a temporary file, and only when it's finished, rename this file to `chromedriver_linux64.zip`. It also avoids problems when other test processes run at the same time and try to use the `chromedriver_linux64.zip` being downloaded at the moment. 

```
INFO BrowserManager - Latest version of [chromedriver] is 2.33

INFO Downloader - Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip to /home/travis/.m2/repository/webdriver/chromedriver/linux64/2.33/chromedriver_linux64.zip

WARN BrowserManager - There was an error managing [chromedriver] LATEST (invalid distance code) ... trying again forcing to use cache

INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]

INFO BrowserManager - Exporting webdriver.chrome.driver as /home/travis/.m2/repository/webdriver/chromedriver/linux64/2.33/chromedriver_linux64.zip
```

**Comment by asolntsev** [comment]
Fixed in pull request https://github.com/bonigarcia/webdrivermanager/pull/164

**Comment by bonigarcia** [comment]
Thank you very much for your contribution. Merged.
