### ISSUE TITLE
WebDriverManagers export ZIP instead of binary

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#165]
... when tests run in parallel processes.

I run tests in parallel using Gradle `maxParallelForks = 2` option. It means that tests run in parallel **processes**, not threads. It means that all keywords `synchronized` in WebDriverManager sources have no effect. 

Below is a log from my tests. 
You can see that 
* in one process, `webdriver.chrome.driver=.../chromedriver`,
* but in the other process, `webdriver.chrome.driver=.../chromedriver_linux64.zip`

```
INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]

INFO Downloader - Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip to /home/jenkins/.m2/repository/webdriver/chromedriver/linux64/2.33/chromedriver_linux64.zip
INFO Downloader - Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip to /home/jenkins/.m2/repository/webdriver/chromedriver/linux64/2.33/chromedriver_linux64.zip

INFO BrowserManager - Exporting webdriver.chrome.driver as /home/jenkins/.m2/repository/webdriver/chromedriver/linux64/2.33/chromedriver_linux64.zip
INFO BrowserManager - Exporting webdriver.chrome.driver as /home/jenkins/.m2/repository/webdriver/chromedriver/linux64/2.33/chromedriver
```

**Comment by bonigarcia** [comment]
I think with your PR about the temporary file this behavior should not happen. It will be available in next version.
