### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by andrew-sumner** [bonigarcia/webdrivermanager#169]
I'm developing an open source test framework (https://github.com/concordion/cubano) for [Concordion](http://concordion.org) and WebDriverManager has become central to how I manage browser drivers.

Concordion's project lead was reviewing Cubano to ensure that there weren't any issues with licences and unfortunately he's come back with an issue around WebDriverManager.  Here's his observation:

The webdrivermanager project is licensed under LGPL. The problem with LGPL is that it is incompatible with the Apache 2.0 license that Concordion uses. As per the Apache legal page:

> WHICH LICENSES MAY NOT BE INCLUDED WITHIN APACHE PRODUCTS?
> ...
> GNU LGPL 2, 2.1, 3

We do have one LGPL-licensed library in Concordion, XOM, which we plan to replace at some stage. For example, the use of this library has caused trouble for the Isis project, which has meant that it needs to be excluded from the pom.xml and requires end-users to explicitly add the reference to XOM in their own pom files. I'm keen to avoid this sort of nonsense.

Is the webdrivermanager project is open to changing their license or dual licensing the project under LGPL and Apache?

**Comment by bonigarcia** [comment]
Yes, that can be a good idea. I will change to a dual licence (LGPL-Apache) for next version.

**Comment by andrew-sumner** [comment]
That is awesome news, thank you!

**Comment by bonigarcia** [comment]
Done, next version will be Apache 2.
