### ISSUE TITLE
ignoreVersions(String ... versions) [enhancement]

### ISSUE THREAD

**Issue by Mincol** [bonigarcia/webdrivermanager#171]
I would like to ask for new method called ignoreVersions.

It will take list of versions I do not want to download, because I know they do not work. If newer version is downloaded, webdrivermanager should log warning stating that newer version is available, thus ignoreVersions may be removed from code base.

**Comment by bonigarcia** [comment]
Yes, it can be useful. I am planning to release a new version soon. If you are very interested in this feature, please make a PR implementing this.

**Comment by bonigarcia** [comment]
Done
