### ISSUE TITLE
Sometimes can't set System Property for WebDriver in parallel run

### ISSUE THREAD

**Issue by ansonliao** [bonigarcia/webdrivermanager#172]
* `WDM` version: 1.7.2
* Platform: Mac OS 10.13.1
* Java version: 1.8.0_121

I know someone raised the same issue before: https://github.com/bonigarcia/webdrivermanager/issues/42

But I am facing the problem, and looks like still not fixed.

I created two TestNG test classes,

* one test class initialize `ChromeDriver` by `ChromeDriverManager.getInstance().setup();`
* The another test class initialize `FirefoxDriver` by `FirefoxDriverManager.getInstance().setup();`

so those two TestNG test classes looks like:

Test_1.java

```java
public class Test_1 {

    @BeforeTest(alwaysRun = true)
    public void beforeTest() {
        ChromeDriverManager.getInstance().setup();
    }

    @Test
    public void f1() {
        System.out.println("====> ChromeDriver: " + System.getProperty("webdriver.chrome.driver"));
    }
}
```

Test_2.java

```java
public class Test_2 {

    @BeforeClass(alwaysRun = true)
    public void beforeTest() {
        FirefoxDriverManager.getInstance().setup();
    }

    @Test
    public void f2() {
        System.out.println("====> FirefoxDriver: " + System.getProperty("webdriver.gecko.driver"));
    }
}
```

Yes, I put the `ChromeDriverManager.getInstance().setup();` and `FirefoxDriverManager.getInstance().setup();` into `@BeforeTest`, as @dipan66 updated his [issue](https://github.com/bonigarcia/webdrivermanager/issues/42) he fixed the problem when he place the `xxx..getInstance().setup();` into `@BeforeTest` of TestNG.

I tried and found, sometimes put it into `@BeforeTest` still can't fix the problem.
Please check below test result, I set my TestNG parallel by `Classes` level, it means that my two TestNG classes `Test_1.java` and `Test_2.java` will be run by parallel.

Even I add option `(alwaysRun = true)` for `@BeforeTest` to make sure the method annotated by `@BeforeTest` will be run, but the problem can't fix.

```bash
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
====> ChromeDriver: null
====> FirefoxDriver: /Users/ansonliao/.m2/repository/webdriver/geckodriver/macos/0.19.1/geckodriver
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.886 sec - in TestSuite

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

```

As we can see, `Wdm` failed to set System Property for ChromeDriver: `webdriver.chrome.driver` (value = null), and this System Property of ChromeDriver `webdriver.chrome.driver` can be found from System Properties list as no error exception was threw.

I checked the download directory, also the ChromeDriver downloaded succeeded and uncompressed succeeded, it means that download is no problem.

It easy to reproduce, just created two TestNG test classes and enable parallel and set parallel to `Classes`, and repeat to run this TestNG suite, the `testng.xml` similar as below.

Please note that, each time I run, I cleared the downloaded folder first, make sure `wdm` will download the WebDrivers from web.

From me, the worst case is 5 time run of the TestNG suite, got 2 times set System Property for WebDriver fail, I think it is high rate.

testng.xml

```xml
<suite name="TestNG" verbose="2" parallel="classes" thread-count="2"
       data-provider-thread-count="3" >
    <test name="Test1">
        <classes>
            <class name="om.example.Test_1">
                <methods>
                    <include name="f1"/>
                </methods>
            </class>
            <class name="com.example.Test_2">
                <methods>
                    <include name="f2"/>
                </methods>
            </class>
        </classes>
    </test>

</suite>
```

Please advise.

**Comment by bonigarcia** [comment]
Thanks for reporting, I will try to reproduce and fix it for the next version.

**Comment by bonigarcia** [comment]
It should be fixed in new release, 2.0.0.

**Comment by ansonliao** [comment]
Thanks @bonigarcia , will try with new version

**Comment by bonigarcia** [comment]
At this moment the latest version is 2.1.0. I would use that one.

**Comment by ansonliao** [comment]
@bonigarcia yes, using 2.1.0 version, thanks for note
