### ISSUE TITLE
Is it possible to add functionality to download webdriver for all operation systems?

### ISSUE THREAD

**Issue by AndriiYushkov** [bonigarcia/webdrivermanager#174]
We have internal network, without internet access, but also have internal repository in it.
At the same time we have some workstations where we have internet access and access to internal repository. Now we have jar archive with chrome driver bins for all operation systems on internal repository. We try to automate process of creating new version of our archive on internal repository. Is it possible to use your library for downloading webdriver for all operation systems.

**Comment by bonigarcia** [comment]
I think so. You can prepare your environment to make WebDriverManager to work offline. For that, you need to populate the cache as expected by WebDriverManager (`~/.m2/repository/webdriver` by default) and the use the `.forceCache()` method.

**Comment by AndriiYushkov** [comment]
You did not understand - I want to create jar file on windows machine which will contans chromedriver for all operation system. I checked source code of your library and find that operation system varible has final modificator - so we have no possibility to download linux driver on windows machine.
