### ISSUE TITLE
System.setProperty() does not work since version 1.6.2

### ISSUE THREAD

**Issue by andrew-sumner** [bonigarcia/webdrivermanager#175]
The documentation says that we should be able to use `System.setProperty("wdm.targetPath", "/my/custom/path/to/driver/binaries");` to set the download path for binaries.

Since v1.7.0, it looks like some refactoring was done to improve the code but has broken the documented behavior.

In Class WdmConfig, method getString, the property key is looked up via System.getenv.  System.getenv retrieves environment variables, rather than System.getProperty which retrieves properties set using System.setProperty...

I rely on the documented behavior to read values from my config file and pass to wdm.

The result is that since v1.7.0, only the default value for wdm.targetPath is set (i.e. <user_home>/.m2).

To override any wdm property value since v1.7.0, a user would need to set an environment variable on the command line such as:
setx wdm.targetPath "pathToCustomDownloadDirectory"

**Comment by bonigarcia** [comment]
It should be fixed now. It will be available for next release.
