### ISSUE TITLE
NPE in WdmConfig: Is ForceCache required? 

### ISSUE THREAD

**Issue by kyleshrader** [bonigarcia/webdrivermanager#178]
I am seeing `Wdm.getBoolean("wdm.forceCache")` throwing a NPE because this property is not present in my properties file. Is this meant to be a required property or can we default this? I would assume to false.

Edit: this is occuring [here (permalink)](https://github.com/bonigarcia/webdrivermanager/blob/d5b407422f97e8edb59ed9b49262ee32a6a3b681/src/main/java/io/github/bonigarcia/wdm/BrowserManager.java#L163)

**Comment by bonigarcia** [comment]
As of version 2.0.1, configuration keys of WebDriverManager (`wdm.*`) are optional. The default values if some property is not present is `false` for boolean, `""` for strings, and `0` for integer.
