### ISSUE TITLE
Resource [logback.xml] occurs multiple times on the classpath

### ISSUE THREAD

**Issue by cls452** [bonigarcia/webdrivermanager#181]
When including 2.0.1 as a dependency for a project that contains its own logback.xml file, the following warnings are logged:

10:36:13,756 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
10:36:13,756 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/project/target/classes/logback.xml]
10:36:13,756 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/.m2/repository/io/github/bonigarcia/webdrivermanager/2.0.1/webdrivermanager-2.0.1.jar!/logback.xml]

I checked a few resources online and it seems like logback config files should be excluded from published jars:
https://stackoverflow.com/questions/18263139/how-do-i-suppress-a-inherited-projects-logback-xml-file-2-logback-xml-in-a-sing/18275945#18275945

https://www.mkyong.com/maven/maven-exclude-logback-xml-in-jar-file/

Great library by the way. It's been a big help in cleaning up our webdriver dependencies.

**Comment by bonigarcia** [comment]
Thanks a lot for reporting. It should be fixed now.

**Comment by cls452** [comment]
Looks good, thanks.
