### ISSUE TITLE
Proxy does not work for Chrome

### ISSUE THREAD

**Issue by AleksNFedorov** [bonigarcia/webdrivermanager#182]
Setting Proxy for Chrome driver has no effect, when checking from open window I still see my real IP

**WebSite to check**
http://www.myipaddress.com/show-my-ip-address/

**Proxy**
110.77.226.110:54214

**Other**
OS: MacOS Sierra 10.13.1 (x64)
Lib version: 2.0.1
Browser: Chrome
Driver: latest

**Comment by bonigarcia** [comment]
I think you are confusing things. The proxy settings are for WebDriverManager, which connects to remote repositories (e.g. https://chromedriver.storage.googleapis.com/) to download the proper binary. The fact that you see you real IP with your Chorme in that web has nothing to do with WebDriverManager.
