### ISSUE TITLE
Logback and Spring Boot log level issue

### ISSUE THREAD

**Issue by lilithfr** [bonigarcia/webdrivermanager#184]
I'm trying to use this library for my Spring Boot application but when I activate it, the default log level and log format change automatically. Sadly, it does not impact only the logger of the library but every logger of the application.
I don't think a log configuration file should be inside a library or it should only configure the logger used by the library.

Alex.

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using?

**Comment by lilithfr** [comment]
I use the version 2.0.1. In order to find the module which changed the log level, I created an empty Spring Boot application and used the following Gradle build file:

[build.gradle.txt](https://github.com/bonigarcia/webdrivermanager/files/1598565/build.gradle.txt)

The log level and format change when I enable the webdrivermanager.

**Comment by bonigarcia** [comment]
Fixed in version 2.1.0.
