### ISSUE TITLE
I am trying to run a simple programme but getting an error 

### ISSUE THREAD

**Issue by Hiren81** [bonigarcia/webdrivermanager#187]
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded 

Below is my code 

package selenium1;

import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Basemain {
	WebDriver driver;
	String baseURL;

	@Before
	public void setUp() throws Exception {
		driver = new ChromeDriver();
		baseURL="www.gmail.com";
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		driver.manage().window().maximize();
		
	}
	@Test
	public void test() {
		driver.get(baseURL);
		
	}

	@After
	public void tearDown() throws Exception {
	}

	

	
}

**Comment by Hiren81** [comment]
I have done same test in chrome and also coming up with same error

**Comment by r3d4rmy** [comment]
```
import io.github.bonigarcia.wdm.ChromeDriverManager
import org.openqa.selenium.chrome.ChromeDriver
import org.openqa.selenium.chrome.ChromeOptions

ChromeDriverManager.getInstance().setup()
ChromeOptions o = new ChromeOptions()
o.setOption(some-value)
o.addArguments("--some-argument")
driver = new ChromeDriver(o)

// do stuff with the driver
```
The issue is you aren't using the ChromeDriverManager to actually get the latest version of the chromedriver. If you do that, it will set the `webdriver.chrome.driver` system property to the location of the chromedriver that the error you're getting is complaining about.

**Comment by bonigarcia** [comment]
Thanks @r3d4rmy.
