### ISSUE TITLE
Running headless chrome

### ISSUE THREAD

**Issue by sunbit-zackz** [bonigarcia/webdrivermanager#188]
First of all, excellent project!
I was wondering how can I run the chrome as headless (providing --headless to the executable)

**Comment by bonigarcia** [comment]
This configuration is done using Selenium WebDriver (WebDriverManager has nothing to do). See an example [here](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ChromeHeadlessTest.java).
