### ISSUE TITLE
I am facing the issue while using Firefox 

### ISSUE THREAD

**Issue by vacha-dave** [bonigarcia/webdrivermanager#192]
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable
Using FF version: 58.0.2
Selenium: 2.44.0

Can someone please guide me? I have tried upgrading the Selenium to 3.x and it still has the issue.

@bonigarcia can you please suggest a solution

**Comment by vacha-dave** [comment]
I realized a part of my mistake..I have added Chome driver dependacy seprately after adding this lib..so I think it was creating a confusion for firefox. Puting it here in case it can be helpful to someone.

Now I am dealing with another issue...instead of the website I am trying to open, FF is showing me "Insecure connection" page.

**Comment by bonigarcia** [comment]
This is not related with WebDriverManager, sorry.
