### ISSUE TITLE
The settings.xml <localRepository> tag is not honoured

### ISSUE THREAD

**Issue by AndyGee** [bonigarcia/webdrivermanager#195]
The <localRepository> tag is used to define an alternative location for the 'repository' element.

**Comment by bonigarcia** [comment]
I don't understand this issue. Could you please clarify?

**Comment by AndyGee** [comment]
Sure, if no config override is specified then the driver is currently downloaded to .m2/[repository]/webdriver - The default location, wdm.targetPath=~/.m2/repository/webdriver.

It is possible to specify an alternate location for the [repository] in the .m2/settings.xml - For example, on a second hard-disk with more space.

The configured repository should really be used rather than the default wdm.targetPath=~/.m2/repository/webdriver

I guess this would mean checking for the existence of ~/.m2/repository/ before writing to it, and if not found then check the settings.xml for the configured location.

I know this sounds like a bit of overhead, but in our Jenkins builds we often specify a different repo location for each project (isolation of builds and a clean repo) - So currently we also need to maintain the wdm.targetPath in the build.

I totally understand if there's not going to be an interest in making this change, so I might submit a patch later - I'm crazy busy right now, working over Easter too.

**Comment by bonigarcia** [comment]
@AndyGee I'm planning to make a new release of WebDriverManager soon. If you submit a PR about this issue it could be available for that new version.

**Comment by skutnar72** [comment]
As a workaround, you can create a soft link so that ~/.m2 points to the real location.  This worked for me.

**Comment by bonigarcia** [comment]
Closing unresponsive issue.
