### ISSUE TITLE
Architecture will be ignored

### ISSUE THREAD

**Issue by Maruku-san** [bonigarcia/webdrivermanager#200]
When the architecture is set to 32bit/linux and for example (in my case not only an example) the chrome driver 2.37 does not exists as a 32bit/linux Version, the list `out.size()` will be with size 1. The list only includes the 64bit/linux Version. So the `out.size() > 1` does not match an I get as result the 64bit version and not an exception that the configured version is not available.  

https://github.com/bonigarcia/webdrivermanager/blob/9043447a9ea9779f5536caa1e8c96153b310f3fe/src/main/java/io/github/bonigarcia/wdm/UrlFilter.java#L70

Best regards
Maruku-san

**Comment by Maruku-san** [comment]
Hi, thanks for the fast reply, I have a question. Why don't you filter every-time for architecture? [`if ((forcedArch || out.size() > 1) && arch != null) {` to  `if (arch != null) {`]

Best Regards
Maruku-san

**Comment by bonigarcia** [comment]
It cannot be filtered every time. This is a corner case, and it should be treated carefully. For instance, in the common case of using WebDriverManager in Windows 64 bits, there is only a version of `chromedriver`, which for 32 bits, but also works in 64 bits. For that reason only applied the filtering logic if explicit configuration for architecture (e.g. WebDriverManager.chromedriver().arch32()`) is done.

I'm preparing a new release of wdm, it will be available in a few moment.

**Comment by Maruku-san** [comment]
Thanks for the answer.

Best regards
Maruku-san
