### ISSUE TITLE
Exclude logback-classic from compile scope.

### ISSUE THREAD

**Issue by rosolko** [bonigarcia/webdrivermanager#202]
Currently with custom SLF4J implementation it's produce error:
```java
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/arasolka/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.11.0/9ba207b78e470fe7765ebee14f1f0336c9cbcc18/log4j-slf4j-impl-2.11.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/arasolka/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```
Dependency tree shows:
```
     +--- io.github.bonigarcia:webdrivermanager:2.2.1
     |    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
     |    +--- commons-io:commons-io:2.5
     |    +--- com.google.code.gson:gson:2.8.0 -> 2.8.2
     |    +--- org.apache.commons:commons-lang3:3.5 -> 3.7
     |    +--- org.apache.httpcomponents:httpclient:4.5.3 (*)
     |    +--- org.rauschig:jarchivelib:0.7.1
     |    |    \--- org.apache.commons:commons-compress:1.9
     |    +--- org.jsoup:jsoup:1.10.2
     |    \--- ch.qos.logback:logback-classic:1.2.3
     |         +--- ch.qos.logback:logback-core:1.2.3
     |         \--- org.slf4j:slf4j-api:1.7.25
```
In this situation `logback-classic` also override library's `slf4j-api` with newest version.
So, please exclude logback-classic from compile scope by moving them at least to test scope.

**Comment by sukhjinder-sdei** [comment]
And also Please remove extra noisy DEBUG logs for httpclient.

**Comment by AlexanderPoleschuk** [comment]
@sukhjinder-sdei For noisy debug logs I've submitted another ticket: https://github.com/bonigarcia/webdrivermanager/issues/203. Sorry, haven't read this before I've created mine.
There is actually a crutch solution that will allow to supress all this noise.

**Comment by bonigarcia** [comment]
This dependency was needed at compile level since logging is necessary for the interactive mode of WebDriverManager. I've made some adjustments to use logback-classic at test level but also in interactive mode (using mvn exec:java or in a fat-jar). It will be available on next version.
