### ISSUE TITLE
Can't find Opera binary

### ISSUE THREAD

**Issue by Viral1010** [bonigarcia/webdrivermanager#205]
I am Using latest maven dependency and get this error for opera

My code :
 WebDriverManager.operadriver().setup();
 driver = new OperaDriver();  

Error : 
Starting OperaDriver 2.35 (ee0117ea0f7f76009fd2aa3dd6b6164205de32b5) on port 15882
Only local connections are allowed.
org.openqa.selenium.WebDriverException: unknown error: cannot find Opera binary
  (Driver info: OperaDriver=2.35 (ee0117ea0f7f76009fd2aa3dd6b6164205de32b5),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'DESKTOP-7RV9GVN', ip: '172.28.192.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_152'
Driver info: driver.version: OperaDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by bonigarcia** [comment]
Due to an old bug in Opera, it is required to set the Opera binary path using `OperaOptions`. You can find a test example [here](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/OperaTest.java).

**Comment by kriegaex** [comment]
The code does not work for me under Windows because launcher.exe starts opera.exe asynchronously, thus driver creation fails. I modified the code for myself so as to search in the opera base directory for opera.exe recursively. Because I use Spock/Geb and thus Groovy, the code looks like this in my GebConfig.groovy:

      OperaDriverManager.instance.setup("2.38")
      def os = OperatingSystem.current
      def operaBinary = os.windows ? new FileNameByRegexFinder().getFileNames("c:\\Program Files\\Opera", "opera.exe").first()
        : os.macOs ? "/Applications/Opera.app/Contents/MacOS/Opera" : "/usr/bin/opera"
      OperaOptions options = new OperaOptions()
      options.binary = operaBinary
      new OperaDriver(options)

Just do something similar from Java and you are all set.
