### ISSUE TITLE
SLF4J Error

### ISSUE THREAD

**Issue by rosolko** [bonigarcia/webdrivermanager#21]
Hello,

On init project step SLF4J always show error:
``` java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Is it ok, or need to be investigated?

**Comment by bonigarcia** [comment]
This is normal, since WebDriverManager uses SLF4J (logging facade), but the specific logging implementation (e.g. `slf4j-simple`, `slf4j-jdk14`, `logback-classic`) should be added by the final application. Please see further details on #4.
