### ISSUE TITLE
Grabs wrong driver from cache

### ISSUE THREAD

**Issue by titusfortner** [bonigarcia/webdrivermanager#216]
I'm trying to use the same code for both Windows & Mac users without having access to the internet.

On a Mac, it is grabbing the Windows version. I believe the expectation is that ` config().isExecutable(new File(driverInCache))` will return false for a Windows executable on a Mac platform, but this is not the case. (https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/java/io/github/bonigarcia/wdm/WebDriverManager.java#L563)

I believe `this.myOSName` also needs to be referenced, but I'm not sure the best way to do it. I can try to take a stab at a PR if this isn't a trivial update for you.

Thanks!

**Comment by bonigarcia** [comment]
I don't understand your problem, please clarify.

**Comment by titusfortner** [comment]
The use case is that I do Selenium training courses and want to have one directory on a USB drive for all trainees regardless of operating system. The goal was for the same basic code (with no conditionals) to work for everyone without requiring an internet connection. This library should work for this purpose, but doesn't right now.

**Comment by bonigarcia** [comment]
This issue should be solve in new version 2.2.2, just released.
