### ISSUE TITLE
Webdrivermanage is not downloading correct chrome version

### ISSUE THREAD

**Issue by sukhjinder-sdei** [bonigarcia/webdrivermanager#218]
Hi Team,
Please check that WebDriverManager is not downloading the correct version for chrome.
Latest version 2.38.552522 instead downloading 2.38.551601
which is causing throwing error SessionNotCreatedException while running test parallel.

WebDriverManager is a great tool. Thanks for creating it.

**Comment by AlexanderPoleschuk** [comment]
Any chance to provide information on the OS and architecture, where you face such issue?
Just checked on Win x64 and WDM downloads 2.38.552522 version by default, which is latest.

**Comment by sukhjinder-sdei** [comment]
@AlexanderPoleschuk I have tested it on Win10 and Mac as well but not redirect WDM to use Arch-64. I am using the Default configuration.

**Comment by bonigarcia** [comment]
The patch version of chromedriver is not managed by WebDriverManager, meaning that the only information WebDriverManager knows is that chromedriver is 2.28 or 2.39. Maybe the patch version can be changed in the chromedriver repository, in that case I propose you to force the download, i.e. override the existing chromedriver to get the latest version.

**Comment by sukhjinder-sdei** [comment]
I have tried to override the url as well but it was not worked for me. 
Anyway now 2.39 is here.
Thanks @bonigarcia
