### ISSUE TITLE
Internet Explorer 64bit no binary found

### ISSUE THREAD

**Issue by chesterT** [bonigarcia/webdrivermanager#219]
case: Try to set up a 64bit version of Internet Explorer.
WebDriverManager.iedriver().architecture(Architecture.X64).setup();
response:
13:36:43.579 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://selenium-release.storage.googleapis.com/ to seek IEDriverServer 13:36:44.224 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 3.12 13:36:44.225 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for IEDriverServer 3.12 ... seeking another version 13:36:44.280 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 3.11 13:36:44.282 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for IEDriverServer 3.11 ... seeking another version 13:36:44.318 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 3.10......
Some other versions .....
3:36:44.800 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 2.42 13:36:44.800 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for IEDriverServer 2.42 ... seeking another version 13:36:44.803 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 2.41 13:36:44.804 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for IEDriverServer 2.41 ... seeking another version 13:36:44.807 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 2.40 13:36:44.807 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for IEDriverServer 2.40 ... seeking another version 13:36:44.809 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 2.39 13:36:44.809 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for IEDriverServer 2.39 ... seeking another version 13:36:44.811 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is null 13:36:44.811 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - IEDriverServer (latest version) for WIN64 not found in https://selenium-release.storage.googleapis.com/ 13:36:44.813 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing IEDriverServer (IEDriverServer (latest version) for WIN64 not found in https://selenium-release.storage.googleapis.com/) ... trying again forcing to use cache io.github.bonigarcia.wdm.WebDriverManagerException: IEDriverServer (latest version) for WIN64 not found in https://selenium-release.storage.googleapis.com/ at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:451) at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:219)

But in https://selenium-release.storage.googleapis.com/
you can see the versions mentioned in the error log.

3.12/IEDriverServer_x64_3.12.0.zip
1525799913484150
1
2018-05-08T17:18:33.446Z
"c058b42ed67b53784403035041735011"
1175137

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using? This was supposed to be fixed in version 2.2.3.

**Comment by chesterT** [comment]
Sorry i was using 2.2.2 I did the update and everything works fine
