### ISSUE TITLE
forceCache picks up incorrect webdriver

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#220]
WDM - 2.2.3
wdm.forceCache=true

STR:
Clean-up .m2\..\webdriver storage.
Start a test against any browser (e.g. Chrome) and execute it.
Result: Chrome binary is downloaded to .m2\..\webdriver storage.

Run the test against other browser(e.g. IE).
Result: The test is considered to be executed against IE, however, it starts against Chrome (as a downloaded browser).

RCA:
Fault occurs in method:
protected Optional<String> getDriverFromCache(String driverVersion,
            Architecture arch, String os) {}
from WebDriverManager.java.

Method filterCacheBy() should also **and first of all** filter by driver name.

**Comment by AlexanderPoleschuk** [comment]
https://github.com/bonigarcia/webdrivermanager/pull/223

**Comment by bonigarcia** [comment]
In fact this was a bug. Thanks a lot for reporting and contributing. PR merged.
