### ISSUE TITLE
SLF4J errors after implementing WebDriverManager in test

### ISSUE THREAD

**Issue by yahmedov** [bonigarcia/webdrivermanager#221]
I have implemented the WebDriverManager as follows:

```
String baseUrl = "https://www.google.com/";
private WebDriver driver;

@Before
public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();    
}

@Test
public void myTest() {
    driver.get(baseUrl);
    assertEquals(
                baseUrl,
                driver.getCurrentUrl()
        );
}

@After
public void tearDown() {
    driver.quit();
}
```

All seems fine but when I run the Test method I get SLF4J errors in the console log:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".`
`SLF4J: Defaulting to no-operation (NOP) logger implementation`
`SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`

After those error messages myTest is getting executed correctly, but still the errors are annoying.

Why am I getting those messages, what I have to do with SLF4J and what's the best way to work it around?

**Comment by lukaszgo3** [comment]
I have the same issue :)

**Comment by bonigarcia** [comment]
WebDriverManager uses SLF4J (logging facade), but the specific logging implementation (e.g. slf4j-simple, slf4j-jdk14, logback-classic) should be added by the final application. Please see further details on #4.

**Comment by swapnil789** [comment]
Even i am getting the same error!! Could you help here?

**Comment by TheWoops** [comment]
Hello @swapnil789 , no idea if you still need help. 

If you have normal java project , download [this jar-file](https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar) and add it to your java project.

If you use Maven and included WebDriverManager in your pom.xml e.g. as follows:

```
		_<!-- https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager -->
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.8.1</version>
		</dependency>_
```
Just add e.g. the Logging Framework Logback as follows and these error messages disappear.

```
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.3</version>
		</dependency>
```
