### ISSUE TITLE
Unable to start SonarQube server from non-master branch

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#224]
Each time Travis starts to verify the build from NON-master branch it fails w/ message:
[ERROR] SonarQube server [http://localhost:9000] can not be reached

Example: https://travis-ci.org/bonigarcia/webdrivermanager/builds/398301493

**Comment by bonigarcia** [comment]
I'm aware of this issue. Unfortunately it seems that SonarCloud is not able to analyze external PRs at the moment for security constraints. See this question on [StackOverflow](https://stackoverflow.com/questions/45612758/how-do-i-get-sonarcloud-to-run-on-pull-requests-from-forks-with-travis-maven) (last answer was done by SonarCloud guy).
