### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property;

### ISSUE THREAD

**Issue by harshitaGupta1** [bonigarcia/webdrivermanager#227]
Hello friends,
 
I am learning selenium , & try to face difficulties in running this basic code.

Error :  exception in thread " main" java.lang.IllegalStateException:  The path to the driver executable must be set by the webdriver.chrome.driver system property;

This is my code , pls help me out -

package demo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;

public class demo1 {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.gecko.driver", "C:/Users/harshita/Desktop/geckodriver-v0.21.0-win64/geckodriver.exe");
WebDriver driver = new  ChromeDriver();
driver.get("http://google.com");
Thread.sleep(5000);
driver.quit();
	}

}

**Comment by bonigarcia** [comment]
See #42.
