### ISSUE TITLE
WDM doesn't check filesInCache() list before calls to filterCacheBy()

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#229]
STR:
User's webdriver folder is empty.
wdm.forceCache=true is set in properties.
Debug via ChromeTest test.

If there is no driver binaries in user's folder 
`List<File> filesInCache = getFilesInCache();`
from getDriverFromCache() returns an empty collection, that then leads to calls to filterCacheBy() at least 3 times. 
Even when input collection is checked for emptiness in the method, it leads to log message with same output being logged by filterCacheBy() method.

Same stuff happens if e.g. the outcome of filtering by name have led to removing the file from candidates. filterCacheBy(filesInCache, driverVersion) will receive an empty collection.

**Comment by AlexanderPoleschuk** [comment]
https://github.com/bonigarcia/webdrivermanager/pull/230

**Comment by bonigarcia** [comment]
@AlexanderPoleschuk Thanks a lot for contributing.

I've reviewed your PR. These lines makes sense to me:

```
            if (filesInCache.isEmpty()){
                break;
            }
```
But the rest of them, basically moves the condition '!filesInCache.isEmpty()` from the method 'filterCacheBy` to `getDriverFromCache`. Moreover, if the list were empty, we have already broke the loop (according to your first change).

Overall, I will merge the PR but only adding lines from 568 to 571.

**Comment by AlexanderPoleschuk** [comment]
yes, it moves the condition '!filesInCache.isEmpty() from the method 'filterCacheBy to getDriverFromCache, cause there is no need to call the method and initialize List<File> output in filterCacheBy() method, when filesInCache is an empty list, right?
and moreover, there is no need to return an empty list as a method result...

it's not a rocket science change, though. If you want to keep the code as is (check for emptiness inside of filterCacheBy()) - it's completely okay :)
