### ISSUE TITLE
Explicit version passing does not work

### ISSUE THREAD

**Issue by jerzynowakowski** [bonigarcia/webdrivermanager#23]
**Pre-requisities**
Library 1.3.1 / 1.4.1 version:
Java 1.8.0_74 JDK

**Description**
_Code call # 1:_
`ChromeDriverManager.getInstance().setup();`

_Code call # 2:_
`String version = "2.20";
ChromeDriverManager.getInstance().setup(version);`

When running maven via:
`mvn clean install`
Library is always downloading LATEST version despite the call with explicit one, crashing in maven when other version is passed and library is not present in the ~/.m2/repositries/webdriver directory

When passing 
`-Dwdm.chromeDriverVersion=2.20`
 on mvn command line, I face the crash issue

**Steps to reproduce**
Please try to observe when  does not contain any downloaded version of the driver :

1. Remove `~/.m2/repository/webdriver` folder
2. Pass version of Code # 2
3. Run `mvn -DsuiteXmlFile=src/test/resources/testngsuite.xml test`

or 
1. Remove `~/.m2/repository/webdriver` folder
2. Run `mvn -Dwdm.chromeDriverVersion=2.20 -DsuiteXmlFile=src/test/resources/testngsuite.xml test`

**Actual**
`Parameter** 'directory' is not a directory`

`Tests run: 383, Failures: 1, Errors: 0, Skipped: 382, Time elapsed: 3.662 sec <<< FAILURE! - in TestSuite
initWebBrowserBeforeSuite(com.xxxx.XXXXTest)  Time elapsed: 2.061 sec  <<< FAILURE!

java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:210)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:87)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:74)`

**Expected**
Desired version is downloaded.

**Additional information**
As a conclusion - only LATEST version is taken into account and downloaded, passing any version creates "directory" problem when calling by maven.

I did not face the issue once Code # 1 downloaded the latest version, and stored it, then everything was fine until today.

P.S.
Despite I have to go with the latest version, thank you for the library @bonigarcia , it is really awsome! Thanks!

**Comment by bonigarcia** [comment]
Thanks for reporting @jerzynowakowski, but I am not able to reproduce it. I am testing with version 1.4.2-SNAPSHOT and everything seems to work correctly.

Which operative system are you using?

You can try to use the development version (1.4.2-SNAPSHOT) changing the log level to `TRACE` instead of `INFO`. Maybe with that we have more information to trace the error.

BTW, what is this parameter?

`-DsuiteXmlFile=src/test/resources/testngsuite.xml`

This is not related with WebDriverManager. I don't know if this is adding some side effect in the test.

**Comment by jerzynowakowski** [comment]
Win7 SP1 x64
maven 3.2.5

`-DsuiteXmlFile=src/test/resources/testngsuite.xml` is just a maven parmeter for passing the suite variable, it is passed with success

I will check with 1.4.2-SNAPSHOT as soon as I will be able to. Thanks

**Comment by bonigarcia** [comment]
I think I found the issue. You are deleting completely the target repository (`~/.m2`). WebDriverManager is not able to store the binary since that folder does not exist. I added a condition to avoid the problem in version 1.4.2-SNAPSHOT.

**Comment by jerzynowakowski** [comment]
To clarify : I have removed `webdriver` only from `~/.m2/repositories` was not removed 

This is the case of first usage when explicit version `ChromeDriverManager.getInstance().setup("2.20");` is passed for the first time, webdriver can not create the folder `webdriver` in `~/.m2/repositories`

**Comment by bonigarcia** [comment]
Anyway, test with version 1.4.2-SNAPSHOT please.

**Comment by jerzynowakowski** [comment]
`<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>1.4.2-SNAPSHOT</version>
</dependency>`

I do have enabled :

`<snapshots>
	<enabled>true</enabled>
</snapshots>`

despite that the library is not resolved, I get error, 1.4.1 is the latest version I can get

**Comment by bonigarcia** [comment]
This is Maven issue.

You have to clone the project webdrivermanager and then install it in your local repository:

> mvn install -DskipTests

After that you will be able to use version 1.4.2-SNAPSHOT.

**Comment by jerzynowakowski** [comment]
**NOT REPRODUCED with 1.4.2-SNAPSHOT**
- Java
- 1.8.0_74 JDK
- Win7 SP1 x64
- Maven 3.2.5

Thanks for hints with maven, it worked, I got 1.4.2-SNAPSHOT in 2 seconds...

The fix really solved the issue, and the issue does not persist,
I can pass any version I want on 1.4.2-SNAPSHOT

**Additional information on 1.4.2-SNAPSHOT**
However, I observe, the "code" versus "maven command line" is stronger i.e. :

When running from command line:
`mvn -Dwdm.chromeDriverVersion=2.20 clean test` 
and in code `ChromeDriverManager.getInstance().setup("2.21");`

the "2.21" is downloaded. So the code is stronger than command line. And it should be the opposite. 
But this is a topic for other issue. 

I will keep using your library @bonigarcia - It is fantastic!
