### ISSUE TITLE
Download actual web browsers?

### ISSUE THREAD

**Issue by allquixotic** [bonigarcia/webdrivermanager#231]
Is there any plan to add support to download at least the free and open source web browsers as part of webdrivermanager? A lot of my use cases involving CI/CD systems don't have a very convenient way of wrangling browser binaries, and for various reasons sometimes it's not possible or not easy to bake them into the image of a container used for testing, for example.

It'd be great if we could use the same file caching, platform sensing infrastructure as webdrivermanager already has, but extend it to also support downloading an appropriate web browser. 

Webdrivermanager could also be aware of which versions of the drivers are compatible with which versions of the browsers. The default behavior should be to download the latest stable browser version that is still compatible with the desired version of the driver. So for example if you download chromedriver 2.40, and it supports up to Chrome 68, then even if Chrome 69 comes out, you wouldn't just download that if either: (1) chromedriver > 2.40 is not even available, putting a hard limit on the latest chrome version that works with Selenium at Chrome 68 until chromedriver is updated, or (2) the user requests (via API or via Maven properties) to hard-code a specific version of the browser driver. They should also optionally be able to request a specific version of a web browser to be downloaded.

Obviously this can't be applied evenly to all browsers, since at least Edge, IE and possibly Opera can't be downloaded at all, or legally distributed by us. But it should definitely work for Firefox and Chrome/Chromium at a minimum.

I think the time when Selenium is a heavyweight platform that comes with lots of dependencies that have to be manually setup to work, should quickly come to an end, but except for the Docker support in Selenium-Jupiter, Selenium still has dependency on web browsers today.

Also, I don't think the functionality of managing webdriver instances should necessarily be tightly coupled to JUnit 5. It would be nice to be able to do a one-line local headless Chrome/Firefox, like `WebDriver wd = WebDriverManager.chromedriverHeadless().setup().newInstance();` without having to depend on selenium-jupiter. I say this because many of my projects still use JUnit 4, or even TestNG. The act of downloading the required binaries (browser and driver) and getting a functional local driver for a headless browser should be extremely simple and fluent, IMO.

**Comment by AlexanderPoleschuk** [comment]
@allquixotic Could you please paraphraze your thoughts into the real issue that you've faced with?

WDM allows you to download appropriate browser version. Example: WebDriverManager.chromedriver().version("2.26").setup();

You should manage pairs browser - supported webdriver version on your own.
Just an example: 
ChromeDriver 2.40 - Supports Chrome v66-68
ChromeDriver 2.39 - Supports Chrome v66-68

What would you select in this case: 2.39 or 2.40?)

**Comment by allquixotic** [comment]
> You should manage pairs browser - supported webdriver version on your own.

That's sort of what I'm saying webdrivermanager should do.

  > What would you select in this case: 2.39 or 2.40?)

If my code says `chromedriver().version("2.40")` then I would select the newest-available stable version of the chrome *browser* that is still compatible with chrome*driver* version 2.40.

If my code says `chromedriver().version("2.39")` then I would do the same, but for chromedriver version 2.39, since that's what the code specified.

Basically, you would not need to specify *both* the version of the *web browser* and the *browser driver* -- just one or the other. 

For example, if there were code like: `WebDriverManager.chrome().browserVersion("68").setup();` in this case I am specifying the version of the Chrome *web browser* at version 68, not the *browser driver*. Webdrivermanager would then download the latest stable release of Chrome 68 *and* the latest ChromeDriver that still supports Chrome 68. So, hypothetically, if ChromeDriver 2.45 were the last version of ChromeDriver to support Chrome 68, then *even if ChromeDriver 2.46 were released* it would still download and stay on ChromeDriver 2.45, as long as my code asks for Chrome 68.

But, you should also be allowed to specify the specific version of both the web browser and the browser driver if you wish. This would also be fine: `WebDriverManager.chromedriver().version("2.40").chrome().browserVersion("68").setup();`

The benefit of having Webdrivermanager "figure out" the correct version of ChromeDriver to download is that you get automatic bugfixing for free when a new ChromeDriver is released, but I guess there is also risk that your tests will break too, so this feature should definitely be optional.

But that discussion is completely separate from the fact that, to the best of my knowledge, currently *WebdriverManager does not download web browsers at all*. It downloads *browser drivers*, but not *web browsers*. In order to use WebdriverManager I have to supply a copy of the appropriate web browser using other means. I'd like to not have to do that, for at least Firefox and Chrom(e,ium).

**Comment by bonigarcia** [comment]
In fact, WebDriverManager only deals with webdriver binaries, not with actual browsers. It is not planned to be supported in the future, sorry.

Nevertheless, maybe you can be interested in another of my projects: [Selenium-Jupiter](https://bonigarcia.github.io/selenium-jupiter/). It allows to use Selenium in JUnit 5 tests. One of its features is using browsers (Chrome, Firefox, Opera, and even browsers in Android) in Docker containers. Selenium-Jupiter is in charge of pulling the images, in other words, it actually downloads the browsers and make it available for tests.
