### ISSUE TITLE
Mirroring driver repositories on the intranet without XML

### ISSUE THREAD

**Issue by rkrisztian** [bonigarcia/webdrivermanager#233]
Hi,

I would like to mirror the original driver repositories on a machine of my intranet, however, the following code fails:

```java
WebDriverManager.chromedriver().driverRepositoryUrl(new URL("https://my-artifactory-url.here/chromedriver")).setup();
```
Because it expects an XML as a response:

```none
    [junit] io.github.bonigarcia.wdm.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 55; White spaces are required between publicId and systemId.
    [junit] io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 55; White spaces are required between publicId and systemId.
    [junit] 	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:471)
    [junit] 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
    [junit] 	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:468)
    [junit] 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
    [junit] 	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:215)
```

Why is it really necessary to have that XML? The `http://npm.taobao.org/mirrors/chromedriver` mirror doesn't seem to have it, and I presume it would still work (didn't test).

I would need this feature very much, and I don't think it's possible to mirror the XML like https://chromedriver.storage.googleapis.com/ does, so please relax this limitation.

**Comment by bonigarcia** [comment]
WebDriverManager parses the XML contained in the chromedirver repository to find out how many versions are available. If you plan to create your own mirror, you need to clone also that XML file. See issue related #157 or [StackOverflow](https://stackoverflow.com/questions/50702219/using-webdrivermanager-properties-file-with-artifactory).

**Comment by rkrisztian** [comment]
Oh, I didn't know that, thanks!

**Comment by rkrisztian** [comment]
@bonigarcia, sorry for still asking about this, but my problem is that this XML does not even have a path, it's just `/` (relative to the mirror), which is very hard to mirror with Artifactory. In fact, seemingly noone knows the answer:

https://stackoverflow.com/questions/50707542/preserve-remote-repository-url-xml-format

=> We can't mirror something that doesn't have a path.

I'm already puzzled how the mirror site works, because it returns HTML, and not XML, and still works with WebDriverManager.

So can you please either help me with that, or what would be better: provide a way of mirroring that does not require special magic to happen?

Thanks in advance.

**Comment by rkrisztian** [comment]
I'm not getting any response, should I open a new ticket?
