### ISSUE TITLE
PhantomJsDriverManager doesn't work anymore.

### ISSUE THREAD

**Issue by RationalMachine** [bonigarcia/webdrivermanager#234]
```
PhantomJsDriverManager.getInstance().setup();
driver = new PhantomJSDriver();
```

PhantomJSDriver() does not resolve anymore.

Following is the OS info:

```
Distributor ID:	elementary
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki
```

**Comment by bonigarcia** [comment]
I checked that PhantomJS tests in Ubuntu (and Windows) are working fine. I'm not sure what can be different in elementary OS.

In any case... which version of WebDriverManager are you using? Just in case, try to use the latest version.

**Comment by RationalMachine** [comment]
If you don't mine me asking I have a question. Why do we have a WebDriverManager and also a separate driver specific manager like ChromeDriverManager for example? I'd like to know why would I be inclined to use one of them as opposed to the other? Why not just have the WebDriverManager?

**Comment by bonigarcia** [comment]
ChromeDriverManager is the old API (WebDriverManager 1.x). I leave there in WebDriverManager 2.x for compatibility reasons (internally it's the same logic). WebDriverManager will be the only alternative as of WebDriverManager 3.x.
