### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by yvanavermaet** [bonigarcia/webdrivermanager#238]
Dear

I was wondering if you have any plans of supporting Safari?
I saw an issue of early 2016 that stated you need a browser extension. It seems that is no longer the case since late 2016.

Thanks in advance. 

Kind regards,
Yannick

**Comment by bonigarcia** [comment]
As far as I know, latest versions of Safari does not require to resolve any driver binary (like Chrome or Firefox) to be used from WebDriver. As you said, the extension is no longer required, but instead, the own Safari binary talks the [WebDriver protocol](https://www.w3.org/TR/webdriver/) and therefore can be driven automatically form WebDriver code. More info [here](https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari) or [here](https://webkit.org/blog/6900/webdriver-support-in-safari-10/).

**Comment by 0TT0mation** [comment]
what about chrome and firefox on macOS? Through something like jenkins pipelines
