### ISSUE TITLE
Correct version for installed chrome/chromium version

### ISSUE THREAD

**Issue by nikolauskrismer** [bonigarcia/webdrivermanager#239]
I do have a short question:
If I am using chrome browser version 66 right now (which is the up-to-date version on fedora 28 when using the repo from google). Webdrivermanager now uses chromedriver 2.41 on my system, since this is the latest version of it.

Now there is a problem...
Chromedriver 2.41 does not support chrome 66. It is limited to versions 67-69 (according to http://chromedriver.chromium.org/downloads).
As a result my selenium tests do not run (chrome starts up, but does not load the page it should).
When using chromedriver 2.40 that supports version 66 everything runs without problems.

I know that i can hard-code the chromedriver version in my code, but wouldn't is be also possible for the webdrivermanager to check for the latest version that supports the installed chrome/chromium browser version?

**Comment by bonigarcia** [comment]
This has been implemented in WebDriverManager 3, recently released.

**Comment by nikolauskrismer** [comment]
Oh wow... that was quick :-)
Thank you for the implementation!

**Comment by TheDhamo** [comment]
I know I fix for temporary by myself but wanted to let you know that it is occuring again now as the latest version of Chrome Driver [v74.0.3729.6] which is used by WebDriverManager is not supporting the latest Chrome browser Version 73.0.3683.75 (Official Build). 

org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.23 seconds
