### ISSUE TITLE
Test will freeze/fail, trying to download driver binary, when developer computer is temporarily offline

### ISSUE THREAD

**Issue by djangofan** [bonigarcia/webdrivermanager#24]
I have a scenario where I had online access and was initially able to download the Chrome driver into my local machine but, when network access is limited/offline,  my test  will freeze before it starts and never get past this line in the output log:

2016-03-29 08:56:03 [pool-1-thread-1]  INFO  io.github.bonigarcia.wdm.BrowserManager - Reading http://chromedriver.storage.googleapis.com/ to seek chromedriver 
   --- then, after 40 seconds  ---
2016-03-29 08:56:43 [pool-1-thread-1]  WARN  io.github.bonigarcia.wdm.BrowserManager - [1/3] Exception reading http://chromedriver.storage.googleapis.com/ to seek chromedriver: java.net.SocketException Software caused connection abort: recv failed 
    -- test suite fails to start --

What I am expecting here is for WebDriverManager to fallback and use the previously downloaded binary driver.  Is this possible to fix?

**Comment by bonigarcia** [comment]
Use a fixed version of chromedriver instead of reading to the repository to get the latest version. That should do the trick. For example:

`ChromeDriverManager.getInstance().setup("2.21");`

**Comment by djangofan** [comment]
Using your suggestion didn't change anything about the behavior:
`ChromeDriverManager.getInstance().setup("2.21");`
So, I have this setup in my application.properties : 
```wdm.chromeDriverUrl=http://chromedriver.storage.googleapis.com/
wdm.chromeDriverExport=webdriver.chrome.driver
wdm.chromeDriverVersion=2.21
```
And I start the driver like this:
`ChromeDriverManager.getInstance().setup(Architecture.x32);`
So, my question is:  WHY would you suggest I call setup with a version number if I clearly state the version number that I want in my application.properties file?  Also, if I want to run a previously download driver: 2.18, 2.20, or whatever, why does your code ALWAYS try to download via the  wdm.chromeDriverUrl  when the driver (with that version) was already previously download by WDM?

**Comment by bonigarcia** [comment]
There was an issue related to this in version 1.4.1. Test with WebDriverManager 1.4.2 and the following command:

`ChromeDriverManager.getInstance().setup(Architecture.x32, "2.21");`

**Comment by djangofan** [comment]
It works now for me, thanks.  Forgot to tell you that I think.

**Comment by djangofan** [comment]
Was having this problem again on version 1.4.1  and I just verified again that version 1.4.2 fixes the problem.   Thanks again.

**Comment by andrey-epifanov** [comment]
hello ! 
Many thanks for your library ! :) 
I have such case. 
And this fix is available for versions of chrome driver like 2.0 - 2.24 .
But  http://chromedriver.storage.googleapis.com does not contain 3.0.1 chromedriver , that's why it is not work with 3.0.1 .
Can it be fixed? 

Andrey

**Comment by bonigarcia** [comment]
@andrey-epifanov I don't understand your point. The latest version of _chromedriver_ at writing time is 2.27. You should be able to use `ChromeDriverManager` to force a given version, for example this way:

`ChromeDriverManager.getInstance().setup("2.27");`

What's the problem?

**Comment by djangofan** [comment]
He is right, that site only hosts ChromeDriver up to version 2.27 :
https://sites.google.com/a/chromium.org/chromedriver/home

As far as I can tell, there is not a ChromeDriver version higher than 2.27:
 https://github.com/SeleniumHQ/selenium/issues/2566

**Comment by andrey-epifanov** [comment]
Official Selenium News 
http://www.seleniumhq.org/about/news.jsp 

Also I try to research pages / sites like http://chromedriver.storage.googleapis.com with higher version of ChromeDriver , and  don't find.

**Comment by bonigarcia** [comment]
You are confusing the version of Selenium WebDriver which is 3.x with the version of chromedriver, which is the specific binary aimed to control Google Chrome browser with Selenium Webdriver. The latest version of chromedriver, as I said before is 2.27 currently.

**Comment by andrey-epifanov** [comment]
May be. Sorry if I have mistake .
But - I execute for my maven project command : mvn dependency:tree -Dverbose
and see following : 
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.0.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.0.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.0.1:compile

With best regards,
Andrey

**Comment by andrey-epifanov** [comment]
@bonigarcia 
After check I inclined to think that you are right, because without concrete  version of chromedriver in setup  I see in log : 
2017-01-24 20:17:42 [main] INFO  i.g.bonigarcia.wdm.BrowserManager - Reading http://chromedriver.storage.googleapis.com/ to seek chromedriver
2017-01-24 20:17:44 [main] INFO  i.g.bonigarcia.wdm.BrowserManager - Latest version of chromedriver is 2.27
2017-01-24 20:17:44 [main] INFO  i.g.bonigarcia.wdm.BrowserManager - Exporting webdriver.chrome.driver as C:\Users\Epifanov\.m2\repository\webdriver\chromedriver\win32\2.27\chromedriver.exe

but this conflict of version is looking like trick, sorry ))  

where can I watch matching versions chrome driver in seleniumhq and chromedriver in http://chromedriver.storage.googleapis.com/ ?
