### ISSUE TITLE
Error at Shell runAndWaitNoLog

### ISSUE THREAD

**Issue by lucasn580** [bonigarcia/webdrivermanager#241]
Hi,

I'm getting the following error:

> io.github.bonigarcia.wdm.Shell:runAndWaitNoLog(63) | There was an error executin commannd [google-chrome, --version] on the shell
> java.io.IOException: Cannot run program "google-chrome": error=2, File or directory do not exist
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
> 	at io.github.bonigarcia.wdm.Shell.runAndWaitNoLog(Shell.java:59)
> 	at io.github.bonigarcia.wdm.Shell.runAndWaitArray(Shell.java:50)
> 	at io.github.bonigarcia.wdm.Shell.runAndWait(Shell.java:44)
> 	at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:969)
> 	at io.github.bonigarcia.wdm.ChromeDriverManager.getBrowserVersion(ChromeDriverManager.java:68)
> 	at io.github.bonigarcia.wdm.WebDriverManager.getVersionForInstalledBrowser(WebDriverManager.java:477)
> 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:430)
> 	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
> 	at br.com.me.core.utilitario.driver.ChromeDriver.driverUpdate(ChromeDriver.java:49)
> 	at br.com.me.core.utilitario.driver.ChromeDriver.<clinit>(ChromeDriver.java:18)
> 	at br.com.me.core.utilitario.driver.WebDriverFactory.criarNovoWebDriver(WebDriverFactory.java:78)
> 	at br.com.me.core.utilitario.driver.WebDriverFactory.criarNovoWebDriver(WebDriverFactory.java:50)

And some of my methods:

```
 @NotNull
    static WebDriver getDriver(Boolean headless) {
        ChromeOptions options = getChromeOptions(headless, getStringObjectMap());

        options.merge(getCapabilities(options));

        return new org.openqa.selenium.chrome.ChromeDriver(getService(), options);
    }

    private static void driverUpdate() {
        if (Data.get("DriverUpdate").equals("y"))
            WebDriverManager.chromedriver().setup();

        else WebDriverManager.chromedriver().forceCache().setup();
    }

    @NotNull
    private static Map<String, Object> getStringObjectMap() {
        Map<String, Object> prefs = new HashMap<>();
        prefs.put("download.default_directory", resourcePath);
        return prefs;
    }

    @NotNull
    private static ChromeOptions getChromeOptions(Boolean headless, Map<String, Object> prefs) {
        ChromeOptions options = new ChromeOptions();
        if (headless) {
            Data.set("browser", "chromeheadless");

            options.addArguments("headless");
            options.addArguments("window-size=1920x1080");

        } else Data.set("browser", "chrome");

        options.addArguments("--no-sandbox");
        options.addArguments("--start-maximized");
        options.setExperimentalOption("prefs", prefs);
        return options;
    }
```

Do you know how to solve it? Thanks very much

**Comment by bonigarcia** [comment]
I think this a warning, not an error, isn't it? WebDriverManager should work fine even with when this warning trace happens. In any case, I will remove this trace in next version to avoid misunderstandings.
