### ISSUE TITLE
WDM should not perform OPTIONS request to github too often

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#250]
```java
public abstract class WebDriverManager {
  ..
  protected void manage(Architecture arch, String version) {
    ...
    boolean cache = config().isForceCache() || !isNetAvailable();
    ...
  }
}
```

Method `isNetAvailable` performs `OPTIONS` request to github which is quite slow (takes at least 0.5 seconds on my laptop). When I need to 

Actually it's not needed (at least so often). WDM behaviour should not depend on network availability. If a correct binary is found in cache, it should be used. If not, it should be downloaded. Period.

So, we should better improve the check for cached webdriver.

**Comment by bonigarcia** [comment]
Thanks again @asolntsev. I am going to change also this behavior in the new version.

**Comment by bonigarcia** [comment]
Done. It will be available on next version.
