### ISSUE TITLE
getDefaultBrowserVersion throws NullPointerException on 32-bit versions of Windows

### ISSUE THREAD

**Issue by adamjson** [bonigarcia/webdrivermanager#255]
The implementation for Chrome and Firefox (oddly, not for Opera) relies on a Windows environment variable "PROGRAMFILES(X86)" which doesn't exist on 32-bit versions of Windows. I believe "%programfiles%" works on both 32 and 64 bit versions of Windows:

**From Wikipedia**

> %ProgramFiles%, %ProgramFiles(x86)%, %ProgramW6432%
> The %ProgramFiles% variable points to the Program Files directory, which stores all the installed programs of Windows and others. The default on English-language systems is "C:\Program Files". In 64-bit editions of Windows (XP, 2003, Vista), there are also %ProgramFiles(x86)%, which defaults to "C:\Program Files (x86)", and %ProgramW6432%, which defaults to "C:\Program Files". The %ProgramFiles% itself depends on whether the process requesting the environment variable is itself 32-bit or 64-bit (this is caused by Windows-on-Windows 64-bit redirection).
> 

See: https://en.wikipedia.org/wiki/Environment_variable

**Comment by bonigarcia** [comment]
This should be fixed now.
