### ISSUE TITLE
Getting the latest stable version of ChromeDriver

### ISSUE THREAD

**Issue by baflQA** [bonigarcia/webdrivermanager#258]
Hi @bonigarcia . 
First of all - thanks a lot for Your great job!
Since version 3.x, We all rely even more on Your hard work - to always get the latest version of the driver, You have to release a new version.
Currently (27.09.2018) the Chrome 69 is out. The latest stable version of the Chromedriver is 2.42. 
In the properties file of the webdrivermanager, there is 2.41 version. 
I would like to get the latest release available. 
When I create a driver this way:
`				WebDriverManager.config().setAvoidAutoVersion(true);
				WebDriverManager.chromedriver().setup();
`
given version of Chromedriver is gonna be set up:
`io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 70.0.3538.16`

If I set up the driver using: 
`WebDriverManager.config().setAvoidAutoVersion(true);
				WebDriverManager.config().setUseBetaVersions(false);
				WebDriverManager.chromedriver().setup();`

The same version will be returned. 
I also tried with specifying "latest" version:
`WebDriverManager.config().setAvoidAutoVersion(true);
WebDriverManager.config().setUseBetaVersions(false);
WebDriverManager.config().setDriverVersion("latest");
WebDriverManager.chromedriver().setup();`

I get `[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is latest
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - No binary found for chromedriver latest ... seeking another version
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is null
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - chromedriver (latest version) for MAC64 not found in https://chromedriver.storage.googleapis.com/`

My workaround for that is to use given code:
`try (BufferedReader reader = new BufferedReader(
					new InputStreamReader(new URL(latestUrl).openStream()))) {
				WebDriverManager.chromedriver().version(reader.readLine()).setup();
				driver = new ChromeDriver(options);`

It would be nice to have a method for setting up the latest stable version of the driver, without waiting for the new release of the webdrivermanager. Or in case of this configuration:
`WebDriverManager.config().setAvoidAutoVersion(true);
WebDriverManager.config().setUseBetaVersions(false);
WebDriverManager.config().setDriverVersion("latest");
WebDriverManager.chromedriver().setup();`
where no beta, no auto version, and the latest version is required, the latest stable release is returned.

**Comment by blacelle** [comment]
While not documented elsewhere, this new chromedriver version mapping with the latest chrome version seems a valid latest chromedriver

see https://chromedriver.storage.googleapis.com/

**Comment by bonigarcia** [comment]
Thanks for your comments @baflQA. I plan to implemented an auto update mechanism of browser versioning in next version of  WebDriverManager. Please stay tuned.

**Comment by bonigarcia** [comment]
WebDriverManager 3.1.0 is out. Now, if a driver cannot is not contained in the internal content of versions.properties, the [online master version](https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/src/main/resources/versions.properties) is used instead.
