### ISSUE TITLE
Code always re-downloads PhantomJS driver even when previously downloaded

### ISSUE THREAD

**Issue by djangofan** [bonigarcia/webdrivermanager#26]
I am experiencing another problem similar to what you fixed in pull request #24  :   Code always re-downloads PhantomJS driver even when previously downloaded.

So, on version 1.4.2,  and I am using a MAC-Pro now,  the PhantomJS driver download site only has 1 driver binary available, which is 32-bit.    Now, when that driver is stored locally on my computer (in the configured location),  it is stored in a folder called  phantomjs/macosx/2.1.1/phantomjs   instead of what I was expecting, which is  phantomjs/macosx/2.1.1/mac32/phantomjs   .    So, it is my belief that the code is not able to detect that a 32-bit version of 32-bit phantom was previously downloaded and therefore, it always tries to re-download it every time.   

NOTE: All other configurations I have are configured like i described in pull request #24

**Comment by djangofan** [comment]
More specifically, here is the error I get from WebDriverManager:
```

2016-05-04 10:15:05 [main]  TRACE BrowserManager - Checking if phantomjs 2.1.1 (32 bits) exists in cache /Users/r626095/.m2/repository 
2016-05-04 10:15:05 [main]  TRACE BrowserManager - phantomjs 2.1.1 (32 bits) do not exist in cache /Users/r626095/.m2/repository 
2016-05-04 10:15:05 [main]  DEBUG BrowserManager - Reading https://bitbucket.org/ariya/phantomjs/downloads/ to find out the latest version of PhantomJS driver 
... infinite timeout here ...
```

**Comment by bonigarcia** [comment]
The problem here is that PhantomJS for Mac (and Windows) are not specific for a platform (32, 64 bits). I made a minor change to take into account this issue.

A new version of WebDriverManager has been released (1.4.3). Please try with that version.

**Comment by djangofan** [comment]
@bonigarcia   I'll probably have time to verify the fix today.  I'll comment on this as soon as I verify.

**Comment by djangofan** [comment]
Can't quite verify yet until  your new release shows up at maven central.  It doesn't appear to be there yet.

**Comment by bonigarcia** [comment]
Sorry, my fault. I forget to close/release the artifact in the repository manager. Now it's done, and version 1.4.3 is available on Maven Central.

**Comment by djangofan** [comment]
When i look at your repo (master branch), its labeled 1.4.4-SNAPSHOT .  Also, not seeing it yet on search.maven.org .   Can you verify again?

**Comment by bonigarcia** [comment]
Version 1.4.3 seems to be deployed in Maven Central:

http://search.maven.org/#artifactdetails%7Cio.github.bonigarcia%7Cwebdrivermanager%7C1.4.3%7Cjar

**Comment by djangofan** [comment]
Your right. I was thinking it was 1.4.4 rather than 1.4.3.  My bad.  Thanks.  My verification of this is imminent.

**Comment by djangofan** [comment]
I found some time to try to validate this but for some reason the artifactory server at my work is unable to proxy the version 1.4.3 of the webdrivermanager.    I tried to work around it by running this command but the command fails (perhaps due to a typo?):   
```mvn install:install-file -Dfile=.m2/repository/io/github/bonigarcia/webdrivermanager/1.4.3/webdrivermanager-1.4.3.jar -DgroupId=io.github.bonigarcia -DartifactId=webdrivermanager -Dversion=1.4.3 -Dpackaging=jar```

**Comment by djangofan** [comment]
Ok, I managed to verify this.  It works now.  Thank you!
