### ISSUE TITLE
Edge 44 (Windows 10 1809) is not possible to use with webdrivermanager

### ISSUE THREAD

**Issue by mseele** [bonigarcia/webdrivermanager#262]
webdrivermanager tries to use latest edge driver via download but the webdriver for edge 44 is now integrated in windows (https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/).

Therefore the edge unit tests are failing. There need to be a check for this and the local webdriver should be used.

**Comment by mseele** [comment]
The path is `C:\Windows\system32\MicrosoftWebDriver.exe`, and it’s now conveniently also in the PATH.

For more details, please see: https://macops.ca/installing-webdriver-as-a-feature-on-demand-in-windows-redstone-5/

**Comment by bonigarcia** [comment]
Thank you @mseele. I've just committed a patch solving this issue for Edge 44.

**Comment by Mini-Thomas** [comment]
Hi,
I am using Selenium+C# and facing issues while running the automation tool in Edge 44 version.
The same works fine in Edge 42 version.
Could you please provide solution in c#
