### ISSUE TITLE
Cannot get list of firefox drivers.

### ISSUE THREAD

**Issue by szorlowski** [bonigarcia/webdrivermanager#264]
Hi

Currently, if we try to get a list of firefox's drivers we get null.

Possible cause:
We get 404 Not found from there.
https://api.github.com/repos/mozila/geckodriver/releases

**Comment by bonigarcia** [comment]
That URL you wrote is incorrect (notice "mozilla"):

https://api.github.com/repos/mozilla/geckodriver/releases
