### ISSUE TITLE
System proxy settings are not taken by default when proxy configuration is not provided

### ISSUE THREAD

**Issue by NallaSandeep** [bonigarcia/webdrivermanager#265]
When giving proxy configuration, it's able to connect & get the needed driver.
Eg: WebDriverManager.chromedriver().proxy("a.b.c.d:e").setup();  

But, when proxy configuration is not given, it's not able to connect through the System proxy settings, but the connection is getting timed out.
org.apache.http.conn.HttpHostConnectException: Connect to api.github.com:443 [api.github.com/192.30.253.116, api.github.com/192.30.253.117] failed: Connection timed out: connect  

In a similar line, if RestAssured.proxy configuration is not given, it's taking the System proxy settings and able to make consequent requests. 

Can the same be implemented for WebDriverManager also?

**Comment by bonigarcia** [comment]
I'm going to change a bit the behavior of the connectivity of WebDriverManager in the next version. Please stay tuned.

**Comment by bonigarcia** [comment]
WebDriverManager 3.1.0 has been released. Please try the new version and confirm if the issue is solved.

**Comment by bonigarcia** [comment]
Please use WebDriverManager 3.1.1 instead (version 3.1.0 had a bug).

**Comment by bonigarcia** [comment]
No clue. Maybe the problem is in your network configuration. I am not able to reproduce it.
