### ISSUE TITLE
By adding dependency issue on XSI:SchemaLocation

### ISSUE THREAD

**Issue by ishah09** [bonigarcia/webdrivermanager#267]
By adding dependency, pom.xml having issue on xsi:schemaLocation

Failure to transfer org.apache.commons:commons-compress:jar:1.14 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.commons:commons-compress:jar:1.14 from/to central (https://repo.maven.apache.org/maven2): The operation was cancelled.

	
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.0.0</version>
			   <scope>test</scope>
		</dependency>

![image](https://user-images.githubusercontent.com/32862749/47896023-75a26000-de91-11e8-83c9-9375c03db89b.png)

**Comment by ishah09** [comment]
I resolved it.

**Comment by deepanshuMi** [comment]
how u resolved it
