### ISSUE TITLE
Proxy Server

### ISSUE THREAD

**Issue by nickdunand** [bonigarcia/webdrivermanager#27]
I get  a Connection refused exception. 
This is probably due to our proxy server. Is it possible to specify a proxy server?

**Comment by bonigarcia** [comment]
IMHO this issue is not related with WebDriverManager, but with the network capabilities of Java. There are plenty of information online to change the proxy settings of a JVM (e.g. [here](http://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm)).
