### ISSUE TITLE
org.openqa.selenium.NoSuchWindowException: Currently focused window has been closed

### ISSUE THREAD

**Issue by aneesforgit** [bonigarcia/webdrivermanager#270]
Hi,

I am using a framework having Geb+cucumber+groovy as the components. When I try to run for Chrome with the below code in GebConfig.groovy its working fantastically. But when I try to run Edge and IE its throwing below errors. 
Attaching file for each browser with error details

**Working fine:**
WebDriverManager.chromedriver().setup()
driver = {
	def driver = new ChromeDriver()
	driver.manage().window().maximize()
	return driver
}

bonigarcia:webdrivermanager version used in gradle is
testCompile("io.github.bonigarcia:webdrivermanager:2.2.4") {
		exclude group: 'org.seleniumhq.selenium'
	}

**Not working:**

WebDriverManager.iedriver().setup()
driver = {
	def driver = new InternetExplorerDriver()
	driver.manage().window().maximize()
	return driver
}

WebDriverManager.edgedriver().setup()
driver = {
	def driver = new EdgeDriver()
	driver.manage().window().maximize()
	return driver
}

WebDriverManager.firefoxdriver().setup()
driver = {
	WebDriver driver = new FirefoxDriver()
	driver.manage().window().maximize()
	return driver
}

[Error for FF.txt](https://github.com/bonigarcia/webdrivermanager/files/2565683/Error.for.FF.txt)
[Error for IE.txt](https://github.com/bonigarcia/webdrivermanager/files/2565684/Error.for.IE.txt)
[Error for Edge.txt](https://github.com/bonigarcia/webdrivermanager/files/2565685/Error.for.Edge.txt)

**Comment by bonigarcia** [comment]
This is not a WebDriverManager issue.
