### ISSUE TITLE
There is no support to download driver for 32 bit machine

### ISSUE THREAD

**Issue by prateek1605** [bonigarcia/webdrivermanager#276]
protected Optional<String> getBrowserVersion() {
        return getDefaultBrowserVersion("PROGRAMFILES(X86)",
                "\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe",
                "google-chrome",
                "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                "--version", driverManagerType.toString());
    }

The above function contains string "PROGRAMFILES(X86)" which works for only on 64 bit architecture for windows, for 32 bit it gives error.  For making it work we need to provide the version like 

WebDriverManager.chromedriver().version("2.39").setup();.

Please fix this issue

**Comment by pierrepinon** [comment]
Hello @prateek1605,

I try to make PR soon

**Comment by bonigarcia** [comment]
Fixed. It will be available on next version.
