### ISSUE TITLE
Doesn't work when building on Jenkins

### ISSUE THREAD

**Issue by ndtreviv** [bonigarcia/webdrivermanager#28]
Do I still need to install the binaries on my Jenkins build server, or does this library remove the need for that as well? Only, at the moment this works wonderfully locally, but not at all on Jenkins.

Unfortunately the only bit of the exception that Jenkins logging gives me is:
`org.openqa.selenium.WebDriverException`
and nothing else...

**Comment by ndtreviv** [comment]
Ok, finally got the exception, which is:

`
org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.16.0-4-amd64 x86_64)`

Any ideas?

**Comment by bonigarcia** [comment]
No clue.

We are using WebDriverManager in my lab with no problems. Whatever is happening is in your side.
