### ISSUE TITLE
In case of IE driver, It is not working.

### ISSUE THREAD

**Issue by viveksingh1992** [bonigarcia/webdrivermanager#288]
Whenever I am giving IE driver to runt tests I am getting following issue:

java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html

Please help.

**Comment by viveksingh1992** [comment]
Please help me with this.
This is not invalid.

**Comment by viveksingh1992** [comment]
![untitled](https://user-images.githubusercontent.com/38939348/49935282-aa74ee80-fef6-11e8-81b6-15708e89398e.png)

**Comment by viveksingh1992** [comment]
@bonigarcia Please look into the issue above.

**Comment by bonigarcia** [comment]
It seems the `BeforeClass` method is being skipped. It is not a issue of WebDriverManager but your test configuration/implementation.

**Comment by viveksingh1992** [comment]
![untitled](https://user-images.githubusercontent.com/38939348/49936360-c037e300-fef9-11e8-8f7b-4243d2f555ac.png)
Even after using always run, its not working.

**Comment by viveksingh1992** [comment]
@bonigarcia Please look into the comment above.
