### ISSUE TITLE
webdriver manager in CLI mode refers to HTTPS_PROXY environment variable in caps only

### ISSUE THREAD

**Issue by PrakharSuhane** [bonigarcia/webdrivermanager#292]
webdrivermanager in CLI mode refers to HTTPS_PROXY in caps however the normal for environment variables is the 'lower case' in linux. I understand there is no convention as such. It will be appreciable if both https_proxy and HTTPS_PROXY are referred.

**Comment by bonigarcia** [comment]
Done.
