### ISSUE TITLE
Add support for trifleJS

### ISSUE THREAD

**Issue by kathyrollo** [bonigarcia/webdrivermanager#294]
# Summary
WebDriverManager to support [trifleJS](https://github.com/sdesalas/trifleJS).
# Possible Solution
Something to the likes of:
```
WebDriverManager.triflejs.setup();
```
With `arch32()` or `arch64()` support if available.
# Context & Motivation
PhantomJS development has been [suspended](https://github.com/ariya/phantomjs/issues/15344) indefinitely due to lack of active contribution. trifleJS is a port and is in active development.

**Comment by bonigarcia** [comment]
I'm not sure about this. I've checked TrifleJS and it seems a headless Internet Explorer browser using the V8 JavaScript engine for running scripted tests. At low level, it is a binary file for Windows, but its usage  seems independent to what WebDriverManager does, which is resolving binary drivers such as  *chromedriver* or *geckodriver* previously to the use of the corresponding Selenium WebDriver Java class (`ChromeDriver`,  `FirefoxDriver`, and so on).
