### ISSUE TITLE
Chrome version not being detected on Windows 7

### ISSUE THREAD

**Issue by ali-185** [bonigarcia/webdrivermanager#296]
Environment: 
Windows 7, x64
Java 8
WebDriverManager 3.1.1
Chrome 67.0.3396.99

I am not running the latest version of Chrome which can't use the latest chrome driver. WebDriverManager should detect this and use the correct chromedriver, however it is installing the latest chromedriver.

The cause of this issue can be seen in the trace level log lines:

> Property wdm.binaryPath not found in /webdrivermanager.properties, using default values (in /webdrivermanager.properties)
> Property wdm.binaryPath not found in /webdrivermanager.properties, using blank value

These are printed out from method `io.github.bonigarcia.wdm.Config.class#getProperty` when called by method `io.github.bonigarcia.wdm.WebDriverManager.class#getDefaultBrowserVersion`

This means that if `wdm.binaryPath` is not present, it will be a blank value. However, in the
`io.github.bonigarcia.wdm.WebDriverManager.class#getDefaultBrowserVersion` method at line 1039 of the class file. The following code shows that the value is compared against null (which it will never be, it'll be the blank value).

```
            String browserPath = browserBinaryPath != null ? browserBinaryPath
                    : programFiles + winBrowserName;
```

This results in my browserPath being set as the blank value, and not being detected for my machine.

**Comment by bonigarcia** [comment]
The issue is not related with the value of `wdm.binaryPath`. That configuration key is empty by default. It can be used to override the default value of the binary path for a given browser.

**Comment by ali-185** [comment]
Yes, the default key from the properties file is empty and loaded into Java as an **empty Java String, ""**. However, when it is checked in the code to see if one was supplied or it is to look in the Program Files folder, it is checked against **null, not an empty Java String, ""**. And therefore will always fail.

You can see that `io.github.bonigarcia.wdm.WebDriverManager.class#getDefaultBrowserVersion` at line 1039 it's checked against null.
```
            String browserPath = browserBinaryPath != null ? browserBinaryPath
                    : programFiles + winBrowserName;
```

**Comment by bonigarcia** [comment]
You were right, the condition against the empty String was missing. Now it is fixed. Thanks a lot for reporting.
