### ISSUE TITLE
Can WDM download binaries from mirror when primary link have failed?

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#302]
Currently when WDM downloads the binary and the limit of downloads is exceeded - we receive a nasty Error HTTP 403 executing GET https://api.github.com/repos/operasoftware/operachromiumdriver/releases HTTP/1.1 error and have to wait up to an hour to try to download a binary(or switch to mirror link manually). 
This limit is very easily exceeded in large companies that use 1-2 static IPs as a gateway for the Internet connection.

WDM has an ability to download the binary from a mirror browser storage, so we have all set to avoid such errors from Github(used to download gecko and opera driver).

Could WDM try alternative (mirror) URL by default to download the binary if 403 error is received from Github and mirror link is set in properties file?

**Comment by bonigarcia** [comment]
In theory, latest versions of WebDriverManager (3.1 and 3.2) are supposed to reduce significantly the occurrence of the 403 error. In this versions, the resolved version for drivers are stored persistently as Java preferences with an expiration time (TTL=1 hour by default). Together with the use of cached driver binaries, the connections to online repositories (i.e. GitHub and so on) is supposed to be reduced.

@AlexanderPoleschuk In which version of WebDriverManager are you experiencing 403 errors? Can you provide extra details about it?

**Comment by AlexanderPoleschuk** [comment]
The version I use is the latest available - 3.2.0.
I've tried to help a team mate with the issue he experienced with Opera browser. I haven't downloaded Opera binary before, so after I've switched to Opera browser - I received 403 error. This is kind of "natural" thing for big companies that use a static gateway IP address that is exposed to the Internet.
All the requests from such regions are recognized as requests from the only IP.
I'm not familiar with github limitation in detail, but I believe that it counts all the calls from IP to github, so this limit amount is easily expired.

**Comment by bonigarcia** [comment]
I tried to improve this behavior in the latest release (3.3.0). Now, mirror is used (if available) when an exception happens for the first time (e.g. 403 error). Please have a try.

**Comment by AlexanderPoleschuk** [comment]
Yep, now the mirror is used and the probability to have an issue with driver download became lower.
The only thing I've noticed that candidatesUrls are downloaded very slowly from taobao, but there is nothing we may influence on, I believe.
