### ISSUE TITLE
Firefox/geckodriver/Marionet URL isn't working, neither is the overide with new URL.

### ISSUE THREAD

**Issue by Shauneh** [bonigarcia/webdrivermanager#31]
Firefox/geckodriver/Marionet URL isn't working, neither is the overide with new URL.

Currently cannot get it to work, I am also unsure what the new URL is for the API to get to the newest download.

I have used a few from https://github.com/mozilla/geckodriver/releases/ but didn't appear to work...

**Comment by bonigarcia** [comment]
Yes, the latest release of Marionette driver is called geckodriver instead of wires. This has broken the compatibility with WebDriverManager. I am on it, I'll release a new patch version of WebDriverManager to solve this problem ASAP.

**Comment by bonigarcia** [comment]
Version 1.4.5 has been released to solve this problem.
