### ISSUE TITLE
Unable to locate the correct path to Chrome

### ISSUE THREAD

**Issue by alenmeister** [bonigarcia/webdrivermanager#310]
I'm trying to run our regress suite on Jenkins on the OpenShift platform. However, there seems to be a mismatch between the chrome paths. Is this a potential bug related to WebDriverManager or does this have something to do with the stable version from RHEL's repository?

> Starting ChromeDriver 73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017) on port 27293
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
2019-03-05 13:48:29.894 [main] WARN  i.g.bonigarcia.wdm.WebDriverManager - The driver version for Google Chrome /usr/bin/google-chrome: line 49: /usr/bin/chrome: No such file or directory is unknown ... trying with latest

Quick note, we did try to create a symlink from /usr/bin/google-chrome to /usr/bin/chrome - but that really messed up the build and created a bunch of other warnings.

Any ideas?

**Comment by alenmeister** [comment]
Forgot to mention that I'm using version 3.3.0 of WDM and the current stable version in RHEL's repository is version 68.0.3440 I believe. I might have to double check that.

**Comment by bonigarcia** [comment]
You can try the following:

`WebDriverManager.chromedriver().browserPath("/path/to/your/google-chrome").setup();`
