### ISSUE TITLE
Chrome 74. Global Config via code. README is out of date.

### ISSUE THREAD

**Issue by evanliferock** [bonigarcia/webdrivermanager#313]
Chrome 74 is a thing now. The webdrivermanger downloads chrome 74 but tries to run chrome 73 causing failure.

I was using version 3.0.0 and using `WebDriverManager.config()` to globally set the target path for all drivers to put the binaries in. However in the newer versions it doesn't seem to work. I would rather not set a target path for each browser individually so I looked for how to set global config but found this in the README:
```
Moreover, as of WebDriverManager 2.2.x, configuration value can be customized using a configuration manager. This manager can be accessed using WebDriverManager.config(). For example:
```
which doesn't work. How can I globally setTargetPath for all drivers.

**Comment by materia2021** [comment]
using 3.0.0 too 
upgrading to the latest release will fix this issue.

**Comment by winscon** [comment]
Hi, i'm getting the same error too. Any workarounds for now?

**Comment by agdula** [comment]
try running using this system property: -Dwdm.chromeDriverVersion=73

**Comment by bonigarcia** [comment]
@evanliferock Thanks for reporting.

Indeed the README is outdated. As of WDM 3.2.0 `WebDriverManager.config()` is not available because it might cause problems between managers. As of this version, configuration is done per manager (e.g. `WebDriverManager.chromedriver().config()`).

I have just committed a patch to allow global configuration from code using a new method: `WebDriverManager.globalConfig()`. It will be available for next version.

**Comment by nomerson** [comment]
and what about chromedriver 74? why does manager download beta driver instead of stable by default?

**Comment by nerjamartin** [comment]
Another workaround is to rename the folder for ChromeDriver 74 to use ChromeDriver 73 instead... While we wait for Chrome 74.
It's a little trick, but it works :-)

**Comment by sanp0001** [comment]
> Another workaround is to rename the folder for ChromeDriver 74 to use ChromeDriver 73 instead... In the while we're waiting for chrome 74
> It's a little trick, but it works :-)

Where do you find this Chrome folder ?

**Comment by sanp0001** [comment]
> and what about chromedriver 74? why does manager download beta driver instead of stable by default?
> 
> Latest stable release: ChromeDriver 73.0.3683.68
> Latest beta release: ChromeDriver 74.0.3729.6

Yes, this is first thing I saw in the morning today. 

This version of ChromeDriver only supports Chrome version 74                           
(Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server  did not provide any stacktrace information)

**Comment by bonigarcia** [comment]
To avoid this kind of problems, the latest version of WebDriverManager (3.3.0 at the time of this writing) is highly recommended.

**Comment by nerjamartin** [comment]
> 
> 
> > Another workaround is to rename the folder for ChromeDriver 74 to use ChromeDriver 73 instead... In the while we're waiting for chrome 74
> > It's a little trick, but it works :-)
> 
> Where do you find this Chrome folder ?

If you are under Windows you should find it here : 
`C:\Users\<your_user>\.m2\repository\webdriver\chromedriver\`

**Comment by sanp0001** [comment]
> To avoid this kind of problems, the latest version of WebDriverManager (3.3.0 at the time of this writing) is highly recommended.

Sry, my bad. Updated the version to 3.3.0 and it perfectly works. 

@bonigarcia thanks for quick reply and this amazing DriverManager.

**Comment by sanp0001** [comment]
@nomerson add latest version in maven dependency - 3.3.0.

<dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.3.0</version>
        </dependency>

It works as smooth as butter.

**Comment by nerjamartin** [comment]
Another workaround (if you use Selenide) : 

https://twitter.com/jselenide/status/1105734134633127938

**Comment by evanliferock** [comment]
Wow a lot more comments thank I expected haha

The workaround I was using for the meantime for Chrome 74 is 
```java
WebDriverManager.chromedriver().version("73");
```
Easy enough. I assumed the `3.3.0` would fix the Chrome 74 issue. Just wanted to make sure you aware if it didn't and needed to fix anything since 74 was released recently (yesterday right?).

I will stick with chrome 73 until the newest version with the global config is out! Thanks for the fast response and adding the globalConfig!

**Comment by sanp0001** [comment]
Guys, I have a question. How to automatically set in dependency so that it always gets the latest version from repo? So that I don't have to update the version every time new version releases.

**Comment by nomerson** [comment]
@sanp0001, try this:


<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>LATEST</version>
</dependency>

**Comment by sanp0001** [comment]
One more, I'm running tests on CI. Linux machine has picked up my project and is throwing this error.

![image](https://user-images.githubusercontent.com/48517243/54345531-3d920180-4669-11e9-9200-e2c924e6d7b4.png)


This is what I have for driver

![image](https://user-images.githubusercontent.com/48517243/54345716-9cf01180-4669-11e9-91e6-1dbb806a1ce8.png)

**Comment by sanp0001** [comment]
> @sanp0001, try this:
> `<dependency> <groupId>io.github.bonigarcia</groupId> <artifactId>webdrivermanager</artifactId> <version>LATEST</version> </dependency>`
> 
> https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency

@nomerson , LATEST and RELEASE have been taken out from Maven 3.0 onwards. It doesn't work.

**Comment by purplekiz17** [comment]
> Another workaround is to rename the folder for ChromeDriver 74 to use ChromeDriver 73 instead... In the while we're waiting for chrome 74
> It's a little trick, but it works :-)

where is this folder situated ?

**Comment by nerjamartin** [comment]
> 
> 
> > Another workaround is to rename the folder for ChromeDriver 74 to use ChromeDriver 73 instead... In the while we're waiting for chrome 74
> > It's a little trick, but it works :-)
> 
> where is this folder situated ?

GoTo : https://github.com/bonigarcia/webdrivermanager/issues/313#issuecomment-472406700

:-)

**Comment by hpinglia** [comment]
I reverted back to Chrome Version 73.0.3683.75 but WebDriverManager (version 3.0.0) keeps downloading chromedriver version 74.0.3729.6. (This version of ChromeDriver only supports Chrome version 74)

**Comment by evanliferock** [comment]
This issue is closed. Just do 
```java
WebDriverManager.chromedriver().version("73");
```
or upgrade to version 3.3.0.

Or follow the other suggestions in this thread

**Comment by utkarsh1996** [comment]
> To avoid this kind of problems, the latest version of WebDriverManager (3.3.0 at the time of this writing) is highly recommended.

works for me!!! Thanks

**Comment by RoakyWood** [comment]
This seems to be a Linux thread and I know the issue is closed, but I am seeing the same issue on the Windows version: webdriver-manager v13.0.0 All the folders are different so I can't employ the workaround listed here. Please provide a windows based workaround. Will the underlying defect be fixed? i.e., the mismatch with Chrome version? If this is the wrong place, where would I post this for a solution? Cheers - RW

**Comment by evanliferock** [comment]
https://github.com/bonigarcia/webdrivermanager/issues/313#issuecomment-473050909

**Comment by RoakyWood** [comment]
@evanliferock I can't see your comment. It is only visible on hover and just where you recommended some solution it is cut off.

**Comment by evanliferock** [comment]
It's in this thread, about 5 comments up. https://github.com/bonigarcia/webdrivermanager/issues/313#issuecomment-473050909

**Comment by RoakyWood** [comment]
@evanliferock Thx, I see it, in what file/folder do you put that line of code?
