### ISSUE TITLE
How to handle the webdriver manager for below 60 version in chrome browser

### ISSUE THREAD

**Issue by divyarahavan** [bonigarcia/webdrivermanager#314]
I need to execute my script using chrome for below 60 version. How can I achieve this by using web driver manager

**Comment by bonigarcia** [comment]
First you need to have installed that Chrome in the machine running the test. Then find out the proper chromedriver version for your Chrome < 60 (see [here](http://chromedriver.chromium.org/downloads) and [here](https://chromedriver.storage.googleapis.com/index.html)) and then set that version in WDM. Supposing that version is 2.32 (I don't know, it's just an example):

`WebDriverManager.chromedriver().version("2.32").setup();`

**Comment by Krieg552** [comment]
work by this way, ChromeDriverManager.getInstance().version("73.0.3683.68").setup(); Thanks!

**Comment by bonigarcia** [comment]
It seems you are using an old version of WebDriverManager. I highly recommend to update to the latest version.

**Comment by ashokkumarg** [comment]
> First you need to have installed that Chrome in the machine running the test. Then find out the proper chromedriver version for your Chrome < 60 (see [here](http://chromedriver.chromium.org/downloads) and [here](https://chromedriver.storage.googleapis.com/index.html)) and then set that version in WDM. Supposing that version is 2.32 (I don't know, it's just an example):
> 
> `WebDriverManager.chromedriver().version("2.32").setup();`

@bonigarcia  Are you concluding that the chrome browser version lesser than 60 is not handled and the driver version needs to be coded in the way you provided.

Also, the relationship between browser and driver as per your version.properties would be handled automatically
