### ISSUE TITLE
Webdriver manager is not working for chrome browser.

### ISSUE THREAD

**Issue by viveksingh1992** [bonigarcia/webdrivermanager#315]
Try to run your test case in chrome. It does not work. Browser opens up like a pop up and then immediately closes. Please take a look. Same test case is working with the manual webdriver setup.

**Comment by nomerson** [comment]
https://github.com/bonigarcia/webdrivermanager/issues/313#issuecomment-472395623

**Comment by msaperst** [comment]
upgrading worked for me and several of my projects!

**Comment by viveksingh1992** [comment]
Works for me now.
