### ISSUE TITLE
Issue in io.github.bonigarcia.wdm.WebDriverManagerException: 

### ISSUE THREAD

**Issue by aruvimal** [bonigarcia/webdrivermanager#325]
i have used below dependency in my maven project, 

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.4.0</version>
</dependency>
[Even I have tried even lower version, but pom.xml itself giving error (Failed to read artifact descriptor for io.gitub.nonigarcia:webdrivermanager.jar ) ]

**Error Message** 

**SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 08, 2019 4:07:00 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

FAILED CONFIGURATION: @BeforeClass setUp
io.github.bonigarcia.wdm.WebDriverManagerException: org.apache.http.conn.HttpHostConnectException: Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out: connect**

Looks like the package it’s referencing no longer exists 
https://npm.taobao.org/package/114.55.80.225

**Comment by bonigarcia** [comment]
Reading your trace it seems there are several issues in your project:

- You don't have any logger, which is highly recommended.
- It seems there is some kind of connection problem (the taobao.org is a mirror, used when the official driver repository is not accessible).

None of these problem is directly related to WebDriverManager.
