### ISSUE TITLE
Load webdrivermanager.properties from a disk path

### ISSUE THREAD

**Issue by Yobikap** [bonigarcia/webdrivermanager#326]
Is it possible to load webdrivermanager.properties file from system disk instead from resources inside the package?

**Comment by bonigarcia** [comment]
Yes, a custom properties can be specified using the configuration key `wdm.properties`, or using the method `properties() `of a given manager, e.g. Chrome:

```
WebDriverManager.chromedriver().properties("my.properties").setup();
```

... or using global config:

```
WebDriverManager.globalConfig().setProperties("my.properties");
```
