### ISSUE TITLE
wires (latest version) for win64 not found in https://api.github.com/repos/jgraham/wires/releases

### ISSUE THREAD

**Issue by jamiejackson** [bonigarcia/webdrivermanager#33]
When trying to setup MarionetteDriverManager I get `wires (latest version) for win64 not found in https://api.github.com/repos/jgraham/wires/releases`.

Does something different need to happen now that `wires` changed names to `gecko` a few days ago? https://github.com/mozilla/geckodriver/releases

**Comment by jamiejackson** [comment]
I think you dealt with it in some recent commits. Checking...

**Comment by bonigarcia** [comment]
Version 1.4.5 has been released to solve this problem.
