### ISSUE TITLE
changelog format

### ISSUE THREAD

**Issue by BigMichi1** [bonigarcia/webdrivermanager#331]
is it possible to change the current used format of the changlog file to a mardown changelog file like CHANGELOG.md and use the pseudo format defined here https://keepachangelog.com/en/1.0.0/ ? this would help parsers to read the file, e.g. for https://github.com/renovatebot/renovate/

**Comment by bonigarcia** [comment]
Thanks for the suggestion, I will look into it.

**Comment by bonigarcia** [comment]
Done.

**Comment by BigMichi1** [comment]
thank you very much
