### ISSUE TITLE
setUseBetaVersions does not work

### ISSUE THREAD

**Issue by medy75** [bonigarcia/webdrivermanager#333]
If I use
`ChromeDriverManager.chromedriver().config().setUseBetaVersions(false);`
I am still getting chromedriver v75, but v75 is in beta release right now.
http://chromedriver.chromium.org/

With this option it should give me a stable version, which is v74, compatible with actual stable Chrome v74.

**Comment by laxersaz** [comment]
A colleague of mine also got the beta driver today which leads to an incompatibility with his currently installed chrome 74. Is this a bug in the webdrivermanager?

**Comment by AshciR** [comment]
Hey, @laxersaz I updated to v3.4.0 and I'm still having the same issue. Did your colleague do additional steps?

**Comment by laxersaz** [comment]
No, we just removed the beta driver from .m2 and started the webdrivermanager again.

**Comment by bonigarcia** [comment]
Unfortunately latest versions of WebDriverManager is not aware of chromedriver beta versions, and therefore the method `setUseBetaVersions()` has not effect. I'm planning to make a deep refactoring for a new major version of WebDriverManager, I will consider this for future versions.

**Comment by bonigarcia** [comment]
This should be fixed in version 3.6.0, recently released.
