### ISSUE TITLE
Failed to parse xml from https://chromedriver.storage.googleapis.com/

### ISSUE THREAD

**Issue by jerry153fish** [bonigarcia/webdrivermanager#336]
Failed to parse xml from https://chromedriver.storage.googleapis.com/

```
// WebDriverManger line: 1013 throw exception
                Document xml = loadXML(reader);
                NodeList nodes = (NodeList) newInstance().newXPath().evaluate(
                        "//Contents/Key", xml.getDocumentElement(), NODESET);
```

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using? How this problem can be reproduced?

**Comment by jerry153fish** [comment]
1. WebDriverManager version 3.4.0
2. OS: macOS High Sierra Version 10.13.6
3. java openjdk 11.0.2
4. Editor: Eclipse Version: 2018-09 (4.9.0)

in junit4 just call

```
WebDriverManager.chromedriver().setup();

will throw

Exception:  NoSuchMethodError -> org.apache.xpath.XPathContext.<init>(Z)V

```

**Comment by bonigarcia** [comment]
It seems there is a conflict with the class `org.apache.xpath.XPathContext`,  probably you are using a different version of the library xalan in your project and the one used internally by WebDriverManager.

**Comment by jerry153fish** [comment]
thanks
