### ISSUE TITLE
Incorrect WebDriver downloaded for Microsoft Edge

### ISSUE THREAD

**Issue by peterjohngriffin** [bonigarcia/webdrivermanager#339]
I am using WebDriverManager v3.4.0.

The Microsoft Edge WebDriver downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ is incorrect.  

The WebDriver that is downloaded seems to be offset by 3 versions.

- WebDriver Version 3.14393 is downloaded when Version 6.17134 is required.

- WebDriver Version 2.10586 is downloaded when Version 5.16299 is required.

- WebDriver Version 1.10240 is downloaded when Version 4.15063 is required.

- It fails to download anything when Versions 3.14393, 2.10586 or 1.10240 are required with the following error message:

<pre>io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: MicrosoftWebDriver 3.14393 for WIN64 not found in https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:715)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:712)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)</pre>

**Comment by bonigarcia** [comment]
There were problems with Edge in former version of WebDriverManager. I have recently released version 3.5.0, which in theory solved these issues. Please update to that version.

**Comment by deeppatel2** [comment]
I tried updating to 3.5.0 and issue still exists.
