### ISSUE TITLE
There are 2 reasons when this issue may occur.

### ISSUE THREAD

**Issue by bhavinshah09** [bonigarcia/webdrivermanager#340]
I am having Chrome Version 74.0.3729.131 (Official Build) (64-bit), what do I need to do ? Possibly my case is first option of the below suggested reason so let me know what to do ? 

There are 2 reasons when this issue may occur.

1. Case when WebDriverManager is not in use and somehow chromedriver.exe binary was updated which supports chrome browser version 74 but OS having browser as 72. In this case you would need to update binary compatible to browser version.

2. When WebDriverManager is in use which downloads browser binary automatically. Its tries to download latest chromedriver binary which may not be compatible to your chrome browser installed version let say 72 (my guess). If so, in that case we have to tell WebDriverManager to download chromedriver binary which would be compatible to your browser version 72. For doing so, please take a reference of below line and do update your code.

WebDriverManager.chromedriver().version("2.46").setup();

Note - We have added version("2.46") that means WebDriverManager would find out this specific version of chromedriver binary.

Let's know if this resolve your problem.

_Originally posted by @robintyagi12 in https://github.com/bonigarcia/webdrivermanager/issues/317#issuecomment-485118115_

**Comment by robintyagi12** [comment]
Please let me know your browser version.
