### ISSUE TITLE
WEb driver manager is picking Beta version by default

### ISSUE THREAD

**Issue by PradeepAutomate** [bonigarcia/webdrivermanager#341]
Starting ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}) on port 44420
Only local connections are allowed.

75 version Chrome driver is picked by default web driver manager setup when 
![image](https://user-images.githubusercontent.com/50614383/57679895-63506e00-75fa-11e9-8cbc-989e55244ab3.png)

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using?

**Comment by PradeepAutomate** [comment]
> Which version of WebDriverManager are you using?

3.3.0

**Comment by bonigarcia** [comment]
You should better use latest version, at this moment is 3.4.0. Moreover, you should post the WebDriverManager traces, at least at DEBUG level to check what is going on in your test.

**Comment by bonigarcia** [comment]
This should be fixed in version 3.6.0, recently released.
