### ISSUE TITLE
Error when used in AWS Lambda

### ISSUE THREAD

**Issue by meenakshi2501** [bonigarcia/webdrivermanager#345]
![image](https://user-images.githubusercontent.com/38277253/58782665-cf703180-85fc-11e9-9eb8-b2124b1b45a1.png)

getting exception in AWS lambda.

**Comment by bonigarcia** [comment]
https://stackoverflow.com/questions/56422178/parameter-directory-is-not-a-directory-home-sbx-user1051-m2-repository-webd
