### ISSUE TITLE
Problem with SLF4J on use webdrivermanager and rest-assured

### ISSUE THREAD

**Issue by crfnunes** [bonigarcia/webdrivermanager#352]
**Description of the problem**: 
Hi, first thank you for webdrivermanager. 
I get a problem when use webdrivermanager and rest-assured, when I try execute rest tests the IDE show error with SLF4J version.

**Browser and version**: 
Chrome (but problem ocurr when rest-assured tests is executed)

**Operating system**: 
Windows 10 64 bits

**WebDriverManager version**: 
3.6.1

**WebDriverManager use**: 
..

**WebDriverManager traces**: 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/psrobche/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/psrobche/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: slf4j-api 1.6.x (or later) is incompatible with this binding.
SLF4J: Your binding is version 1.5.5 or earlier.
SLF4J: Upgrade your binding to version 1.6.x.

**Error trace**: 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/psrobche/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/psrobche/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: slf4j-api 1.6.x (or later) is incompatible with this binding.
SLF4J: Your binding is version 1.5.5 or earlier.
SLF4J: Upgrade your binding to version 1.6.x.

**Comment by bonigarcia** [comment]
This is not a WebDriverManager issue. It is related to the logging configuration in your project. As the warning in your traces says, visit https://www.slf4j.org/codes.html#multiple_bindings for further info.
