### ISSUE TITLE
WebDriverManager Jar files is not visible in src/main/java folder

### ISSUE THREAD

**Issue by boyhub** [bonigarcia/webdrivermanager#354]
**Description:**
WebDriverManager Jar files is not visible in src/main/java folder in Maven Project.
But it is visible in src/test/java folder.

**Description of the problem**: 
Expected: WebDriverManager.chromedriver().setup();
Actual: While typing webdri and autolist view, it shows WebDriver, WebDriverWait, etc.. except WebDriverManger.

**Browser and version**: Latest Chrome - 75.0.3

**Operating system**: Windows 7 - 64 bit

**WebDriverManager version**: 3.6.1
**WebDriverManager use**: 
	static public void openBrowser(String b) { // Open browser method
		if (b.equals("Chrome")) {
			**WebDriverManager**.chromedriver().setup();
			driver = new ChromeDriver();
              } 
	}
![error](https://user-images.githubusercontent.com/38520868/60705275-5417dd80-9f24-11e9-98de-97c25b064990.png)

**Comment by boyhub** [comment]
![image](https://user-images.githubusercontent.com/38520868/60705228-321e5b00-9f24-11e9-9e83-12a26dcfb64b.png)

**Comment by bonigarcia** [comment]
If you want to WebDriverManager is visible in the main folder, remove the `<scope>test</scope>` from the dependency declaration.
