### ISSUE TITLE
Selenium Marionette driver UnreachableBrowserException upon second launch in linux mint

### ISSUE THREAD

**Issue by pupie** [bonigarcia/webdrivermanager#36]
I get same issue and found some info from web.
Please refer:
http://stackoverflow.com/questions/34510794/selenium-marionette-driver-unreachablebrowserexception-upon-second-launch/35852698

I was using selenium 2.53 + firefox driver + testng and everything is ok. Since firefox is upgraded to version 47. I tried to switch to Marionette.

I compiled same test code to jar and run under different OS. I also encountered this issue in linux, Selenium Marionette driver UnreachableBrowserException upon second launch in linux mint.
But no such issue in Windows7 x64.

meanwhile, I also noticed a error when using driver.quit() in windows after running some test

    @AfterClass
    public void quit() {
        driver.quit();
    }
1465889422630	Marionette	TRACE	conn0 -> [0,57,"quitApplication",{"flags":["eForceQuit"]}]
1465889422631	Marionette	TRACE	conn0 <- [1,57,null,{}]
[NPAPI 6324] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2027

org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.

**Comment by bonigarcia** [comment]
I think this is a issue related with Marionette, not with WebDriverManager.
