### ISSUE TITLE
The import io can not be resolved

### ISSUE THREAD

**Issue by ledaivuong** [bonigarcia/webdrivermanager#360]
I meet this issue when I try to use webdrivermanager by injecting dependency into Maven
```
<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.6.2</version>
			<scope>test</scope>
</dependency>
```
Even thought I try to re-install, clean, update Maven

**Comment by pkoleva** [comment]
We're facing the same issue. It seems like the package in the maven repository is broken. The WebDriverManager.class looks strange 
![image](https://user-images.githubusercontent.com/7813201/61795898-14f6f100-ae2d-11e9-890f-4f2d2a5474e0.png)

**Comment by bonigarcia** [comment]
This is quite strange, it seems there is a problem in the artifact downloaded from Maven. Is the problem still happening?

**Comment by NalinRai** [comment]
We are still facing this issue, It still says "The import io cannot be resolved".

**Comment by shanvit** [comment]
Hi, I am facing this issue. Could anyone please help

The import io cannot be resolved
WebDriverManager cannot be resolved

Thanks,
Priya.

**Comment by Rush910** [comment]
I'm also having this issue.my dependency is as below
```
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>4.3.1</version>
		</dependency>
```
but i can't import to the test class. it shows as " WebDriverManager cannot be resolved"and there is no quick fixes also

**Comment by vikram375** [comment]
Hi @bonigarcia  Can you please check this, we are not able to get a workaround for this.

**Comment by LUAYS888** [comment]
> Hi @bonigarcia Can you please check this, we are not able to get a workaround for this.
> 
> Update: Saved the code, clean and it worked.

Sorry, Can you help me? What did you do to fix it?

**Comment by Marzoukatasnim** [comment]
At first save the code using Ctrl+S, then clean the code from Project-->Clean

**Comment by saloni070599** [comment]
I am facing the same issue
