### ISSUE TITLE
Issue in using Webdriver Manager in Appium Chrome driver

### ISSUE THREAD

**Issue by aruvimal** [bonigarcia/webdrivermanager#361]
**Description of the problem**

i am trying execution chrome driver in Android Emulator. i was using desired Capabilities for Chrome driver in Appium but it is not launching the chrome driver. Please advise on this. 

Script:

		@Test
		public void manin1 () throws InterruptedException, IOException
		{	
			
			String mydevice = "Pixel_3_XL_API_28";
			
			WebDriverManager.chromedriver().proxy(Constants.MACPROXY).setup();
					
			oCaps = new DesiredCapabilities();
			oCaps.setCapability("noReset", "false");
			oCaps.setCapability("browserName", "Chrome");
			oCaps.setCapability("deviceName", mydevice);
			oCaps.setCapability("platformName", "Android");
			oCaps.setCapability("automationName", "UiAutomator2");
	oCaps.setCapability("chromedriverExecutable",WebDriverManager.chromedriver().getBinaryPath());
	
			URL url = new URL("http://127.0.0.1:4723/wd/hub");
			setupEmulator(mydevice);
			
			driver = new AndroidDriver<MobileElement> (url,oCaps);
			driver.manage().timeouts().implicitlyWait(Constants.WAIT, TimeUnit.SECONDS);
			
			driver.get("http://www.ally.com");
	                 driver.close();		
		}

**Appuim Errorn Log**

	[WD Proxy] Proxying [POST /session] to [POST http://localhost:8200/wd/hub/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","chromedriverExecutable":"/Users/vz8zw5/.m2/repository/webdriver/chromedriver/mac64/2.45/chromedriver","deviceName":"Pixel_3_XL_API_28","noReset":false},"browserName":"Chrome","platformName":"android","automationName":"UiAutomator2","chromedriverExecutable":"/Users/vz8zw5/.m2/repository/webdriver/chromedriver/mac64/2.45/chromedriver","deviceName":"emulator-5554","noReset":false,"appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","deviceUDID":"emulator-5554"}}
	[WD Proxy] Got response with status 200: {"sessionId":"678ca872-4348-44d5-b3a8-5cf23eece558","status":0,"value":"Created Session"}
	[WD Proxy] Proxying [GET /appium/device/info] to [GET http://localhost:8200/wd/hub/session/678ca872-4348-44d5-b3a8-5cf23eece558/appium/device/info] with no body
	[WD Proxy] Got response with status 200: "{\"sessionId\":\"678ca872-4348-44d5-b3a8-5cf23eece558\",\"status\":0,\"value\":{\"androidId\":\"091a86b330d9bc8b\",\"manufacturer\":\"Google\",\"model\":\"Android SDK built for x86\",\"brand\":\"google\",\"apiVersion\":\"28\",\"platformVersion\":\"9\",\"carrierName\":\"Android\",\"realDisplaySize\":\"1440x2960\",\"displayDensity\":560,\"networks\":[{\"type\":0,\"typeName\":\"MOBILE\",\"subtype\":13,\"subtypeName\":\"LTE\",\"isConnected\":true,\"detailedState\":\"CONNECTED\",\"state\":\"CONNECTED\",\"extraInfo\":\"epc.tmobile.com\",\"isAvailable\":true,\"isFailover\":false,\"isRoaming\":false,\"capabilities\":{\"transportTypes\":\"NET_CAPABILITY_MMS\",\"networkCapabilities\":\"\",\"linkUpstreamBandwidthKbps\":51200,\"linkDownBandwidthKbps\":102400,\"signalStrength\":-2147483648,\"networkSpecifier\":\"1\",\"SSID\":null}},{\"type\":1,\"typeName\":\"WIFI\",\"subtype\":0,\"subtypeName\":\"\",\"isConnected\":true,\"detailedState\":\"CONNECTED\",\"state\":\"CONNECTED\",\"extraInfo\":null,\"isAvailable\":true,\"i...
	[ADB] Running '/Users/vz8zw5/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
	[AndroidDriver] Screen already unlocked, doing nothing
	[AndroidDriver] Starting a chrome-based browser session
	[AndroidDriver] A port was not given, using random free port: 8001
	[AndroidDriver] Before starting chromedriver, androidPackage is 'com.android.chrome'
	[Chromedriver] Changed state to 'starting'
	[Chromedriver] Set chromedriver binary as: /Users/vz8zw5/.m2/repository/webdriver/chromedriver/mac64/2.45/chromedriver
	[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Users/vz8zw5/.m2/repository/webdriver/chromedriver/mac64/2.45/chromedriver.*--port=8001"
	[Chromedriver] No old chromedrivers seem to exist
	[Chromedriver] Cleaning any old adb forwarded port socket connections
	[ADB] List forwarding ports
	[ADB] Running '/Users/vz8zw5/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --list'
	[Chromedriver] Spawning chromedriver with: /Users/vz8zw5/.m2/repository/webdriver/chromedriver/mac64/2.45/chromedriver --url-base=wd/hub --port=8001 --adb-port=5037 --verbose
	[Chromedriver] Chromedriver version: '2.45.615355'
	[WD Proxy] Matched '/status' to command name 'getStatus'
	[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8001/wd/hub/status] with no body
	[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8001}
	[WD Proxy] Matched '/status' to command name 'getStatus'
	[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8001/wd/hub/status] with no body
	[WD Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189)\"},\"message\":\"ChromeDriver ready for new sessions.\",\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.14.5\"},\"ready\":true}}"
	[WD Proxy] Determined that the downstream protocol for proxy is MJSONWP
	[WD Proxy] Matched '/session' to command name 'createSession'
	[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"},"loggingPrefs":{"browser":"ALL"}}}
	[Chromedriver] Webview version: 'Chrome/69.0.3497.100'
	[WD Proxy] Got response with status 200: {"sessionId":"cb1e983c1a723f5e8bdb1d2336492758","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[WD Proxy] Got an unexpected response: {"sessionId":"cb1e983c1a723f5e8bdb1d2336492758","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[MJSONWP] Matched JSONWP error code 33 to SessionNotCreatedError
	[Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
	[Chromedriver]   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)
	[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
	[Chromedriver]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:499:13)
	[WD Proxy] Matched '/session' to command name 'createSession'
	[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"},"loggingPrefs":{"browser":"ALL"}}}
	[Chromedriver] Webview version: 'Chrome/69.0.3497.100'
	[WD Proxy] Got response with status 200: {"sessionId":"eb1795ee8ab3316671d88aad2450911d","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[WD Proxy] Got an unexpected response: {"sessionId":"eb1795ee8ab3316671d88aad2450911d","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[MJSONWP] Matched JSONWP error code 33 to SessionNotCreatedError
	[Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
	[Chromedriver]   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)
	[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
	[Chromedriver]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:499:13)
	[WD Proxy] Matched '/session' to command name 'createSession'
	[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"},"loggingPrefs":{"browser":"ALL"}}}
	[Chromedriver] Webview version: 'Chrome/69.0.3497.100'
	[WD Proxy] Got response with status 200: {"sessionId":"e13266b5997c69dcef417bec62bf7037","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[WD Proxy] Got an unexpected response: {"sessionId":"e13266b5997c69dcef417bec62bf7037","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[MJSONWP] Matched JSONWP error code 33 to SessionNotCreatedError
	[Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
	[Chromedriver]   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)
	[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
	[Chromedriver]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:499:13)
	[WD Proxy] Matched '/session' to command name 'createSession'
	[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"},"loggingPrefs":{"browser":"ALL"}}}
	[Chromedriver] Webview version: 'Chrome/69.0.3497.100'
	[WD Proxy] Got response with status 200: {"sessionId":"30a32a02c6b191780e31894b7473f278","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[WD Proxy] Got an unexpected response: {"sessionId":"30a32a02c6b191780e31894b7473f278","status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)"}}
	[MJSONWP] Matched JSONWP error code 33 to SessionNotCreatedError
	[Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
	[Chromedriver]   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)
	[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
	[Chromedriver]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:499:13)
	[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
	[Chromedriver] Changed state to 'stopped'
	[Chromedriver] Error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
	[Chromedriver] Chrome version on the device: Chrome/69.0.3497.100
	[Chromedriver] Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
	[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
	[Chromedriver]   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)
	[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
	[Chromedriver]     at Chromedriver.errorAndThrow [as start] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:447:11)
	[UiAutomator2] Deleting UiAutomator2 session
	[UiAutomator2] Deleting UiAutomator2 server session
	[WD Proxy] Matched '/' to command name 'deleteSession'
	[WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/678ca872-4348-44d5-b3a8-5cf23eece558] with no body
	[WD Proxy] Got response with status 200: "{\"sessionId\":\"678ca872-4348-44d5-b3a8-5cf23eece558\",\"status\":0,\"value\":\"Session deleted\"}"
	[Logcat] Stopping logcat capture
	[ADB] Removing forwarded port socket connection: 8200 
	[ADB] Running '/Users/vz8zw5/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
	[UiAutomator2] Restoring hidden api policy to the device default configuration
	[ADB] Running '/Users/vz8zw5/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
	[Instrumentation] .
	[ADB] Running '/Users/vz8zw5/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
	[ADB] Running '/Users/vz8zw5/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
	[BaseDriver] Event 'newSessionStarted' logged at 1563937679064 (23:07:59 GMT-0400 (EDT))
	[W3C] Encountered internal error running command: Error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
	[W3C] Chrome version on the device: Chrome/69.0.3497.100
	[W3C] Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
	[W3C] Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
	[W3C]   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.5 x86_64)
	[W3C]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
	[W3C]     at Chromedriver.errorAndThrow [as start] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:447:11)

**Comment by bonigarcia** [comment]
According to the traces, your Chrome version is 69.0.3497.100. Therefore, the proper chromedriver should be 2.44. You can force it using the `.version()` method of WebDriverManager.
