### ISSUE TITLE
How to get the version of chrome drive 

### ISSUE THREAD

**Issue by aruvimal** [bonigarcia/webdrivermanager#362]
i want to run the script in Android emulator's chrome browser. Since various emulator has different version of chrome driver.  So i want to get the version of chrome and have to download the driver binary by passing the version. Kindly advise me how to achieve this.

**Comment by PJSOConnell** [comment]
I implemented this exact functionality using Python - https://github.com/bonigarcia/webdrivermanager/issues/372
