### ISSUE TITLE
Webdriver manager is not picking right version

### ISSUE THREAD

**Issue by sukhjinder-sdei** [bonigarcia/webdrivermanager#364]
I have chrome installed on my windows system version 75.0.3770.142.
I am using latest Webdriver manager version 3.6.2

By default, Webdriver manager is pointing to 76.0.3809.68  version and  this is working.
So I have explicitly, copy binary(75.0.3770.140) into folder 76.0.3809.68 in order to work it.

Please fix it if Webdriver manager pick the right version for installed chrome.

Logs 
----------------
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 76.0.3809.68 (since Google Chrome 75 is installed in your machine)

**Comment by sukhjinder-sdei** [comment]
Operating system: Windows 10 and architecture (64 bits)
WebDriverManager version: 3.6.2
Chrome version: 75.0.3770.142

**Comment by ckempster** [comment]
![image](https://user-images.githubusercontent.com/36272475/63863745-a0bce980-c9a6-11e9-88ed-581403ea32b1.png)
Having the same issue

**Comment by bonigarcia** [comment]
I'm not sure if this is a bug. This trace has no sense:

```
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 76.0.3809.68 (since Google Chrome 75 is installed in your machine)
```

Is still happening? How can I reproduce it?

**Comment by ckempster** [comment]
Im still seeing the issue - 
![image](https://user-images.githubusercontent.com/36272475/63947830-91ee3980-ca6f-11e9-8c8e-10c5baf74791.png)

I have the artifactc in my POM - As 

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.6.2</version>
</dependency>

Do you need to release a new version?

**Comment by bonigarcia** [comment]
@ckempster According to your first message, you are using Chrome 76.x, and then, the selected version for chromedriver is also 76.x. This should work, isn't it?

What worries me most is the case reported originally (i.e. Chrome 75, and selected version of chromedriver 76). Is this problem still happening @sukhjinder-sdei?

**Comment by sukhjinder-sdei** [comment]
@ckempster  Yes you are WDM was selecting the wrong version Installed version was old but downloaded version was new.

But now after new chrome Version, 76.0.3809.132 WDM is pointing to 76.0.3809.12 that is working fine now without changing any line in code.  

If I find anything odd, I will post again.

Thanks!
