### ISSUE TITLE
WebDriverManager-versioned 3.6.1 (Gecko driver versioned 0.24.0) Problem - Firefox versioned 68.0.1 64 bit , Windows 10 , Selenium version 3.141.59 

### ISSUE THREAD

**Issue by arsekisser** [bonigarcia/webdrivermanager#365]
**Description of the problem**:

Hi,
I am Using WebDriverManager-versioned 3.6.1 (Gecko driver versioned 0.24.0) Problem - Firefox versioned 68.0.1 64 bit , Windows 10 , Selenium version 3.141.59

I have a maven -selenium project with 10+ test classes in testNG.

When i execute these classes on Chrome browsers(WebDriverManager-chrome driver) ,each test class gets executed successfully .
Same test classes when i execute on Firefox using the (WebDriverManager-Gecko driver) the test classes execute for some time say 5-10 seconds and then abruptly closes and opens next test class for execution ,even this test class execute for some time and then closes .
Same thing happens with each test class.

Suggest some work around for executing the test classes on Firefox browser successfully .

### **System**

- Version: geckodriver version 0.24.0
- Platform: Windows Version 10.0.10240 Build 10240
- Firefox: 68.0.1
- Selenium: 3.141.59 version

### **Error trace**: 
[Just log.docx](https://github.com/bonigarcia/webdrivermanager/files/3434401/Just.log.docx)

**Comment by pierrepinon** [comment]
Hello @arsekisser, i see your log file. WebDriverManager work fine, you can create issue in seleniumhq tracker

**Comment by bonigarcia** [comment]
Indeed WebDriverManager seems to work properly fine here:

```
10:46:45.213 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as C:\Users\srawat\.m2\repository\webdriver\geckodriver\win32\0.24.0\geckodriver.exe
```
