### ISSUE TITLE
Chrome browser auto-detect always return latest

### ISSUE THREAD

**Issue by hendryang** [bonigarcia/webdrivermanager#368]
**Description of the problem**: 
as per google-chrome --version , my chrome inside a docker (headless) is running on version 72.0.3626.109 , but wdm setup() keep on downloading latest chrome version 76.0.3809.68
Is this a bug or did i miss out any configuration to ensure auto-detect browser is done correctly? 

**Browser and version**: 
Chrome 72.0.3626.109

**Other**:
java 8 , Selenium 3.10

**Operating system**: 
Ubuntu 16.04

**WebDriverManager version**: 
3.6.2

**WebDriverManager use**:
WebDriverManager.chromedriver().setup();
logging("downloaded chromedriver : " + WebDriverManager.chromedriver().getDownloadedVersion());

**WebDriverManager traces**: 
Logs added. For some machine, it able to detect correctly. I've also verified that the location of chromedriver.exe is same across all machine.

**Error trace**: 
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 77.0.3865.10
[main] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\tsting\.m2\repository\webdriver\chromedriver\win32\77.0.3865.10\chromedriver.exe
[TAF] downloaded chromedriver : 77.0.3865.10
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 42594
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

**Comment by DazedNConfused-** [comment]
I also experience this issue (and also with a Chrome inside a Docker container).

**Comment by hendryang** [comment]
Log traces are added.
