### ISSUE TITLE
fat-jar from the CLI sets wdm.avoidAutoVersion to true

### ISSUE THREAD

**Issue by mikebro** [bonigarcia/webdrivermanager#369]
**Description of the problem**: 
When using the _fat-jar_ from the CLI `wdm.avoidAutoVersion` and a couple other default settings are changed.

https://github.com/bonigarcia/webdrivermanager/blob/42d99067e7a04e3a24f2a25f953f9fdf4ae45417/src/main/java/io/github/bonigarcia/wdm/WebDriverManager.java#L1260-L1262

I believe `java -Dwdm.avoidAutoVersion="false" -jar webdrivermanager-3.6.2-fat.jar chrome` is giving me the behavior I expected. The documentation led me to believe that this would be the behavior by default, if this is intentional it would be nice to have it documented since this is 1 of the very appealing features of WebDriverManager.

https://github.com/bonigarcia/webdrivermanager/blame/e6bc5902abae34361afb5db698796e9e62b82c85/README.md#L238
https://github.com/bonigarcia/webdrivermanager/blame/e6bc5902abae34361afb5db698796e9e62b82c85/README.md#L111-L112

**Browser and version**: 
Chrome 76

**Operating system**: 
Windows 10

**WebDriverManager version**: 
3.6.2

**WebDriverManager use**: 
`java -jar webdrivermanager-3.6.2-fat.jar chrome`

**Comment by bonigarcia** [comment]
I have removed this default behavior. It will be available for next version (I plan to release it ASAP).
