### ISSUE TITLE
Snippet to get currently installed version of Chrome

### ISSUE THREAD

**Issue by PJSOConnell** [bonigarcia/webdrivermanager#372]
Hi there,

For the project I am working on, as we use random sandboxes and automated testing, I can neither - hardcode the Chrome Version, or use .install() to use the most recent version, as the most recent ChromeDriver will only support its own version, and all my browser instances have different versions. It used to be the case that it would be backwards compatible with the prior 3 versions.

Here is a solution I came up with to grab your current Chrome version, compare it with the list of ChromeDrivers found at - "http://chromedriver.storage.googleapis.com" - (Change the attached file from .txt to .py to execute)

[chromeDriverManagerExtended.txt](https://github.com/bonigarcia/webdrivermanager/files/3492563/chromeDriverManagerExtended.txt)

#Walkthrough#
install_necessary_packages = accepts an array of package names to install them if they havent been installed already.

get_version_via_com = Gets working Chrome version and returns it to return_chrome_version

return_chrome_version = Uses above function to return version of Chrome. (This returns the whole number version of chrome, the variable 'fullVersion' holds the complete version.)

return_valid_version = Compares your version to ChromeDriver versions and grabs most appropriate ChromeDriver.
#End#

Thank you so much to @bonigarcia for an excellent tool, just thought I would share my particular application of it!

PJ

**Comment by bonigarcia** [comment]
Thanks for sharing @PJSOConnell!
