### ISSUE TITLE
Issue while using ChromeOptions and DesiredCapabilities

### ISSUE THREAD

**Issue by venkywarriors619** [bonigarcia/webdrivermanager#378]
**Description of the problem**: Windows download prompt is not appearing after adding preferences.put("download.prompt_for_download", true); ChromeOptions with WebDriverManger, i tried same  ChromeOptions with ChromeDriver with System.setProperty which is working fine

**Browser and version**: Chrome version  76.0.3809.68

**Operating system**: Windows 10, 64 bits architecture 

**WebDriverManager version**:3.6.2 

**WebDriverManager use**: 3.6.2

**WebDriverManager traces**:  WebDriverManager.chromedriver().setup();
			    Map<String, Object> preferences = new Hashtable<String, Object>();
			   preferences.put("profile.default_content_settings.popups", 3);
			   preferences.put("download.prompt_for_download", true);
			   ChromeOptions options = new ChromeOptions();
			   options.setExperimentalOption("prefs", preferences);
			   DesiredCapabilities capabilities = DesiredCapabilities.chrome();
			   capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
			   capabilities.setCapability(ChromeOptions.CAPABILITY, options);
			   driver=new ChromeDriver(capabilities); 

**Error trace**:

**Comment by bonigarcia** [comment]
Sorry, this is not related with WebDriverManager.
