### ISSUE TITLE
Exception while try to download Phantomjs

### ISSUE THREAD

**Issue by jesanchezgo** [bonigarcia/webdrivermanager#38]
I have added the following dependency into my pom.xml:

```
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>1.4.5</version>
</dependency>
```

But when I launch my tests and execute the following line: 

`PhantomJsDriverManager.getInstance().setup("2.1.1");`

I get the exception below:

```
   [31mjava.lang.RuntimeException: org.openqa.selenium.NoSuchElementException: Unable to locate element with ID: available-downloads
      For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
      Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
      System info: host: 'ALC-1DT2L12', ip: '7.110.43.105', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_51'
      Driver info: driver.version: BrowserDriver
      	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:272)
      	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:103)
      	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:86)
```

Thanks in advance

**Comment by bonigarcia** [comment]
Could you please provide the full trace error? (I am interested in the Caused by clause)

**Comment by bonigarcia** [comment]
In addition it would be interesting you set your logger configuration to DEBUG for WebDriverManager and share the log information here.

I am not sure what is happening, but I made some quick test I am not able to reproduce this error. In other words, it seems that WebDriverManager is still working for PhantomJS.

**Comment by toschder** [comment]
I have the same problem - caused by the corparate network proxy that blocks Internet URLs.
=> Solution would be to be able to set a proxy - so WebDriverManager can download the binaries properly using HtmlUnitDriver:

```
public List<URL> getDrivers() throws Exception {
...
        // Using HtmlUnitDriver to read package URL
        HtmlUnitDriver driver = new HtmlUnitDriver();
        if( autoProxyUrl != null )
        {
          driver.setAutoProxy(autoProxyUrl);
        }
...

```
I worked around that by subclassing PhantomJSDriverManager and overriding this method - and public void setup(Architecture arch, String version), too, where the instance is being cloned.
