### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; 

### ISSUE THREAD

**Issue by Abishek-godsu** [bonigarcia/webdrivermanager#382]
HI ,
I am getting the below error:
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

Please find my code:
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class demo {

public static void main(String[] args) {
	// TODO Auto-generated method stub
WebDriver driver = new ChromeDriver();
System.setProperty("WebDriver.chrome.driver", "C:\Users\Abishek R\Downloads.exe");
driver.get("www.google.com");
System.out.println(driver.getTitle());
}
}

Please help

@Abishek-godsu

**Comment by bonigarcia** [comment]
Call WebDriverManager before creating the `ChromeDriver` instance:

```
WebDriverManager.chromedriver().setup();
WebDriver driver = new ChromeDriver();
```

**Comment by Abishek-godsu** [comment]
Hi,
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method chromedriver() is undefined for the type WebDriverManager
	at demo.main(demo.java:8)

As you have told I called WebDriverManager 

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class demo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		WebDriverManager.chromedriver().setup();
WebDriver driver = new ChromeDriver();
System.setProperty("WebDriver.chrome.driver", "C:\\Users\\Abishek R\\Downloads.exe");
driver.get("www.google.com");
System.out.println(driver.getTitle());
	}
}

Please help with the exact code
