### ISSUE TITLE
Exception in thread "main" java.lang.Error: Unresolved compilation problem:  	WebDriverManager cannot be resolved

### ISSUE THREAD

**Issue by Abishek-godsu** [bonigarcia/webdrivermanager#384]
Hi,
Exception in thread "main" java.lang.Error: Unresolved compilation problem:
The method chromedriver() is undefined for the type WebDriverManager
at demo.main(demo.java:8)

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class demo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		WebDriverManager.chromedriver().setup();
WebDriver driver = new ChromeDriver();
System.setProperty("WebDriver.chrome.driver", "C:\\Users\\Abishek R\\Downloads.exe");
driver.get("www.google.com");
System.out.println(driver.getTitle());
	}
}

Please help with the exact code

**Comment by bonigarcia** [comment]
Include WebDriverManager dependency in your project.
