### ISSUE TITLE
Why Appium tries to find chrome driver in node_modules ?

### ISSUE THREAD

**Issue by Naumansh** [bonigarcia/webdrivermanager#385]
**Question**

Hi,

I am running appium based test execution on chrome. Appium always tries to search for chrome driver in node_modules instead of fetching it from the .m2 webdriver folder. I am using the below desired capability for chrome driver:
,
androidCapabilities.setCapability("chromedriverExecutable", WebDriverManager.chromedriver().getBinaryPath());
'
Browser version : chrome 77
Version is fine as far as the chrome driver binaries are concerned.

**Error**
UnknownError: An unknown server-side error occurred while processing the command. Original error: No Chromedrivers found in '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'

**Comment by bonigarcia** [comment]
No clue. It seems an issue related to Appium, not WebDriverManager.
