### ISSUE TITLE
.version doesn't work on mutli-thread runs

### ISSUE THREAD

**Issue by jamesxu81** [bonigarcia/webdrivermanager#389]
**Description of the problem**: 

due to the headless chrom not working properly on the latest driver 77, we had to force use version 2.44 with command below, it works fine with single thread run
WebDriverManager.chromedriver().version("2.44").setup();

but when set test ng file "thread-count" = 5 then webdrivermanager will try to mach the current chrome version and download it in some instances randoml.

error	26-Sep-2019 04:19:56	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
error	26-Sep-2019 04:19:56	SLF4J: Defaulting to no-operation (NOP) logger implementation
error	26-Sep-2019 04:19:56	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
error	26-Sep-2019 04:19:57	Starting ChromeDriver 2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926) on port 14727
error	26-Sep-2019 04:19:57	Only local connections are allowed.
error	26-Sep-2019 04:19:57	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
build	26-Sep-2019 04:19:58	INITIATING Chrome Headless for qa
build	26-Sep-2019 04:19:58	setting up driver
error	26-Sep-2019 04:19:58	Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 18383
error	26-Sep-2019 04:19:58	Only local connections are allowed.
error	26-Sep-2019 04:19:58	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
error	26-Sep-2019 04:19:58	Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 24918
error	26-Sep-2019 04:19:58	Only local connections are allowed.
error	26-Sep-2019 04:19:58	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
error	26-Sep-2019 04:19:58	Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 30641
error	26-Sep-2019 04:19:58	Only local connections are allowed.
error	26-Sep-2019 04:19:58	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
error	26-Sep-2019 04:19:58	Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 18759
error	26-Sep-2019 04:19:58	Only local connections are allowed.
error	26-Sep-2019 04:19:58	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
error	26-Sep-2019 04:19:58	Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 22423
error	26-Sep-2019 04:19:58	Only local connections are allowed.
error	26-Sep-2019 04:19:58	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

**Browser and version**: 
Chrome 77
**Operating system**: 
Mac & Linux (Bamboo)
**WebDriverManager version**: 
3.7.1
**WebDriverManager use**: 
 WebDriverManager.chromedriver().version("2.44").setup();
**WebDriverManager traces**: 

**Error trace**:

**Comment by bonigarcia** [comment]
This is a side-effect of the global configuration instance of WebDriverManager. A rapid way to avoid it would be as follows:

```
WebDriverManager.globalConfig().setAvoidAutoReset(true);
WebDriverManager.chromedriver().version("2.44").setup();
```
