### ISSUE TITLE
SimpleLogger doesn´t support DEBUG

### ISSUE THREAD

**Issue by toschder** [bonigarcia/webdrivermanager#39]
per default, the application is shipped with a simplelogger.properties file, so adding
```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.4</version>
        </dependency>

```
will output some INFO.
The bad thing about SimpleLogger is, that it doesn´t support "DEBUG" Leven, its implemented with NOP.

Of course, anyone is free to choose whatever impl. right now,but:

=> maybe it´s a better idea to ship with another logging setup, that supports DEBUG level out of the box.

**Comment by bonigarcia** [comment]
In fact SimpleLogger indeed supports other log levels than `INFO` (i.e. `DEBUG`, `TRACE`, and so on). You just need to configure it properly. For example, with a properties file like [this one](https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/simplelogger.properties). Then you just need to define the log level as follows:

`org.slf4j.simpleLogger.defaultLogLevel=DEBUG`
