### ISSUE TITLE
WDM uses ChromeDriver 77 while Chrome 78 is installed locally

### ISSUE THREAD

**Issue by ZheSun88** [bonigarcia/webdrivermanager#396]
**Description of the problem**: 
I have Chrome 78 installed on my PC, but when i run the WDM, it starts to use ChromeDriver 77.
```
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 77.0.3865.40 (since Google Chrome 77 is installed in your machine)
```
later, you can see a warning about the version mismatch
```
[1572506117.075][WARNING]: This version of ChromeDriver has not been tested with Chrome version 78.
```
**Browser and version**: 
Chrome 78

**Operating system**: 
Windows 10

**WebDriverManager version**: 
3.7.1

**Comment by bonigarcia** [comment]
Is this issue still happening to you? If so, please post your WebDriverManager traces also at DEBUG level.

**Comment by ZheSun88** [comment]
I looks this is not a problem any more. 
let us close it.
