### ISSUE TITLE
Driver version property specified from commandLine don't download chromedriver of that version

### ISSUE THREAD

**Issue by mangeshrane** [bonigarcia/webdrivermanager#398]
System: Windows 10,
Chrome Version : 78 
Passing commandline parameter while building project -Dwdm.chromeDriverVersion dont download chromedriver for specified version it always downloading the latest chromedriver

**Comment by bonigarcia** [comment]
Please reopen the issue following the issue template, since relevant information to trace the possible problem is missing (e.g. WebDriverManager version, traces, and so on).
