### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by TheFifthFreedom** [bonigarcia/webdrivermanager#4]
It seems that the SLF4J Maven child dependency (1.7.5) included with WebDriverManager 1.2.0 is not sufficient to prevent this error when running a Selenium test:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
A temporary workaround was to include the latest `slf4j-simple` to my Maven project:
```
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-simple</artifactId>
	<version>1.7.12</version>
</dependency>
```

**Comment by bonigarcia** [comment]
Could you please provide more details about this issue? I would like to be able to reproduce the problem in order to find a solution. Thanks.

**Comment by TheFifthFreedom** [comment]
Of course! Here's the code I used:
```java
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.ChromeDriverManager;

public class Tester {

	public static void main(String[] args) {
		ChromeDriverManager.getInstance().setup();
		WebDriver driver = new ChromeDriver();
		driver.get("http://www.google.com/");
		WebElement searchBox = driver.findElement(By.name("q"));
		searchBox.sendKeys("ChromeDriver" + Keys.ENTER);
		driver.close();
	}
}
```
The only other Maven dependency that this snippet requires is `selenium-chrome-driver` (I'm using 2.47.1). I ran this on Java SE 8 with `webdrivermanager` 1.2.0, and while the code runs fine, here's what the log says:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 2.17.340128 (994135a3538dd99439ef22cea8a9b098e00d8eb4) on port 22214
Only local connections are allowed.
```
Now according to the website that the log points to:
"This error is reported when the org.slf4j.impl.StaticLoggerBinder class could not be loaded into memory.
This happens when no appropriate SLF4J binding could be found on the class path. Placing one (and only one) of slf4j-nop.jar, slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem."

And indeed, if I add `slf4j-simple` (1.7.12) to the Maven dependencies, which comes with `slf4j-api` 1.7.12, thus overriding webdrivermanager's 1.7.5 child version, the error message does not pop up.

**Comment by bonigarcia** [comment]
Indeed, webdrivermanager uses SLF4J as logging facade. This is the usual way that Java libraries use logging, in order to avoid forcing an specific implementation of logging. This way, the application using the library is free to use one implementation or other (e.g. `slf4j-simple`, `slf4j-jdk14`, `logback-classic`).

As you pointed, this can be solved easily simply adding and SL4JF implementation in your project, which is IMHO the best solution.

More information about this at:

http://stackoverflow.com/questions/9740569/logger-for-java-library
http://saltnlight5.blogspot.com.es/2013/08/how-to-configure-slf4j-with-different.html

**Comment by marionh03** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by cvargasr31** [comment]
Im getting this error too, I have to use:
```
        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.30</version>
            <scope>test</scope>
        </dependency>
```
As a workaround.

Im using webdrivermanager version 4.3.1
