### ISSUE TITLE
chromium support

### ISSUE THREAD

**Issue by Relaximus** [bonigarcia/webdrivermanager#400]
Hi, 
I have a short question, are there any plans to add support of chromium driver. I saw some of the issues regarding it in history, but the recipe, as I understand, is to hardcode the need version of chrom driver while creating it.
thx.

**Comment by bonigarcia** [comment]
I have lost the context here. Could you please remind me of that recipe? Is this related to #403?

**Comment by Relaximus** [comment]
Not exactly, the beginning is the same. `chromium --version` returns some output, which is not parsed or parsed in wrong way by wdm and it just fallback to the latest version of the driver. The test don't start, claiming the version mismatch between driver and browser.

**Comment by bonigarcia** [comment]
WebDriverManager 3.8.0 provides support for Chromium (also for snap packages):

```
WebDriverManager.chromiumdriver().setup();
```
