### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76

### ISSUE THREAD

**Issue by sanjay058** [bonigarcia/webdrivermanager#409]
I trying to run my script on Grid, but getting error "**SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76**"
Selenium standalone server version -3.141.59
Chrome Browser version : 78.0.3904.97

Could you please help me how to solve below issue

------------------------------
Nov 21, 2019 4:58:39 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'system name', ip: 'ip', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
	Ordinal0 [0x00E17C53+1473619]
	Ordinal0 [0x00D9AD71+961905]
	Ordinal0 [0x00D242B3+475827]
	Ordinal0 [0x00CBF365+62309]
	Ordinal0 [0x00CBBC77+48247]
	Ordinal0 [0x00CD9149+168265]
	Ordinal0 [0x00CD8D1D+167197]
	Ordinal0 [0x00CD742B+160811]
	Ordinal0 [0x00CC0AE6+68326]
	Ordinal0 [0x00CC1BF0+72688]
	Ordinal0 [0x00CC1B89+72585]
	Ordinal0 [0x00DB4B37+1067831]
	GetHandleVerifier [0x00EB6845+506677]
	GetHandleVerifier [0x00EB65E0+506064]
	GetHandleVerifier [0x00EBD188+533624]
	GetHandleVerifier [0x00EB701A+508682]
	Ordinal0 [0x00DAC226+1032742]
	Ordinal0 [0x00DAC09F+1032351]
	Ordinal0 [0x00DB6A4B+1075787]
	Ordinal0 [0x00DB6BB3+1076147]
	Ordinal0 [0x00DB5B65+1071973]
	BaseThreadInitThunk [0x77096A14+36]
	RtlInitializeExceptionChain [0x77E2AD8F+143]
	RtlInitializeExceptionChain [0x77E2AD5A+90]
---------------------------------------------------
Code:
String nodeUrl= "nodeUlr";
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        WebDriver driver = new RemoteWebDriver(new URL(nodeUrl),capabilities);
        System.out.println("---End---");
        driver.get("https://www.google.in/")

**Comment by AlexisGuetat** [comment]
Hi ! I have same probleme =) 
What is the answer ?
