### ISSUE TITLE
webdriver exception

### ISSUE THREAD

**Issue by AgeshAalam** [bonigarcia/webdrivermanager#411]
![Capture1](https://user-images.githubusercontent.com/44727659/69847642-b7bcf180-129d-11ea-99e7-c4b5a8905648.PNG)
![Capture2](https://user-images.githubusercontent.com/44727659/69847644-b7bcf180-129d-11ea-8eef-333712927854.PNG)
![Capture3](https://user-images.githubusercontent.com/44727659/69847645-b7bcf180-129d-11ea-81f0-6e94d929de70.PNG)

**Comment by bonigarcia** [comment]
Maybe this can be solved using the latest version of Selenoid.

**Comment by AgeshAalam** [comment]
I am using latest version of selenide
