### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 77

### ISSUE THREAD

**Issue by rmedina6** [bonigarcia/webdrivermanager#416]
**Description of the problem**:
I am using webdrivermanager to manage chromedriver.exe. But it isn't finding my chrome.exe binary, so it defaults to the latest chromedriver.exe version. And at the moment this results in a version conflict.

**Browser and version**: Chrome 79.0.3945.79

**Operating system**: Windows 10 and macOs 10.15.2

**WebDriverManager version**:  3.7.1

**WebDriverManager use**: 
WebDriverManager.chromedriver().setup();

**WebDriverManager traces**: 

**Error trace**:

**Comment by bonigarcia** [comment]
It is not possible to find out what is going on here if you skip the WebDriverManager traces. If you want support, please include these traces at DEBUG level.
