### ISSUE TITLE
Chromium Edge Drivers Not Downloading

### ISSUE THREAD

**Issue by Carlbc18** [bonigarcia/webdrivermanager#417]
Are there plans to support automatic downloading of the chromium edge drivers?  Currently i'm forced to set the webdriver.edge.driver property to override the driver used. 
 
My code is as follows: 
```
WebDriverManager.edgedriver().setup();
// full path to the below driver
System.setProperty("webdriver.edge.driver", "msedgedriver.exe");
final ChromeOptions chromeOptions = new ChromeOptions();
                       // custom path to both Edge Beta or Edge Dev
			chromeOptions.setBinary(applicationPath);
			chromeOptions.setExperimentalOption("useAutomationExtension", false);
			chromeOptions.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));

final EdgeOptions edgeOptions = new EdgeOptions().merge(chromeOptions);

final WebDriver webDriver = new EdgeDriver(edgeOptions);
```

When `WebDriverManager.edgedriver().setup()` is called, it sets up based on the older edge even though i have both edge and chromium edge installed.  I see the versions.properties has support for the newer edge drivers, but i must be missing something with the setup.

Thanks.

**Comment by Carlbc18** [comment]
Update:  I was able to properly get things to work if i passed in a version. I am able to determine that version by lexicographically comparing all installed versions of the chromium edge browser based off the application path and instantiate with the appropriate driver. 

e.g.  
```
WebDriverManager.edgedriver().version("the version of chromium edge").setup();
```

**Comment by bonigarcia** [comment]
In fact, the latest version of WebDriverManager is already working for the development version of Edge. I need to check it for the beta version too.

@Carlbc18 In which folder is installed Edge in your system?

**Comment by Carlbc18** [comment]
Hi @bonigarcia,

The latest dev driver (80.xxx.xxx) throws ordinal errors for Edge Dev.  I think the reason that dev is failing is because the versions.properties has the wrong dev version defined for the driver.  Keep in mind on my Windows system edge is preinstalled and `WebDriverManager.edgedriver` spins up the preinstalled browser.

I was trying with Beta.  Beta is using driver version 79.xxx.xxx .   In any case, the path for the installs are: 

````
C:\Program Files (x86)\Microsoft\Edge Beta\...
C:\Program Files (x86)\Microsoft\Edge Dev\...
C:\Program Files (x86)\Microsoft\Edge <Canary Path>\...  
````

I'm looping over the version folders inside the application path and picking the largest and passing that in since some chromium versions are updating more frequently than others.

**Comment by bonigarcia** [comment]
Version 3.8.0 (recently released) of WebDriverManager has improved the support for Edge. I have checked with this [test](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/EdgeTest.java) in a Windows machine, and it works. But I need to include the Edge folder in the `PATH` environment variable, otherwise, I got the error `cannot find Microsoft Edge binary`.
