### ISSUE TITLE
protractor 2.5.4 E/launcher - session not created: This version of Chrome Driver only supports Chrome version 79

### ISSUE THREAD

**Issue by sangeethacg** [bonigarcia/webdrivermanager#418]
I have researched a lot and used many possible solutions mentioned in the various forums, none of them worked for me. I am trying to run this in CI/CD pipeline although able to run the protractor test cases in local and able to launch the browser but in CI/CD pipeline build it is failing below are the details the issue occurs for protractor 2.5.4 E/launcher - session not created: This version of ChromeDriver only supports Chrome version 79

i am using below postinstall under scripts in package.json

"postinstall": "npm uninstall -g webdriver-manager protractor && npm install -g webdriver-manager protractor && webdriver-manager update && cd ./node_modules/protractor && npm i webdriver-manager@latest",

"postinstall": "cd ./node_modules/protractor && npm i webdriver-manager@latest",

for the above script command below error is thrown I/file_manager - creating folder D:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium I/config_source - curl -oD:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/ I/downloader - curl -oD:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_79.0.3945.36.zip https://chromedriver.storage.googleapis.com/79.0.3945.16/chromedriver_win32.zip I/update - chromedriver: unzipping chromedriver_79.0.3945.36.zip I/launcher - Running 1 instances of WebDriver I/direct - Using ChromeDriver directly... E/launcher - session not created: This version of ChromeDriver only supports Chrome version 79

when i use below script command i get version issue for 76
postinstall": "webdriver-manager update"
I/update - chromedriver: file exists D:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_76.0.3809.12.zip I/update - chromedriver: unzipping chromedriver_76.0.3809.12.zip I/update - chromedriver: chromedriver_76.0.3809.12.exe up to date I/launcher - Running 1 instances of WebDriver I/direct - Using ChromeDriver directly... E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76 (Driver info: chromedriver=76.0.3809.12

below is config.json under webdriver-manager

{
"webdriverVersions": {
"selenium": "2.53.1",
"chromedriver": "2.27",
"maxChromedriver": "77",
"geckodriver": "v0.13.0",
"iedriver": "2.53.1",
"androidsdk": "24.4.1",
"appium": "1.6.5"
},
"cdnUrls": {
"selenium": "https://selenium-release.storage.googleapis.com/",
"chromedriver": "https://chromedriver.storage.googleapis.com/",
"geckodriver": "https://github.com/mozilla/geckodriver/releases/download/",
"iedriver": "https://selenium-release.storage.googleapis.com/",
"androidsdk": "http://dl.google.com/android/"
}
}

Below is the package.json file:

{
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "postinstall": "cd ./node_modules/protractor && npm i webdriver-manager@latest",
    "ng": "ng",
    "start": "ng serve -p 9091 -o",
    "build": "ng build --prod --named-chunks",
    "test": "ng test --code-coverage",
    "lint": "ng lint",
    "e2e": "ng e2e --env=e2e",
    "code-scan": "retire --ignorefile .retireignore -p --severity high --nocache -v "
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "ag-grid": "^18.1.2",
    "ag-grid-angular": "^19.1.2",
    "ag-grid-community": "^19.1.2",
    "ag-grid-enterprise": "^19.1.2",
    "angular-oauth2-oidc": "^3.1.4",
    "angular-tree-component": "^8.0.0",
    "angular2-fontawesome": "^5.2.1",
    "bootstrap": "4.1.3",
    "core-js": "^2.4.1",
    "d3": "^5.12.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "material-design-icons": "^3.0.1",
    "ng2-toastr": "^4.1.2",
    "ngx-loading": "^2.0.1",
    "rxjs": "^5.5.6",
    "tether": "1.4.0",
    "tslint-origin-ordered-imports-rule": "^1.2.2",
    "zone.js": "^0.8.19",
    "webdriver-manager": "^12.1.7"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-phantomjs-launcher": "^1.0.4",
    "ngx-cookie-service": "^1.0.10",
    "node-sass": "^4.13.0",
    "protractor": "^5.4.2",
    "retire": "^1.6.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}

Tried many commands that might get worked on the pipeline build but none of them is helping me out. Can any one please suggest what could be the possible issue.

**Comment by bonigarcia** [comment]
See: https://www.npmjs.com/package/webdriver-manager
