### ISSUE TITLE
Feature Request: Detect the chrome version on Android.

### ISSUE THREAD

**Issue by kartikjain12** [bonigarcia/webdrivermanager#421]
This tool is awesome but I wish it would also detect the chrome version installed on the android phone attached to your computer and download the correct version on driver, this would be really cool.

We test on every browser, even on mobile. The driver used for android chrome is not automatically updated.

**Comment by bonigarcia** [comment]
I don't plan to implement this feature. Nevertheless, this project is open to PR, so feel free to give a try.
