### ISSUE TITLE
Error java.lang.NoClassDefFoundError: org/rauschig/jarchivelib/ArchiveFormat when add library 

### ISSUE THREAD

**Issue by Thuhuong-1988** [bonigarcia/webdrivermanager#424]
I have a function to use open multi-browser: 	public WebDriver openmultiBrowser(String browser, String version) {
		
		if (browser.equalsIgnoreCase("firefox")) {
			FirefoxDriverManager.getInstance().setup();
			driver = new FirefoxDriver();			
		} else if (browser.equalsIgnoreCase("chrome")) {			
			ChromeDriverManager.getInstance().version(version).setup();
			driver = new ChromeDriver();			
		} else if (browser.equalsIgnoreCase("ie")) {			
			InternetExplorerDriverManager.getInstance().version(version).setup();
			driver = new InternetExplorerDriver();
	}
		return driver;
	}
**At the Testcase:** 
@Parameters({ "browser", "version" })
	@BeforeClass
	public void beforeClass(String browser, String version) {		
		driver = openmultiBrowser(browser, version);
		loginPage = new LoginPage(driver);
		driver.get(Constants.EOP_URL);
	}

And when I run Tescase.xml then see this issue: 
![image](https://user-images.githubusercontent.com/37929864/71867685-b81e9700-313d-11ea-819d-05761df2c413.png)

Please support to me! Thanks you so much!

**Comment by bonigarcia** [comment]
It seems you have a conflict with the dependency jarchivelib (WebDriverManager uses version 1.0.0).
