### ISSUE TITLE
Feature request: Make DriverManagerType return the driver class name

### ISSUE THREAD

**Issue by eliasnogueira** [bonigarcia/webdrivermanager#426]
## Background
We can pass an enum value from `DriverManagerType` on  `WebdriverManager.getInstance()` to set up a target browser. The example on the documentation is:
```java
WebDriverManager.getInstance(CHROME).setup();
WebDriver driver = new ChromeDriver();
```

There's also a way to create the driver instance through the `WebdriverManager.getInstance()` as we can see as an example in the documentation.

```java
Class<? extends WebDriver> driverClass = ChromeDriver.class;
WebDriverManager.getInstance(driverClass).setup();
WebDriver driver = driverClass.newInstance();
```

## Proposed feature
We could have a way to get the driver class from the `DriverManagerType`, so the browser instance creation by the `WebdriverManager.getInstance()` will be easy, as we can have fewer lines of code and apply a better solution get ride of switch-case solutions.

### Expected code
```java
DriverManagerType chrome = DriverManagerType.CHROME;
WebDriverManager.getInstance(chrome).setup();
Class<?> chromeClass =  Class.forName(chrome.browserClass());
driver = (WebDriver) chromeClass.newInstance();
```
In the code snippet above we can already pass the enum `CHROME` from `DriverManagerType` to create the browser setup.
The next code has a new method inside the `DriverManagerType` called `browserInstance` that returns the complete driver class name. If we have the complete driver class name we can use the `Class.forName()` to create this class and, after, use it to instantiate the browser.

### Benefits
With this approach we can apply better code design in a browser factory design patter, having fewer lines of code for a browser creation, like:
```java
// try-catch block ignored
public WebDriver createInstance(String browser) {
   WebDriver driver = null;
   // getting the correct DriverManagerType using the browser parameter from this method
   DriverManagerType driverManagerType = DriverManagerType.valueOf(browser.toUpperCase());
   WebDriverManager.getInstance(driverManagerType).setup();

   Class<?> browserToInstantiate =  Class.forName(driverManagerType.browserClass());

   return browserToInstantiate.newInstance();
}
```

The code snippet above will create a new browser instance based on the browser name informed in the method parameter. It's a generic function that can help during browser creation.

#### DriverManagerType
We must add the complete class name as a parameter on this enum.

```java
CHROME("org.openqa.selenium.chrome.ChromeDriver")

String browserClass;

// method that will allow to the the complete driver class
DriverManagerType(String browserClass) {
   this.browserClass = browserClass;
}
```

### Development
This feature proposal was already implemented. The PR https://github.com/bonigarcia/webdrivermanager/pull/427 was created for further review.

**Comment by bonigarcia** [comment]
Thanks a lot! Merged.
