### ISSUE TITLE
WebDriverManager.getInstance() doesn't have branch for chromium

### ISSUE THREAD

**Issue by Relaximus** [bonigarcia/webdrivermanager#429]
Thank you a lot for implementing #400, but I can't run it now because:

```
public Downloader(DriverManagerType driverManagerType) {
        this.driverManagerType = driverManagerType;

        WebDriverManager webDriverManager = WebDriverManager
                .getInstance(driverManagerType);
        config = webDriverManager.config();
        httpClient = webDriverManager.getHttpClient();
    }
```

retrieves void webDriverManger, which provides httpClient = null, and thus there is no download possible. Could you fix this bug? Or I can contribute if it is welcome here?

**Comment by bonigarcia** [comment]
Yes, please. Send a PR solving this issue if you want.

**Comment by bonigarcia** [comment]
BTW how are you calling WebDriverManager to reproduce the error?

**Comment by Relaximus** [comment]
> BTW how are you calling WebDriverManager to reproduce the error?

`WebDriverManager.chromiumdriver().setup();`

**Comment by bonigarcia** [comment]
Merged. Thanks a lot for the PR.
