### ISSUE TITLE
Chromium Edge Replacing Edge

### ISSUE THREAD

**Issue by Carlbc18** [bonigarcia/webdrivermanager#431]
It looks like the new edge which released yesterday https://www.microsoft.com/en-us/edge replaces the existing install of edge.  When launching with edge as the browser, an error is thrown regarding the pre_installed version.  Since the default (old) edge was replaced, shouldn't the instantiation support launching the correct edge?  I'm still having to default to using the application path.

**Comment by bonigarcia** [comment]
The latest version of WebDriverManager (i.e. 3.8.1 at the time of this writing) is compatible with Microsoft Edge (stable, beta, and dev) based on Chromium. If you experience some kind of problem, please open a new issue following the template.
