### ISSUE TITLE
Getting expection "java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;" on line "WebDriverManager.chromedriver().setup();"

### ISSUE THREAD

**Issue by racchouhan12** [bonigarcia/webdrivermanager#432]
Hi Team,

I am having a multiple module project and my project has selenium code so I am using Webdriver Manager 3.8.1 I am getting exception on line "WebDriverManager.chromedriver().setup()" I am not sure why it is coming.

**Comment by racchouhan12** [comment]
Resloved by changing commons-io lib with latest(2.6) mvn dependency.

**Comment by rganjare** [comment]
Resolved by changing commons-io lib with latest(2.8) mvn dependency.	
	<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.8.0</version>
		</dependency>

**Comment by dhust** [comment]
In pom.xml add these lines inside `<dependencies></dependencies>`

```
<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
  <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.8.0</version>
  </dependency>
```

**Comment by saikrishnameda248** [comment]
I am facing the same issue
**java.lang.NoSuchMethodError: 'java.lang.String org.apache.commons.io.IOUtils.toString(java.io.InputStream, java.nio.charset.Charset)'**
I am using the latest WebDriverManager version i.e 5.3.1 and the latest common.io version i.e 2.11.0

**Comment by saikrishnameda248** [comment]
Can anyone help me to find a solution for my issue?

**Comment by asolntsev** [comment]
@dhust Who said `2.8.0` is the latest version? It's 2.5 years old. :)

@saikrishnameda248 You just need to remove this `commons-io` dependency. Or at least you the true latest version `2.11.0`.

**Comment by saikrishnameda248** [comment]
Hello @asolntsev ,
I tried both the ways & didn't work for me

**Comment by racoonbest** [comment]
Webdriver Manager requires Commons IO to run, but there is another dependency that includes an older version of Apache Commons IO. Webdriver Manager is using this older version of Commons IO, which does not support the required method. To resolve this issue, you need to identify the problematic dependency. In IntelliJ, run the following command: "dependency:tree". If you are using the CLI, use "mvn dependency:tree". Search for "commons-io" in the output. This will indicate which dependency includes the older version of Commons IO. Once you have identified the culprit, update that specific dependency to a newer version that supports the required method.
