### ISSUE TITLE
Facing issue with Firefox 73.0.1 (64-bit) in Ubuntu 

### ISSUE THREAD

**Issue by jitsolution19** [bonigarcia/webdrivermanager#445]
I have written the simple program for launching the firefox with selenium 3.141.59 , Can you please provide the appropriate solution
code is 
System.out.println("Launch Firefox Browser");
WebDriverManager.firefoxdriver().setup();
WebDriver driver = new FirefoxDriver();
driver.get("https://timesofindia.indiatimes.com/");
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
List<WebElement> newslink = driver.findElements(By.tagName("a"));
		Iterator<WebElement> counter = newslink.iterator();
		while(counter.hasNext())
		{
			WebElement items = counter.next();
			if(items.isDisplayed()) {
				System.out.println(items.getText());
			}
		driver.quit();
		}
		
Error message is 

Launch Firefox Browser
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
1583054405059	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilebVhjVT"
1583054432581	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1583054437698	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1583054437698	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1583054437698	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1583054437699	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*

###!!! [Child][MessageChannel] Error: (msgtype=0xFFF7,name=<unknown IPC msg name>) Channel error: cannot send/recv

Exiting due to channel error.

**Comment by bonigarcia** [comment]
No clue, but this is not an issue of WebDriverManager for sure.
