### ISSUE TITLE
UnreachableBrowserException: Firefox

### ISSUE THREAD

**Issue by SaranyaSriram** [bonigarcia/webdrivermanager#446]
**Description of the problem**: 

Test running fine on chrome after I update the webdrivermanager but throws unreachablebrowser error in firefox

Actual Behavior
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

Expected Behavior
Browser opens up and run tests without any error.
 
**Browser and version**: Version 73.0.1 (64-bit) Mozilla Firefox for Ubuntu 

**Operating system**:  Ubuntu 16.04 OS type 64-bit

**WebDriverManager version**:  3.8.1 

**WebDriverManager use**:  
WebDriverRunner.FIREFOX:
                WebDriverManager.firefoxdriver().setup(); 

**WebDriverManager traces**:  org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '******', ip: '******', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-88-generic', java.version: '1.8.0_242'
Driver info: driver.version: FirefoxDriver
selenide.url: http://***
selenide.baseUrl: http://localhost:8080
	at ***)
Caused by: java.lang.NullPointerException
	at ***)

After attempting to add below:
Added **WebDriverManager use**:  
WebDriverRunner.GECKO:
                WebDriverManager.geckodriver().setup(); 

But this can't be fixed.

**Comment by bonigarcia** [comment]
It seems it is not a problem with WebDriverManager. I say "seems" because in the trace there is only a NullPointerException in which cause is missing.

**Comment by SaranyaSriram** [comment]
The issue got resolved by adding marionette as browser
```
WebDriverRunner.FIREFOX:
browser = "marionette";
WebDriverManager.firefoxdriver().setup();
```
