### ISSUE TITLE
WDM should detect version of installed Edge browser on MacOS

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#447]
Currently WDM only detects Edge version on Windows. 

**Description of the problem**: 

**Browser and version**: 
* I have installed Microsoft Edge 80.0.361.66 on MacOS
* But WDM downloads (latest) `MSEdgeDriver 82.0.457.0`

**Operating system**: MacOS Catalina (64b architecture)

**WebDriverManager version**: 3.8.1
**WebDriverManager use**: 
```java
  WebDriverManager.edgedriver().setup();
```

### The problem
is in class `EdgeDriverManager`:

```java
public class EdgeDriverManager extends WebDriverManager {
    protected Optional<String> getBrowserVersion() {
        if (IS_OS_WINDOWS) { 
              ...
        }
        return empty();
    }
}
```

### Solution
The following command line returns the version of installed Edge browser on MacOS:
```
"/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" -version                                            
Microsoft Edge 80.0.361.66
```

**Comment by eliasnogueira** [comment]
@asolntsev I've submitted a PR adding this support if you want take a look and give feedback:
https://github.com/bonigarcia/webdrivermanager/pull/451

**Comment by asolntsev** [comment]
@bonigarcia I have reviewed PR #451 . Looks good for me.

**Comment by bonigarcia** [comment]
Thanks a lot, @asolntsev and @eliasnogueira. Merged!
