### ISSUE TITLE
Add support for Safari on DriverManagerType

### ISSUE THREAD

**Issue by eliasnogueira** [bonigarcia/webdrivermanager#449]
**Description of the problem**
The class `DriverManagerType` does not have `SafariDriver` listed.
Even we now that WebDriverManager works with Safari without any additional configuration (see issue #238 ) this could be added to enable the dynamic browser instantiation.

**Changes to do**
- Add on `DriverManagerType` the `SafariDriver`, both the enum item with the value driver class value
- Add the test for Safari on `DriverManagerTypeTest`
- Create a new test for Safari browser using `assumeTrue` on the pre-condition

**Expected result**
Be able to use the dynamic browser instantiation like the example below:
```java
DriverManagerType safari = DriverManagerType.SAFARI;
WebDriverManager.getInstance(safari).setup();
Class<?> safariClass =  Class.forName(safari.browserClass());
driver = (WebDriver) safariClass.getDeclaredConstructor().newInstance();
```

**Comment by bonigarcia** [comment]
Thanks a lot, @eliasnogueira for contributing!
