### ISSUE TITLE
WebDriverManager picks the Two different chrome driver versions on Linux

### ISSUE THREAD

**Issue by NallaSandeep** [bonigarcia/webdrivermanager#454]
**Description of the problem**: WebDriver manager picks two different chrome versions on linux machine. [version 71 most of the times & version 76 some times]

**Browser and version**: Chrome (Version - Not sure. From trace, it's 76)

**Operating system**:  os.arch - amd64, os.name - Linux, os.version - 3.10.0-957.21.3.el7.x86_64

**WebDriverManager version**: 3.8.1

**WebDriverManager use**: WebDriverManager.chromedriver().version("78").setup();

**WebDriverManager traces**: 

- **From the trace, chromeDriver 76 (Some times 78) is picked from cache. But, chromeDriver 71 is started.** [Test Passed]
09:38:47  04:08:47.294 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  04:08:47.294 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Detected Google Chrome version 76
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 76.0.3809.126 (since Google Chrome 76 is installed in your machine)
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Managing chromedriver arch=64 version=76.0.3809.126 getLatest=false cache=false
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Checking if chromedriver exists in cache
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by chromedriver -- input list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver, /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/78/chromedriver] -- output list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver, /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/78/chromedriver] 
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 76.0.3809.126 -- input list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver, /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/78/chromedriver] -- output list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver] 
09:38:47  04:08:47.295 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by LINUX -- input list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver] -- output list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver] 
09:38:47  04:08:47.296 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
**09:38:47  Starting ChromeDriver 71.0.3578.137** (86ee722808adfe9e3c92e6e8ea746ade08423c704:08:47.296 [TestNG-test=PROFLOWERS-1] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  e) 04:08:47.296 [TestNG-test=PROFLOWERS-1] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 76.0.3809.126 found in cache
09:38:47  on port 19423
09:38:47  Only local connections are allowed.
09:38:47  Please protect ports used by ChromeDrive04:08:47.297 [TestNG-test=PROFLOWERS-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver
09:38:47  r and related test frameworks to prevent access by malicious code.

- **In the same job at jenkins node, chromeDriver 76 is picked up.** [Test Failed]
09:38:47  04:08:47.302 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  04:08:47.302 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Detected Google Chrome version 76
09:38:47  04:08:47.302 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  04:08:47.302 [TestNG-test=PROFLOWERS-3] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 76.0.3809.126 (since Google Chrome 76 is installed in your machine)
09:38:47  04:08:47.302 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Managing chromedriver arch=64 version=76.0.3809.126 getLatest=false cache=false
09:38:47  04:08:47.302 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Checking if chromedriver exists in cache
09:38:47  04:08:47.303 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by chromedriver -- input list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver, /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/78/chromedriver] -- output list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver, /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/78/chromedriver] 
09:38:47  04:08:47.303 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 76.0.3809.126 -- input list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver, /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/78/chromedriver] -- output list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver] 
09:38:47  04:08:47.303 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by LINUX -- input list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver] -- output list [/var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver] 
09:38:47  04:08:47.303 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  04:08:47.304 [TestNG-test=PROFLOWERS-3] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
09:38:47  04:08:47.304 [TestNG-test=PROFLOWERS-3] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 76.0.3809.126 found in cache
09:38:47  04:08:47.305 [TestNG-test=PROFLOWERS-3] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /var/home/jenkins/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver
**09:38:47  Starting ChromeDriver 76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}) on port 27981**

**Error trace**: 
09:49:21  org.openqa.selenium.SessionNotCreatedException: 
09:49:21  session not created: This version of ChromeDriver only supports Chrome version 76
09:49:21  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
09:49:21  System info: host: 'automation-gce-bw2vyp', ip: '10.84.216.130', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.21.3.el7.x86_64', java.version: '1.8.0_242'
09:49:21  Driver info: driver.version: ChromeDriver
09:49:21  remote stacktrace: #0 0x5572195e4789 <unknown>
09:49:21  
09:49:21  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
09:49:21  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
09:49:21  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
09:49:21  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
09:49:21  	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
09:49:21  	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
09:49:21  	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
09:49:21  	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
09:49:21  	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
09:49:21  	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
09:49:21  	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
09:49:21  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
09:49:21  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
09:49:21  	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
09:49:21  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
09:49:21  	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
09:49:21  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
09:49:21  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
09:49:21  	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
09:49:21  	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
09:49:21  	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
09:49:21  	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
09:49:21  	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
09:49:21  	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
09:49:21  	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
09:49:21  	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
09:49:21  	at com.ftd.automation.framework.driver.DriverFactory.createChromeDriver(DriverFactory.java:186)
09:49:21  	at com.ftd.automation.framework.driver.DriverFactory.createDriver(DriverFactory.java:87)
09:49:21  	at com.ftd.automation.framework.base.SeleniumBaseTest.beforeClassSelenium(SeleniumBaseTest.java:172)
09:49:21  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:49:21  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:49:21  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:49:21  	at java.lang.reflect.Method.invoke(Method.java:498)
09:49:21  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
09:49:21  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
09:49:21  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
09:49:21  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
09:49:21  	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
09:49:21  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
09:49:21  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:49:21  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:49:21  	at java.lang.Thread.run(Thread.java:748)

**Comment by bonigarcia** [comment]
Not sure what it is going here. Are you running tests in parallel?

**Comment by NallaSandeep** [comment]
Yes @bonigarcia , I'm running tests in parallel.

**Comment by NallaSandeep** [comment]
@bonigarcia 

I got the root cause of the issue.

`WebDriverManager.chromedriver().version("78").setup()`

1. Though ChromeDriver 78 is specified, WDM detected the browser version as 76, so Chrome driver 76 is picked up some times.
2. The text '78' is contained in sub version of chrome version 71, so Chrome driver 71 is picked up some times.<br>
ChromeDriver 71.0.3578.137
3. Windows machine is picking the specified Chrome driver version irrespective of the browser version present in the machine.

**Comment by bonigarcia** [comment]
This should be fixed in version 4.0.0.
