### ISSUE TITLE
WDM downloads ChromeDriver 81 on Linux when i have only Chrome 80 installed

### ISSUE THREAD

**Issue by gamerka** [bonigarcia/webdrivermanager#458]
**Description of the problem**: 
I have Docker image with Chrome 80.0.3987.149 and my compiled test. I ran tests using this image earlier today and they worked just fine, several hours later I ran them again and now I'm receiveing an eror: "session not created: This version of ChromeDriver only supports Chrome version 81" and I see in logs that WDM now downloading ChromeDriver 81.0.4044.69 instead of 80.0.3987.106

**Browser and version**: Chrome 80.0.3987.149

**Operating system**:  Oracle Linux x64

**WebDriverManager version**: 3.8.0

**WebDriverManager use**: I Use Selenide, it has only this in sources:
      WebDriverManager.chromedriver().setup();

**WebDriverManager traces**: 
3680 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
4356 [main] INFO io.github.bonigarcia.wdm.Downloader - Downloading https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
4745 [main] INFO io.github.bonigarcia.wdm.Downloader - Extracting binary from compressed file chromedriver_linux64.zip
4827 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.m2/repository/webdriver/chromedriver/linux64/81.0.4044.69/chromedriver
Starting ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}) on port 23939
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1586370157.937][SEVERE]: bind() failed: Cannot assign requested address (99)
........
org.openqa.selenium.SessionNotCreatedException:
session not created: This version of ChromeDriver only supports Chrome version 81
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'd2ee15240752', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '13.0.2'

**My logs from same image, but earlier today:**
28132 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
29482 [main] INFO io.github.bonigarcia.wdm.Downloader - Downloading https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
30335 [main] INFO io.github.bonigarcia.wdm.Downloader - Extracting binary from compressed file chromedriver_linux64.zip
30622 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.m2/repository/webdriver/chromedriver/linux64/80.0.3987.106/chromedriver
Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 7090
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Apr 08, 2020 1:00:19 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
34472 [main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - BrowserName=chrome Version=80.0.3987.149 Platform=LINUX
34490 [main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenide v. 5.6.1
34490 [main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
34491 [main] INFO com.codeborne.selenide.drivercommands.CreateDriverCommand - Create webdriver in current thread 1: ChromeDriver -> ChromeDriver: chrome on LINUX (0435f073c6c344bded691be9766df369)

**Also when running same project on Windows with Chrome 81 I get following log:**
_2724 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 80.0.3987.106 (since Google Chrome 80 is installed in your machine)_ - this line concerns me as I don't get it in logs from Linux 
2744 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
3552 [main] INFO io.github.bonigarcia.wdm.Downloader - Downloading https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_win32.zip
3829 [main] INFO io.github.bonigarcia.wdm.Downloader - Extracting binary from compressed file chromedriver_win32.zip
3941 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\user\.m2\repository\webdriver\chromedriver\win32\80.0.3987.106\chromedriver.exe
Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 12828
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1586378065.485][WARNING]: This version of ChromeDriver has not been tested with Chrome version 81.
[1586378067.489][WARNING]: Timed out connecting to Chrome, retrying...
[1586378071.509][WARNING]: Timed out connecting to Chrome, retrying...
Apr 08, 2020 11:34:33 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
13825 [main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - BrowserName=chrome Version=81.0.4044.92 Platform=WINDOWS
13825 [main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenide v. 5.6.1
13825 [main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
13826 [main] INFO com.codeborne.selenide.drivercommands.CreateDriverCommand - Create webdriver in current thread 1: ChromeDriver -> ChromeDriver: chrome on WINDOWS (830997bf84bbf40148fc65037fb6db85)

**Comment by bonigarcia** [comment]
Is this issue still happening?

**Comment by gamerka** [comment]
Yes, just checked:
`INFO: Created user preferences directory.
4927 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
5592 [main] INFO io.github.bonigarcia.wdm.Downloader - Downloading https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
6305 [main] INFO io.github.bonigarcia.wdm.Downloader - Extracting binary from compressed file chromedriver_linux64.zip
6389 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.m2/repository/webdriver/chromedriver/linux64/81.0.4044.69/chromedriver
Starting ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}) on port 12662
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1587648826.587][SEVERE]: bind() failed: Cannot assign requested address (99)
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 8.111 s <<< FAILURE! - in TestSuite
[ERROR] ... Time elapsed: 7.701 s <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException:
session not created: This version of ChromeDriver only supports Chrome version 81`

**Comment by bonigarcia** [comment]
Could you please repeat your test, but this time using this line:

```
WebDriverManager.chromedriver().clearPreferences().setup();
```

... and also capturing the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level (not only `INFO`).

**Comment by bonigarcia** [comment]
@gamerka And also, use the latest version of WebDriverManager (3.8.1 at this moment).

**Comment by bonigarcia** [comment]
Please upgrade to WebDriverManager 4.0.0. If the problem persists, open a new issue and include the WebDriverManager traces at `DEBUG` level.

**Comment by gamerka** [comment]
@bonigarcia I will update this bug as I found how to avoid it.
I first tried WDM 4.0.0, it didn't change anything.
Then we turned on DEBUG logs and got this:
DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [google-chrome, --version]
DEBUG io.github.bonigarcia.wdm.versions.Shell - Result:
After that we found out that when we add --headless option for chrome, then --version returns some error.
So to fix this we removed --headless option and set headless mode from mvn with "-Dselenide.headless=true"
Now version detection works fine:
INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 83.0.4103.39 (**since Chrome 83 is installed in your machine**)

**Comment by bonigarcia** [comment]
@gamerka It is not clear for me how the headless option can make the browser detection to fail. I have just executed [this test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ChromeHeadlessTest.java) (which uses Chrome in headless mode) and the browser detection is working fine (both in Windows and Linux).

How do you setup the headless mode in your test? (I mean when it was failing the browser detection by WebDriverManager)

**Comment by gamerka** [comment]
I was adding default chrome options like this:
`sed -i 's/"$HERE\/chrome"/"$HERE\/chrome" --no-sandbox --disable-dev-shm-usage --disable-gpu --headless --window-size=1920,1080/g' /opt/google/chrome/google-chrome && ln -s /opt/google/chrome/google-chrome /usr/bin/chrome`
Basically it's the same as in your test I think.
