### ISSUE TITLE
Automatic PhantomJS driver download - 1.4.7v - still having issue and not supporting win64 OS

### ISSUE THREAD

**Issue by hsirk** [bonigarcia/webdrivermanager#46]
java.lang.RuntimeException: java.lang.RuntimeException: [phantomjs] 2.1.2 for win64 not found in https://bitbucket.org/ariya/phantomjs/downloads/

does that not support for win64 ?

**Comment by bonigarcia** [comment]
Phantomjs 2.1.2 is not released yet.
