### ISSUE TITLE
Wrong driver version is downloaded in Linux for Chromium

### ISSUE THREAD

**Issue by angryziber** [bonigarcia/webdrivermanager#460]
chromium-browser version 80 is installed, but current WebDriverManager downloads chromedriver 81, which doesn't work.

From source code I see that `google-chrome --version` is called for version check, but it should also fallback to `chromium-browser` if `google-chrome` is not available

**Comment by angryziber** [comment]
Or another option: fail if `google-chrome` cannot be executed instead of downloading wrong (usually too-new) version

**Comment by hontrang** [comment]
Hi @gamerka ,
I met the same issue with you, have you had word-around solution ?

**Comment by gamerka** [comment]
@hontrang hi, I have manually set 80.0.3987.106 Chrome driver version in the code. It works both for 80 Chrome on Linux and 81 Chrome on Windows.

**Comment by bonigarcia** [comment]
Please follow the issue template to report any problem. Remember to include the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level. Otherwise, it is impossible to know what is happening.
