### ISSUE TITLE
Feature Request: webdrivermanager server can cache drivers for multiple operating systems

### ISSUE THREAD

**Issue by djangofan** [bonigarcia/webdrivermanager#470]
**Description of the problem**: 
Feature Request:  Can webdrivermanager server be enhanced to cache drivers for multiple operating systems,  in the same way that webdrivermanager stores drivers in the .m2 folder?

When I look at this file, it looks like the handlers are all hard coded to support only the operating system that the "webdrivermanager server" runs on??

https://github.com/bonigarcia/webdrivermanager/blob/c92813a7a715b36238b00111bc1a6cca6f33d740/src/main/java/io/github/bonigarcia/wdm/Server.java

**Browser and version**:   Multiple

**Operating system**: 
Mac and Windows and Linux

**WebDriverManager version**: 
3.8.1

**WebDriverManager use**:   
To reproduce, run this image:  https://hub.docker.com/r/djangofan/webdrivermanagerserver

**Comment by bonigarcia** [comment]
These features are already implemented in the wdm server. For instance, if you made the following request:

http://localhost:4041/chromedriver

... wdm server will serve the driver from the cache (by default in .m2 folder), as you can see in the traces:

```
[INFO] WebDriverManager server listening on port 4041
[INFO] Server request: GET /chromedriver
[DEBUG] Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE is 81.0.4044.69
[DEBUG] Driver chromedriver 81.0.4044.69 found in cache
[INFO] Resulting binary C:\Users\boni\.m2\repository\webdriver\chromedriver\win32\81.0.4044.69\chromedriver.exe
[INFO] Server response: chromedriver.exe 81.0.4044.69 (8124416 bytes)
```

Moreover, you can ask the same server to provide different flavors of driver respecting the operating system, for example as follows:

http://localhost:4041/chromedriver?os=LINUX

```
[INFO] Server request: GET /chromedriver
[INFO] Server query string for configuration {os=[LINUX]}
[DEBUG] Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE is 81.0.4044.69
[INFO] Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[INFO] Downloading https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
[INFO] Extracting binary from compressed file chromedriver_linux64.zip
[INFO] Resulting binary C:\Users\boni\.m2\repository\webdriver\chromedriver\linux64\81.0.4044.69\chromedriver
[INFO] Server response: chromedriver 81.0.4044.69 (10272352 bytes)
```

**Comment by djangofan** [comment]
Thanks!  Since I saw files being saved right next to the server .jar,  I didn't expect to look in the .m2 folder.  Thank you!

**Comment by djangofan** [comment]
Thank you.  I was able to cache a couple default drivers in my Docker image, in the .m2 folder:  https://hub.docker.com/repository/docker/djangofan/webdrivermanagerserver .   Much appreciation for this.
