### ISSUE TITLE
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

### ISSUE THREAD

**Issue by skwolvie** [bonigarcia/webdrivermanager#478]
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

**Comment by walliski** [comment]
@bonigarcia I also saw this issue. The machine it was running on was running Chrome 81, but by some reason webdrivermanager downloaded the driver for 83. So this seems to be a valid issue, although clumsily expressed by op.
