### ISSUE TITLE
Question: is Nexus raw-repo compatible with WebDriverManager?

### ISSUE THREAD

**Issue by djangofan** [bonigarcia/webdrivermanager#481]
**Description of the problem**: 

Is a Nexus 'raw' type repository compatible with WebDriverManager?    I am asking because I tried this (since I cannot get WebDriverManager to download Firefox via my restricted firewall)  and I could not get it to work configured like you see below.   I even tried passing  **-Dhttp.nonProxyHosts=***  to my tests but it still uses the system proxy (instead of bypassing).   I think a Nexus solution would work for me since I could ask IT to put some drivers in the repo.

For example, running a local Docker Nexus:
![Screen Shot 2020-05-19 at 5 56 45 PM](https://user-images.githubusercontent.com/810894/82395946-8843a200-9a01-11ea-8cb1-175ad81d8f84.png)

NOTE: Artifacts were uploaded like this:
`curl --noproxy "*" -i -u uploader:admin123 --upload-file chromedriver/83.0/chromedriver_win32.zip -v http://127.0.0.1:8084/repository/webdrivers/chromedriver/83.0/chromedriver_win32.zip`

webdrivermanager.properties config:
wdm.geckoDriverUrl=http://localhost:8084/service/rest/repository/browse/webdrivers/geckodriver/

**Browser and version**: 
Any

**Operating system**:
Docker Nexus

**WebDriverManager version**:  4.0

**Comment by djangofan** [comment]
Could WebDriverManager work with one of these?
`
import java.net.Authenticator
class ProxyAuthenticator extends Authenticator {
...

and/OR   reenable Basic scheme on command line?

-Djdk.http.auth.tunneling.disabledSchemes=

`

**Comment by bonigarcia** [comment]
WebDriverManager is not compatible with that repository, sorry.

**Comment by djangofan** [comment]
thank you.   i am able to workaround by keeping local driver cached in my
project
