### ISSUE TITLE
#CI #Feature Split tests by Operating System

### ISSUE THREAD

**Issue by edumco** [bonigarcia/webdrivermanager#485]
### Tests should be grouped by Operating system since some browsers only work on specific OS

The `Edge` and `Safari` browsers don't work on Linux so they should be put in a separate suite so the CI could test them on Windows and MacOS.

Actually the CI only runs on linux but this could be easily changed by adding new entries on the OS key on the `.travis.yml` configuration. This would result in parallel executions in multiple OS.

 This way instead of ignoring the tests we could include them under the condition of a specific OS.

I've tried to add this on the Travis CI by adding a `-Dtest=` filter but it became too much verbose because i have to list all test packages:

```shell
-Dtest=**.firefox.**,**.chrome.**,**.chromium.** ...
```

I've also tried a negation filter (`!firefox`) but it did not worked even on my machine.

What do you think about this?

Do you have any recommendation of approach to solve this without have to annotate every test?

**Comment by bonigarcia** [comment]
What are the problematic tests?

We can include assumptions in these tests about the operative system.

**Comment by edumco** [comment]
> What are the problematic tests?

It was:

```log
[ERROR] Failures: 
[ERROR]   ServerTest.testServer:103
[ERROR]   LatestAndBetaTest.testLatestAndBetaedgedriver:76 
```
> We can include assumptions in these tests about the operative system.

Sure! What do you think about adding windows and osx to the OS list?

**Comment by bonigarcia** [comment]
Those tests were flaky, i.e., they failed depending on the status of the driver versions. At this moment LatestAndBetaTest is ignored in the master branch, and I think the problematic input data in ServerTest is removed. Could you please update and test again?

**Comment by edumco** [comment]
@bonigarcia I forgot to answer! Sorry!

The tests are now passing. Do you think we need to test against different operating systems?

If you think it's not necessary this issue can be closed. :)
