### ISSUE TITLE
Edge 83 version is downloading 81 version driver

### ISSUE THREAD

**Issue by sankar6270** [bonigarcia/webdrivermanager#487]
Edge 83 version is downloading 81 version driver.
Webdrivermanager version : 4.0.0
OS: windows 10
Edge version : 83
Note: it downloading correct driver while specifying the version manually.

**Comment by andruhon** [comment]
I just noticed that getDriversFromXml does not find any nodes in https://chromedriver.storage.googleapis.com which makes it impossible to download any version. The issue in the ticked could be related and 81 is simply cached. Configuring with userMirror seems to work.
`WebDriverManager.chromedriver().useMirror().setup()`

**Comment by davidcarvalho** [comment]
https://github.com/bonigarcia/webdrivermanager/issues/486#issuecomment-635364834

**Comment by bonigarcia** [comment]
I think there this [XML](https://chromedriver.storage.googleapis.com/) was out of sync for a while, but now it seems ok. Is this issue still happening?

**Comment by sankar6270** [comment]
Still no luck @bonigarcia . Still it's downloading edge 81 driver instead of 83. Let me know if anything i did wrong.
[image](https://user-images.githubusercontent.com/66047589/83391231-ccc33a80-a410-11ea-8975-67403d04a393.png)

**Comment by sankar6270** [comment]
Still I'm facing same issue. it's not downloading edge 83 version driver.
