### ISSUE TITLE
clearPreferences() builder method no longer available as of 4.0.0?

### ISSUE THREAD

**Issue by jamespizzurro** [bonigarcia/webdrivermanager#489]
**Description of the problem**:
The following doesn't seem to work anymore as of 4.0.0 because 'clearPreferences' can't be resolved:
```java
WebDriverManager webDriverManager = WebDriverManager.chromedriver().clearPreferences();
```
Is there something we should be using instead now that offers the same functionality? If so, could this be included in the documentation somewhere? `clearResolutionCache()` instead of `clearPreferences()`, for example? (I'm not sure if that does the exact same thing, but this commit I've found seems to suggest that it does or something similar: https://github.com/bonigarcia/webdrivermanager/commit/7afe45246d503fad89a70727b489880f6a12b2ba#diff-b17ef556ee73d4a4fe4078fc5586b502R258)

**Browser and version**: 
Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Operating system**: 
macOS Catalina 10.15.5

**WebDriverManager version**: 
4.0.0

**WebDriverManager use**: 
See 'Description of the problem' section for a code-level example.

**WebDriverManager traces**: 
N/A

**Error trace**: 
Maven stack trace specific to my project:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project continuum-java-professional: Compilation failure
[ERROR] /Users/ready/Developer/dev/continuum/continuum-bdd-testing/continuum-java/src/main/java/com/levelaccess/continuum/Continuum.java:[953,92] cannot find symbol
[ERROR]   symbol:   method clearPreferences()
[ERROR]   location: class io.github.bonigarcia.wdm.WebDriverManager
```

**Comment by bonigarcia** [comment]
Indeed the method `clearPreferences()` has been removed in version 4.0.0, and the equivalent method now is `clearResolutionCache()`. I forgot this method in the changelog, I have just added a line about it, thanks for reporting.
