### ISSUE TITLE
Ability to set the driver DesiredCapabilities

### ISSUE THREAD

**Issue by philipbannon** [bonigarcia/webdrivermanager#49]
Hi,

Maybe this is already possible but if not can we get a way to set the browsers DesiredCapabilities.... for instance

`
org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
proxy.setHttpProxy(PROXY)
     .setFtpProxy(PROXY)
     .setSslProxy(PROXY);
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability(CapabilityType.PROXY, proxy);
WebDriver driver = new FirefoxDriver(cap);
`

**Comment by bonigarcia** [comment]
This has to do with Selenium WebDriver. WebDriverManager only handles the binaries needed for Chrome, Opera, Marionette, and so on.

**Comment by philipbannon** [comment]
Ah ok cool thanks for getting back to em on that @bonigarcia 

So I can just setup my capabilities as per normal from the resulting driver?
