### ISSUE TITLE
403 error getting edge driver

### ISSUE THREAD

**Issue by gregma** [bonigarcia/webdrivermanager#499]
Description of the problem: Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1

Browser and version: Edge Version 42.17134.1098.0

Operating system: Windows 10 64 bits

WebDriverManager version: 3.8.1

WebDriverManager traces:

06-19-2020 01:56:52 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
06-19-2020 01:56:52 [main] DEBUG io.github.bonigarcia.wdm.Shell - Running command on the shell: [wmic, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', get, Version, /value]
06-19-2020 01:56:53 [main] DEBUG io.github.bonigarcia.wdm.Shell - Result: 
06-19-2020 01:56:53 [main] DEBUG io.github.bonigarcia.wdm.Shell - Running command on the shell: [wmic, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge Beta\\Application\\msedge.exe', get, Version, /value]
06-19-2020 01:56:53 [main] DEBUG io.github.bonigarcia.wdm.Shell - Result: 
06-19-2020 01:56:53 [main] DEBUG io.github.bonigarcia.wdm.Shell - Running command on the shell: [wmic, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe', get, Version, /value]
06-19-2020 01:56:53 [main] DEBUG io.github.bonigarcia.wdm.Shell - Result: 
06-19-2020 01:56:53 [main] DEBUG io.github.bonigarcia.wdm.Shell - Running command on the shell: [powershell, get-appxpackage Microsoft.MicrosoftEdge]
06-19-2020 01:56:54 [main] DEBUG io.github.bonigarcia.wdm.Shell - Result: Name              : Microsoft.MicrosoftEdge
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : Neutral
ResourceId        : 
Version           : 42.17134.1098.0
PackageFullName   : Microsoft.MicrosoftEdge_42.17134.1098.0_neutral__8wekyb3d8bbwe
InstallLocation   : C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.MicrosoftEdge_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
IsPartiallyStaged : False
SignatureKind     : System
Status            : Ok
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Detected Microsoft Edge version 42
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
06-19-2020 01:56:54 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Getting driver version for edge42 from online versions.properties
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Reading online version.properties to find out driver version
06-19-2020 01:56:54 [main] INFO  io.github.bonigarcia.wdm.WebDriverManager - Using msedgedriver 6.17134 (since Microsoft Edge 42 is installed in your machine)
06-19-2020 01:56:54 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Storing preference edge=42 (valid until 2020-06-20 01:56:54)
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Managing msedgedriver arch=64 version=6.17134 getLatest=false cache=false
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Checking if msedgedriver exists in cache
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.Downloader - Target path C:\Users\EQARunner2SVC/.m2/repository/webdriver
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by msedgedriver -- input list [C:\Users\EQARunner2SVC\.m2\repository\webdriver\chromedriver\win32\83.0.4103.39\chromedriver.exe, C:\Users\EQARunner2SVC\.m2\repository\webdriver\MicrosoftWebDriver\6.17134\MicrosoftWebDriver.exe] -- output list [] 
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 6.17134 -- input list [] -- output list [] 
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 64 -- input list [] -- output list [] 
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - msedgedriver not found in cache
06-19-2020 01:56:54 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
06-19-2020 01:56:54 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Storing preference edge42=6.17134 (valid until 2020-06-20 01:56:54)
06-19-2020 01:56:54 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Reading https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ to find out the latest version of Edge driver
06-19-2020 01:56:55 [main] ERROR io.github.bonigarcia.wdm.HttpClient - Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1
06-19-2020 01:56:55 [main] WARN  io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver 6.17134 (Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1) ... trying again using mirror
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Managing msedgedriver arch=64 version=6.17134 getLatest=false cache=true
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Checking if msedgedriver exists in cache
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.Downloader - Target path C:\Users\EQARunner2SVC/.m2/repository/webdriver
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by msedgedriver -- input list [C:\Users\EQARunner2SVC\.m2\repository\webdriver\chromedriver\win32\83.0.4103.39\chromedriver.exe, C:\Users\EQARunner2SVC\.m2\repository\webdriver\MicrosoftWebDriver\6.17134\MicrosoftWebDriver.exe] -- output list [] 
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 6.17134 -- input list [] -- output list [] 
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 64 -- input list [] -- output list [] 
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - msedgedriver not found in cache
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Using preferences true
06-19-2020 01:56:55 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Reading https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ to find out the latest version of Edge driver
06-19-2020 01:56:55 [main] ERROR io.github.bonigarcia.wdm.HttpClient - Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1
06-19-2020 01:56:55 [main] WARN  io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver 6.17134 (Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1) ... trying again using latest from cache
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Managing msedgedriver arch=64 version= getLatest=true cache=true
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Checking if msedgedriver exists in cache
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.Downloader - Target path C:\Users\EQARunner2SVC/.m2/repository/webdriver
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by msedgedriver -- input list [C:\Users\EQARunner2SVC\.m2\repository\webdriver\chromedriver\win32\83.0.4103.39\chromedriver.exe, C:\Users\EQARunner2SVC\.m2\repository\webdriver\MicrosoftWebDriver\6.17134\MicrosoftWebDriver.exe] -- output list [] 
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by  -- input list [] -- output list [] 
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - Filter cache by 64 -- input list [] -- output list [] 
06-19-2020 01:56:55 [main] TRACE io.github.bonigarcia.wdm.WebDriverManager - msedgedriver not found in cache
06-19-2020 01:56:55 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Reading https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ to find out the latest version of Edge driver
06-19-2020 01:56:55 [main] ERROR io.github.bonigarcia.wdm.HttpClient - Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1
06-19-2020 01:56:55 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver (latest version) (Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1)
io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 403 executing GET https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ HTTP/1.1
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:175) ~[webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.EdgeDriverManager.getDrivers(EdgeDriverManager.java:103) ~[webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:792) ~[webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.downloadAndExport(WebDriverManager.java:568) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:547) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:773) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:766) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260) [webdrivermanager-3.8.1.jar:?]
	at framework.DriverFactory.getDriver(DriverFactory.java:250) [test-automation-framework-2.2.8.jar:?]
	at tests.BaseTest.launchDriver(BaseTest.java:997) [BCBDTests-LOCALBUILD.jar:?]
	at tests.BaseTest.beforeSuite(BaseTest.java:704) [BCBDTests-LOCALBUILD.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) [testng-6.14.3.jar:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1049) [testng-6.14.3.jar:?]
	at org.testng.TestNG.run(TestNG.java:1017) [testng-6.14.3.jar:?]
	at org.testng.TestNG.privateMain(TestNG.java:1354) [testng-6.14.3.jar:?]
	at org.testng.TestNG.main(TestNG.java:1323) [testng-6.14.3.jar:?]

**Comment by bonigarcia** [comment]
Sorry, but as of WebDriverManager 4.0.0, only the Chromium-based versions of Edge (i.e., 75 and above) are supported.
