### ISSUE TITLE
Edge 44 doesn't work on 4.0.0

### ISSUE THREAD

**Issue by LaurensLeeuwis** [bonigarcia/webdrivermanager#502]
**Description of the problem**:
The built-in driver for Edge 44 is not used properly in 4.0.0, while it was in 3.8.1

**Browser and version**:
Edge 44

**Operating system**:
Windows 10, 64 bit (image from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ running in VirtualBox VM on Mac)

**WebDriverManager version**: 
4.0.0
(did work in 3.8.1)

**WebDriverManager use**: 
`WebDriverManager.edgedriver().setup();`

**WebDriverManager traces**: 
3.8.1

```
Jun 22, 2020 1:39:47 AM io.github.bonigarcia.wdm.WebDriverManager detectDriverVersionFromBrowser
INFO: Using msedgedriver pre-installed (since Microsoft Edge 44 is installed in your machine)
Jun 22, 2020 1:39:47 AM io.github.bonigarcia.wdm.WebDriverManager exportDriver
INFO: Exporting webdriver.edge.driver as C:\Windows\System32\MicrosoftWebDriver.exe
```

4.0.0

```
INFO: Please answer the following questionnaire based on your experience with WebDriverManager. Thanks a lot!
Jun 22, 2020 1:43:13 AM io.github.bonigarcia.wdm.WebDriverManager setup
INFO: ====> http://tiny.cc/wdm-survey <====
Jun 22, 2020 1:43:14 AM io.github.bonigarcia.wdm.WebDriverManager exportDriver
INFO: Exporting webdriver.edge.driver as C:\Users\IEUser\.m2\repository\webdriver\edgedriver\win64\x64\83.0.478.54\msedgedriver.exe
Starting MSEdgeDriver 83.0.478.54 (59fa2a2680c37e7ed7af1c9b07be6ec4aa9cda2a) on port 29090
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
```

Everything else in the environment was the same between both runs. Worked perfectly on 3.8.1, doesn't work on 4.0.0

**Comment by bonigarcia** [comment]
Sorry, but as of WebDriverManager 4.0.0, only the Chromium-based versions of Edge (i.e., 75 and above) are supported.

In any case, if your Edge is version 44, you should export the path of the driver as follows:

```
System.setProperty("webdriver.edge.driver", "C:\Windows\System32\MicrosoftWebDriver.exe");
```
