### ISSUE TITLE
Operadriver version 83 issue - not working with opera version 69.0. Getting error - org.openqa.selenium.SessionNotCreatedException: session not created: This version of OperaDriver only supports Opera version 83

### ISSUE THREAD

**Issue by cucumberQATester1428** [bonigarcia/webdrivermanager#505]
Operadriver version 83 issue - not working with opera version 69.0. Getting error - org.openqa.selenium.SessionNotCreatedException: session not created: This version of OperaDriver only supports Opera version 83
-------------
Snippet of browser navigation code :: 

                    if (System.getProperty("os.name").toLowerCase().contains("mac")) {
                        throw new WebDriverException(
                            "Your operating system does not support the requested browser");
                    }
                    WebDriverManager.getInstance(OperaDriver.class).version("68").setup();
                   
                    driver = new OperaDriver();
                    //WebDriverManager.operadriver().version("83").setup();
                    driver.manage().window().maximize();
                    driver.manage().deleteAllCookies();

--------------
Opera version - 69.0
Opera driver version - 83
Dependency  :   tried with version - 3.8.1 and 3.7.1
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.8.1</version>
        </dependency>

Getting below error  : 
 org.openqa.selenium.SessionNotCreatedException: session not created: This version of OperaDriver only supports Opera version 83
        (Driver info: operadriver=83.0.4103.97 (326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 1.10 seconds
      Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
      System info: host: 'XXXXX', ip: 'XXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
      Driver info: driver.version: OperaDriver

**Comment by bonigarcia** [comment]
Please use the latest version of WebDriverManager (4.0.0 at the time of this writing) and follow the template to report issues.

**Comment by cucumberQATester1428** [comment]
Updated WDM to 4.0.0 and worked fine
