### ISSUE TITLE
jenkins unable to run chromedriver on linux master

### ISSUE THREAD

**Issue by AJ198331** [bonigarcia/webdrivermanager#506]
Jul 01, 2020 1:46:35 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
13:46:35.889 [main] DEBUG io.github.bonigarcia.wdm.Shell - Running command on the shell: [google-chrome, --version]
13:46:36.168 [main] DEBUG io.github.bonigarcia.wdm.Shell - Result: Google Chrome 75.0.3770.142
13:46:36.170 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Getting driver version for chrome75 from online versions.properties
13:48:43.500 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - Error reading version.properties, using local instead
13:48:43.501 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 75.0.3770.140 (since Google Chrome 75 is installed in your machine)
13:48:43.502 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Storing preference chrome=75 (valid until 2020-07-02 13:48:43)
13:48:43.514 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Storing preference chrome75=75.0.3770.140 (valid until 2020-07-02 13:48:43)
13:48:43.515 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
13:50:50.861 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 75.0.3770.140 (Connect to chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/216.58.207.208] failed: Connection timed out (Connection timed out)) ... trying again using mirror
13:52:58.219 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 75.0.3770.140 (Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out (Connection timed out)) ... trying again using latest from cache
13:55:05.451 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - Exception reading http://npm.taobao.org/mirrors/chromedriver/LATEST_RELEASE to get latest version of chromedriver (Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out (Connection timed out))
13:57:12.686 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out (Connection timed out))
org.apache.http.conn.HttpHostConnectException: Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out (Connection timed out)
 at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
 at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)

**Description of the problem**: on local machine its runs fine it takes local charomedriver but on jenkins pipeline unable to run

**Comment by bonigarcia** [comment]
It seems there is some kind of connectivity problem in your Jenkins instance. Besides, it would be better using the latest version of WebDriverManager (4.0.0 at the moment of this writing).
