### ISSUE TITLE
Missing path to the integrated Microsoft Edge (windows-> systemapps)

### ISSUE THREAD

**Issue by passerby-afk** [bonigarcia/webdrivermanager#509]
**Description of the problem**: I'm using selenide to write my automation. As you may know, your library is used by it to automatically download the browser's driver. The problem appears with I try to run my automation using Edge browser. Since I'm using the Edge browser that's integrated in the Windows (c:\windows\systemapps\microsoft.microsoftedge_...\MicrosoftEdge.exe) I get the error message that it can't find the MSEdge.exe, which is correct, since you have in your code the paths to c:\program files\Microsoft\Edge\MSEdge.exe, respectively c:\program files(x86)\Microsoft\Edge\MSEdge.exe. This paths are valid if I were to use the new Edge based on chromium. This being said, may you please update the code in order to take the path of the Edge that comes integrated in Windows ? 

**Browser and version**: Microsoft Edge 44.19041.1.0

**Operating system**: Windows 10 x64

**WebDriverManager version**: 4.0.0

**WebDriverManager use**: ---

**WebDriverManager traces**: ---

**Error trace**:

**Comment by bonigarcia** [comment]
As of WebDriverManager 4, the support for Edge is limited to the Chromium-based version. In other words, the driver management for the legacy Edge browser is no longer supported, sorry.
