### ISSUE TITLE
Error downloading geckodriver 0.9.0

### ISSUE THREAD

**Issue by asoee** [bonigarcia/webdrivermanager#51]
when trying to use geckodriver 0.9.0, nothing gets downloaded.

This i caused by the json structure returned from 
https://api.github.com/repos/mozilla/geckodriver/releases
has an empty "name" attribute, for the latest 2 releases (0.9.0 and 0.10.0), and thus doesn't match the version string.

Suggestion: also look at the "tag_name" attribute, when filtering for version.

**Comment by roadrunner2** [comment]
Looks like this was fixed in commit 6d36242035c942f1de9cd075be9d4deb065a26fb, but unfortunately no new release has been made yet that includes that. Could we please get a new release?

**Comment by bonigarcia** [comment]
I've just released version 1.4.8 which solves the issue.
