### ISSUE TITLE
Add the ability to run offline

### ISSUE THREAD

**Issue by jpschewe** [bonigarcia/webdrivermanager#52]
It would be really nice if web driver manager would use the latest download when the test system does not have an internet connection. I frequently work on my code while not connected to the internet and this prevents me from doing that.

**Comment by atanaskanchev** [comment]
+1

**Comment by jpschewe** [comment]
I do see that if I specify an explicit version of the driver to be used, then testing offline works. However it would be nice to have a way to say download the latest driver if online, otherwise use the latest driver that's in the cache. If there isn't anything in the cache, then fail.

**Comment by bonigarcia** [comment]
Yes, it's a good idea. For the next version I will implement this feature (i.e. force to read cache if the system is offline).

**Comment by bonigarcia** [comment]
Implemented in version 1.4.9.
