### ISSUE TITLE
Session not created: This version of ChromeDriver only supports Chrome version 84

### ISSUE THREAD

**Issue by Nab3el07** [bonigarcia/webdrivermanager#520]
**Description of the problem**: 

**Browser and version**: 

**Operating system**: 

**WebDriverManager version**: 

**WebDriverManager use**: 

**WebDriverManager traces**: 

**Error trace**:

**Comment by roy-t** [comment]
Everyone in my team has the same issue. 

**Browser and version:** 84.0.4147.89 (Official Build) (64-bit) (cohort: Stable) 

**Operating system:** Windows 10 OS Version 1909 (Build 18363.959)

If I follow the suggestions here https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection I construct the following url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147 which points me to 84.0.4147.30 which is exactly the same version webdriver manager downloads.

```
[12:12:07] I/update - chromedriver: file exists C:\......\angular\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_84.0.4147.30.zip
[12:12:07] I/update - chromedriver: unzipping chromedriver_84.0.4147.30.zip
[12:12:07] I/update - chromedriver: chromedriver_84.0.4147.30.exe up to date
...
[12:12:29] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 84
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Windows NT 10.0.18363 x86_64)
```

So it looks like webdrivermanager is doing the right thing but there is a problem somewhere higher up the chain?

**Comment by bonigarcia** [comment]
To report properly an issue, please follow the template and fill all the information. In this issue, it is missing relevant information (e.g. WebDriverManager version and traces), so it's impossible to determine the cause.
