### ISSUE TITLE
ERROR webdriver: Request failed due to session not created: session not created: This version of ChromeDriver only supports Chrome version 83

### ISSUE THREAD

**Issue by repl-anjali-mer** [bonigarcia/webdrivermanager#525]
I am running tests in Mocha framework using javascript.
I have set up a Codepipeline and I am running tests in a docker.
My set up is as follows:
Chromedriver version : 84.0.4147.30
Chrome version: 84.0.4147.105
webdriverio: 5.18.6

In the codepipeline while running tests, I am facing the below issue:
 "ERROR webdriver: Request failed due to session not created: session not created: This version of ChromeDriver only supports Chrome version 83"

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
--
45 | System info: host: 'd6f11b78a39a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.181-108.257.amzn1.x86_64', java.version: '1.8.0_252'
46 | Driver info: driver.version: unknown

Can anyone help me with this?

**Comment by bonigarcia** [comment]
https://www.npmjs.com/package/webdriver-manager
