### ISSUE TITLE
Rename application.properties

### ISSUE THREAD

**Issue by atanaskanchev** [bonigarcia/webdrivermanager#53]
The configuration file `application.properties` name is rather confusing if you want quickily to identify it. Would it be possible to rename it to `webdrivermanager.properties`?

**Comment by bonigarcia** [comment]
WebDriverManager uses the [config](https://github.com/typesafehub/config) library (by Typesafe) to handle properties. The use of `application.properties` is one of the standard names for the configuration file. IMHO this is not that confusing.
