### ISSUE TITLE
Is the usage of a mirror possible?

### ISSUE THREAD

**Issue by hennr** [bonigarcia/webdrivermanager#56]
Hi and thanks for this project!

I tried to use a different [download source](https://npm.taobao.org/mirrors/phantomjs/) for the phantomjs binaries which fails due to hard wired code that works for the bitbucket source.

Do you know working mirrors for all the binaries?

if not: I played with the code and got the link scraping to work with [jsoup](https://jsoup.org/) instead of HtmlUnit (which failed to find all elements properly).
Are you in case fine with merging a PR with jsoup as another dependency?

**Comment by bonigarcia** [comment]
Hi, thanks to you for your contributions to the project.

Regarding the use of different sources, it is a good idea, since it would solve the 403 GitHub issue.

Your PR will be welcomed. To kill two birds with one stone, it could be cool if that PR also read the new download source. Thanks!

**Comment by bonigarcia** [comment]
Done. WebDriverManager 1.4.9 get rids of HtmlUnit by downloading PhantomJs binaries from the mirror.
