### ISSUE TITLE
WebDriverManager as Container (for windows) - Volume map works with ${PWD} instead of %cd%. 

### ISSUE THREAD

**Issue by PramodKumarYadav** [bonigarcia/webdrivermanager#560]
With latest docker desktop (or may be because of WSL2), the volumes can be mapped same as to linux and mac. So instead of three separate lines for mac, linux and windows, now you can use just put one line with volume mapped to ${PWD} instead of %cd%.

PS D:\WebdriverCI> docker run --rm -e BROWSER=chrome -e WDM_CHROMEVERSION=84 -e WDM_OS=WIN -v %cd%:/wdm bonigarcia/webdrivermanager:4.2.2
docker: Error response from daemon: create %cd%: "%cd%" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
PS D:\WebdriverCI> docker run --rm -e BROWSER=chrome -e 
WDM_CHROMEVERSION=84 -e WDM_OS=WIN -v **${PWD}:**/wdm bonigarcia/webdrivermanager:4.2.2
[INFO] Using WebDriverManager to resolve chrome
[DEBUG] Created new resolution cache file at /root/resolution.properties
[DEBUG] Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84 is 84.0.4147.30
[INFO] Using chromedriver 84.0.4147.30 (resolved driver for Chrome 84)
[INFO] Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[DEBUG] Driver to be downloaded chromedriver 84.0.4147.30
[INFO] Downloading https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_win32.zip
[INFO] Extracting driver from compressed file chromedriver_win32.zip
[DEBUG] Overriding former driver /wdm/chromedriver.exe
[INFO] Driver location: /wdm/chromedriver.exe
PS D:\WebdriverCI>

**Comment by bonigarcia** [comment]
Thanks for the hint. I added a comment about it in the README.
