### ISSUE TITLE
Does not check Program Files for Firefox

### ISSUE THREAD

**Issue by Pattern-Projects** [bonigarcia/webdrivermanager#563]
**Description of the problem**: 
When checking for installed firefox version, WebDriverManager appears to check twice in Program Files (x86), but not in 64's Program Files. It defaults to installing the latest driver.

**Browser and version**: 

**Operating system**: 
Windows 10

**WebDriverManager version**: 
webdrivermanager-4.2.2

**WebDriverManager use**: 
			//Manage Gecko Driver
			WebDriverManager.firefoxdriver().setup();
			String driverPath = WebDriverManager.firefoxdriver().getDownloadedDriverPath();		

**WebDriverManager traces**: 

[DEBUG] Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe', get, Version, /value]
[DEBUG] Result: 
[DEBUG] Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe', get, Version, /value]
[DEBUG] Result: 
[DEBUG] The driver version for Firefox is unknown ... trying with latest
[INFO] Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
[DEBUG] Driver to be downloaded geckodriver 0.27.0
[INFO] Downloading https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win32.zip
[INFO] Extracting driver from compressed file geckodriver-v0.27.0-win32.zip
[INFO] Exporting webdriver.gecko.driver as C:\Users\me\\.cache\selenium\geckodriver\win32\0.27.0\geckodriver.exe

**Error trace**:

**Comment by bonigarcia** [comment]
To avoid locale problems with the browser location in Windows, WebDriverManager reads environment variables. For Firefox, in the following order:

1. `PROGRAMFILES`
2. `PROGRAMFILES(X86)`

I suspect both envs points to the same folder in your machine (`C:\Program Files (x86)\`). If so, you need to the value of `PROGRAMFILES`.

**Comment by Pattern-Projects** [comment]
My environment variables look ok.
![image](https://user-images.githubusercontent.com/7268419/96857596-10b5eb00-1457-11eb-91be-60254bf57324.png)
I had someone run it on their system with the same result.
![image](https://user-images.githubusercontent.com/7268419/96857456-e8c68780-1456-11eb-90a2-dc9d052fb251.png)

**Comment by bonigarcia** [comment]
Could please confirm you are using the latest version of WebDriverManager (4.2.2)?

If so, to try to debug the issue, please run this code and share the results (it is a copy of the same calls used by WebDriverManager to read the program file envs):

```
public class DummyMain {

    public static void main(String[] args) {
        String programFilesEnv1 = System.getProperty("os.arch").contains("64")
                ? "PROGRAMFILES"
                : "PROGRAMFILES(X86)";
        System.out.println("programFilesEnv1 " + programFilesEnv1);

        String programFilesEnv2 = System.getProperty("os.arch").contains("64")
                ? "PROGRAMFILES(X86)"
                : "PROGRAMFILES";
        System.out.println("programFilesEnv2 " + programFilesEnv2);

        String programFiles1 = System.getenv(programFilesEnv1).replace("\\",
                "\\\\");
        System.out.println("programFiles1 " + programFiles1);
        String programFiles2 = System.getenv(programFilesEnv2).replace("\\",
                "\\\\");
        System.out.println("programFiles2 " + programFiles2);
    }

}
```

**Comment by Pattern-Projects** [comment]
I am using webdrivermanager-4.2.2-fat.jar. I have tried generating a fat jar also with the same result.
The result from DummyMain
```programFilesEnv1 PROGRAMFILES
programFilesEnv2 PROGRAMFILES(X86)
programFiles1 C:\\Program Files
programFiles2 C:\\Program Files (x86)

**Comment by bonigarcia** [comment]
I'm not sure what is happening at your end. The only explanation I find is that the value of the property `wdm.browserPath` (or its equivalent environmental variable, `WDM_BROWSERPATH`) is being defined. If you are using the fat jar, you can change this value as follows:

```
java -Dwdm.browserPath="C:\\Program Files\\Mozilla Firefox\\firefox.exe" -jar webdrivermanager-4.2.2-fat.jar firefox
```

**Comment by Pattern-Projects** [comment]
The issue was that the java applet was running with the incorrect java version. It was running on a version in Program File (x86). As you rightly put it, it was an issue on my side. Appreciate your time.
