### ISSUE TITLE
Mac OS Edge driver download fails with 404

### ISSUE THREAD

**Issue by skinox** [bonigarcia/webdrivermanager#573]
Description of the problem: Webdriver manager tries to download the wrong version for Edge that mismatches the current installed version and for different OS. Currently the last Edge 86 versions ends to 61, Driver Manager is trying to download 61 one, but I currently have 56

Browser version: Version 86.0.622.56 (Official build) (64-bit)

Operating system: Mac OS Catalina 10.15.4

WebDriverManager version: 4.2.2

WebDriverManager use:

```
case "edge":
                    WebDriverManager.edgedriver().setup();
                    driverPool.set(new EdgeDriver());
                    break;
```
WebDriverManager traces:
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using msedgedriver 86.0.622.61 (resolved driver for Edge 86)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://msedgedriver.azureedge.net/?restype=container&comp=list to seek msedgedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip
[main] INFO io.github.bonigarcia.wdm.cache.ResolutionCache - Clearing WebDriverManager resolution cache
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver 86.0.622.61 (Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip) ... trying again avoiding reading release from repository
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using msedgedriver 86.0.622.61 (resolved driver for Edge 86)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://msedgedriver.azureedge.net/?restype=container&comp=list to seek msedgedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver 86.0.622.61 (Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip) ... trying again using latest driver stored in cache
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using msedgedriver 86.0.622.61 (resolved driver for Edge 86)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://msedgedriver.azureedge.net/?restype=container&comp=list to seek msedgedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver 86.0.622.61 (Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip)
io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 404 executing https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/86.0.622.61/edgedriver_mac64.zip

**Comment by bonigarcia** [comment]
Maybe this is a temporary glitch in the edgedriver repository (perhaps due to some synchronization issue). I have just tried to download that version (86.0.622.61) for Mac and it is working. Can you try again?

**Comment by skinox** [comment]
Well, the Microsoft Edge browser version that I have is 86.0.622.56, but
driver is 86.0.622.61, could that be an issue?
I'm still unable to launch Edge on my Computer
I get this error:
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using msedgedriver
86.0.622.61 (resolved driver for Edge 86)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting
webdriver.edge.driver as
/Users/adjamalbek/.cache/selenium/msedgedriver/mac64/86.0.622.61/msedgedriver
dyld: Library not loaded: @rpath/libc++.dylib
  Referenced from:
/Users/adjamalbek/.cache/selenium/msedgedriver/mac64/86.0.622.61/msedgedriver
  Reason: image not found
Nov 04, 2020 9:08:27 PM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an
error: 134 (Exit value: 134)
  Given user logs in with url via "edge"                              #
com.gpstrackit.step_definitions.Login_Stage6_Step_Definitions.user_logs_in_with_url_via(java.lang.String)
      org.openqa.selenium.WebDriverException: Timed out waiting for driver
server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time:
'2018-11-14T08:17:03'
System info: host: 'Aidars-MacBook-Pro.local', ip:
'fe80:0:0:0:101a:8cdb:448f:98c4%en0', os.name: 'Mac OS X', os.arch:
'x86_64', os.version: '10.15.4', java.version: '14.0.2'
Driver info: driver.version: Driver

**Comment by skinox** [comment]
I found an issue, file "libc++.dylib" was not downloading for some reason,
I had to download it manually, after I placed it with WebDriver, everything
was working fine.
Thank you so much for your time and continued support.

**Comment by agpdl** [comment]
@bonigarcia this issue is still happening, the webdriver manager isn't downloading the libc++.dylib file, it can be fixed manually downloading the driver and doing a copy / paste of the file but it would be helpful if the file is downloaded automatically.

**Comment by gabrielrealcme** [comment]
![msedgedriver-issue](https://user-images.githubusercontent.com/58000600/103372458-1b68ae00-4aa0-11eb-8e37-ca5632700074.png)
Thank you all for the help - just a note for anyone else who is looking to solve this issue:
As mentioned by @skinox - you can see at the screenshot I provided -- you need to add both files to the corresponding path. Cheers!

**Comment by jamespizzurro** [comment]
@bonigarcia Could this issue be reopened or another one created for the "dyld: Library not loaded: @rpath/libc++.dylib" error referenced above? Manually downloading that file is a workaround, but it'd be great if this file could be downloaded automatically as part of this library to support macOS clients.

**Comment by bonigarcia** [comment]
@jamespizzurro I think that problem is different to the originally reported in this issue. Feel free to open a new one (please try to follow the issue template). I will look into it.
