### ISSUE TITLE
How to use getDownloadedDriverPath()?

### ISSUE THREAD

**Issue by Sourabh25** [bonigarcia/webdrivermanager#579]
Could you please tell me how to use the getDownloadedDriverPath()?

Thanks,
Sourabh

**Comment by bonigarcia** [comment]
This method is invoked after a driver has been resolved to find out the path of that driver. For instance, for chromedriver:

```
WebDriverManager.chromedriver().setup();
String driverPath = WebDriverManager.chromedriver.getDownloadedDriverPath();
```

**Comment by Sourabh25** [comment]
I am getting the below error:
The method getDownloadedDriverPath() is undefined for the type WebDriverManager

**Comment by bonigarcia** [comment]
Sorry there was a typo:

```
String driverPath = WebDriverManager.chromedriver().getDownloadedDriverPath();
```

**Comment by Sourabh25** [comment]
what was the typo? I could not see any difference. And I am still getting the same error.
