### ISSUE TITLE
--all command line option that installs all web drivers

### ISSUE THREAD

**Issue by damies13** [bonigarcia/webdrivermanager#581]
**Description of the problem**: 
Hi this is a feature request to add an --all option to webdrivermanager, the idea of this option would ideally be to install / upgrade the web drivers for all the browsers that are supported by the os, but if webdrivermanager need the browser installed then this option would install the web drivers for all the browsers that are installed.

I believe this would be useful in the automated setup of temporary test runner vm's that spun up for a test run and disposed of on completion of a test run, It would make my life easier so I don't need to check the os and then decide which browsers to ask webdrivermanager to install.

**Browser and version**: 
Any

**Operating system**: 
All

**WebDriverManager version**: 
Future version

**Comment by bonigarcia** [comment]
I don't see clear this feature. It that for WebDriverManager in CLI mode, right? I think this is equivalent to call to all the managers, using a shell script for instance:

java -jar webdrivermanager-4.2.2-fat.jar chrome

**Comment by damies13** [comment]
I installed webdrivermanager with pip, so I just run it as:
```
webdrivermanager chrome
webdrivermanager firefox
```
perhaps it call the java command in the background?

I guess I wasn't clear enough, so i'll attempt to clarify, the idea is if you ran
```
webdrivermanager --all
```
or I guess the java equivalent 
```
java -jar webdrivermanager-4.2.2-fat.jar --all
```

then webdrivermanager would check the OS it was running on (probably does this anyway) and installs the webdriver for Edge (windows) or Safari (Mac) and then installs the webdriver for Chrome if chrome is installed, Firefox if firefox is installed, etc for any other supported browsers.

I hope that makes it clearer

**Comment by bonigarcia** [comment]
Sorry but that is a different project:

https://github.com/rasjani/webdrivermanager
