### ISSUE TITLE
Update README - Gradle Dependency

### ISSUE THREAD

**Issue by Alken0** [bonigarcia/webdrivermanager#582]
**Description of the problem**: 

using testCompile is deprecated - use testImplementation instead

would be nice to update it for improved copy/pasting experience

**Browser and version**: 

**Operating system**: 

**WebDriverManager version**: 

**WebDriverManager use**: 

**WebDriverManager traces**: 

**Error trace**:

**Comment by bonigarcia** [comment]
Done.
