### ISSUE TITLE
Jenkins is starting the ChromDriver successfully by using io.github.bonigarcia.WebDriverManager dependency.  But it is unable to find the chrome binary.

### ISSUE THREAD

**Issue by senthilhere2019** [bonigarcia/webdrivermanager#598]
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
      [31morg.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'beu360', ip: '10.72.33.160', os.name: 'Linux', os.arch: 'amd64', os.version: '4.12.14-122.32-default', java.version: '1.8.0_252'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x55e128aef199 <unknown>

The OS which i am using is windows 10. But fetching the OS name as Linux.

Kindly help me on this .

BR
Senthil

**Comment by eliasnogueira** [comment]
@senthilhere2019 if the Jenkins is installed in a Linux machine/container the OS where WebDriverManager is trying to get the driver binary is correct. Does not matter if you are triggering the job using Windows 10 or any other SO.

The following is telling you that is no Google Chrome installed in the agent you are using in Jenkins
```
�[31morg.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
```

I have some tips for you:
* Try to use an agent/container that has Google Chrome installed
* Try to make sure you are let the WebDriverManager get the driver without you set explicitly it in your code
* Remove any hardcoded mention to Windows in your code.

It helps if you send a code snippet you are using, the SO Jenkins is using, and the Chrome version.

**Comment by srivenkatjyesta** [comment]
@senthilhere2019 Are you able to solve the issue ? 
I am also facing the same issue. Can you help me on this ?

**Comment by senthilhere2019** [comment]
Hey,

Yes I resolved this issue.

1.Check if Jenkins is installed on a Linux machine.
2.If it is a linux machine ,only the firefox browser will support in
headless mode.

Kindly let me know if you have any questions.

Thanks,
Senthilkumar.M

**Comment by srivenkatjyesta** [comment]
@senthilhere2019 I am using Windows 10 machine, and my jenkins has linux node.
As per your comments Firefox will work in my case as well ?

Can please connect me on LinkedIn ? at Sri Venkat Jyesta
