### ISSUE TITLE
How about adding Edge driver?

### ISSUE THREAD

**Issue by kermek** [bonigarcia/webdrivermanager#6]

**Comment by bonigarcia** [comment]
Good point.

In fact I started to analyse this feature recently. The problem with Microsoft Edge it that the binary for Selenium WebDriver is installed by means of a MSI file:

https://www.microsoft.com/en-us/download/details.aspx?id=48212

I am not sure if it is possible to automate this process from Java code. I will look into this as soon as possible.

Ideas and pull requests are welcome.

**Comment by bonigarcia** [comment]
Implemented in webdrivermanager 1.3.0.
