### ISSUE TITLE
Tests are failing for Chrome Browser version 88

### ISSUE THREAD

**Issue by abu112629** [bonigarcia/webdrivermanager#601]
Tests were failing today for me inspite of using the latest version available @bonigarcia. The chrome browser available in the server is version 88.

Version used as a dependency:

io.github.bonigarcia webdrivermanager 4.3.1
Please see below error :

org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 86
17:43:16 Current browser version is 88.0.4324.104 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
17:43:16 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'

**Comment by lbabich** [comment]
+1 I am experiencing the same issue my side, reinstalled dependencies but still getting this.

**Comment by bonigarcia** [comment]
Please follow the issue template to report any problem. Remember to include the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level. Otherwise, it is impossible to know what is happening.

**Comment by JackQL1119** [comment]
Same happening on version 89

**Comment by bonigarcia** [comment]
As I said, in order to trace a possible problem, a complete description of the problem (traces, version, etc) is needed. I'm closing this issue. If any of you are still experiencing some problem with the latest version of WebDriverManager, please open a new issue and follow the template to report it.
