### ISSUE TITLE
Better detection of the Browser-Version

### ISSUE THREAD

**Issue by mmoossen** [bonigarcia/webdrivermanager#608]
Hi,

first, let me thank you for the great idea and implementation.

i have one improvement suggestion for the way you do the browser version detection.

for instance:
https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/java/io/github/bonigarcia/wdm/managers/FirefoxDriverManager.java#L104

why not to add here a check for the standard environment variable `webdriver.firefox.bin`?

the background is that we do not install software in the standard locations. moreover, we have many versions of the same browser installed at the same time.

many thanks
Michael

**Comment by bonigarcia** [comment]
Thanks for the idea, but unfortunately I think it's not valid. The driver version is required to be resolved before the instantiation of the WebDriver object, and so, we cannot use that value.

**Comment by mmoossen** [comment]
Hi @bonigarcia, 

sorry, but i do not understand how the instantiation of the WebDriver object is related to my suggestion.
(i see the source code link i posted earlier is not correct any more. may be that is the reason of confusion.)

i mean the `getBrowserVersionFromTheShell` Method:
https://github.com/bonigarcia/webdrivermanager/blob/28cd41be83703d8fb06ba091399bc6d92f5ef642/src/main/java/io/github/bonigarcia/wdm/managers/FirefoxDriverManager.java#L104
here you use hard coded default installation locations, and you could check first the standard environment variable `webdriver.firefox.bin` (and the same for the other browsers):

        String envBin = System.getProperty("webdriver.firefox.bin");
        if (envBin != null) {
            // check the version of firefox in envBin
        } else {
            // do as before, checking for instance Program Files in Windows
        }

i know i could just manage the versions by myself, by using i.e. the additional EnvVar WDM_FIREFOXVERSION...

thanks
Michael
