### ISSUE TITLE
Use Proxy

### ISSUE THREAD

**Issue by Sebl29** [bonigarcia/webdrivermanager#61]
In my company, I wanna use webdrivermanager behind a proxy.

This is the issue, pull request will follow soon.

**Comment by craigburke** [comment]
@bonigarcia I'd love to see this merged as well so I can use it on my CI server. Awesome project, I'm getting a lot of use out of it. Thanks for all your work on it.

**Comment by bonigarcia** [comment]
I made some comments in PR #62. I'll merge it and release a new versions as far as these comments are met.

**Comment by bonigarcia** [comment]
This feature has been included in version 1.4.10, just released.
