### ISSUE TITLE
SAXParseException issue with <img> while using npm.taobao.org mirror 

### ISSUE THREAD

**Issue by clueo8** [bonigarcia/webdrivermanager#610]
When trying to use the https://npm.taobao.org/mirrors/chromedriver/ mirror, it appears to be failing on the parsing the img tag on their site since it doesn't have closing tag:

`<img alt="Fork me on GitHub" src="//s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png">`

```
[ERROR] mycompany.test.NewTest.beforeTest  Time elapsed: 19.998 s  <<< FAILURE!
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 7; The element type "img" must be terminated by the matching end-tag "</img>".
	at mycompany.test.NewTest.beforeTest(NewTest.java:33)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 7; The element type "img" must be terminated by the matching end-tag "</img>".
	at mycompany.test.NewTest.beforeTest(NewTest.java:33)
Caused by: org.xml.sax.SAXParseException: The element type "img" must be terminated by the matching end-tag "</img>".
	at mycompany.test.NewTest.beforeTest(NewTest.java:33)
```

If I try to manipulate their HTML myself and host it on my own local web server, there are a ton of other XML related errors because their HTML page doesn't close things like < hr >, < link >, < meta > or even their < head > tag!

How can I get this working correctly with the mirror site?

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using? I have just checked my tests against taobao and it is working properly for the latest version.

Besides, please follow the issue template to report any problem. Remember to include the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level. Otherwise, it is impossible to know what is happening.
