### ISSUE TITLE
Webdrivermanager giving issue

### ISSUE THREAD

**Issue by santanughatak** [bonigarcia/webdrivermanager#611]
> 
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>4.3.1</version>
            <scope>compile</scope>
        </dependency>

**Running on windows**
>[TestNG-PoolService-0] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_88 to get latest version of chromedriver (No such host is known (chromedriver.storage.googleapis.com))
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 88.0.4324.96 (resolved driver for Chrome 88)
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.cache.ResolutionCache - Clearing WebDriverManager resolution cache
[TestNG-PoolService-0] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 88.0.4324.96 (java.net.UnknownHostException: chromedriver.storage.googleapis.com) ... trying again avoiding reading release from repository
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 88.0.4324.96 (resolved driver for Chrome 88)
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-PoolService-0] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 88.0.4324.96 (java.net.UnknownHostException: chromedriver.storage.googleapis.com) ... trying again using latest driver stored in cache
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 88.0.4324.96 (resolved driver for Chrome 88)
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-PoolService-0] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 88.0.4324.96 (java.net.UnknownHostException: chromedriver.storage.googleapis.com)
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.UnknownHostException: chromedriver.storage.googleapis.com

**Running on Linux**
>[TestNG-PoolService-0] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE to get latest version of chromedriver (chromedriver.storage.googleapis.com: Name or service not known)
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.cache.ResolutionCache - Clearing WebDriverManager resolution cache
[TestNG-PoolService-0] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (java.net.UnknownHostException: chromedriver.storage.googleapis.com) ... trying again avoiding reading release from repository
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-PoolService-0] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (java.net.UnknownHostException: chromedriver.storage.googleapis.com) ... trying again using latest driver stored in cache
[TestNG-PoolService-0] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-PoolService-0] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (java.net.UnknownHostException: chromedriver.storage.googleapis.com)
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.UnknownHostException:

**Comment by clueo8** [comment]
Is chromedriver.storage.googleapis.com being blocked from your workstation (Corporate network)?  I know it was for me, so I'm trying to use the mirror, https://npm.taobao.org/mirrors/chromedriver/

Do you need to go through a proxy?  Try setting before your test, System.setProperty("wdm.proxy", "proxy.company.org:80");

**Comment by santanughatak** [comment]
@clueo8 - chromedriver.storage.googleapis.com look like its blocked and the mirror https://npm.taobao.org/mirrors/chromedriver/  is taking such long time that download got failed. Can't use webdriver-manager 👎
