### ISSUE TITLE
no support for sessionTimeout

### ISSUE THREAD

**Issue by sellem777** [bonigarcia/webdrivermanager#621]
webdriver-manager is missing the support for the sessionTimeout command line parameter that is supported by selenium.
would be useful to have the ability to add a -sessionTimeout XXXXX to the start command of webdriver-manager, that will in turn set it when running the selenium server and that will allow the control over the session lifespan.

**Comment by bonigarcia** [comment]
Wrong project, sorry: https://github.com/angular/webdriver-manager
