### ISSUE TITLE
Problem with WebDriverManager arch when using mvn command

### ISSUE THREAD

**Issue by diep-nguyen-hub** [bonigarcia/webdrivermanager#625]
In my project, I used:

`WebDriverManager.iedriver().clearDriverCache();`
`WebDriverManager.iedriver().arch32().setup();`

I expect that when I run previous code, the wdm will download the 32 bit version for IE to execute.
But when I run my scripts by using `mvn` command, wdm download the 64 bit version.
What is the solution for this issue ?

**Comment by bonigarcia** [comment]
I made a test about this and it is working nicely. Please use the latest version WebDriverManager. If the issue persists, open a new issue, but follow the template to report it (i.e., wdm version, traces, etc.). Otherwise it is impossible to make an analysis.
