### ISSUE TITLE
Linux：/root/.cache/selenium/chromedriver/linux64/90.0.4430.24/chromedriver: error while loading shared libraries: libxcb.so.1: cannot open shared object file: No such file or dire

### ISSUE THREAD

**Issue by lopingting** [bonigarcia/webdrivermanager#629]
**Description of the problem**: 

**Browser and version**: 

**Operating system**: 

**WebDriverManager version**: 

**WebDriverManager use**: 

**WebDriverManager traces**: 

**Error trace**:

**Comment by edumco** [comment]
@lopingting Could you please add some more info about the problem?

**Comment by bonigarcia** [comment]
Please follow the issue template for reporting any issue.
