### ISSUE TITLE
BUG for IE under Win10 x64 architecture

### ISSUE THREAD

**Issue by csnemeti** [bonigarcia/webdrivermanager#63]
Hi,

I discovered that using **InternetExplorerDriverManager**, no driver is downloaded.  I'm using Win10 on 64 bits.
The problem looks to be the `BrowserManager#filter(List<URL> list, Architecture arch)` method. Original list of drivers for IE contains the following:
`[http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_x64_2.53.1.zip, 
http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_x64_2.53.0.zip, 
http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip, 
http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.0.zip]`
First you filter for OS and you eliminate all urls that do not have in link the OS name (`win` in our case).
This means the first and second link are eliminated.
Second, you eliminate all those that have incorrect architecture (doesn't have `64` in our case). And you remain with an empty list. :-(

**Comment by bonigarcia** [comment]
Not happening in latest version of webdrivermanager.
