### ISSUE TITLE
error Parameter 'directory' is not a directory is recieved when trying to create edge driver

### ISSUE THREAD

**Issue by LiorUmflat** [bonigarcia/webdrivermanager#652]
**Description of the problem**: 

**Browser and version**: edge browser. my browser version is - 90.0.818.66 

**Operating system**: Windows 10, architecture 64 bits

**WebDriverManager version**: 4.4.3

**WebDriverManager use**: 
WebDriverManager.edgedriver().setup();
driver = new EdgeDriver();

**Error trace**: 
io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory

**Comment by bonigarcia** [comment]
It seems your in configuration file there is some configuration key missing, maybe `wdm.cachePath`. To solve the issue, I think you need to override all the available configuration keys.
