### ISSUE TITLE
Feature Request: Selenium 4 Beta Branch

### ISSUE THREAD

**Issue by nobleburgundy** [bonigarcia/webdrivermanager#664]
Is there a branch yet for pulling Selenium 4 beta that we can pull in?

**Comment by bonigarcia** [comment]
WebDriverManager can be used both with Selenium WebDriver 3 and 4. There you have some repo examples:

https://github.com/bonigarcia/webdrivermanager-basic
https://github.com/bonigarcia/selenium-webdriver-java
