### ISSUE TITLE
Fatal Error: getDriversFromXml

### ISSUE THREAD

**Issue by meintjesbekker** [bonigarcia/webdrivermanager#68]
System.setProperty("wdm.chromeDriverUrl", "https://npm.taobao.org/mirrors/chromedriver/2.24/");
ChromeDriverManager.getInstance().setup();
or 
System.setProperty("wdm.chromeDriverUrl", "https://npm.taobao.org/mirrors/chromedriver/");
ChromeDriverManager.getInstance().setup();

Fails with:
[Fatal Error] :18:7: The element type "img" must be terminated by the matching end-tag "</img>".
[Fatal Error] :18:7: The element type "img" must be terminated by the matching end-tag "</img>".
[Fatal Error] :18:7: The element type "img" must be terminated by the matching end-tag "</img>".

Should it be the case?

**Comment by bonigarcia** [comment]
This does not work since wdm uses the official [chromedriver storage](http://chromedriver.storage.googleapis.com/) to get the binary, not the [taobao mirror](https://npm.taobao.org/mirrors/chromedriver/).

Luckily for you, I decided to implement this feature (i.e., support this mirror for chromedriver downloads) as of version 1.4.10, just released.

**Comment by meintjesbekker** [comment]
Many thanks!

**Comment by meintjesbekker** [comment]
Thanks again for all your changes. I've tried it today, and it fails with:
Connected to the target VM, address: '127.0.0.1:57804', transport: 'socket'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Fatal Error] :18:7: The element type "img" must be terminated by the matching end-tag "</img>".
[Fatal Error] :18:7: The element type "img" must be terminated by the matching end-tag "</img>".
[Fatal Error] :18:7: The element type "img" must be terminated by the matching end-tag "</img>".

It seems to be the xml parser that gets confused with:
  <body>
    <a href="https://github.com/cnpm/cnpmjs.org" id="fork" target="_blank">
        <img alt="Fork me on GitHub" src="//s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png">
    </a>

I guess this is not part of your code. I'll try and debug it for you.
