### ISSUE TITLE
WDM doesn't work without docker-java depedency

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#691]
**Description of the problem**:
I want to exclude `docker-*` all dependencies because I never run browser in Docker:

```groovy
  api('io.github.bonigarcia:webdrivermanager:5.0.1') {
    exclude group: 'org.apache.httpcomponents.core5'
    exclude group: 'com.github.docker-java', module: 'docker-java'
    exclude group: 'org.rauschig'
  }
```

But I am receiving errors - despite the fact I don't use Docker. 
I think class `io.github.bonigarcia.wdm.WebDriverManager` should postpone initialisation of field `dockerService` until it's really needed.

**WebDriverManager version**:  5.0.1

**WebDriverManager call**:  `WebDriverManager.chromedriver().setup();`

**Error log**:
```
java.lang.NoClassDefFoundError: com/github/dockerjava/core/DockerClientConfig
	at io.github.bonigarcia.wdm.WebDriverManager.<init>(WebDriverManager.java:195)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.<init>(ChromeDriverManager.java:47)
	at io.github.bonigarcia.wdm.WebDriverManager.chromedriver(WebDriverManager.java:206)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.setupWebdriverBinary(ChromeDriverFactory.java:44)
```

**Comment by ssurwas** [comment]
true

**Comment by bonigarcia** [comment]
@asolntsev  Have you tested the PR? Is it working in your project with that change?

**Comment by lasnamae** [comment]
Yes, sure. I have tested the change. It works. :)

чт, 9 сент. 2021 г., 19:05 Boni García ***@***.***>:
