### ISSUE TITLE
Exception io.github.bonigarcia.wdm.config.webdrivermanagerexception java.net.UnknownHostexception npm.taobao.org while running in VM machine

### ISSUE THREAD

**Issue by sanoj-s** [bonigarcia/webdrivermanager#693]
Facing the below exception while using Webdriver Manager Version (3.7.1 and 4.3.1) and **_running it on a VM machine. No issues when executing on a local machine._** 

**_Exception in thread "main" io.github.bonigarcia.wdm.config.webdrivermanagerexception java.net.UnknownHostexception npm.taobao.org_**

**Comment by bonigarcia** [comment]
It seems a connectivity issue at your end. Nevertheless, those are old versions. Current version is 5.0.1.
