### ISSUE TITLE
WebdriverManager does not download the correct architecture for my Apple M1

### ISSUE THREAD

**Issue by iamlevik** [bonigarcia/webdrivermanager#697]
**Description of the problem**: 
The issue seems to be that whenever I auto download the Chromedriver, it chooses the Intel version rather than the ARM64 for M1 Chips. How can I ensure it downloads the correct architecture?

**Browser and version**: 
Version 93.0.4577.63 (Official Build) (arm64)

**Operating system**:   macOS Big Sur Version 11.5.2

**WebDriverManager version**:  5.0.1

**WebDriverManager call**: 

**WebDriverManager traces**: 
14:14:22.762 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Using automatically driver download
14:14:22.984 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using chromedriver 93.0.4577.15 (resolved driver for Chrome 93)
14:14:22.990 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/levi/.cache/selenium/chromedriver/mac64/93.0.4577.15/chromedriver

**Error log**:

**Comment by bonigarcia** [comment]
I wasn't aware about the ARM64 versions of chromedriver in Mac. I think it's the artifact which contains `m1` in the chromedriver repository:

https://chromedriver.storage.googleapis.com/index.html?path=93.0.4577.63/

I have just committed a patch to support it. Unfortunately I don't have a Mac to test it. Can you please test it your machine?

You should to bump WebDriverManager to 5.0.2-SNAPSHOT. This version (containing the last patch) is in the sonatype snapshots repositories. If using Maven, you also need to include the following:

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```
... its  equivalent in Gradle:

```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
```

To ensure you are using a fresh cache, you can invoke WebDriverManager as follows:

```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

To check that the patch is working, you should see that WebDriverManager is downloading the `m1` artifact, i.e.:

```
Downloading https://chromedriver.storage.googleapis.com/93.0.4577.63/chromedriver_mac64_m1.zip
```

**Comment by iamlevik** [comment]
![Screenshot 2021-09-09 at 23 35 23](https://user-images.githubusercontent.com/48520797/132758992-d4a89f9e-2f6e-4144-a4ac-0284da0e5bec.png)

**Comment by bonigarcia** [comment]
5.0.2-SNAPSHOT

**Comment by iamlevik** [comment]
![Screenshot 2021-09-10 at 00 04 08](https://user-images.githubusercontent.com/48520797/132762373-10206e96-909a-4dc9-a266-64b5bf0361c1.png)
Sorry, my bad, tired. 

@bonigarcia great job, works like a charm! You're a star!
