### ISSUE TITLE
cachePath()

### ISSUE THREAD

**Issue by AgingOrange** [bonigarcia/webdrivermanager#719]
`WebDriverManager.globalConfig().getCachePath()` isn't valid anymore and we have to use e.g. `WebDriverManager.chromedriver().config().getCachePath()` to get it. Is there another way to get the cache path from one location, instead of having to use the latter in each and every class that instantiates a different WebDriver?

**Comment by bonigarcia** [comment]
The second approach is the one supported in the latest versions of WebDriverManager.
