### ISSUE TITLE
Cannot upload files for browsers running in docker

### ISSUE THREAD

**Issue by sajithatharaka** [bonigarcia/webdrivermanager#726]
**Description of the problem**: When I try to perform file upload in SUT via the browsers running in docker, the file upload popup is not opening and neither accepts any files causing scripts to fail.

**Browser and version**: Safari

**Operating system**: Ran on docker

**WebDriverManager version**: v5.0.3

**Comment by bonigarcia** [comment]
Maybe you can try to mount a volume in the Docker container using the method `dockerVolume()` (see [doc](https://bonigarcia.dev/webdrivermanager/#advanced-configuration)).

**Comment by KentGu** [comment]
FYI, it looks like a selenium and has been fixed already.
https://github.com/SeleniumHQ/selenium/commit/a7102f2a54718f69e7755cd985e6bd4be3ec78b5

**Comment by bonigarcia** [comment]
This issue is related to #746, but it seems it is a limitation on the Selenium WebDriver API.
