### ISSUE TITLE
Chrome / Firefox erros to get the driver version

### ISSUE THREAD

**Issue by matheusm1789** [bonigarcia/webdrivermanager#727]
**Description of the problem**: The connection timeout error is returned when I try to run a simple test.
**Browser and version**: Chrome 94 or Firefox 93
**Operating** system: Mac OS
**WebDriverManager** version: v5.0.3

@Test
public void run_testing(){
    WebDriverManager.chromedriver().setup();
    WebDriver driver = new ChromeDriver();
    driver.get("http://www.google.com.br");
}

**io.github.bonigarcia.wdm.WebDriverManagerException: org.apache.http.conn.HttpHostConnectException: Connect to chromedriver.storage.googleapis.com:443**

I realized that I open **safari** or **edge** browsers and the application works as expected without any proxy setting.
But when I tried open **chrome** browser the **timeout error** was returned. I tried it using **firefox** and the **connection reset error** was returned.

My proxy is set using the Proxy Auto-Configuration (PAC).. I dont know if it can affect.. because safari and edge worked without any proxy instruction like: WebDriverManager.chromedriver().proxy("server:port").setup() 

@bonigarcia  could you help me? 

**NOTE**: I tried to run the same test from my personal computer using windows and worked as well for both browsers: Chrome and Firefox.

Thanks a lot.

**Comment by bonigarcia** [comment]
It seems to be a connectivity problem at your end. See [HTTP response code 403](https://bonigarcia.dev/webdrivermanager/#known-issues) in the doc.
