### ISSUE TITLE
Firefox driver is not working using webdrivermanager.  but if download manually the geckodriver driver and set it from root directory, work fine. 

### ISSUE THREAD

**Issue by jcordova** [bonigarcia/webdrivermanager#728]
**Description of the problem**: 

**Browser and version**: 

**Operating system**: 

**WebDriverManager version**: 

**WebDriverManager call**: 

**WebDriverManager traces**: 

**Error log**:

**Comment by niteshdl** [comment]
update gekodriver to manully to latest version 0.30.0 also update the firefox browesr version to latest 94.0.1. This solution helped me

**Comment by bonigarcia** [comment]
I don't understand your problem. Please follow the issue template to report your issue.
