### ISSUE TITLE
Unable to read the wdm.proxy value from Webdrivermanager.properties file through Intelij IDE only.

### ISSUE THREAD

**Issue by dineshkumarravi** [bonigarcia/webdrivermanager#729]
Hi .

wdm.proxy property shown as greyed out in properties file and unable to read the value from webdrivermanager.properties file , issue only in Intelij IDE, working fine in eclipse IDE(able to read the property)
![Intelij](https://user-images.githubusercontent.com/39761013/138385862-b309d524-13b5-475c-ab5e-f4c82365af98.JPG)
. please response if anybody knows the answer.

Thanks.

**Comment by bonigarcia** [comment]
I don't know, but I suppose this is something related to your IDE.
