### ISSUE TITLE
Option to set ChromeDriver port? 

### ISSUE THREAD

**Issue by brookslyrette** [bonigarcia/webdrivermanager#74]
Is there any way to set what port chromedriver will use? It seems to grab a random port, I'd like to fix it to a port that I know is not used in our build.

**Comment by bonigarcia** [comment]
This is actually a question of WebDriver in Java, not WebDriverManager. Anyway I think you look for something like this:

```
    int port = 8081;
    ChromeDriverService service = new ChromeDriverService.Builder().usingPort(port).build();
    WebDriver driver = new ChromeDriver(service);
```
