### ISSUE TITLE
getDownloadedDriverPath is null after calling setup

### ISSUE THREAD

**Issue by ibodog** [bonigarcia/webdrivermanager#744]
**Description of the problem**:  WebDriverManager getDownloadedDriverPath is null after calling setup.  I expected that to be set to the file system location of the driver after calling .setup()

**Browser and version**: tried with Chrome and Firefox

**Operating system**:  Windows 10 & Ubuntu Linux 20.04 (both Chrome & Firefox each)

**WebDriverManager version**:  5.0.0 and up
The problem does not happen in version 4.4.3.

**WebDriverManager call**:

        WebDriverManager.firefoxdriver().setup();
        System.out.println("*** " + WebDriverManager.firefoxdriver().getDownloadedDriverPath());

Outputs: *** null

**WebDriverManager traces**:  There does not appear to be any WebDriverManager traces

**Error log**:  My junit5 test fails on a null pointer when trying to use the downloaded driver path

**Comment by bonigarcia** [comment]
As of version 5, you need to use the same instance for that (see [doc](https://bonigarcia.dev/webdrivermanager/#advanced-settings)):

```
WebDriverManager wdm = WebDriverManager.firefoxdriver().setup();
wdm.setup();
System.out.println("*** " + wdm.getDownloadedDriverPath());
```

**Comment by jaluram01** [comment]
@bonigarcia I am using version 5.1.1 and I can see that above solution won't work as setup method is type of void.
Hence this will not be possible:
WebDriverManager wdm = WebDriverManager.firefoxdriver().setup();

So in this could you please let me know how to get getDownloadedDriverPath().

**Comment by AlexeyGirin** [comment]
Hi @jaluram01 we have the same issue. This is "peculiarity" of implementation - you have to wait after setup some time till manager extracts driver to target directory. During that process - driverpath is null.
