### ISSUE TITLE
Need binds on browser container

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/webdrivermanager#746]
**Description of the problem**: 
Currently with latest version 5.0.3, and since with selenium api 4.0 it seems that file upload required the file to be on the filesystem where the driver (chrome, etc..) is running, we need to be able to pass files via volume binds. It is currently only passing the volumes to the recording container, but I think it would make sense to also pass them to the browser container.

**Browser and version**: Chrome 95

**Operating system**: Mac OS , Linux

**WebDriverManager version**: 5.0.3

**WebDriverManager call**:  startBrowserContainer(...)

**WebDriverManager traces**:  Not apply
**Error log**: Not apply

**Comment by tyge68** [comment]
Actually I think the issue with the upload is more likely in the selenium api itself, it used to work in older version of webdriver manager (4.4.3 etc..) now with selenium 4.0 , if we use "driver.setFileDetector(new LocalFileDetector())" before using for example SelenideElement.uploadFile(...) helper method , it fails with following error
```
Caused by: UnsupportedCommandException: unknown command: unknown command: session/ad8f87656a14ba129df7d8faf083c6de/se/file

	at com.codeborne.selenide.ex.UIAssertionError.wrapToUIAssertionError(UIAssertionError.java:103)
```

**Comment by bonigarcia** [comment]
I'm reopening this issue since it seems relevant (at least, seems related to #726).

@tyge68 Can you please confirm if is it a limitation on the Selenium WebDriver API? Thanks.

**Comment by tyge68** [comment]
@bonigarcia indeed there is a limitation as the selenoid/vnc images are not using selenium server, instead it uses the original driver (chromedriver) directly, which uses a different endpoint for allowing to send files (it uses /file instead of /se/file that selenium guys implemented).

On my side I simply implemented an helper method for my IT tests (i.e an uploadFile(File, SelenideElement) which use the WedDriverManager api to access the docker container and then to use the docker-java api command to copy the file, of course if that is running locally (without the docker), it would simply use the SeleniumElement.uploadFile(...) as usual.


```
    private static final String REMOTE_PATH = System.getProperty("wdm.dockerRemotePath", "/home/selenium/Downloads");
    public static String copyFileToContainer(File from) {
        final File toUpload = new File(REMOTE_PATH, from.getName());
        WebDriverManager wdm = WebdriverSetupExtension.getWebdriverManager();
        String containerId = wdm.getDockerBrowserContainerId(WebDriverRunner.getWebDriver());
        DockerClient dockerClient = wdm.getDockerService().getDockerClient();
        dockerClient
                .copyArchiveToContainerCmd(containerId)
                .withHostResource(from.getAbsolutePath())
                .withRemotePath(REMOTE_PATH)
                .exec();
        return toUpload.getAbsolutePath();
    }
```

It could be nice eventually to add that copyFileToContainer helper method directly in the WebdriverManager or in any other place where it could be called for the current thread attached container.

There might be other ideas, or using the binding, but it would still need to have some "rewrite" logic I suppose as the local file system path will be unlikely the same in the docker container.

**Comment by Thibstars** [comment]
Volume binds are now implemented as well: https://github.com/bonigarcia/webdrivermanager/pull/745
