### ISSUE TITLE
Better Example Setting up 

### ISSUE THREAD

**Issue by skonthebass** [bonigarcia/webdrivermanager#75]
I'm using Gradle to build my project and my project is used to house selenium tests for our applications.  I'm not seeing how or where the drivers are put and I'm receiving the error "The path to the driver executable must be set by the webdriver.chrome.driver system property"

**Comment by bonigarcia** [comment]
I suppose you are calling to WebDriverManager in your code like this:

`ChromeDriverManager.getInstance().setup();`

By default, the chromedriver binary is stored in the path `~/.m2/repository/webdriver`. This path can be changed by tuning the value of the configuration key `wdm.targetPath`. More info [here](https://github.com/bonigarcia/webdrivermanager).

**Comment by skonthebass** [comment]
I believe i've got it working now, but I'm not using maven, using gradle
and eclipse.   I think i hadn't re-run gradle eclipse.
