### ISSUE TITLE
Proxy settings ignored when configuration programmatically

### ISSUE THREAD

**Issue by MaxCherry** [bonigarcia/webdrivermanager#751]
**Description of the problem**: 

When configurating i.e. chrome driver like the following:

`WebDriverManager.chromedriver()
                .proxy("myproxy:3128")
                .setup();`

underlying instances of` io.github.bonigarcia.wdm.online.HttpClient` and `io.github.bonigarcia.wdm.online.Downloader` are created without the expected proxy settings being set.

Call of setup() fails during WebDriverManager#getDriversFromXml with an UnknownHostException.

From my point of view, 

```
httpClient = new HttpClient(config);
downloader = new Downloader(httpClient, config, this::postDownload);
```

instances should not be created in the constructor of WebDriverManager, but in the setup method. Otherwise, underlying implementation of Apache's HttpClient remains uninitialized regarding proxy settings.

This issue does not occur when using -Dwdm.proxy=myproxy:3128 or by calling System.setProperty("wdm.proxy", "proxy:3128") in the first place. Instances of httpClient and downloader are then initialized properly.

**WebDriverManager version**: 
5.0.3

**WebDriverManager call**: 
`WebDriverManager.chromedriver()
                .proxy("myproxy:3128")
                .setup();`

**Comment by hjmwijnen** [comment]
Hi, thanks for noticing. I faced the same issue. Worked around it by setting: System.setProperty("wdm.proxy", proxy).

The original implementation was: WebDriverManager.chromedriver().proxy("http://" + proxy).setup();

**Comment by bonigarcia** [comment]
Thanks for reporting, I need some time to look into this issue. If I confirm the bug, I try to solve for the next version.

**Comment by bonigarcia** [comment]
I confirmed this bug. I have just submitted a patch that solved the issue. It will be available for next release.
