### ISSUE TITLE
Phantomjs 32-bit not found because of the name

### ISSUE THREAD

**Issue by lusche83** [bonigarcia/webdrivermanager#77]
The phantomjs Driver for 32bit is named like this: 
phantomjs-2.1.1-linux-i686.tar.bz2 
But in the BrowserManager.filter method only 'x86' is detected as 32 Bit system. There must also be a check for 'i686'. 

```
// Exception: 32 bits (sometimes referred as x86 or i686)
if (arch == Architecture.x32 && (url.getFile().contains("x86") || url.getFile().contains("i686"))) {
		continue;
}
```

**Comment by bonigarcia** [comment]
Thanks for reporting. It will be fixed in next version of wdm.
