### ISSUE TITLE
WebDriverManager is not working

### ISSUE THREAD

**Issue by svadivel0006** [bonigarcia/webdrivermanager#775]
**Description of the problem**: In Selenium C#, WebDriverManager is not downloading the old browser version drivers.

**Browser and version**: Chrome and V 86.0.4240.75

**Operating system**: Windows 10

**WebDriverManager version**: V 2.12.3

**WebDriverManager call**: 
new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig());

**WebDriverManager traces**: 

Message: 
System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 86.0.4240.75 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

**Error log**: 
  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeOptions options)
ChromeDriver.ctor()

Error Message:
![Error Message](https://user-images.githubusercontent.com/85741928/149607005-f5b8a272-0728-4aa2-9567-323ea4584ae7.png)

CodeBase:
![CodeBase](https://user-images.githubusercontent.com/85741928/149607012-159b83f0-2b55-43d7-934c-5d4b416bbb89.png)

Chrome Installed Version:
![Chrome Installed Version](https://user-images.githubusercontent.com/85741928/149607026-e0a17fd6-f9b2-4625-a7df-7bdbcd887c45.png)

Chrome Driver not found:
![Chrome Driver not found](https://user-images.githubusercontent.com/85741928/149607031-76a3563e-81bd-4090-9e8d-17565fd7679e.png)

**Comment by bonigarcia** [comment]
I think you mean this project:

https://github.com/rosolko/WebDriverManager.Net

**Comment by fizzajawed** [comment]
I am getting the same issue, webdriver manager is not downloading old browser versions
![image](https://user-images.githubusercontent.com/97277754/200044999-becdd054-3b2a-4008-ab06-ced71892abd7.png)


Can anyone help me fixing this ?

**Comment by Abhijith1190** [comment]
Hi @bonigarcia , I am still facing this issue. 
this is how my code looks like. 
![MicrosoftTeams-image (28)](https://github.com/bonigarcia/webdrivermanager/assets/8774768/8131f4fb-b3db-406c-a1e6-3d4220457b79)

Duration: 2.3 sec
Message: 
System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 113.0.5672.127 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

 

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeOptions options)
ChromeDriver.ctor()
Selenium.Setup() line 24
--TearDown
Selenium.TearDown() line 30


Please help!! 
Thanks in advance

**Comment by Abhijith1190** [comment]
> I am getting the same issue, webdriver manager is not downloading old browser versions ![image](https://user-images.githubusercontent.com/97277754/200044999-becdd054-3b2a-4008-ab06-ced71892abd7.png)
> 
> Can anyone help me fixing this ?

Were you able to fix this issue?
