### ISSUE TITLE
Provide possibility to get drivers from Maven repositories

### ISSUE THREAD

**Issue by wheleph** [bonigarcia/webdrivermanager#78]
In corporate environments it's not always possible or desirable to download drivers directly from remote locations due to security restrictions.

Although WebDriverManager provides possibility to override the _location_ of the driver, it is not flexible in the _structure_ of the storage. Which means that to be able to use it out of the box one needs to mimic Github, Amazon, etc within a private network.

It would be great to have possibility to fetch drivers from Maven repositories because those can easily be hosted within private networks (Nexus, Artifactory).

**Comment by bonigarcia** [comment]
This is out of the scope of wdm.
