### ISSUE TITLE
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download chromedriver 98.0.4758.80

### ISSUE THREAD

**Issue by amir-gauss** [bonigarcia/webdrivermanager#781]
Hi mr. @bonigarcia 

I use DriverManager in my project with this specification:

Browser and version: Chrome Browser : 98.0.4758.80

Operating system: Windows 10 64 Bit

WebDriverManager version: 5.0.3

In my project  WebDriverManager API used like this : 
`WebDriverManager.chromedriver().useMirror().setup();`

but get this error : 
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download chromedriver 98.0.4758.80

I get all TRACE Log:
[TRACE.log](https://github.com/bonigarcia/webdrivermanager/files/8010486/TRACE.log)

please help me how to resolve this problem

_Originally posted by @amir-gauss in https://github.com/bonigarcia/webdrivermanager/issues/521#issuecomment-1030854145_

**Comment by bonigarcia** [comment]
Thanks for reporting. I have confirmed that there is a problem with `.useMirror()`. It seems the layout of the mirror page has changed, and as a result, this feature has stopped working. So far, the workaround is avoid using it, as follows:

```
WebDriverManager.chromedriver().setup();
```

I will fix this issue for the next version of WebDriverManager. Stay tuned if you still need that feature.

**Comment by rugbyRoad** [comment]
Yes, I have the same problem.  Thanks for your help.

**Comment by amir-gauss** [comment]
Thanks for your attention @bonigarcia

**Comment by JackQL1119** [comment]
Anyone else having issues with chrome 98 when clearing input fields with Keys.chord(Keys.CONTROL+"a+Keys.DELETE) ?

It adds a special character  after clearing field

I had to downgrade to chrome 97 to resolve this issue, hopefully when google release 99 it will be solved.

**Comment by DG606** [comment]
Hi, I have same Problem wihr Keys.chord issue. Also with BACKSPACE.. Same Problem wiht geckodriver.
My temporary Solution I set WebDriverManager.chromedriver().driverVersion("97.0.4692.71").setup(); works with installed Chrome 98.0.4758.82 too. I hove so release 99 will be fix this Problem.

**Comment by bonigarcia** [comment]
I have just committed a patch that should solve this issue. It will be available for the next, to be released soon.
