### ISSUE TITLE
Running jar artifact packaged with intellij with webdrivermanger maven dependency throws error on run

### ISSUE THREAD

**Issue by kevinthegreat1** [bonigarcia/webdrivermanager#791]
**Description of the problem**: Running a jar artifact with ```java -jar PathToJar``` packaged with IntelliJ with the following dependencies in pom.xml

```
  <dependencies>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.6.2</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>4.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>4.1.2</version>
        </dependency>
    </dependencies>
```
throws
```
Error: Could not find or load main class MainClassName
Caused by: java.lang.ClassNotFoundException: MainClassName
```
<hr>
The jar is packaged through intellij through the following procedure

```File -> Project Structure -> Artifacts -> + -> JAR -> From modules with dependencies -> Select main class -> Ok -> Ok -> Ok```

The jar is built with

```Build -> Build Artifacts -> Build```
<hr>

- The program runs fine on dev mode
- This problem persists if the dependency is in pom.xml and there are no usages in code.
- This problem goes away when the dependency is removed from pom.xml.
- This issue exists in webdrivermanager versions 5.1.0 and 5.0.3
- This issue does not exist in version 4.4.3

**Github repository of full project is [here](https://github.com/kevinthegreat1/Auto-Ruvna)**
<hr>

**Browser and version**: Chrome version 98.0.4758.102 (Official Build) (x86_64)  and chromedriver 98

**Operating system**: OSX Big Sur Version 11.1 Intel 64 bits

**WebDriverManager version**: 5.1.0 (newest version)

**WebDriverManager call**: ```WebDriverManager.chromedriver().setup();```

**WebDriverManager traces**: 

**Error log**:

**Comment by bonigarcia** [comment]
I'm sorry but I don't have any clue about this issue.
