### ISSUE TITLE
Detect Chrome version 98.0.4758.102 but download 98.0.4758.80

### ISSUE THREAD

**Issue by amir-gauss** [bonigarcia/webdrivermanager#793]
Hi @bonigarcia 

wdm detect Chrome version 98.0.4758.102 but download 98.0.4758.80

`WebDriverManager.chromedriver().useMirror().setup()`
JDK 13
Output of -Dorg.slf4j.simpleLogger.defaultLogLevel=TRAC

[TRACE-21-2-2022.txt](https://github.com/bonigarcia/webdrivermanager/files/8110452/TRACE-21-2-2022.txt)

**Comment by Azohba** [comment]
I have the same issue but a little bit different. I have 98.0.4758.102 64x version but wdm detect 98.0.4758.80 and wdm couldn't find 98.0.4758.80x64 version. Help for the issue please

**Comment by bonigarcia** [comment]
WebDriverManager downloads the proper driver version for the browser major version. See for instance this [doc](https://chromedriver.chromium.org/downloads) for chromedriver.
