### ISSUE TITLE
org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:22586

### ISSUE THREAD

**Issue by SharmaKKamal** [bonigarcia/webdrivermanager#794]
Hi @bonigarcia 
**Not able to launch firefox driver using gecko driver downloaded using webdriver manager**: 

**Browser and version**: Firefox 97.0

**Operating system**: Mac OS (os.arch = x86_64)

**WebDriverManager version**: 5.0.2

**WebDriverManager call**: WebDriverManager.firefoxdriver().setup();

**WebDriverManager traces**: 20:10:35.522 [main] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file geckodriver-v0.30.0-macos-aarch64.tar.gz
20:10:35.666 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Bypass notarization requirement for geckodriver on Mac OS
20:10:35.666 [main] DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [xattr, -r, -d, com.apple.quarantine, /var/folders/bv/9z5dl3h53f32pp0vnl8r1n3m0000gp/T/3415470038909163802/geckodriver]
20:10:36.536 [main] DEBUG io.github.bonigarcia.wdm.versions.Shell - Result: 
20:10:36.544 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as /Users/kamal/.cache/selenium/geckodriver/mac64/0.30.0/geckodriver
20:10:58.019 [main] ERROR com.ig.paqman.utils.ReportHandler - Error when logging failure/skip results: 

org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:10112
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'MB-101162.local', ip: '2401:4900:47f3:789c:b505:134:811d:46bd%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_271'
Driver info: driver.version: FirefoxDriver

**Finding**: Webdriver manager downloading "geckodriver-v0.30.0-macos-aarch64.tar.gz" driver for Mac OS(arch x86_64) intel chip machine. Manually I have verified the same version driver and causing same issue.

I think for Mac OS(arch x86_64) intel chip machine, we need to download "geckodriver-v0.30.0-macos.tar.gz".

**Comment by bonigarcia** [comment]
I think this should be fixed in the latest version of WebDriverManager. If not, please reopen this issue.
