### ISSUE TITLE
WebdriverDecorator throws IllegalArgumentException when safari webdriver instance instatiated using webDriverManager is passed

### ISSUE THREAD

**Issue by NayanaGopinath** [bonigarcia/webdrivermanager#807]
After  instantiating driver object by
`String browsername = "Safari";
WebDriverManager.getInstance(browsername).create();
`
```
public static ThreadLocal <WebDriver> driver_thread = new ThreadLocal <>();
WebDriverListener listener = new BaseListener();
driver_thread.set(new EventFiringDecorator(listener).decorate(driver));
```
throws the below exception
`java.lang.IllegalArgumentException: WebDriver must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:59)
at org.openqa.selenium.support.decorators.WebDriverDecorator.decorate(WebDriverDecorator.java:187)`

Expected Result
Should be able to create decorators of the safari driver instance. The same working with rest of the driver instances.

Browser and version : Safari  - Version 14.0.3 (16610.4.3.1.7)
OS -: Mac OS Big Sur -11.2.3
WebDriverManager version -5.1.0

**Comment by samagarw** [comment]
Getting similar exception . 

Its downloading the latest version of Safari Driver but not able run on that browser .

**Comment by bonigarcia** [comment]
I don't understand this issue. Please, follow the issue template to report all the information. Otherwise it is imposible to understand or trace the problem.

**Comment by bonigarcia** [comment]
Not sure about this. In any case, to control Safari with Selenium WebDriver, you don't any driver to be downloaded. In other words, WebDriverManager is not necessary. In any case, remember you need to configure Safari manually to authorize remote automation. To that aim, first, use  the menu option Safari → Preferences → Advanced tab. Then, enable the “Show Develop Menu” checkbox. After that, the “Develop” menu should appear, and you should click on “Allow Remote Automation”.
