### ISSUE TITLE
Add java version support 

### ISSUE THREAD

**Issue by ripper2hl** [bonigarcia/webdrivermanager#81]
java.lang.UnsupportedClassVersionError: io/github/bonigarcia/wdm/ChromeDriverManager : Unsupported major.minor version 51.0
 :cry:

**Comment by hennr** [comment]
Seems like you are still on java < 7 there. Update to at least java 7 and you should be fine.

**Comment by ripper2hl** [comment]
yep, but i recommend put this on documentation, otherwise i don't find this in documentation, nice project

**Comment by bonigarcia** [comment]
Included a note about the required Java version in README.
