### ISSUE TITLE
Remote noVNC

### ISSUE THREAD

**Issue by marstona** [bonigarcia/webdrivermanager#816]
Is it possible to connect noVNC from remote pc? Because i still have same error when try to access.
![novnc](https://user-images.githubusercontent.com/7075723/163404302-c93be80a-181e-4761-8330-fc23da2b0c4f.png)

**Comment by bonigarcia** [comment]
Please follow the issue template (including the WebDriverManager traces) to report your problem. Otherwise, it is impossible to know anything about it.
