### ISSUE TITLE
ClassNotFoundException when including WebDriverManager in build.gradle

### ISSUE THREAD

**Issue by matintokyo** [bonigarcia/webdrivermanager#819]
Hi, I am facing the following issue:

After building a "fat" jar containing all dependencies, including WebDriverManager, for my program,
I get the following error when trying to run the jar, using java -jar myprogram-uber.jar

```
Error: Could not find or load main class MainApp
Caused by: java.lang.ClassNotFoundException: MainApp
```

This did not happen until I add the WebDriverManager dependency to my dependencies in build.gradle.
When removing the WebDriverManager dependency  from build.gradle, I can run my program again without issues.

Attaching build.gradle file:
[build.gradle.txt](https://github.com/bonigarcia/webdrivermanager/files/8522418/build.gradle.txt)

The "MainApp" class which is not found is directly under src/main/java/ as specified using mainClassName = "MainApp"

Note that I can run the program with gradle's run task without issues.
Could this an issue with WebDriverManager itself?

**Browser and version**:  Chrome 100.0.4896.127 (Official Build) (64-bit)

**Operating system**:  reproduced issue on both on Ubuntu 21.04 and Windows 10

**WebDriverManager version**:  5.1.1

**Error log**: 
java -jar .\myprogram.jar
output:
Error: Could not find or load main class MainApp
Caused by: java.lang.ClassNotFoundException: MainApp

Thank you

**Comment by bonigarcia** [comment]
No clue, but this does not seem to be caused by WebDriverManager.

**Comment by abaldwin-op** [comment]
I'm experiencing this too. Will post solution once I figure it out.

**Comment by abaldwin-op** [comment]
@matintokyo @bonigarcia --

https://github.com/docker-java/docker-java/issues/1098#issuecomment-487161247

>The reason was that the library's signature files were copied into the META-INF of my fat jar and it broke class loading of my main class. Here is the fix:

```
    jar {
        ...
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
        ...
    }
```

---

You can verify **docker-java** is the culprit by adding the below _instead_ of the exclude, then running [successfully]:

```
    implementation  group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.2.1', {
        exclude group: 'com.github.docker-java', module: 'docker-java'
    }
```

**Comment by matintokyo** [comment]
@abaldwin-op 

Thank you for taking the time to share this! Adding the exclude in the build.gradle indeed solves the original error. ("Error: Could not find or load main class"). I however get the following new error:

`Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.tar.TarArchiveInputStream`

It is triggered by the following code:

`WebDriverManager.chromedriver().setup();`

Your kind help on understanding why this is happening would be greatly appreciated!

**Comment by matintokyo** [comment]
@abaldwin-op

Sorry I had misunderstood that the fix was to exclude from the gradle dependency section, rather than from jar build task.
Including the below in my uberJar build task solved the issue.

`   jar {
        ...
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
        ...
    }`
