### ISSUE TITLE
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0

### ISSUE THREAD

**Issue by beluha** [bonigarcia/webdrivermanager#824]
**io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0**: 

**Firefox 99.0.1 (64-bit)**: 

**Windows 10 Enterprise 64 bits**: 

**WebDriverManager version 5.1.1**: 

**WebDriverManager.firefoxdriver().setup()**: 

**WebDriverManager traces**: 

**Stack Trace:
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1306)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1089)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1322)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1299)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1089)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:396)**: 

Hi, I'm getting error in my project. I checked information about latest geckodriver version in the https://github.com/mozilla/geckodriver/releases, but there is only 0.30.0 (2021-09-16, d372710b98a6) version. Latest geckodriver 0.31.0 is in different mirror https://www.nuget.org/packages/Selenium.WebDriver.GeckoDriver/0.31.0 and https://www.nuget.org/packages/Selenium.WebDriver.GeckoDriver.Win64/0.31.0.

Can you please fix this and most important - provide workaround because of blocking issue?

**Comment by beluha** [comment]
Geckodriver 0.31.0 has been released couple mins ago in official site https://github.com/mozilla/geckodriver/releases and now it's working, no errors.

**Comment by tsoyaleksey** [comment]
Still valid.. we also observe such issue while trying to instantiate a FF driver. We have almost the same configuration as author.

**Comment by beluha** [comment]
Hi @tsoyaleksey, sorry for the late response.
Do you still have this issue? I can check it in August only in my env.

**Comment by tsoyaleksey** [comment]
> Hi @tsoyaleksey, sorry for the late response. Do you still have this issue? I can check it in August only in my env.

@beluha we do have. Could you please add any details on how you've solved the issue?

**Comment by beluha** [comment]
@tsoyaleksey , I remember that all I did I just ran my test script in debug mode and observed that required URL to download the geckodriver became correct past couple hours and required version of webdriver downloaded. that happened without any fixes and workarounds.

Now I debugged code a little bit and see that first of all this url should be accessible for you https://api.github.com/repos/mozilla/geckodriver/releases. Open it in browser. There is a first object [0] referencing to the latest version of geckodriver.

For more details you can debug code setting breakpoint in these 2 classes:
- io.github.bonigarcia.wdm.WebDriverManager - method String download(String driverVersion)
- io.github.bonigarcia.wdm.online.UrlHandler - watch the candidateUrls variable.

Verify that file /webdrivermanager.properties has the following properties:
- wdm.geckoDriverUrl=https://api.github.com/repos/mozilla/geckodriver/releases
- wdm.geckoDriverMirrorUrl=https://registry.npmmirror.com/-/binary/geckodriver/
- wdm.geckoDriverExport=webdriver.gecko.driver

Now I use latest version of FF 102.0.1 (64-bit) and webdrivermanager 5.2.3. Unfortunately I can't help you, because I cannot reproduce this issue anymore. At the same time I can say that running script in debug mode (with some delay between code lines) fixed couple issues with downloading incorrect version of FF before. I assume it looks like wdm configures env and tries to download webdriver simultaneously without confirming that new configs are in place (that delay in debug mode allows to things to be done, to complete required configs). Maybe there is a bug which is not easy to detect.
