### ISSUE TITLE
Chrome Driver not initialized

### ISSUE THREAD

**Issue by theautomationtesterx** [bonigarcia/webdrivermanager#827]
I have tried using this dependency
<dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.1.0</version>
        </dependency>
and code as

 WebDriverManager.chromedriver().setup();
    WebDriver driver = new ChromeDriver();

but I'm getting error as below, Couldn;t find what the exact issue is

[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Error reading commands.properties, using local instead
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_101 to get latest version of chromedriver (Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/142.250.189.144] failed: Connection timed out: connect)

**Comment by bonigarcia** [comment]
It seems a connectivity issue at your end.
