### ISSUE TITLE
Resolving driver for Selenium Grid that is already running

### ISSUE THREAD

**Issue by jacattau** [bonigarcia/webdrivermanager#828]
I am looking at the examples of how to resolve drivers on Selenium grid.  We have a Hub/Node setup already running for us and I think this is maybe where my issue lies.  I am not starting a grid on demand like the examples show.  What I am trying to do is modify a batch file on the nodes so that it will start instances of Chrome but we don't have to manually update the Chromedriver for each new version.  Current batch file I am attempting to try is this:

```
java -jar "C:\Selenium\BatchFiles\selenium-server-standalone-3.141.59.jar" -log d:\seleniumlog.txt -host %COMPUTERNAME%.corporate.company.com -role node -hub http://server.company.com:21002 -browser browserName=chrome,maxInstances=5
PAUSE
```

For the driver creation, I am trying:
```
WebDriverManager.chromedriver().setup()
        def remoteDriver = WebDriverManager.chromedriver().remoteAddress("https://OHCIMXDSGM1P.corporate.company.com:3266/wd/hub").create()
```

This doesn't seem to be working.  What I don't have is this line from the example because our grid and nodes are already running:
```
 // Start Selenium Grid in standalone mode
        Main.main(new String[] { "standalone", "--port", "4444" });
```

So I'm thinking either 1) this isn't possible with this setup or 2) I'm missing something in the node batch files perhaps.  I don't think my driver creation code is wrong considering it's only 2 lines, but I could be wrong.

**Comment by bonigarcia** [comment]
For me better understanding, drivers should be known by the hub at startup. The [WebDriverManager doc](https://bonigarcia.dev/webdrivermanager/#selenium-grid) shows a couple of example about how WebDriverManager can help with this: 1) using the CLI. 2) Using the Java API.
