### ISSUE TITLE
WebDriverManager for Selenium Grid downloading wrong arch

### ISSUE THREAD

**Issue by jacattau** [bonigarcia/webdrivermanager#838]
I have the WebDriverManager jar file on our selenium grid and I have it working to download the drivers, however our Windows OS is on x64 and the WebDriverManager keeps downloading x32.  This seems to work fine for Chrome but geckodriver is not liking this at all.  Is there a way I can force it to download the 64-bit arch?  I looked through documentation and I don't see a way to do this with the jar file.

**Comment by hiep2fooder** [comment]
Nguu

**Comment by bonigarcia** [comment]
I suppose you need something like this:

```
java -Dwdm.architecture=X64 -jar wdm.jar
```

See [doc](https://bonigarcia.dev/webdrivermanager/#advanced-configuration).
