### ISSUE TITLE
While using the latest version of WebDriverManager, the driver object is gettting closed automatically without using driver.quit() function

### ISSUE THREAD

**Issue by sprahul333** [bonigarcia/webdrivermanager#839]
**Description of the problem**:  Browser should not be killed unless and until you use quit()

**Browser and version**: Chrome Browser (v102)

**Operating system**: Windows

**WebDriverManager version**: 5.1.0 and above

**WebDriverManager call**: WebDriverManager.chromedriver.create();

**WebDriverManager traces**: No Traces 

**Error log**: 

Attaching the screenshot for more INFO: 
![image](https://user-images.githubusercontent.com/20122410/170911068-2d84175a-6aab-4515-ac6d-6e1122864397.png)

**Comment by bonigarcia** [comment]
As of version 5.2.1, just released, I added a new method in the WebDriverManager API to avoid the default behavior:

```
WebDriver driver = WebDriverManager.chromedriver().avoidShutdownHook().create();
```

As explained in the [doc](http://localhost:8080/#advanced-configuration), this API method is equivalen to the configuration key `wdm.avoidShutdownHook`.
