### ISSUE TITLE
Getting SSL exception while using WebdriverManager

### ISSUE THREAD

**Issue by seleniumLearner1** [bonigarcia/webdrivermanager#84]
Hi,
I have added maven dependancy for webdrivermanager and following steps as mentioned in Github.
However when following line of code is excuted:

ChromeDriverManager.getInstance().setup();

It throws following exception:
[31mjava.lang.RuntimeException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
      	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:284)
      	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:108)
      	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:87)

It looks like it is related to proxy settings as I am working on company's computer.
Can someone please help me with it.

Thanks.

**Comment by bonigarcia** [comment]
No clue. Which is the setup for your proxy?

@Sebl29: You implemented the PR about the proxy. Does this exception ring a bell with you?

**Comment by Sebl29** [comment]
Hi, I am sorry but I didn't see anything like that before.
What are your environment variables for HTTP_PROXY and HTTPS_PROXY?
Which version of webdrivermanager?
I would recommend to take a minute and step quickly into that function, to see exactly what's the cause. BrowserManager.java:284 catches a large function and it's hard to guess where it comes from.
