### ISSUE TITLE
Chrome Browser does not start with chrome profile when using browserInDocker

### ISSUE THREAD

**Issue by xMH85x** [bonigarcia/webdrivermanager#843]
**Description of the problem**:  I need the chrome browser to start with a user profile. It works fine, if I'm using the webdriver locally, by passing the chrome profile as a chrome option. It also works if I run my tests in a docker container. But if I'm using the webdrivermanager with browserInDocker, the browser always starts without that profile. 
If I use the webdriver the browser starts with that chrome profile, so no need to accept cookies for example.
I don't get that with the webdrivermanager. Maybe you have any ideas how this could work, or what I'm doing wrong. Thanks.

**Operating system**:  Ubuntu 22.04

**WebDriverManager version**:  5.1.1

**WebDriverManager call**:  

public void setupBrowserInDockerWithProfile() {

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--user-data-dir=/home/seluser/.config/google-chrome/Default");
        driver = WebDriverManager
                .chromedriver()
                .capabilities(options)
                .browserInDocker()
                .dockerLang("de")
                .create();
        driver.manage().window().maximize();
        driver.get(APP_URL);
    }

**Comment by bonigarcia** [comment]
https://stackoverflow.com/questions/72462980/how-to-use-chrome-profile-when-using-browserindocker-with-webdrivermanager/72484477
