### ISSUE TITLE
Exception while setup() |  Network is unreachable (connect failed)

### ISSUE THREAD

**Issue by krishnapollu** [bonigarcia/webdrivermanager#847]
[io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.HttpHostConnectException: Connect to [https://chromedriver.storage.googleapis.com:443](https://chromedriver.storage.googleapis.com/) [chromedriver.storage.googleapis.com/172.217.15.240, chromedriver.storage.googleapis.com/2607:f8b0:4025:802:0:0:0:2010] failed: Network is unreachable (connect failed)]

Please help me with the root cause.

**Comment by bonigarcia** [comment]
It seems a connectivity issue at your end.
