### ISSUE TITLE
Build jar file will be erro

### ISSUE THREAD

**Issue by sacriley** [bonigarcia/webdrivermanager#848]
I find a issue. new version 5.x build jar file will be error.

```
Error: Could not find or load main class [xxxxx]
Caused by: java.lang.ClassNotFoundException: [xxxxx]
```

and 4.4.3 can run it, thank you.

**Comment by abaldwin-op** [comment]
This is the same as this report: https://github.com/bonigarcia/webdrivermanager/issues/819?

Something is conflicting somewhere with everyone's [gradle/manifest] setups -- and only when WebDriverManager is included as a dependency.

`implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.2.1'`

Still looking.

**Comment by abaldwin-op** [comment]
I forgot to tag you on the other issue @[sacriley](https://github.com/sacriley). This is what I found: https://github.com/bonigarcia/webdrivermanager/issues/819#issuecomment-1183783922
