### ISSUE TITLE
Error when using Edge Driver

### ISSUE THREAD

**Issue by pr0t3us** [bonigarcia/webdrivermanager#85]
Have some issues with the folder where is edge driver downloading, check it out:
[main] INFO BrowserManager - Latest version of [MicrosoftWebDriver] is Try Microsoft Edge, a fast and secure browser that's designed for Windows 10Get started
[main] INFO BrowserManager - Exporting webdriver.edge.driver as C:\Users\Serhio\.m2\repository\webdriver\MicrosoftWebDriver\Try Microsoft Edge, a fast and secure browser that's designed for Windows 10Get started\MicrosoftWebDriver.exe
openURL
org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\Serhio\.m2\repository\webdriver\MicrosoftWebDriver\Try Microsoft Edge, a fast and secure browser that's designed for Windows 10Get started\MicrosoftWebDriver.exe" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)
[main] ERROR WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.edge.EdgeDriver: Could not instantiate class org.openqa.selenium.edge.EdgeDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.edge.EdgeDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:128)
	...

**Comment by oscarcarlsson** [comment]
I've had the same problem so I made an attempt to fix it, see [PR #87](https://github.com/bonigarcia/webdrivermanager/pull/87). Let's see if the maintainer accepts it, I think my PR needs some cleaning before being used.

**Comment by bonigarcia** [comment]
Indeed, a recent change in the web page of Edge driver has led to this error.

PR #87 by @oscarcarlsson has solved the issue. I have just merged the change.

Thanks for reporting and contributing.

**Comment by oscarcarlsson** [comment]
Thanks for developing WDM in the first place! :)
