### ISSUE TITLE
Session Not Created Exception 

### ISSUE THREAD

**Issue by gs-karthik** [bonigarcia/webdrivermanager#852]
I have test setup(Java/Maven) that run through Jenkins CLI on os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.62.1.el7.x86_64', java.version: '1.8.0_322' and chromium-browser - Current browser version is 99.0.4844.84 with binary path /usr/bin/chromium-browser, the browser is set to auto update so I am using Webdriver manager to handle the browser versions, but whenever the test starts the webdriver manager downloads the 101 version only.

Following is the error message in Jenkins Console output
org.openqa.selenium.SessionNotCreatedException:
session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 99.0.4844.84 with binary path /usr/bin/chromium-browser
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'slpjenkl01.unix.magellanhealth.com', ip: '10.200.44.100', os.name: 'Linux', os.arch: 'amd64',

Appreciate it if you can help me in understanding the root cause of this issue, please if I run the test on windows locally no issues webdriver manager identifies the correct chrome version though. Please let me know if you need any additional information related to this issue

**Comment by bonigarcia** [comment]
The [motivation](https://bonigarcia.dev/webdrivermanager/#motivation) section of WebDriverManager doc explains about the need of drivers for Selenium WebDriver. Then, the [resolution algorithm](https://bonigarcia.dev/webdrivermanager/#resolution-algorithm) section explain how WebDriverManager manges automatically these drivers.
