### ISSUE TITLE
[🐛 Bug]: WebDriverManager downloads inappropriate versions of drivers and test executions are failing

### ISSUE THREAD

**Issue by svadivel0006** [bonigarcia/webdrivermanager#861]
When old versions of Chrome/Edge/Firefox are installed and when the WebDriverManager is used/run, it downloads the latest version of chromedrive.exe or respective drivers and hence the test executions are failing

### **Screenshots:**

**Error Details:**
![Error Details_Java](https://user-images.githubusercontent.com/85741928/176258433-8a2fa76d-48b4-44c0-8719-586d5842c708.png)

**Browser Installed Version:**
![image](https://user-images.githubusercontent.com/85741928/176186326-5eb5b761-7509-4ded-ae41-fb5440fee945.png)

**Comment by bonigarcia** [comment]
WebDriverManager does not use the latest driver version from ages. My recommendation for you is to use the latest version. If there is problem, please open a new issue and follow the issue template to report any problem.
