### ISSUE TITLE
Unable to create browser instance while specifying jar path locally in pom.xml

### ISSUE THREAD

**Issue by Sureshsekar123** [bonigarcia/webdrivermanager#863]
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>5.2.1</version>
    <scope>system</scope>
    <systempath>${project.basedir}/webdrivermanager-5.2.1.jar</systempath>
</dependency>
 PS: Jar stored in specified local path.

Getting unable to create instance error and its retrying to start browser

**Comment by bonigarcia** [comment]
Please follow the issue template to report any problem.
