### ISSUE TITLE
Can't run downloaded FirefoxDriver if it's already installed in system

### ISSUE THREAD

**Issue by pr0t3us** [bonigarcia/webdrivermanager#88]
Tests always run on the Firefox already installed in the system regarding of version set by variables:

[main] INFO BrowserManager - Latest version of [wires, geckodriver] is 0.11.1
[main] INFO Downloader - Downloading https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz to /home/serhio/.m2/repository/webdriver/geckodriver/linux64/0.11.1/geckodriver-v0.11.1-linux64.tar.gz
[main] INFO BrowserManager - Exporting webdriver.gecko.driver as /home/serhio/.m2/repository/webdriver/geckodriver/linux64/0.11.1/geckodriver
browserName = firefox
os = LINUX
browserVersion = 50.0
platformVersion = 4.4.0-47-generic

**********************************************

-Dwdm.geckoDriverVersion=0.10.0

[main] INFO Downloader - Downloading https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz to /home/serhio/.m2/repository/webdriver/geckodriver/linux64/0.10.0/geckodriver-v0.10.0-linux64.tar.gz
[main] INFO BrowserManager - Exporting webdriver.gecko.driver as /home/serhio/.m2/repository/webdriver/geckodriver/linux64/0.10.0/geckodriver
browserName = firefox
os = LINUX
browserVersion = 50.0
platformVersion = 4.4.0-47-generic

**Comment by bonigarcia** [comment]
Indeed, you are going to use always the Firefox installed in your system. WebDriverManager handles the driver binary (_geckodriver_), not the actual browser.
