### ISSUE TITLE
[Deprecation Warning] executable_path has been deprecated, please pass in a Service object

### ISSUE THREAD

**Issue by hydino2085143** [bonigarcia/webdrivermanager#881]
**Description of the problem**: Upon running a script using webdriver_manager, a deprecation warning is emitted in the console

**Browser and version**: Chrome 104

**Operating system**: Windows 10

**WebDriverManager version**: 3.8.3

**WebDriverManager call**: 
```python
driver = webdriver.Chrome(ChromeDriverManager().install())
```

**WebDriverManager traces**: 
```
%userprofile%\Programming\project\src\main.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
```

**Comment by bonigarcia** [comment]
Wrong repo, see: https://github.com/SergeyPirogov/webdriver_manager

**Comment by hydino2085143** [comment]
Oh dear, sorry for the mistake!
