### ISSUE TITLE
Configuring connection timeout for WebDriverManager

### ISSUE THREAD

**Issue by UpasanaC02** [bonigarcia/webdrivermanager#882]
Hi,

My question is related to the WebDriverManager HttpConnection timeout issue. This is the log entry -
io.github.bonigarcia.wdm.WebDriverManagerException: org.apache.http.conn.HttpHostConnectException: Connect to chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/172.217.17.80, chromedriver.storage.googleapis.com/2a00:1450:400e:805:0:0:0:2010] failed: Connection timed out: connect

I know that setting proxy would solve the problem. 
The issue is, I do not know whether my application users would be in VPN or not. So, currently what I am doing is I first try without proxy and if it fails(in the exception block), I set the proxy and try again.
But the problem is, it takes a very long time(almost 7 minutes). My test hangs for that much time and then it starts.
I tried setting the timeout like this -
`WebDriverManager.chromedriver().proxy("server:port").timeout(20).setup();`

But it doesnt seem to work. The Test seems to be hanging waiting for the driver. 

Any idea how to handle this ?

I am using Cucumber+Selenium+Junit for the tests.

Thanks for your support in advance.

**Comment by bonigarcia** [comment]
No clue, sorry.
