### ISSUE TITLE
ChromeDriverManager tries to download the latest ChromeDriver from incorrect url

### ISSUE THREAD

**Issue by Debanjan-B** [bonigarcia/webdrivermanager#885]
**Description of the problem**: ChromeDriverManager (Python) tries to download the latest ChromeDriver (v104.0.x) from incorrect url

As per [Index of /104.0.5112.79/](https://chromedriver.storage.googleapis.com/index.html?path=104.0.5112.79/) the download path should have been:

    https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_win32.zip

instead of 

    https://chromedriver.storage.googleapis.com/104.0.5112/chromedriver_win32.zip

**Browser and version**: Chrome v104

**Selenium version**: 4.4.2

**Client and version**: Python v3.8.0

**Operating system**: Windows 10, 64 bit

**WebDriverManager version**: `<TBD>`

**WebDriverManager call**: 
```
latest_release_url = 'https://chromedriver.storage.googleapis.com/{LATEST_RELEASE}_{full_version}'
driver = webdriver.Chrome(ChromeDriverManager(latest_release_url=latest_release_url).install(), options=options, desired_capabilities=caps)
```
**WebDriverManager traces**: 

    10:32:22 INFO About to download new driver from https://chromedriver.storage.googleapis.com/104.0.5112/chromedriver_win32.zip

**Error log**: 

    10:32:22 INFO About to download new driver from https://chromedriver.storage.googleapis.com/104.0.5112/chromedriver_win32.zip

**Comment by Devparihar5** [comment]
I was trying to run this line but it's showing me this error:

```
latest_release_url = 'https://chromedriver.storage.googleapis.com/{LATEST_RELEASE}_{full_version}'
driver = webdriver.Chrome(ChromeDriverManager(latest_release_url=latest_release_url).install(), options=options, desired_capabilities=caps)
```

error
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_21780\672334961.py in <module>
----> 1 driver = webdriver.Chrome(ChromeDriverManager(latest_release_url=latest_release_url).install(), options=options, desired_capabilities=caps)

NameError: name 'options' is not defined

```

**Comment by bonigarcia** [comment]
Wrong repo. See: https://pypi.org/project/webdriver-manager/
