### ISSUE TITLE
Calling wdm.getDownloadedDriverPath() after wdm.setup() may produce a 'null' as a result

### ISSUE THREAD

**Issue by vklonin** [bonigarcia/webdrivermanager#889]
**Description of the problem**: calling wdm.getDownloadedDriverPath() after wdm.setup() may produce a 'null' as a result

**Browser and version**: Chrome 103

**Operating system**: macOS Monterey

**WebDriverManager version**: 5.3.0

**WebDriverManager call**: 
```
public static String downloadDriver(DriverTypes driverType, Platform platform, String version) {
        try {
            String driverName = driverType.toString();
            switch (driverType) {
                case CHROME:
                    wdm = chromedriver(); break;
                case FIREFOX:
                    wdm = firefoxdriver(); break;
                case IE:
                    wdm = iedriver(); break;
                case EDGE:
                    wdm = edgedriver(); break;
                case OPERA:
                    wdm = operadriver(); break;
                case SAFARI:
                    return isBlank(DRIVER.path)
                        ? SAFARI_INFO.path.execute()
                        : DRIVER.path;
                default:
                    throw runtimeException("%s driver not supported for download");
            }
            switch (platform) {
                case X32:
                    wdm = wdm.arch32();
                    break;
                case X64:
                    wdm = wdm.arch64();
                    break;
            }
            driverName += " " + platform;
            if (hasVersion(version)) {
                wdm = wdm.browserVersion(version);
                driverName += " " + version;
            }
            if (version.equalsIgnoreCase(PENULT.value)) {
                wdm.setup();
                wdm.browserVersion(getBelowVersion());
            }
            if (isNotBlank(DRIVER.gitHubToken)) {
                wdm.gitHubToken(DRIVER.gitHubToken);
            }
            wdm.setup();
            logger.info("Download driver: '" +  driverName + "' successfully");
            driverDownloaded = true;
            downloadedDriverInfo = format("%s:%s:%s", driverType, platform, version);
            driverPath = wdm.getDownloadedDriverPath();
            return driverPath;
        } catch (Exception ex) {
            throw exception(ex, "Can't download latest driver for " + driverType);
        }
    }
}

```

**WebDriverManager traces**: 

56:52.135 [io.github.bonigarcia.wdm.online.Downloader:INFO]: Extracting driver from compressed file chromedriver_linux64.zip
[198](https://github.com/jdi-testing/jdi-light/runs/7945452656?check_suite_focus=true#step:9:199)
56:52.446 [io.github.bonigarcia.wdm.WebDriverManager:INFO]: Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/103.0.5060.134/chromedriver
[199](https://github.com/jdi-testing/jdi-light/runs/7945452656?check_suite_focus=true#step:9:200)
56:52.453 [JDI:INFO]: [23] Download driver: 'CHROME X64' successfully
[200](https://github.com/jdi-testing/jdi-light/runs/7945452656?check_suite_focus=true#step:9:201)
56:52.454 [JDI:INFO]: [23] Download driver path : 'null' successfully

**Comment by AlexeyGirin** [comment]
In other words - calling wdm.setup() and having it done successfully I would expect to have driver downloaded and ready for use. But in current webdrivermanager implementation - it is not since it continue its setup (i.e. unzipping chrome driver asynchronously).
This is why it returns NULL as driver path.
Can we make .setup() method wait everything done before method end?

**Comment by bonigarcia** [comment]
I am unable to reproduce this issue. In fact, there are several tests in WebDriverManager using `getDownloadedDriverPath()`, and all of them are working correctly (e.g., this [one](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/forced/ForceOsTest.java) and others).

I tried the code you provided, but it seems incomplete (the imports are missing, and I think there are errors, like `runtimeException`). If you provide a complete self-contained Java class that reproduces the issue, I can test it on my side.

**Comment by AlexeyGirin** [comment]
We will try to provide problem demo, but that will be hard since it is flaky problem that appears in very specific circumstances.
But sometimes - it affects up to 30% of tests ( https://github.com/jdi-testing/jdi-light/issues/2971 )

**Comment by pnatashap** [comment]
There is a PR https://github.com/bonigarcia/webdrivermanager/pull/895 which enables parallel test execution. They are always failed.

**Comment by AlexeyGirin** [comment]
@bonigarcia please have a look on Natasha's PR: https://github.com/bonigarcia/webdrivermanager/pull/895 that demonstrates the problem

**Comment by bonigarcia** [comment]
Indeed, there are failed tests running the WebDriverManager tests in parallel. I just checked it once again, and the cause for failed tests in parallel is related to frozen browsers or irresponsive drivers. But I don't see any test that fails due to `getDownloadedDriverPath()`, sorry.

**Comment by bonigarcia** [comment]
Any update on this?
