### ISSUE TITLE
CredentialsProvider Error

### ISSUE THREAD

**Issue by DimitriJambers** [bonigarcia/webdrivermanager#9]
Hi,

I use the webdriver manager to get the latest versions of all browsers and install them in the correct places now i recieve an error when trying to download edge driver it says:

java.lang.NoClassDefFoundError: org/apache/http/client/CredentialsProvider

**Comment by bonigarcia** [comment]
I have just checked the `EdgeDriverManager` capability and seems to be working properly. Could you please provide more information on the error you are facing? How it can be reproduced?

**Comment by DimitriJambers** [comment]
It is no longer an issue with the drivermanager but with our other dependencies that were out of date
