### ISSUE TITLE
error io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IllegalArgumentException: Key too long: chromeChromeDriver

### ISSUE THREAD

**Issue by irfanlogisly** [bonigarcia/webdrivermanager#900]
Hi , 

anyone could help me, i got this error "io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IllegalArgumentException: Key too long: chromeChromeDriver" when run my selenium in jenkins. in th pom file i used these webdriver version

<groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.8.1</version>

**Comment by bonigarcia** [comment]
First, upgrade to the latest version of WebDriverManager. That one is too old. Second, please follow the issue template to report any issue.
