### ISSUE TITLE
"The POM for com.github.docker-java.docker-java:docker-java:jar:3.2.13 is missing, no dependency information available"

### ISSUE THREAD

**Issue by TolstoyDotCom** [bonigarcia/webdrivermanager#912]
**Description of the problem**: I get the titular error message when running 'mvn clean compile'. That results in the build failing with "Could not resolve dependencies for project io.github.bonigarcia:webdrivermanager:jar:5.3.1-SNAPSHOT: The following artifacts could not be resolved: com.github.docker-java.docker-java:docker-java:jar:3.2.13, com.github.docker-java.docker-java:docker-java-api:jar:3.2.13, com.github.docker-java.docker-java:docker-java-core:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport-httpclient5:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport-jersey:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport-netty:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport-okhttp:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport-tck:jar:3.2.13, com.github.docker-java.docker-java:docker-java-transport-zerodep:jar:3.2.13: Failure to find com.github.docker-java.docker-java:docker-java:jar:3.2.13 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced".

In the project's POM, I changed docker-java.version to 3.2.12 and it compiled and ran.

**Operating system**: Ubuntu 18/OpenJDK 17

**Comment by bonigarcia** [comment]
I don't understand the issue, sorry. In any case, it does not seems related directly to WebDriverManager, sorry.
