### ISSUE TITLE
Not able to download drivers under a VPN

### ISSUE THREAD

**Issue by sumankundusitaaero** [bonigarcia/webdrivermanager#920]
**Description of the problem.** I need to use  a VPN to access my application, when Webdriver manager is trying to download/connect with it's server with VPN ON it is failing with an exception. where if I am trying without VPN it is working properly fine

This is happening for Chrome,Firefox, edge for Windows 10.

Has anyone solved this issue earlier ?
![Capture](https://user-images.githubusercontent.com/115992401/196163139-f0b97cee-33a0-4274-9f0a-3e467454d7e7.JPG)

**Comment by bonigarcia** [comment]
I'm not sure if you need some proxy configuration (see [doc](https://bonigarcia.dev/webdrivermanager/#advanced-configuration)).
