### ISSUE TITLE
For Firefox 106 on Windows 10, WebDriverManager tries downloading Linux driver unless clearResolutionCache

### ISSUE THREAD

**Issue by Meownjik** [bonigarcia/webdrivermanager#923]
**Description of the problem**: When Firefox got updated to v.106, startup errors appeared. Namely, for setting `WebDriverManager.firefoxdriver().setup();` the Manager logs: 

> Using geckodriver 0.32.0-linux (resolved driver for Firefox 106)

 and then crashes. When I added `WebDriverManager.firefoxdriver().clearResolutionCache().setup();` it works as expected: resolves 0.32.0-win geckodriver. Therefore, I believe the problem is somewhere in ResolutionCache.
By the way, explicit setting `firefoxdriver().win()` doesn't help as well, only `.clearResolutionCache()`.

**Browser and version**: Firefox 106.0 (64-bit)

**Operating system**: Windows 10, 21H2, 64-bit

**WebDriverManager version**: 5.3.0

**WebDriverManager call**: `WebDriverManager.firefoxdriver().setup();`

**WebDriverManager traces**: 10:47:25,798  INFO io.github.bonigarcia.wdm.WebDriverManager:resolveDriverVersion:1237 - Using geckodriver 0.32.0-linux (resolved driver for Firefox 106)
10:47:25,927  INFO io.github.bonigarcia.wdm.WebDriverManager:logSeekRepo:1582 - Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver to seek geckodriver
10:47:26,456  WARN io.github.bonigarcia.wdm.WebDriverManager:fallback:1432 - There was an error managing geckodriver 0.32.0-linux (No proper candidate URL to download geckodriver 0.32.0-linux) ... trying again using latest driver stored in cache
10:47:26,458  INFO io.github.bonigarcia.wdm.WebDriverManager:resolveDriverVersion:1237 - Using geckodriver 0.32.0-linux (resolved driver for Firefox 106)
10:47:26,544  INFO io.github.bonigarcia.wdm.WebDriverManager:logSeekRepo:1582 - Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver to seek geckodriver
10:47:26,604 ERROR io.github.bonigarcia.wdm.WebDriverManager:handleException:1421 - There was an error managing geckodriver 0.32.0-linux (No proper candidate URL to download geckodriver 0.32.0-linux)

**Error log**: 
10:47:26,604 ERROR io.github.bonigarcia.wdm.WebDriverManager:handleException:1421 - There was an error managing geckodriver 0.32.0-linux (No proper candidate URL to download geckodriver 0.32.0-linux)
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.32.0-linux
	at io.github.bonigarcia.wdm.online.UrlHandler.getCandidateUrl(UrlHandler.java:287)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1279)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1197)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1438)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1415)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1203)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:418)
	at *******.DriverRepository.downloadWebDriver(DriverRepository.java:45)

**Comment by msedhu1007** [comment]
I still face the same issue "Exporting webdriver.gecko.driver as /Users/SedhuS/.cache/selenium/geckodriver/mac64/0.32.0/geckodriver" when I trigger remote execution(Windows) from mac. It picks up my mac binary.

**Comment by bonigarcia** [comment]
There was a problem related to latest versions of geckodriver. It should be fixed now.

**Comment by bonigarcia** [comment]
This fix is available on WebDriverManager 5.3.1, just released.
