### ISSUE TITLE
Chrome version 106.0.5249.119 is having issue when performing execution

### ISSUE THREAD

**Issue by jaydip-LYFT** [bonigarcia/webdrivermanager#926]
I have admin approved version of Chrome to be 106.0.5249.119 and the driver we have is ChromeDriver 106.0.5249.61. What I am facing is that thread stops responding/moving ahead with the executing the steps and sometimes returns the error that target window is closed even when the browser instance is open. This wasnt an issue until the chrome was updated to this 106.0.5249.119  version. have you got this issue reported by anyone else OR do you have any idea how to handle this situation?

**Comment by bonigarcia** [comment]
The official chromedriver for Chrome 106 at the time of this writing is 106.0.5249.61. See:

https://chromedriver.chromium.org/downloads
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_106

In any case, you can force the driver version you want using the method `driverVersion()` of WebDriverManager (see [doc](https://bonigarcia.dev/webdrivermanager/#advanced-configuration)).
