### ISSUE TITLE
Can not run Browser Docker in Gitlab CI 

### ISSUE THREAD

**Issue by bacnn0701** [bonigarcia/webdrivermanager#932]
Sorry when push this to issue tab but I don't know  where to raise it .

I am using WebDriverManager wdm = WebDriverManager.chromedriver().browserInDocker(); to run my test. I copied the code at https://bonigarcia.dev/webdrivermanager/#browsers-in-docker (3.4) and run success in my local with docker desktop.

However, when I push code and run it by gitlab ci, there is errror below:

Running TestSuite
07:46:00.031 [docker-java-stream--1817625110] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [2] No such file or directory

[INFO] Running TestSuite
/root/.cache/selenium/chromedriver/linux64/106.0.5249.61/chromedriver: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 3.33 s <<< FAILURE! - in TestSuite
[ERROR] mypackagetest.elements.BrowserInDocker.setupTest  Time elapsed: 3.239 s  <<< FAILURE!
io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1774)

**My Gitlab-ci.yml:**

```
image: maven:3.8.6-openjdk-18
stages:
  - test
e2e-chrome-test:
  stage: test
  script:
    - mvn clean test -Dtest.suite=testing.xml
  artifacts:
    paths:
      - target
```

**My test case:**

`public class BrowserInDocker {

    WebDriver driver;

    @BeforeClass
    void setupTest() {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("start-maximized");
        chromeOptions.addArguments("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36");
        chromeOptions.setHeadless(true);
        driver = WebDriverManager.chromedriver().capabilities(chromeOptions).browserInDocker().create();
    }

    @AfterClass
    void teardown() {
        driver.quit();
    }

    @Test
    void test() {
        driver.get("https://bonigarcia.dev/selenium-webdriver-java/");
        Assert.assertTrue(driver.getTitle().contains("Selenium WebDriver"));
        System.out.println("Test finished");
    }

}`

**I don't know how to run it with gitlab -ci, please help me explain this problem. Thank you very much!**

**Comment by bonigarcia** [comment]
No clue, sorry. It seems your problem is related to your environment, but not directly because of WebDriverManager.
