### ISSUE TITLE
unable to launch edge in headless mode

### ISSUE THREAD

**Issue by ranjeet-rk33** [bonigarcia/webdrivermanager#935]
**Description of the problem**: unable to launch edge in headless mode

**Browser and version**: Edge  Version 107.0.1418.26

**Operating system**: <!-- Windows 10 and architecture (64 bits)

**WebDriverManager version**:  WebDriverManager 5.3.0

**WebDriverManager call**: driver = WebDriverManager.edgedriver().capabilities(options).create();

**WebDriverManager traces**: There is no error,  Webdrivermanager is launching edge in normal mode instead of headless mode

**Comment by bonigarcia** [comment]
I have checked this and it is working well in my tests. Please double check your options, since this should work.

**Comment by ranjeet-rk33** [comment]
Can u please share what options you are sharing for edge headless
