### ISSUE TITLE
Version 5.3.1 displays no SLF4J information when starting tests

### ISSUE THREAD

**Issue by hetacz** [bonigarcia/webdrivermanager#945]
**Description of the problem**: 

After bumping from 5.3.0 to 5.3.1 I see SLF4J error everytime I start test.

**Browser and version**:  Selenium 4.6.0, newest chrome downloaded by WDM (107 now)

**Operating system**: Win 11 64bit

**WebDriverManager version**: 5.3.1 (5.3.0 had no issues)

**WebDriverManager call**: 
    public WebDriver createDriver() {
        WebDriverManager.chromedriver().cachePath("drivers").setup();
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        System.setProperty("webdriver.chrome.silentLogging", "true");
        System.setProperty("webdriver.chrome.silentOutput", "true");
        return driver;
    }

**WebDriverManager traces**:

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/Hetacz/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.19.0/1a0c9615ba9fd5b96db8c1136afbef4394286e93/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

Additional info:

This wasn't visible in version 5.3.0
I use latest lombok and log4j, never had problems with this message up until new wdm release.
Here are my dependecies (I keep all in test):

    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.6.0'
    // https://mvnrepository.com/artifact/org.testng/testng
    testImplementation 'org.testng:testng:7.6.1'
    // https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.3.1'
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    testImplementation 'org.apache.logging.log4j:log4j-api:2.19.0'
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
    testImplementation 'org.apache.logging.log4j:log4j-core:2.19.0'
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl
    testImplementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.19.0'
    // https://mvnrepository.com/artifact/org.projectlombok/lombok
    testCompileOnly 'org.projectlombok:lombok:1.18.24'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'

**Comment by bonigarcia** [comment]
The latest versions of WebDriverManager uses the latest version of SLF4J, i.e., 2.x.x. Maybe bumping to SLF4J 2 in your project will solve the issue.
