### ISSUE TITLE
Cannot run remote webdriver

### ISSUE THREAD

**Issue by frankvu191** [bonigarcia/webdrivermanager#95]
Hi,
Is it possible to run webdriver remotely with WebDriverManager?
Thanks

**Comment by bonigarcia** [comment]
To run WebDriver remotely you need Remote WebDriver. You can get more info for example [here](https://github.com/selenium-webdriver-book/manuscript/blob/master/manuscript/ch11_drivers.adoc). What do you expect from WebDriverManager?

**Comment by Lucasgermani** [comment]
@bonigarcia, about this question, it's possible to run a RemoteWebdriver using our webdrivermanager API to manage the webdriver binaries at the selenium nodes?

**Comment by bonigarcia** [comment]
@Lucasgermani You can use WebDriverManager to manage the binaries when register nodes in a hub. For instance [here](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/main/java/io/github/bonigarcia/wdm/RegisterChrome.java) (Chrome) or [here](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/main/java/io/github/bonigarcia/wdm/RegisterFirefox.java) (Firefox).
