### ISSUE TITLE
Getting expection on line "WebDriverManager.chromedriver().setup();

### ISSUE THREAD

**Issue by saikrishnameda248** [bonigarcia/webdrivermanager#963]
I am facing the below issue 
java.lang.NoSuchMethodError: 'java.lang.String org.apache.commons.io.IOUtils.toString(java.io.InputStream, java.nio.charset.Charset)' on line "WebDriverManager.chromedriver().setup();

I am using the latest WebDriverManager version i.e 5.3.1 and the latest commons.io version i.e 2.11.0

_Originally posted by @saikrishnameda248 in https://github.com/bonigarcia/webdrivermanager/issues/432#issuecomment-1362636263_

**Comment by bonigarcia** [comment]
https://stackoverflow.com/questions/74896786/getting-expection-on-line-webdrivermanager-chromedriver-setup/

**Comment by saikrishnameda248** [comment]
Still, we are facing the same issue even without the commons.io dependency in the pom.xml

**Comment by Wyifei** [comment]
same problem:java.lang.NoSuchMethodError: 'io.github.bonigarcia.wdm.WebDriverManager io.github.bonigarcia.wdm.WebDriverManager.version(java.lang.String)'

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.4.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.13.0</version>
        </dependency>
