### ISSUE TITLE
Error when I try to go on my localhost page with Firefox since I downgrade Selenium to 2.53.1

### ISSUE THREAD

**Issue by fannyv** [bonigarcia/webdrivermanager#98]
Hi I need a little help, 
I'm working with selenium 3.0.1. However, I need to change to 2.53.1 because Actions (moveto and doubleclick) are not implemented yet for Firefox. 

With your code, I was able to have the firefox webdriver for selenium 3.0.1. Since I downgrade it, I cannot run Firefox (chrome and IE are good!). 

My code is : 
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setPlatform(Platform.WIN10);
switch (browserType){
   case Firefox:
			FirefoxDriverManager.getInstance().setup();
			//capabilities.setCapability("marionette", true); 
			capabilities.setBrowserName("firefox");
			capabilities.setVersion("46");
			
			ProfilesIni profile = new ProfilesIni();
			FirefoxProfile ffProfile = profile.getProfile("default");
			//accept the certificate
			ffProfile.setAcceptUntrustedCertificates(true);
			ffProfile.setAssumeUntrustedCertificateIssuer(false);
			capabilities.setCapability(FirefoxDriver.PROFILE, ffProfile);
			WebDriver  webDriver = new FirefoxDriver(capabilities);

			break;
  //... case for Chrome and IE
}
webDriver.manage().window().maximize();
webDriver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
```
The error is : 

> org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
> o pdf","creator":"pdfforge GmbH","homepageURL":"http://pdfarchitect.org"},{"locales":["ru-RU"],"name":"PDF Architect 2 Creator","description":"Данное расширение позволяет преобразовать HTML страницу в документ формата PDF.","creator":"pdfforge GmbH","homepageURL":"http://pdfarchitect.org"}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"10.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0,"seen":true}

What did I do wrong? 

Thanks

**Comment by fannyv** [comment]
You can close it. It was because I did not have the good FF version. Thanks

**Comment by hennr** [comment]
@fannyv You should be able to close the issue buy yourself now.

@bonigarcia Did you consider to add a note to the readme that points to [stackoverflow]( https://stackoverflow.com/questions/tagged/webdrivermanager) for questions about the project?
That we the github issue section could be kept for bug reports and feature requests only.

**Comment by bonigarcia** [comment]
@hennr Yes, it's a good idea, will do some day
