### ISSUE TITLE
After updateding the chrome driver version to 91 for electron app, getting white screen on launch for electron app automation

### ISSUE THREAD

**Issue by shankaram** [bonigarcia/webdrivermanager#980]
I am trying to automate an electron app using selenium webdriver
My electron app migrated to electron version -"electron": "13.6.9". Hence i needed to update my chrome driver version from 85 to 91 .
But on launching the application its showing white screen.

Code:-
System.setProperty(DataManager.getChromeDriver(), DataManager.getElectronDriverPath());
ChromeOptions opt = new ChromeOptions();
opt.setBinary(DataManager.getElectronAppPath());
ChromeDriverService chromeservices = new ChromeDriverService.Builder().build();
electronDriver=new ChromeDriver(chromeservices, opt);

Note:- Before it was working fine.

Software version:
Java v1.8.0_311
Selenium- 3.141.59
Chrome version- 91

**Comment by bonigarcia** [comment]
It seems you are using a different manager.
