### ISSUE TITLE
Chromedriver is loading a blank page on Jenkins with newest version of Chrome on Windows.

### ISSUE THREAD

**Issue by editrocchio** [bonigarcia/webdrivermanager#981]
**Description of the problem**:
We have some code running on Jenkins on a Windows machine which uses webdrivermanager to download the correct version of chromedriver. The last successful run was Nov 30 2022 and outputs these logs:

10:34:44  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-106 - Initializing the chrome webdriver
10:34:44  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-122 - Chrome will run in headless mode
10:34:44  Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 63028
10:34:44  Only local connections are allowed.
10:34:44  Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
10:34:44  ChromeDriver was started successfully.
10:34:45  Nov 30, 2022 10:34:45 AM org.openqa.selenium.remote.ProtocolHandshake createSession
10:34:45  INFO: Detected upstream dialect: W3C
10:34:45  Nov 30, 2022 10:34:45 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
10:34:45  WARNING: Unable to find an exact match for CDP version 107, so returning the closest version found: 104
10:34:45  Nov 30, 2022 10:34:45 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
10:34:45  INFO: Found CDP implementation for version 107 of 104
10:34:45  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-130 - chrome webdriver initialized
...
...
Continues to successfully run.

I tried to run it again today and it was broken with these logs:

15:57:12  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-103 - Initializing the chrome webdriver
15:57:12  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-119 - Chrome will run in headless mode
15:57:12  Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 9922
15:57:12  Only local connections are allowed.
15:57:12  Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
15:57:12  ChromeDriver was started successfully.
15:57:13  Jan 13, 2023 3:57:13 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
15:57:13  WARNING: Unable to find an exact match for CDP version 109, so returning the closest version found: 106
15:57:13  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-127 - chrome webdriver initialized
...
...
Proceeds to fail with TimeoutException looking for the first element.

I added some code to take a screenshot after the .load(url) call and it's just loading a blank white page. Chrome was on 109.0.5414.75 so I assume it was updated between now and the previous successful run.  I can run the same branch/code in headless mode locally with Chrome version 109 and it works.

**Browser and version**: 
Windows: Version 109.0.5414.75 (Official Build) (64-bit) <--Jenkins box which is failing
Mac: Version 109.0.5414.87 (Official Build) (arm64) <-- Running locally where it succeeds

**Operating system**: 
Windows 10 64 bit

**WebDriverManager version**: 
5.3.1

**WebDriverManager call**: 
Note: I've tried adding all the options below to the headless run and it doesn't seem to help.

 WebDriverManager chrome = WebDriverManager.chromedriver();
        chrome.setup();
        ChromeOptions options = new ChromeOptions();
        if (isWebDriverUi()) {
            LOG.debug("Chrome will run in browser mode");
            options.addArguments("--disable-extensions"); // Disable extensions
            options.addArguments("--allow-http-background-page ⊗");
            options.addArguments("--allow-insecure-localhost"); // Enables TLS/SSL errors on localhost to be ignored (no interstitial, no blocking of requests).
            options.addArguments("--allow-silent-push");
            options.addArguments("--disable-ios-password-suggestions");
            options.addArguments("--ignore-certificate-errors");
            options.addArguments("--no-sandbox");
            options.addArguments("--start-maximized");
        } else {
            LOG.debug("Chrome will run in headless mode");
            options.addArguments("--start-fullscreen");
            options.addArguments("--window-size=1920,1080");
            options.addArguments("--disable-gpu");
            options.addArguments("--headless");
        }

**Error log**: 
15:57:14  DEBUG com.ea.systest.orc.selenium.SeleniumUtil-212 - Finding element By.className: sim_desc
15:57:24  ERROR com.ea.systest.orc.Orc-72 - Expected condition failed: waiting for com.ea.systest.orc.selenium.SeleniumUtil$$Lambda$471/0x0000000801038a40@66223d94 (tried for 10 second(s) with 500 milliseconds interval)
15:57:24  org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.ea.systest.orc.selenium.SeleniumUtil$$Lambda$471/0x0000000801038a40@66223d94 (tried for 10 second(s) with 500 milliseconds interval)
15:57:24  	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)
15:57:24  	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
15:57:24  	at com.ea.systest.orc.selenium.SeleniumUtil.findElement(SeleniumUtil.java:213)
15:57:24  	at com.ea.systest.orc.selenium.SeleniumUtil.findElement(SeleniumUtil.java:208)
15:57:24  	at com.ea.systest.orc.selenium.SeleniumUtil.getText(SeleniumUtil.java:326)
...
...
...
15:57:24  Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".sim_desc"}

**Comment by editrocchio** [comment]
I was able to get access to the Jenkins machine and ran a local test there, and it's working. So it seems the issue is not with this library but something happening on Jenkins. I'm going to close the issue for now while I do more investigation since I think it's on our side.

**Comment by elalish** [comment]
@editrocchio Curious if you found anything? My local macbook just updated from Chrome 108 to 109 and suddenly my headless tests can't create a webGL context anymore:

Chrome Headless 109.0.5414.87 (Mac OS 10.15.7) ERROR: 'THREE.WebGLRenderer: A WebGL context could not be created. Reason: ', 'Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, GL_VENDOR = Google Inc. (Google), GL_RENDERER = ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (LLVM 10.0.0) (0x0000C0DE)), SwiftShader driver-5.0.0), GL_VERSION = 5.0.0, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .'
